### ISSUE TITLE
Missing Status of  VS1 for Buderus SM200

### ISSUE THREAD

**Issue by briegra** [emsesp/EMS-ESP32#1034]
I miss the status of the valve VS1. This is the valve which switches  from Boiler to Solar.
Can someone tell me where to find?

**Comment by MichaelDvP** [comment]
The SM200 have a lot of possible configurations and only a few users have checked the telegrams in their configuration. 
I think this valve status could be in telegram 0x36A. Try in terminal `read 30 36A`, wait for a change of the valve and read again. I guess it is status 03 for off and 04 for on.
If you find it, please also suggest a shortname for mqtt and a fullname for the web dashboard.

**Comment by briegra** [comment]
Great! Thank you for the quick response!
I can confirm that I get 03 for a switched off valve. Now I must wait for sunshine to confirm the status 04. Hope it will not last too long anymore.
My suggestions are:

  *   MQTT would be: “Valve_VS1”
  *   Fullname for dashboard: “Solar Valve (VS1) open”

BTW: I also miss the flame status. Is there also something available?

BR

Ralf

**Comment by MichaelDvP** [comment]
>  BTW: I also miss the flame status. Is there also something available?

A flame in a SM200 is no good, smells like molten plastic.

**Comment by briegra** [comment]
LOL

Von: MichaelDvP ***@***.***>
Gesendet: Donnerstag, 16. Februar 2023 19:50
An: emsesp/EMS-ESP32 ***@***.***>
Cc: Ralf Brieger ***@***.***>; Author ***@***.***>
Betreff: Re: [emsesp/EMS-ESP32] Missing Status of VS1 for Buderus SM200 (Issue #1034)


BTW: I also miss the flame status. Is there also something available?

A flame in a SM200 is no good, smells like molten plastic.

**Comment by briegra** [comment]
I found something but I don’t know how to put it to a read command. This could be the flame status I’m looking for.
Can u help?

***@***.***

Von: MichaelDvP ***@***.***>
Gesendet: Donnerstag, 16. Februar 2023 19:50
An: emsesp/EMS-ESP32 ***@***.***>
Cc: Ralf Brieger ***@***.***>; Author ***@***.***>
Betreff: Re: [emsesp/EMS-ESP32] Missing Status of VS1 for Buderus SM200 (Issue #1034)


BTW: I also miss the flame status. Is there also something available?

A flame in a SM200 is no good, smells like molten plastic.

**Comment by briegra** [comment]
Hi,

I can confirm both. 03 for closed and 04 for open valve.
Will you put this information to next version?

**Comment by MichaelDvP** [comment]
> I can confirm both. 03 for closed and 04 for open valve.

Which byte? The telegram 0x36A looks like this: `data: 03 03 03 03 01 03 03 03 03 03 01 03`. We know, second byte is pump2, 5th byte VS2, 11th byte pump1, I can add if i know the right position. 

For the flame we need motre info from your system and what you've found.

**Comment by briegra** [comment]
Let me Double Check it again. I had the change in the first one. When I remember right there was another change in the queue.

Von meinem iPhone gesendet

Am 21.02.2023 um 07:25 schrieb MichaelDvP ***@***.***>:

﻿

I can confirm both. 03 for closed and 04 for open valve.

Which byte? The telegram 0x36A looks like this: data: 03 03 03 03 01 03 03 03 03 03 01 03. We know, second byte is pump2, 5th byte VS2, 11th byte pump1, I can add if i know the right position.

For the flame we need motre info from your system and what you've found.

**Comment by briegra** [comment]
This is what I got in the different state:
[emsesp] solar(0x30) -W-> Me(0x0B), SM100Status2(0x036A), data: 04 03 03 03 03 03 03 03 03 03 03 03 --> Valve open
[emsesp] solar(0x30) -W-> Me(0x0B), SM100Status2(0x036A), data: 03 03 03 03 03 03 03 03 03 03 03 03 --> Valve closed

**Comment by MichaelDvP** [comment]
Ok, lucky me, i have already implemented the right offset. Try 3.5.1-dev from https://github.com/MichaelDvP/EMS-ESP32/releases or compile the latest tech-upgrade branch from here.

**Comment by briegra** [comment]
Great – Thank you very much!

**Comment by proddy** [comment]
assuming this is resolved now. Otherwise please re-open.
