### ISSUE TITLE
Junkers or Bosh boiler don't execute commands 

### ISSUE THREAD

**Issue by matteopedani** [emsesp/EMS-ESP32#1074]
### If a Junkers or Bosh boiler is connected to EMS-ESP32,  the boiler   aspect a thermost 

As the EMS interface is active  (the cable is connected and the EMS-ESP32 is powered)  the boiler:

1. Change the way as go ON/OFF  the boiler and no more accept  the alternative  ON/OFF  contact.  
1. Stay always ON and try to modulate the power, keeping the water at constant temperature all the times.

Using a program to emulate one thermostat like  Home Hassistant  give do not help, the boiler ignore the commands.  
 
### TO REPRODUCE

Connect just  one EMS-ESP32  to a  Junker boiler  or BOSH and do not  have  a real thermostat. 
You can't send command to boiler but you can only  read data from boiler.

### EXPECTED BEHAVIOUR
Read data and send command to boiler (and the command are executed)

**Comment by proddy** [comment]
https://emsesp.github.io/docs/Troubleshooting/#changing-a-value-on-an-ems-device-doesnt-work
