### ISSUE TITLE
some settings randomly disappear and become reset

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#1078]
I've been doing lots of re-work on MQTT and noticed a few times the whole MQTT settings would be reset. Haven't looked into the reason why.  Have you noticed this too @MichaelDvP ?

**Comment by MichaelDvP** [comment]
Could be this: https://github.com/emsesp/EMS-ESP32/blob/3e9f63a913403c010720b5c98a9e0627f24e08cb/lib/framework/StatefulService.h#L17 
We have this 8k for customizations, but most configs does not need it. If alloc fails the config safe clears the config (i guess). 
I've tested to go back to 1k and set the buffer for each config-file independent. I could make a PR for this.

**Comment by proddy** [comment]
I don't believe FS_BUFFER_SIZE is used at all.

The MQTT isn't the largest file either. Pressing the button on the dev board shows me

![image](https://user-images.githubusercontent.com/1230712/221012525-6b9ea686-d768-49f8-a798-24b8b5410b98.png)

**Comment by proddy** [comment]
closing this. I think it happens when USB flashing and may be driver related. Will re-open if I can reproduce it.

**Comment by proddy** [comment]
re-opening. happened again upgrading from 3.5.0 to 3.6.0. time to debug....

**Comment by MichaelDvP** [comment]
Was this only mqtt? Or also other settings affected? We had this very few times with settings (board-profile), but it's long ago.

**Comment by proddy** [comment]
yeah, only the MQTT is missing. I think it's something in `System::check_upgrade()`

**Comment by proddy** [comment]
I tested 3.5.0 -> 3.6.0 and back and can't reproduce.

**Comment by proddy** [comment]
I noticed also some of the settings (like shower time, led etc) were also reset. It happens between version uploading but I can't reproduce it. I'll keep this issue open in case it happens again
