### ISSUE TITLE
thermostat modetype is not changing when mode changes (e.g. to night)

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#1098]
### Discussed in https://github.com/emsesp/EMS-ESP32/discussions/1096

<div type='discussions-op-text'>

<sup>Originally posted by **JokerGermany** March  4, 2023</sup>
![grafik](https://user-images.githubusercontent.com/30293477/222881857-0cd2e24e-68a0-4205-9ff8-ba30c6070e35.png)
![grafik](https://user-images.githubusercontent.com/30293477/222881877-b7ee18b4-1a1d-4a27-9077-8a36d2b9c631.png)

![grafik](https://user-images.githubusercontent.com/30293477/222881922-7c5de431-443e-4b51-9846-cd05b02e1c9f.png)
![grafik](https://user-images.githubusercontent.com/30293477/222881935-9cd8730b-5048-4f0b-825d-d6f21c3151f8.png)

Locks like the option isn't transfered to ems-esp?</div>

**Comment by proddy** [comment]
Michael fixed with https://github.com/emsesp/EMS-ESP32/pull/1097

Please test

**Comment by MichaelDvP** [comment]
BTW: the title is wrong, changing to night works, but the modetype wasn't updated after this change.

**Comment by JokerGermany** [comment]
Thanks
Didn't notice, that this happened again.
