### ISSUE TITLE
wwonetimecharging not working

### ISSUE THREAD

**Issue by Ivannefit** [emsesp/EMS-ESP32#112]
Hello,

The ww one time charging does not work on my nefit enviline tower 2 (monoblock)

The option to adjust is not available EMS-ESP web interface.

In Domoticz is no hardware available for wwonetimecharging.

![screenshot](https://user-images.githubusercontent.com/90444124/133880814-6b2e8f3e-ea63-42d5-bb0b-ede2f7f5c6e2.png)

When i use the Nefit phone app the ww temperature is default on 70 degrees, The only thing i need to set is the time that extra ww wil be active .( varies from 15 min to 48 hours in steps of 15 min)

![Screenshot_20210918-093240_Nefit ProControl (002)](https://user-images.githubusercontent.com/90444124/133881247-30528490-2237-477f-8aa3-82510ccf90e1.jpg)

Device information
![versie](https://user-images.githubusercontent.com/90444124/133881337-7f684d29-55bb-4306-9519-8746e16ba709.png)

**Comment by proddy** [comment]
can you post your system info (from the help tab) so we can see the devices

**Comment by Ivannefit** [comment]
Here is the info.


{
  "System": {
    "version": "3.2.1",
    "uptime": "003+01:45:06.741",
    "uptime_sec": 265506,
    "freemem": 174
  },
  "Status": {
    "bus": "connected",
    "bus protocol": "Buderus",
    "telegrams received": 808472,
    "read requests sent": 57535,
    "write requests sent": 0,
    "incomplete telegrams": 21,
    "tx fails": 0,
    "rx line quality": 100,
    "tx line quality": 100,
    "MQTT publishes": 45073,
    "MQTT publish fails": 0,
    "dallas sensors": 0,
    "dallas reads": 0,
    "dallas fails": 0
  },
  "Devices": [
    {
      "type": "Boiler",
      "name": "Enviline/Compress 6000AW/Hybrid 7000iAW/SupraEco (DeviceID:0x08, ProductID:172, Version:01.15)",
      "handlers": "0x10 0x11 0x14 0x15 0x1C 0x18 0x19 0x1A 0x35 0x16 0x33 0x34 0x26 0x2A 0xD1 0xE3 0xE4 0xE5 0xE6 0xE9 0xEA 0x494 0x495 0x48D 0x48F"
    },
    {
      "type": "Thermostat",
      "name": "RC300/RC310/Moduline 3000/1010H/CW400/Sense II (DeviceID:0x10, ProductID:158, Version:13.07)",
      "handlers": "0xA3 0x06 0xA2 0x12 0x2A5 0x2B9 0x2AF 0x29B 0x2A6 0x2BA 0x2B0 0x29C 0x2A7 0x2BB 0x2B1 0x29D 0x2A8 0x2BC 0x2B2 0x29E 0x2F5 0x31B 0x31D 0x31E 0x23A 0x267 0x240"
    },
    {
      "type": "Heatpump",
      "name": "HP Module (DeviceID:0x38, ProductID:200, Version:40.04)",
      "handlers": "0x42B 0x47B"
    },
    {
      "type": "Gateway",
      "name": "KM200/MB LAN 2 (DeviceID:0x48, ProductID:189, Version:04.07)",
      "handlers": ""
    }
  ]
}

**Comment by proddy** [comment]
thanks. Could you also send the output of http://ems-esp/api/boiler/wwonetime

**Comment by Ivannefit** [comment]
You mean with MQTT exploder?

**Comment by proddy** [comment]
no, EMS-ESP has an REST API. The URL will query EMS-ESP and bring back the ww onetime details. You may need to replace ems-esp with the IP address

**Comment by Ivannefit** [comment]
Ah ok.

  "name": "wwonetime",
  "fullname": "ww one time charging",
  "circuit": "ww",
  "value": "off",
  "type": "boolean",
  "writeable": true
}

**Comment by proddy** [comment]
So we need to figure out why you can't change it from the Web UI. Just to be safe could you restart EMS-ESP and also Shift-Refresh your browser to make sure nothing is cached.

Also you can try setting the value directly from the Console. Telnet into EMS-ESP, do a `su` with the default system password and type `call boiler wwonetime` to see the settings and then try `call boiler wwonetime on` to change a value.

The feature from the Nefit app is interesting. We could consider making a new feature that does the same if you want - but then please create a new GitHub enhancement request with some specifications on how it works.

**Comment by MichaelDvP** [comment]
@Ivannefit Please use the [latest dev-build](https://github.com/emsesp/EMS-ESP32/releases), sunbuzz has [recently fixed](https://github.com/emsesp/EMS-ESP32/commit/1b9a2f21d2778215c707a5a63435a30b1aaa10a0) the (for some heatpumps) too small json buffer, cutting the pencil and some other paramters from webpage. 

On some systems ww is only managed by thermostat and wwonetime-command on boiler does not work, than try thermostat wwcharge command.

**Comment by Ivannefit** [comment]
Ok i have done it with versie 3.2.1 and 3.2.2b5
![telnet](https://user-images.githubusercontent.com/90444124/133884348-e0af1150-e3fe-4020-a6e0-de5bb9935c69.png)


![Telnet versie 3 2 2b5](https://user-images.githubusercontent.com/90444124/133884356-a6de0192-e5c9-44d9-b769-a0a09c30fc22.png)

**Comment by MichaelDvP** [comment]
> Both not working

As mentioned: Have you tried `call thermostat wwcharge on`. The command from terminal is send to the boiler, but the boiler ignores it. The dev fixes only the missing values on web-page.

**Comment by Ivannefit** [comment]
now i have tried call thermostat wwcharge on.

![rge](https://user-images.githubusercontent.com/90444124/133885569-16bf29b8-a6b4-4260-ba8f-0f20f73c7b08.png)

Still nothing happens

**Comment by MichaelDvP** [comment]
From [here](https://github.com/emsesp/EMS-ESP/issues/589#issuecomment-726140292): Try with `call system send "0B 10 FF 0B 01 F5 FF"`

I think the thermostat command sends 1 instead of 0xFF.

**Comment by Ivannefit** [comment]
This one works, but default time is now 45 min. it would be nice to set the timer and be able to use it in domoticz

![test](https://user-images.githubusercontent.com/90444124/133887256-16aaf50b-45d3-4138-a452-698edfe2d3f2.png)

**Comment by MichaelDvP** [comment]
Ok, i'll change the wwcharge-command to make it work. I think `wwchargeduration` can also be set in steps of 15min, doesn't it work?
With domoticz i can't help, i've never tried it.

**Comment by Ivannefit** [comment]
wwchargeduration is not in my web interface, and with telnet i get error ( command not found)

**Comment by MichaelDvP** [comment]
Should be right before wwcharge in thermostat values. Please check `call thermostat info` and `read 10 2F5`

**Comment by Ivannefit** [comment]
Ya sorry was looking in boiler, wwchargeduration works properly

**Comment by Ivannefit** [comment]
i'm using 3.2.2.b8 now and all value that are writable in the web intrerface dont have a pull down menu.

![ems](https://user-images.githubusercontent.com/90444124/134921739-a930d3db-39b4-4595-9be2-fec85965be41.png)

**Comment by MichaelDvP** [comment]
I think you're using a cached webpage, please reload page in browser.

**Comment by Ivannefit** [comment]
I have reload the de page and pull down menu's are back, Only wwonetimecharging isn't working

**Comment by MichaelDvP** [comment]
> Only wwonetimecharging isn't working

As mentioned: if ww is managed by thermostat the `boiler wwontime` is not working, you have to use `thermostat wwcharge`, this should work now.
For systems with working boiler command it is only starting if the current temp is more than 5 degrees under setpoint, otherwise the boiler ignores the command.

**Comment by Ivannefit** [comment]
Ah ok ,sorry forgot about that. wwcharge is working!!!
