### ISSUE TITLE
Wrong mapping for "hc1 nofrost mode"

### ISSUE THREAD

**Issue by Marcwa19197** [emsesp/EMS-ESP32#1134]
### PROBLEM DESCRIPTION

Wrong mapping for "hc1 nofrost mode". It shows "room" in the WebUI but on the device (Buderus) its "outside".
Im using EMS-ESP Version v3.5.1.

Or is this fixed in the latest DEV Version?

### TO REPRODUCE

Set "room" for "hc1 nofrost mode" via WebUI and check the setting on the device (RC35). It shows "Outside" and not "room". (and if you choose "outside" in webUI it shows "room" on the device.) so there must be a wrong mapping.

### EXPECTED BEHAVIOUR

Mapping should be correct.

### SCREENSHOTS
<img width="552" alt="Screenshot 2023-03-21 at 10 48 41" src="https://user-images.githubusercontent.com/5463753/226570458-b3737131-b23a-4b0f-8a09-d5bfb96575a0.png">

![IMG_2008](https://user-images.githubusercontent.com/5463753/226570717-a61c682f-7212-4f06-9741-2c6dcca16663.jpeg)

**Comment by MichaelDvP** [comment]
I've already mentioned it here: https://github.com/emsesp/EMS-ESP32/issues/1132#issuecomment-1476172282
It is fixed in the 3.6.dev. (also mypatch-branch, but not merged to official yet).

**Comment by Marcwa19197** [comment]
Yeah, sorry for creating a new issue! This took a time to figure out. I was wondering why my pump war working in during the night, so i cam across this bug... ;-)

You can close it! Thanks!
