### ISSUE TITLE
Dev EMS-ESP Version v3.6.0-dev.8 Dashboard Status EMS Read Quality 

### ISSUE THREAD

**Issue by Vikingn** [emsesp/EMS-ESP32#1144]
### PROBLEM DESCRIPTION

The Raad was about 50% after upload of the newest version

After some minutes its 91% now
![image](https://user-images.githubusercontent.com/36015094/227586558-7f89d04b-814d-4c6a-b562-a843bd61d9f6.png)

Then i use this instead: EMS-ESP-3_6_0-dev_7-ESP32

The read etc are at 100% Quality from the start !

_A clear and concise description of what the problem is._

### REQUESTED INFORMATION

_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Searched the problem in [issues](https://github.com/emsesp/EMS-ESP32/issues)
- [ ] Searched the problem in [discussions](https://github.com/emsesp/EMS-ESP32/discussions)
- [ ] Searched the problem in the [docs](https://emsesp.github.io/docs/Troubleshooting/)
- [ ] Searched the problem in the [chat](https://discord.gg/3J3GgnzpyT)
- [ ] Provide the output of http://ems-esp.local/api/system :

```lua
  System information output here:


```

### TO REPRODUCE

_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR

_A clear and concise description of what you expected to happen._

### SCREENSHOTS

_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT

_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Vikingn** [comment]
I will try the dev-8 again today and power off and on again then to test

**Comment by Vikingn** [comment]
Tried now after about 30-60 s it look like this 
![image](https://user-images.githubusercontent.com/36015094/227709732-88be7683-32c0-4e5b-a280-22212f8f501d.png)
after 2 min like this

![image](https://user-images.githubusercontent.com/36015094/227709762-5b2221b7-f0f6-4fb6-a6ca-ef80839623a7.png)
So i go back to EMS-ESP-3_6_0-dev_7-ESP32.bin
After 1 min look like this:
![image](https://user-images.githubusercontent.com/36015094/227709897-30f2bedb-7f11-4300-88d0-f997ea7716ac.png)

**Comment by Vikingn** [comment]
![image](https://user-images.githubusercontent.com/36015094/227709910-1e8f7651-84f7-444f-971d-d9e9c77de24f.png)

**Comment by Vikingn** [comment]
We can do a web meeting and look at it together if you want.

**Comment by proddy** [comment]
are you using the bins from the GH repo or compiling & building yourself? The only thing I can think of is the increased uart stack but it shouldn't make a difference.

**Comment by Vikingn** [comment]
I downloaded it from your GH repo

**Comment by proddy** [comment]
still seeing this issue?

**Comment by nhmariend** [comment]
I csn try and check out but i tried det 8 2-3 times very slow to increase the read percentage. On det 7 its 100%. After short time. So something does norsk fine here. We can do s web meeting on it if you want that.
