### ISSUE TITLE
custom telegram handler

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#1155]
### Discussed in https://github.com/emsesp/EMS-ESP32/discussions/1079

<div type='discussions-op-text'>

<sup>Originally posted by **proddy** January 21, 2023</sup>
from @tp1de 

> Very long time ago I made a proposal to introduce "customizable" entities by telegram-type and offset. Maybe still an idea to support special installations and requirements.

I don't recall that, but its really good idea. We could add to the Customization page the ability to add a new Telegram to the EMS device in which you choose a name, the type (short, int), the divider (div10, div2 etc) and position. This would only be for read telegrams though.

_Originally posted by @proddy in https://github.com/emsesp/EMS-ESP32/issues/908#issuecomment-1399201035_
            </div>

**Comment by proddy** [comment]
Michael created this in https://github.com/emsesp/EMS-ESP32/pull/1151

**Comment by proddy** [comment]
@MichaelDvP the webUI needs a little tidying up and also some mock data in server.js. Shall I do this?

**Comment by MichaelDvP** [comment]
Yes, please do this.

**Comment by proddy** [comment]
> Yes, please do this.

I've been working on the web code, making minor changes and then decided to look at replacing all the form validation code with a new library, and at the same time refactoring the component rendering since it's really quite inefficient (many renders). So it's going to take some time. I'm checking it into my local repo

**Comment by proddy** [comment]
think we can close this. The updated web code is in PR https://github.com/emsesp/EMS-ESP32/pull/1162 

It's a great feature, thanks.
