### ISSUE TITLE
PlatformIO 6.2.0 breaks compilation

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#1166]
PIO 6.2.0 is out with [Arduino 2.0.8](https://github.com/espressif/arduino-esp32/releases/tag/2.0.8) and IDF 4.4.4 but breaks ESPAsyncWebServer because of the FlashStringHelper that was removed and added back again in WString.h. https://github.com/espressif/arduino-esp32/pull/7941

Need to find a work-around.

**Comment by MichaelDvP** [comment]
Workaround is to edit 5 files in asyncWebServer:

[ESPAsyncWebServer.zip](https://github.com/emsesp/EMS-ESP32/files/11361392/ESPAsyncWebServer.zip)

**Comment by proddy** [comment]
Thanks @MichaelDvP ! It compiles and I'll include in my latest dev-11 PR which I'm testing now
