### ISSUE TITLE
Need fresh test data

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#1168]
@MichaelDvP I need fresh test data to test the WebUI and it's new functionality. Today I'm using my old setup from years ago with just 2 devices and it'll be good to get some more EMS devices and data in, like the Solar and Mixer from your setup:

![image](https://user-images.githubusercontent.com/1230712/236392000-9e363557-706a-46c6-88c1-bf81ef9aeba0.png)

What you'll need to do is grab the output from `/rest/deviceData` endpoint for each of those id's. It will be compressed, so either modify the code to not use `MsgpackAsyncJsonResponse` in `WebDataService::device_data()` or just send me the binary files capturing direct from the browsers dev window (after a ctrl-r in Network tab). Or you can use a script like on Linux/Windows WSL:
```sh
curl --output - -X POST -H "Content-Type: application/json" -d '{"id": 1}' http://ems-esp.local/rest/deviceData | msgpack2json -d
```

Then I can add to `server.js` and continue testing the new web changes.

thanks

**Comment by MichaelDvP** [comment]
[Devices.zip](https://github.com/emsesp/EMS-ESP32/files/11404203/Devices.zip)

**Comment by proddy** [comment]
Thanks Michael. I've updated the test data and added to my open PR
