### ISSUE TITLE
NTP: cant apply changed timezone 

### ISSUE THREAD

**Issue by g6094199** [emsesp/EMS-ESP32#1182]
### PROBLEM DESCRIPTION
on NTP settings: if u try to change timezone only (without changint the ntp server) the apply button does not appear.

### REQUESTED INFORMATION

_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x ] Searched the problem in [issues](https://github.com/emsesp/EMS-ESP32/issues)
- [ ] Searched the problem in [discussions](https://github.com/emsesp/EMS-ESP32/discussions)
- [ ] Searched the problem in the [docs](https://emsesp.github.io/docs/Troubleshooting/)
- [ ] Searched the problem in the [chat](https://discord.gg/3J3GgnzpyT)
- [ ] Provide the output of http://ems-esp.local/api/system :

```lua
v3.6.0-dev.12


```

### TO REPRODUCE

change  the timezone . no apply button appears

**Comment by MichaelDvP** [comment]
Yes, i can reproduce. As temporary workaround: 
- change timezone
- disable NTP
- apply settings
- enable NTP
- apply settings
