### ISSUE TITLE
Setting Request: Dew Point Temperature Difference

### ISSUE THREAD

**Issue by MichScha** [emsesp/EMS-ESP32#1190]
### PROBLEM DESCRIPTION

For cooling the HP uses the dew point as the lowest possible temperature. You should not use the dew point as the reference but something above the value. This is the setting for the offset

- name: Dewpoint Temperaturedifference
- unit: k
- limits: 2-10

```
3 - 002+00:19:46.546 N 446: [emsesp] thermostat(0x10) -B-> All(0x00), ?(0x0467), data: 03 (offset 4)
4 - 002+00:20:29.346 N 473: [emsesp] thermostat(0x10) -B-> All(0x00), ?(0x0467), data: 04 (offset 4)
```

```
System: RC300 in WLW196i
    "version": "3.6.0-dev.12",
    "platform": "ESP32",
```

**Comment by proddy** [comment]
@MichaelDvP something to add?

**Comment by MichScha** [comment]
See  #1187

**Comment by MichScha** [comment]
@MichaelDvP Seems that the json entry doesn´t serve the correct min/max values.
They should be 2-10

```
{
  "name": "dewoffset",
  "fullname": "hc1 dew point offset",
  "circuit": "hc1",
  "value": 4,
  "type": "number",
  "min": 0,
  "max": 254,
  "uom": "K",
  "readable": true,
  "writeable": true,
  "visible": true
}
```

**Comment by MichaelDvP** [comment]
@MichScha For most of the values we do not know the min/max values, so it shows the range of the datatype (UINT: 0-254, 255=not set). Check in settings customizations the limits. You can set a custom limit there, but if you know the limits, tell us we can add to code, saving the memory needed for the custom setting. (I'll add 2-10 to dewoffset).
