### ISSUE TITLE
 Setting Request: Roomtemperature Switching Difference

### ISSUE THREAD

**Issue by MichScha** [emsesp/EMS-ESP32#1191]
### PROBLEM DESCRIPTION

It is possible to set the Switching Difference based on the Rommtemperature

- name: Roomtemperature Switching Difference
- unit: k
- limits: 1-10

```
2 - 002+00:21:23.184 N 497: [emsesp] thermostat(0x10) -B-> All(0x00), ?(0x0467), data: 02 (offset 3)
```

```
System: RC300 in WLW196i
    "version": "3.6.0-dev.12",
    "platform": "ESP32",
```

**Comment by proddy** [comment]
@MichaelDvP something to add?

**Comment by MichScha** [comment]
Tested and works with latest test-version - R / W
@proddy probably you want to tag with 3.6.0
