### ISSUE TITLE
Italian Language

### ISSUE THREAD

**Issue by cicos99** [emsesp/EMS-ESP32#1199]
Hi everyone ,

in the attachment the files for the Italian language .
Sorry but I left only English and German because it was too messy to enter a new language ..
Greetings to all

[ENG_DE_ITA_EMS_ESP32_v3.6_dev.zip](https://github.com/emsesp/EMS-ESP32/files/11926763/ENG_DE_ITA_EMS_ESP32_v3.6_dev.zip)

**Comment by proddy** [comment]
Thanks @cicos99 . We'll merge into dev after the other pending changes.

**Comment by MichaelDvP** [comment]
> Sorry but I left only English and German because it was too messy to enter a new language ..

A while ago i've converted to excel to make editing easier. I've added your translation, please check. There are some new translations for ventilation in the dev, could you please add the few missing, also some new in the web-index (i've renamed ts->txt for uploading here, last 20 lines are new).
BTW: Very good and complete work!


[index.txt](https://github.com/emsesp/EMS-ESP32/files/11928947/index.txt)
[locale_translations_w_it.xlsx](https://github.com/emsesp/EMS-ESP32/files/11928948/locale_translations_w_it.xlsx)

**Comment by MichaelDvP** [comment]
@cicos99 The translation is included in the dev2 branch.
@proddy Should we add a Development-bin here to have more testers? I've build the dev2 to https://github.com/MichaelDvP/EMS-ESP32/releases/tag/latest

**Comment by proddy** [comment]
@MichaelDvP yes, was thinking the same. If you could extend the github actions are do a separate dev2 build that would be great.

Shall I look at getting the standalone C++ working?

**Comment by proddy** [comment]
IT added to the new Test build: https://github.com/emsesp/EMS-ESP32/releases/tag/test

**Comment by proddy** [comment]
Thanks. If you have the repo forked you can test locally without needing to build and upload the firmware to an EMS-ESP. Just install nodejs/npm and yarn, and run `yarn run standalone` from the interface directory. For the first install, you will also need to run`yarn`in the `mock-api` folder. Instructions are in https://emsesp.github.io/docs/Building/#testing-locally

**Comment by proddy** [comment]
close this @MichaelDvP?

**Comment by MichaelDvP** [comment]
I think it's all implemented, we have to ask @cicos99: Ok to close?

**Comment by proddy** [comment]
closing for now - can re-open if we find issues
