### ISSUE TITLE
JSON formatting problem

### ISSUE THREAD

**Issue by tp1de** [emsesp/EMS-ESP32#1213]
I had an user of my ioBroker Adapter reporting crashes while reading his heatpump values.
I recognized that this was due to formatting within the JSON values for the field:

boiler.uptimecomppool 
{ "name": "uptimecomppool", "fullname": "operating time compressor pool", "circuit": "", "value": 71582784., "type": "number", "uom": "minutes", "readable": true, "writeable": false, "visible": true }

Javascript JSON.parse is crashing on the value field ending with a decimal point.  
I changed my ioBroker Adapter code to avoid crashing but it would be better to change the formatting ems-esp code either to avoid a decimal point the end or add 1 decimal place ... e.g. 71582784.0

**Comment by proddy** [comment]
which version of EMS-ESP is this?

**Comment by tp1de** [comment]
Originally 3.5.1 as delivered from BBQKees. But the User tested with latest 3.6 dev as well. 
Formatting was the same ... I can't judge

**Comment by tp1de** [comment]
https://github.com/tp1de/ioBroker.ems-esp/issues/20#issuecomment-1627384694

**Comment by MichaelDvP** [comment]
The ending 0 is cut because render_value uses char[10]. Easy fix.

**Comment by proddy** [comment]
fixed
