### ISSUE TITLE
Show Wifi SSID and strength (RSSI) in Network Status web page

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#1271]
Network Status page is missing some important data, like the SSID and Wifi Strength.

**Comment by MichaelDvP** [comment]
added in my dev1d (SSID was there, only RSSI missing)

**Comment by MichaelDvP** [comment]
BTW: Should we color the icon to show wifi quality, <-85dBm => red, <-75dBm orange, else green (because of #1264)?

**Comment by proddy** [comment]
excellent idea, let me know if you need help

**Comment by MichaelDvP** [comment]
added to PR #1284
