### ISSUE TITLE
(ESP32) Ethernet support

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#13]
Option to use an Ethernet/LAN connection, and disabling WiFi.

**Comment by proddy** [comment]
@crocchietta I'm making some changes to how the ethernet settings are stored, so please don't update to any latest Dev builds just yet. It'll break your config. I'll let you know when it's completed

**Comment by crocchietta** [comment]
@proddy : ok, thanks.

**Comment by proddy** [comment]
built and ready to test. Now WiFi and Ethernet work together. Use a blank SSID to disable Wifi. If the Ethernet drops it will start the AP captive portal.
