### ISSUE TITLE
minor translation issue, missing Warmwater in some names

### ISSUE THREAD

**Issue by harvey637** [emsesp/EMS-ESP32#1301]
Hi,

just a reminder:

some (german) translation use the same wording for eg. "total consumption" AND "total consumption warmwater"
... the additional word ".... Verbrauch Warmwasser" would clarify this without checking the internal names. Also this leads to some duplicate german names. With memory constraints this could also be an additional WW :-)

![grafik](https://github.com/emsesp/EMS-ESP32/assets/10156426/52062f99-e4c9-4d81-b397-2ad865f0891f)

thank you
harvey

**Comment by MichaelDvP** [comment]
I think they should be tagged with DHW/WW, added to my testbuild

**Comment by MichaelDvP** [comment]
With the tags added we have some dhw values with double dhw in name now:
![grafik](https://github.com/emsesp/EMS-ESP32/assets/59284019/d60a8669-a4cc-40d9-929b-0adecf4643b1)
Sometimes it also depends on translation.

**Comment by proddy** [comment]
I think that should be fine, unless someone complains
