### ISSUE TITLE
version 3.7.0 vs.3.6.2 - confused ??

### ISSUE THREAD

**Issue by zibous** [emsesp/EMS-ESP32#1307]
### PROBLEM DESCRIPTION

I'm confused with the version information. Since version 3.6 was unstable, I loaded version 3.7.0-dev.2 (ESP32). 

Runs for several days without any problems. 

But I don't know how to access the current stable version since there is no longer 3.7.0?

![Bildschirmfoto 2023-09-28 um 12 51 27](https://github.com/emsesp/EMS-ESP32/assets/30198737/188efb7f-7176-495c-8530-db76dd096642)

**Comment by proddy** [comment]
3.7.0-dev.2 was renamed to 3.6.2 after we found issues with WiFi and Mesh networks on the latest espressif core. We'll release 3.6.2 as the next official version tonight
