### ISSUE TITLE
Add timestamp in MQTT shower message

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#1329]
From the discussion https://github.com/emsesp/EMS-ESP32/discussions/1328 started by @sciurius

he said in HA we use the `last-updated` property of the sensor to determine the timestamp. Sometimes it's not accurate and would be nicer to add the timestamp to the `shower_data` MQTT payload which is persisted.

**Comment by proddy** [comment]
@MichaelDvP said:

"If the esp32-RTC isproper set by NTP, thermostat or manual we can add it.
Do you need timestamp or a time-string (or both)? Of shower end or start/end?
e.g.

{"duration":600, 
"timestamp": 1697294490,
"time":"2023-10-14T16:42:07"
}"

**Comment by proddy** [comment]
I think time in HH:MM:SS is universal and ok. It's just for displaying in the Home Assistant dashboard.

**Comment by sciurius** [comment]
A timestamp (seconds since epoch) would avoid timezone issues. Otherwise `"2023-10-14T18:46:44+0200"` is ok.

**Comment by proddy** [comment]
@MichaelDvP shall you add or I?

**Comment by MichaelDvP** [comment]
For the publish it's only 
```
                        time_t now = time(nullptr);
                        if (now > 1576800000) { // year 2020
                            doc["timestamp"] = now; // if needed
                            tm *   tm_ = localtime(&now);
                            char dt[25];
                            strftime(dt, sizeof(dt), "%FT%T%z", tm_);
                            doc["time"] = dt;
                        }
```
but for the HA config it's better you add it to test and choose the right types.

**Comment by proddy** [comment]
thanks, I'll add and do a PR now. Along with https://github.com/emsesp/EMS-ESP32/issues/1323
