### ISSUE TITLE
Home Assistant API (ESPHOME like)

### ISSUE THREAD

**Issue by TimoFriedri** [emsesp/EMS-ESP32#133]
Hi,

do you have any plans to integrate the native Home Asisstant API. This works very nice as one can see with the ESPHome project and the according integration in HA.
For me the best part, you can skip MQTT, which I personally do not like so much.

Some Info:

https://esphome.io/components/api.html
https://www.home-assistant.io/components/esphome/

Greetings
Timo

**Comment by proddy** [comment]
moved to EMS-ESP32 project. HA MQTT Discovery kinda sucks and it's about time to move to using the new APIs.

https://developers.home-assistant.io/docs/creating_component_index/
