### ISSUE TITLE
Energy statistics entity nrgheat double counts ww preparation

### ISSUE THREAD

**Issue by tp1de** [emsesp/EMS-ESP32#1335]
@MichaelDvP 
I switched on heating 2 days ago and recognized that nrgheat includes now ww preparation as well. 

I see that my heating pumps are off when ww preparation is done. Nevertheless the nrgheat value increases during ww preparation.
thermostat_hc .._wwprio is true so nrgheat should not increase. 

How do you determine and differentiate between heating/ww preparation?

**Comment by MichaelDvP** [comment]
Please check if `heating_active` and `tapwater_active` is right. Do have a 3-way-valve or charge pump? With chargepump check if the heatingpump turns off for dhw preparation.

**Comment by tp1de** [comment]
tapwater_active is ok. I am using wwcharging since I do have a ww storage tank- but they share the same data.

heatingactive was on during ww preparation and off afterwards since boiler temp was too high for heating circuits.
So heating active is not the right indicator. Within RC310 there are parameters to be configure if ww prep has priority to heating circuits or not. This can be set per hc. I believe that most installations will use ww priority.

To check this within ems-esp either test thermostat hcxx wwprio if aktivated or check the heating pumps if switched off.

**Comment by tp1de** [comment]
Since it it not possible to split energy consumption between ww and heating when ww priority is not set, 
I believe ist fair enough to just check tapwater_active or wwcharging. When active then heating is off. 
This avoids double counts.

**Comment by tp1de** [comment]
@MichaelDvP There is no change in latest dev.5 version.  It's still the double count. 
Could you please give a short status update?

**Comment by MichaelDvP** [comment]
It's fixed in my dev2, I'll make a PR when the changes are confirmed to work (EM100, roomcontrol, heatpump energy, etc.)
My dev build is much behind the official, i concentrate on the dev2 now.

**Comment by proddy** [comment]
@MichaelDvP did this make it to the 3.6.3?

**Comment by tp1de** [comment]
Energy statistics are very exact .... better then from km200.
Please release.

**Comment by tp1de** [comment]
@MichaelDvP I lost any transparency if this topic is still open or in the meantime within original dev?

**Comment by MichaelDvP** [comment]
I think it's in the official dev, but i have no possibility to check, If you think it's ok now, close the issue.
