### ISSUE TITLE
Add message 0x4AE (HP energy counters w/ hi resolution)

### ISSUE THREAD

**Issue by KarstenBr** [emsesp/EMS-ESP32#1349]
### PROBLEM DESCRIPTION
Up to version 3.6.3dev3 message 0x4AE is not processed. It is being provided by my heatpump Bosch CS6800i and contains at least the same energy counters as message 0x494 but using a 100 times higher resolution in 0x4AE.

### REQUESTED INFORMATION
I did a respective read and compared it to the actual values provided by the heatpump itself.
ems-esp:$ read 8 0x4ae
003+02:06:46.230 N 17: [emsesp] boiler(0x08) -W-> Me(0x0B), ?(0x04AE), data: 00 00 BD C4 00 00 5B 6A 00 00 00 24 00 00 62 59 00 00 00 00 00 00 00 00
003+02:06:46.268 N 18: [emsesp] boiler(0x08) -W-> Me(0x0B), ?(0x04AE), data: 00 00 00 00 00 00 00 00 (offset 24)

At the same time the energy counters of the heatpump are as follows:
total energy: 485.80 kWh
energy for heating: 234.02 kWh
energy for warm water: 251.77 kWh

### EXPECTED BEHAVIOUR
Message 0x4AE added to the SW with the following entities
total energy: 32bit integer, offset 0, divider 100, unit kWh
energy used for warm water: 32bit integer, offset 4, divider 100, unit kWh
energy used for heating: 32bit integer, offset 12, divider 100, unit kWh

**Comment by proddy** [comment]
In https://github.com/emsesp/EMS-ESP32/releases/tag/test
