### ISSUE TITLE
Add message 0x4AF (HP electrical meters w/ hi resolution)

### ISSUE THREAD

**Issue by KarstenBr** [emsesp/EMS-ESP32#1350]
### PROBLEM DESCRIPTION
Up to version 3.6.3dev3 message 0x4AF is not processed. It is being provided by my heatpump Bosch CS6800i and contains at least the same electrical meters as in message 0x495 but using a 100 times higher resolution in message 0x4AF.

### REQUESTED INFORMATION
I did a respective read and compared it to the actual values provided by the heatpump itself.
ems-esp:$ read 8 0x4af
003+02:07:38.316 N 19: [emsesp] boiler(0x08) -W-> Me(0x0B), ?(0x04AF), data: 00 00 48 B2 00 00 48 55 00 00 00 5D 00 00 01 78 00 00 00 00 00 00 07 61
003+02:07:38.373 N 20: [emsesp] boiler(0x08) -W-> Me(0x0B), ?(0x04AF), data: 00 00 24 B0 00 00 00 12 00 00 23 A5 00 00 00 4B 00 00 00 00 00 00 00 00 (offset 24)
003+02:07:38.411 N 21: [emsesp] boiler(0x08) -W-> Me(0x0B), ?(0x04AF), data: 00 00 00 00 00 00 00 00 (offset 48)

At the same time the electrical meters of the heatpump are as follows:
electrical meter, total: 186.10 kWh
electrical meter, compressor: 185.17 kWh
electrical meter, add. electrical heater: 0.93 kWh

### EXPECTED BEHAVIOUR
Message 0x4AF added to the SW with the following entities
total electrical meter: 32bit integer, offset 0, divider 100, unit kWh
electrical meter of compressor: 32bit integer, offset 4, divider 100, unit kWh
electrical meter of add. electrical heater: 32bit integer, offset 8, divider 100, unit kWh

**Comment by proddy** [comment]
In https://github.com/emsesp/EMS-ESP32/releases/tag/test
