### ISSUE TITLE
Inconsistent naming

### ISSUE THREAD

**Issue by unstressable** [emsesp/EMS-ESP32#1366]
Theres no naming difference between:
<img width="694" alt="image" src="https://github.com/emsesp/EMS-ESP32/assets/50423935/15849365-8950-42d1-b36b-a47d4ae9b405">

as it should be:
<img width="693" alt="image" src="https://github.com/emsesp/EMS-ESP32/assets/50423935/01780fc3-765c-40c9-b78c-fc073f6bbe3c">

**Comment by proddy** [comment]
what needs to be changed?

**Comment by unstressable** [comment]
I think at the screenshot above. The clarification of "selflowtemp" should not be the same as for "setflowtemp".
I think it should be as in screenshot below "gewählte Vorlauftemperatur".

**Comment by proddy** [comment]
@MichaelDvP  ?

**Comment by KarstenBr** [comment]
I just checked the entities of my boiler: selflowtemp is correctly named “Sollwert Vorlauftemperatur” as it is indeed the target value computed by the boiler dependent of the outside temperature and used as input for the boiler’s controller of the current flow line temperature. For setflowtemp I cannot comment as it is not provided by my boiler.

**Comment by MichaelDvP** [comment]
This is the same value. `selflowtemp` is taken from UBAMonitor, the value the boiler reports, 'setflowtemp' from the `UBASettings`, what the thermostat tells the boiler. Depending on version we do not process the command telegram and do not show setflowtemp. In actual main/dev we show it: https://github.com/emsesp/EMS-ESP32/blob/df9f75a5c99a6360d3cf68b7d207f37e3558b17a/src/emsesp.cpp#L944-L945

**Comment by SebastianSinger** [comment]
Does not seem to be the same value here. 
![2023_diag](https://github.com/emsesp/EMS-ESP32/assets/65016119/42d5e859-e0cf-4ad9-bfb5-15c75daba8b1)
"selflowtemp" is target value of flow temperature ("Sollwert Vorlauftemperatur") and includes heating and warm water heating. 
"setflowtemp" does not include warm water heating and could be a similar value as "targetflowtemp", but shows jumps to 0° every few seconds. 
Data is taken from Buderus GB 192, EMS-ESP Version 3.6.2. 
I really appreciate this EMS-ESP project and the work you are doing.

**Comment by unstressable** [comment]
thats what I meant to say. Thanks a lot for these data!
I think these 0° values show us the times, where no heating is needed or the gas is off because of hysteresis for example.

So there must be a difference in clarification between these values to make it clear.

Maybe you shouldname it like this in german:
"selflowtemp" -> "Sollwert Vorlauftemperatur Kessel"
"setflowtemp" -> "Sollwert Vorlauftemperatur Heizkreislauf"

**Comment by unstressable** [comment]
another interesting aspect:
these both values are correlating:
<img width="799" alt="image" src="https://github.com/emsesp/EMS-ESP32/assets/50423935/3ecd8e1c-b238-4501-a5ca-001065e7f347">

when "setburnpow" is 0%, then "setflowtemp" is also 0° and vice versa (in my case 100% and 33°)

**Comment by proddy** [comment]
@unstressable can we close this out?

**Comment by unstressable** [comment]
If theres a change in latest version, yes.
If not, then no.

**Comment by proddy** [comment]
what needs to be changed exactly? A PR would be very welcome.

**Comment by unstressable** [comment]
Please change the german description of the datapoint "selflowtemp" to "Gewählte Vorlauftemperatur".

This should make it more clear. Thanks!

**Comment by proddy** [comment]
@MichaelDvP ok?

**Comment by MichaelDvP** [comment]
I don't think it matters much, we have also the feature to rename the entities indvidual.
If we change, than we should also change other languages to have different names for these:
```
MAKE_TRANSLATION(selFlowTemp, "selflowtemp", "selected flow temperature", "Sollwert Vorlauftemperatur", "Ingestelde aanvoertemperatuur", "Börvärde Flödestemperatur", "wybrana temperatura zasilania", "valgt turtemperatur", "température de flux selectionnée", "seçili akış sıcaklığı", "flusso temperatura selezionato", "zvolená teplota prívodu")
MAKE_TRANSLATION(setFlowTemp, "setflowtemp", "set flow temperature", "Sollwert Vorlauftemperatur", "Ingestelde aanvoertemperatuur", "Börvärde Flödestemperatur", "zadana temperatura zasilania", "innstilt turtemperatur", "température du flux définie", "akış sıcaklığını ayarla", "impostare temperatura di mandata", "nastavená teplota prívodu")
```
and these
```
MAKE_TRANSLATION(selBurnPow, "selburnpow", "burner selected max power", "Sollwert Brennerleistung", "Ingestelde maximale brandervermogen", "Brännare vald maxeffekt", "wybrana moc źródła ciepła", "settpunkt brennerkapasitet", "puissance max du brûleur selectionnée", "seçili kazan maksimum güç", "Setpoint potenza bruciatore", "horák zvolený maximálny výkon")
MAKE_TRANSLATION(setBurnPow, "setburnpow", "burner set power", "Sollwert Brennerleistung", "Ingesteld brandervermogen", "Värmepanna vald Effekt", "zadana moc palnika", "varmekjele valgt effekt", "puissance du brûleur définie", "kazan gücünü ayarla", "impostare potenza bruciatore", "výkon nastaveného horáka")
```
@unstressable: Please make a PR

**Comment by unstressable** [comment]
What is a PR?

**Comment by proddy** [comment]
> What is a PR?

It's a Git Pull Request. Basically modifying the code and submitting a change to be merged. Easiest way is via https://github.com/emsesp/EMS-ESP32/blob/dev/src/locale_translations.h to edit the translations from the browser and at the bottom of the page it'll give you a button to submit the changes as a PR

**Comment by unstressable** [comment]
Done. Thx.
