### ISSUE TITLE
support String entities in Home Assistant

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#1373]
Reported in https://github.com/emsesp/EMS-ESP32/issues/600#issuecomment-1786988227 String's are sent as sensor's in HA and thus not editable/writable. The change here is to explore using https://www.home-assistant.io/integrations/text.mqtt which was added to HA in December last year after the the original EMS-ESP HA discovery code was written.

This will also benefit other String entities like thermostat's datetime, holiday programs, wwswitchtime etc

**Comment by proddy** [comment]
added to dev2 (test build)

**Comment by masterx1981** [comment]
Thanks for this fix. Now i can also sync the time of the heat pump via ha, using the ntp ha time 😅
