### ISSUE TITLE
EMS-ESP32 naming convention changed after upgrade. My historical data in Home Assistant are messed up

### ISSUE THREAD

**Issue by bartplessers** [emsesp/EMS-ESP32#1392]
### PROBLEM DESCRIPTION

I'm using EMS-ESP32 with Home Assistant to generate some long term graphs.
This is done by registering sensor values in InfluxDB and visualisation in Grafana.
Typical example:

![2023-11-06_16-11-34](https://github.com/emsesp/EMS-ESP32/assets/10470708/0f39db95-db81-44a1-834e-a50985e84984)

Now, my ESP32 board broke and I had to replace it.
As a good customer, after replacing the ESP32 board, flashing with newest firmware version 3.6.2 (ESP32), I cleaned the ems-topic on my MQTT broker.
Started EMS-ESP32 and everything works fine.... until I noticed that a lot of my sensors were renamed 

I.e. 

```
old name of entity in Home Assistant
new name of entity in Home Assistant
```

```
sensor.boiler_heating_pump_modulation
sensor.boiler_heatingpumpmod
```

```
boiler_burner_current_power
sensor.boiler_curburnpow
```

```
number.boiler_selected_flow_temperature
number.boiler_selflowtemp
```

```
sensor.boiler_current_flow_temperature
sensor.boiler_curflowtemp
```

```
sensor.boiler_return_temperature
sensor.boiler_rettemp
```

But his also means that I lost my historical data in Home Assistant !!!!

My graph now looks like:
![2023-11-06_16-31-03](https://github.com/emsesp/EMS-ESP32/assets/10470708/e3704196-2b99-4cfa-83c7-7621e8b0d101)

For some sensors, I can rename them in Home Assistant.
But is there a more structural way to avoid this problem? Is there a way to use the "old" naming convention in v3.6.2?
What is the reason why this naming convention is changed? The old names are more descriptive and clearer to me!

kind regards,
Bart Plessers

**Comment by MichaelDvP** [comment]
Go to mqtt settings:
![grafik](https://github.com/emsesp/EMS-ESP32/assets/59284019/92cf51d1-64ac-460a-b9cf-2e3a19761e61)

**Comment by proddy** [comment]
thanks Michael.

Also @bartplessers as a last resort there's always https://emsesp.github.io/docs/Troubleshooting/#ha-has-messed-up-the-names-of-my-entities

**Comment by MichaelDvP** [comment]
@proddy: I wanted to write that it's also possible to choose long names and set a custom name to keep compatbility if long names change (they do, we have actual a lot of discussion about naming), but see that always the original en-long name is used. Is this intended?

**Comment by bartplessers** [comment]
OK,
- I changed setting to Single Instance, long name, cleared MQTT topic and rebooted device --> no solution
- same as above, but first deleted the devices in home assistant --> OK, "long names" are used now

thanx for prompt reply and help!

>always the original en-long name is used. Is this intended?
not a big issue for me, as long as this name is stable (as it is apparently not?)

For some critical things, I created my own custom sensors in Home Assistant: with a template you can "translate" (and/or manipulate) an incomming mqtt sensor.

I.e.
https://community.home-assistant.io/t/energy-dashboard-how-to-add-integral-template-sensor-to-dashboard/599211/3

```
  # ---------------------------------------------------
  - name: "Elektriciteit datacenter power"
    unique_id: "sensor.elektriciteit_datacenter_power"
    icon: mdi:flash
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    state: >
      {{ states('sensor.tasmota_108_energy_power') | float(default=0.0) }}
    availability: >
      {{ states('sensor.tasmota_108_energy_power') | is_number }}

```
Here, I created my own sensor "sensor.elektriciteit_datacenter_power", based on "sensor.tasmota_108_energy_power".
If for some reason the source changes to sensor.tasmota_108_energy_pwr, or sensor.tasmota_199_energy_power, I can redefine my definition and everything works again. But it takes some work to to....


Just out of interest: why was this decision made from "long name" to "short name"? Were there some issues with long names?

grtz
B

**Comment by proddy** [comment]
> @proddy: I wanted to write that it's also possible to choose long names and set a custom name to keep compatbility if long names change (they do, we have actual a lot of discussion about naming), but see that always the original en-long name is used. Is this intended?

I think it's by design to always use the EN long name, for backwards compatibility with 3.4.
