### ISSUE TITLE
Incomplete Rx

### ISSUE THREAD

**Issue by FunnyPaul** [emsesp/EMS-ESP32#1403]
Hello everyone and thank you for this great project!
I'm new here, have experience with the ESP32 and hardware development and have the system running almost straight away on a BOSCH GC7000F, but I haven't yet set up MQTT etc. I can read all the values etc.

What surprises me, however, is that 
**"... WARNING nnnn: [telegram] Incomplete Rx ..."** 

appears in the system log for every packet. Is this normal or what do I have to do?

Best regards from Germany

**Comment by proddy** [comment]
Look at https://emsesp.github.io/docs/Troubleshooting/#many-rx-errors

**Comment by FunnyPaul** [comment]
Thank you! It was due to my hardware design. I would like to supply the module via the voltage on the bus. I have now optimized this and the errors are gone.

So the case is not an error or bug. It can be closed :-)

**Comment by proddy** [comment]
great!
