### ISSUE TITLE
add boost mode for heating

### ISSUE THREAD

**Issue by Bingo2023** [emsesp/EMS-ESP32#1446]
can we add the command to turn on heating for a settable amount of time?

As you can see in the screenshots, the logfile will include following steps:
- heating off
- boostmode on (3h)
- boostmode deactivated

![Screenshot_20231121-104547](https://github.com/emsesp/EMS-ESP32/assets/61052575/0c95f86e-b0ca-4608-bd42-f51b7debdfd4)
![Screenshot_20231121-104626](https://github.com/emsesp/EMS-ESP32/assets/61052575/b26e5637-cb1c-40d4-90ef-b9b6d876b2af)
![Screenshot_20231121-104703](https://github.com/emsesp/EMS-ESP32/assets/61052575/3780ee5f-d744-4e2d-b400-e24b54a39d49)
[log_Heizung_Boost.txt](https://github.com/emsesp/EMS-ESP32/files/13424639/log_Heizung_Boost.txt)

PS: screenshots and control are done from Buderus App with MX300. HP with BC400 (touch screen) and RC220 remote connected.

**Comment by Bingo2023** [comment]
> Test with https://github.com/MichaelDvP/EMS-ESP32/releases/tag/test
> 
> BTW: in other thermostats (RC30/35) this mode is called "Party mode" and there is also a " Pause mode" to switch the heating off (night) for some hours.

I confirm, it is working great :) - good job !

**Comment by proddy** [comment]
Close this @Bingo2023 ?

**Comment by Bingo2023** [comment]
I'm using it since November - works good.
-> close
