### ISSUE TITLE
Last Error and/or actual error Message not updatet @ GB172 with RC300

### ISSUE THREAD

**Issue by Peter-Aschinger** [emsesp/EMS-ESP32#1453]
### PROBLEM DESCRIPTION

_A clear and concise description of what the problem is._

I use the EMS-ESP32 (with actual 3.6.3 fw)
In the WebIf from EMS-ESP and also MQTT i can see a errormessage from 06.11.23.
When i delete the error history the last errormessage stays in the WebIf and Mqtt.
But during the day occur several same errormessages about lost the connection to the mixer.
This messages did not appear in the webif and also mqtt.

Please see the pictures and screenshot
![PXL_20231121_160033385](https://github.com/emsesp/EMS-ESP32/assets/151680150/ac0c96ef-64b8-4fa5-b36d-3b94d43fa15c)
![PXL_20231121_160053216](https://github.com/emsesp/EMS-ESP32/assets/151680150/c17ecb7b-b5c1-4a7e-a7dc-b917a6ac6c49)
![Screenshot 2023-11-22 181419](https://github.com/emsesp/EMS-ESP32/assets/151680150/5987ba4c-e3ab-4993-9618-e62d25208ac6)

```lua
  System information output here:


```

**Comment by MichaelDvP** [comment]
6A(227) is a flame (ionization) error from boiler, the boiler stores a log in telegrams 0x10, 0x11 and we publish the newest. But these are only boiler errors.
A31 is a communication error, these errors are stored in the thermostat telegrams 0x12, 0x13 for my RC35 and we also show the newest for thermostat last error. Maybe your thermostat use different storage, try to `read 10 12` in terminal.
Actual errors are published in telegram 0xBE and 0xBF from the device that have the error. But these telegrams are not readable, only published on error.

**Comment by Peter-Aschinger** [comment]
i watched the mqtt explorer a while an found out that it is puplished under the thermostat data:
![image](https://github.com/emsesp/EMS-ESP32/assets/151680150/9d748b09-8862-4b35-8307-7b863e6259ab)

**Comment by proddy** [comment]
@Peter-Aschinger what shall we do with this issue?

**Comment by proddy** [comment]
ok, I'll close for now and we can always re-open if it appears again, or others report it.
