### ISSUE TITLE
Get/set compressor max power

### ISSUE THREAD

**Issue by petslane** [emsesp/EMS-ESP32#1475]
I have Bosch Compress CS7800i LW. From HVAC screen, I can change the heat pump "Max. power f. compressor". This is the maximum power heat pump can work in percentage.

On 1. December somewhere at 15:00 I set the max to 85%. From HA history, I can see that it works, although the max speed is actually 78%, not 85%:
![image](https://github.com/emsesp/EMS-ESP32/assets/2674369/15dc51de-7c2f-4719-a4b7-797d445c2137)

I would like to see that max compressor power setting from HA and also I would like to change it from HA.

I thought that "burner selected max power (selburnpow)" is for that, but when i write something to that, then this value will be set to "burner set power (setburnpow)" and "burner selected max power (selburnpow)" remains unchanged. And this setting in HVAC actually does not change.

I opened a telnet connection, started "watch on", and changed the setting from HVAC to 83%, then 86%, and then 90%. From telnet logs, i found that `HpPower` at index 18 is showing that settings:
```
petslane@mf:~$ grep HpPower test2.log 
001+05:56:04.736 N 2: [emsesp] Me(0x0B) -R-> boiler(0x08), HpPower(0x048D), length: 0x19
001+05:56:04.773 N 3: [emsesp] boiler(0x08) -W-> Me(0x0B), HpPower(0x048D), data: 03 00 10 30 1F 45 00 01 01 00 00 3C 00 00 00 2B 17 4E 53 00 00 0B 50
001+05:56:06.324 N 12: [emsesp] boiler(0x08) -B-> All(0x00), HpPower(0x048D), data: 03 00 10 30 1F 45 00 01 01 00 00 3B 00 00 00 2B 17 4E 53 00 00 0B 50
001+05:56:09.648 N 34: [emsesp] boiler(0x08) -B-> All(0x00), HpPower(0x048D), data: 03 00 10 30 1E 44 00 01 01 00 00 3B 00 00 00 2B 17 4E 53 00 00 0B 50
001+05:56:40.438 N 120: [emsesp] boiler(0x08) -B-> All(0x00), HpPower(0x048D), data: 03 00 10 30 1E 40 00 01 01 00 00 3B 00 00 00 2B 16 4D 53 00 00 0B 50
001+05:56:43.413 N 121: [emsesp] boiler(0x08) -B-> All(0x00), HpPower(0x048D), data: 03 00 10 30 1E 40 00 01 01 00 00 3B 00 00 00 2B 17 4D 53 00 00 0B 50
001+05:56:58.063 N 158: [emsesp] boiler(0x08) -B-> All(0x00), HpPower(0x048D), data: 03 00 10 30 1E 42 00 01 01 00 00 3B 00 00 00 2B 16 4D 53 00 00 0B 50
001+05:56:59.439 N 160: [emsesp] boiler(0x08) -B-> All(0x00), HpPower(0x048D), data: 03 00 10 30 1F 42 00 01 01 00 00 3B 00 00 00 2A 17 4D 53 00 00 0B 50
001+05:57:03.414 N 163: [emsesp] boiler(0x08) -B-> All(0x00), HpPower(0x048D), data: 03 00 10 30 1F 44 00 01 01 00 00 3B 00 00 00 2B 17 4D 53 00 00 0B 50
001+05:57:05.088 N 174: [emsesp] Me(0x0B) -R-> boiler(0x08), HpPower(0x048D), length: 0x19
001+05:57:05.125 N 175: [emsesp] boiler(0x08) -W-> Me(0x0B), HpPower(0x048D), data: 03 00 10 30 1F 43 00 01 01 00 00 3B 00 00 00 2B 17 4E 53 00 00 0B 50
001+05:57:06.163 N 181: [emsesp] boiler(0x08) -B-> All(0x00), HpPower(0x048D), data: 03 00 10 30 1F 44 00 01 01 00 00 3B 00 00 00 2A 17 4E 53 00 00 0B 50
001+05:57:22.465 N 271: [emsesp] boiler(0x08) -B-> All(0x00), HpPower(0x048D), data: 03 00 10 30 1F 46 00 01 01 00 00 3B 00 00 00 2B 17 4D 56 00 00 0B 50
001+05:57:25.039 N 281: [emsesp] boiler(0x08) -B-> All(0x00), HpPower(0x048D), data: 03 00 10 30 1E 46 00 01 01 00 00 3B 00 00 00 2B 17 4D 56 00 00 0B 50
001+05:57:26.701 N 289: [emsesp] boiler(0x08) -B-> All(0x00), HpPower(0x048D), data: 03 00 10 30 1F 46 00 01 01 00 00 3B 00 00 00 2B 17 4D 56 00 00 0B 50
001+05:57:50.614 N 331: [emsesp] boiler(0x08) -B-> All(0x00), HpPower(0x048D), data: 03 00 10 30 1E 44 00 01 01 00 00 3B 00 00 00 2B 17 4E 56 00 00 0B 50
001+05:57:58.077 N 343: [emsesp] boiler(0x08) -B-> All(0x00), HpPower(0x048D), data: 03 00 10 30 1F 44 00 01 01 00 00 3B 00 00 00 2B 17 4D 56 00 00 0B 50
001+05:57:58.453 N 344: [emsesp] boiler(0x08) -B-> All(0x00), HpPower(0x048D), data: 03 00 10 30 1F 44 00 01 01 00 00 3B 00 00 00 2B 17 4D 56 00 00 0B 50
001+05:58:04.454 N 355: [emsesp] boiler(0x08) -B-> All(0x00), HpPower(0x048D), data: 03 00 10 30 1F 46 00 01 01 00 00 3B 00 00 00 2B 16 4D 56 00 00 0B 50
001+05:58:05.028 N 358: [emsesp] Me(0x0B) -R-> boiler(0x08), HpPower(0x048D), length: 0x19
001+05:58:05.065 N 359: [emsesp] boiler(0x08) -W-> Me(0x0B), HpPower(0x048D), data: 03 00 10 30 1F 46 00 01 01 00 00 3B 00 00 00 2B 16 4D 56 00 00 0B 50
001+05:58:07.440 N 375: [emsesp] boiler(0x08) -B-> All(0x00), HpPower(0x048D), data: 03 00 10 30 1F 46 00 01 01 00 00 3B 00 00 00 2B 17 4E 56 00 00 0B 50
001+05:58:26.516 N 472: [emsesp] boiler(0x08) -B-> All(0x00), HpPower(0x048D), data: 03 00 10 30 1F 46 00 01 01 00 00 3C 00 00 00 2B 17 4E 5A 00 00 0B 50
001+05:58:36.242 N 479: [emsesp] boiler(0x08) -B-> All(0x00), HpPower(0x048D), data: 03 00 10 30 1F 46 00 01 01 00 00 3B 00 00 00 2B 17 4D 5A 00 00 0B 50
001+05:58:47.566 N 499: [emsesp] boiler(0x08) -B-> All(0x00), HpPower(0x048D), data: 03 00 10 30 1F 46 00 01 01 00 00 3B 00 00 00 2B 17 4D 5A 00 00 0B 51
001+05:59:04.780 N 531: [emsesp] Me(0x0B) -R-> boiler(0x08), HpPower(0x048D), length: 0x19
001+05:59:04.817 N 532: [emsesp] boiler(0x08) -W-> Me(0x0B), HpPower(0x048D), data: 03 00 10 30 1F 46 00 01 01 00 00 3B 00 00 00 2B 17 4D 5A 00 00 0B 51
```

From the source code, it looks like `Boiler::process_HpPower` does not read index 18 at all.

For testing purposes, is it possible to write a new value there using telnet? And if it works, make a separate entity for it?

Using EMS-ESP version v3.6.5-dev.2 

### PROBLEM DESCRIPTION

_A clear and concise description of what the problem is._

### REQUESTED INFORMATION

_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Searched the problem in [issues](https://github.com/emsesp/EMS-ESP32/issues)
- [ ] Searched the problem in [discussions](https://github.com/emsesp/EMS-ESP32/discussions)
- [ ] Searched the problem in the [docs](https://emsesp.github.io/docs/Troubleshooting/)
- [ ] Searched the problem in the [chat](https://discord.gg/3J3GgnzpyT)
- [ ] Provide the output of http://ems-esp.local/api/system :

```lua
  System information output here:


```

### TO REPRODUCE

_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR

_A clear and concise description of what you expected to happen._

### SCREENSHOTS

_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT

_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by MichaelDvP** [comment]
In telnet you can use the send command for a raw telegram:
`call system send "0B 08 FF 12 03 8D xx"` with xx the new value in hex.
Easier is to use web and add a custom entity with device 08, type 48D, offset 18 and make it writeable. This will show up in dashboard and mqtt. If it works we can add the entity.

BTW: your methode is best for sensor values, for settings it's easier to check the log for the command telegram from thermostate to boiler e.g. `thermostat(0x10) -W -> Boiler(0x08), HPPower(0x48D) data: 53 (offset 18)` when changing the value (for themostate values it is a broadcast to All)

**Comment by MichaelDvP** [comment]
This looks ok to me, it's the right custom setting. It could take a minute for custom values to show up, but it should work. What happend when you set a new value by dashboard - custom entitiy? You should see the read/write of offset 31 in the log. Is it overwritten by thermostat?

The process function is not processing offset 31 because you have determined the meaning now and we did not know about before.

**Comment by MichaelDvP** [comment]
Ok, i'll add it to dev and make a PR.
