### ISSUE TITLE
Entity Customisations are saved over reboot, and can not be saved in System->Download

### ISSUE THREAD

**Issue by Pelgarnaal** [emsesp/EMS-ESP32#1476]
### PROBLEM DESCRIPTION

Entity Customisations are saved over reboot.
Entity Customisations are not saved in System->Download. It created a almost empty json file.

**Comment by Pelgarnaal** [comment]
My EMS-ESP version is 3.6.4
<img width="637" alt="Scherm­afbeelding 2023-12-03 om 16 42 22" src="https://github.com/emsesp/EMS-ESP32/assets/152786136/776636e8-9650-4ba6-a6ec-b15b37746a95">


With the following Customisations
<img width="1123" alt="Scherm­afbeelding 2023-12-03 om 16 40 52" src="https://github.com/emsesp/EMS-ESP32/assets/152786136/6d976fec-40fa-4bcc-8238-a301737cb0ce">


Download of customisations result is the following json
<img width="578" alt="Scherm­afbeelding 2023-12-03 om 16 41 37" src="https://github.com/emsesp/EMS-ESP32/assets/152786136/cb89f469-06e0-482f-8972-bd92dd187ee9">

**Comment by proddy** [comment]
ok thanks, checking...

**Comment by MichaelDvP** [comment]
@Pelgarnaal How many entities do you have flaged?  (sum of all devcies) The entities without value (like switchtemp) are not shown/published, there is no need to set the exclude flag. Does it work if you remove some flags?

**Comment by Pelgarnaal** [comment]
Thanks, it works when I remove some flags.

**Comment by proddy** [comment]
@MichaelDvP shall we increase the buffer or add a check and report back a message in the JSON exported file saying "too big!".

**Comment by proddy** [comment]
ok, let's leave as it is for now. This is the first report I've seen from the thousands of users, so low priority.

**Comment by proddy** [comment]
shouldn't happen with Arduino 7 now
