### ISSUE TITLE
Properly parse F7 and F9 telegram type

### ISSUE THREAD

**Issue by hpanther** [emsesp/EMS-ESP32#150]
The CS200 standalone solar controller sends a number of short Version 2 packets to the MS100 on startup and retrieves various data in this fashion.
[CS200-MS100 startup.txt](https://github.com/proddy/EMS-ESP/files/5421432/CS200-MS100.startup.txt)

**Comment by yazend** [comment]
Proddy asked to put my collected data here,
the protocol ems-esp_protocol is this one that was already attached in discord,
Today I had time to log the whole thing again while starting the system, once normally and once as RAW data, I hope this helps with the analysis, In the file Bootup_log_F7_F9 I have already sorted the sequences a bit, these are with ############ divided up.
[Bootup_log_F7_F9.txt](https://github.com/emsesp/EMS-ESP32/files/9960092/Bootup_log_F7_F9.txt)
[ems-esp_protokoll.txt](https://github.com/emsesp/EMS-ESP32/files/9960093/ems-esp_protokoll.txt)
[RAW_Bootup_log_F7_F9.txt](https://github.com/emsesp/EMS-ESP32/files/9960094/RAW_Bootup_log_F7_F9.txt)
