### ISSUE TITLE
MQTT: Home assistant discovery - analog sensor invalid dev section

### ISSUE THREAD

**Issue by arturzx** [emsesp/EMS-ESP32#1516]
### PROBLEM DESCRIPTION

Invalid dev section for analog sensor in HA discovery leads to HA displaying all sensors prefixed with analog sensor name.

### TO REPRODUCE

Add analog sensor.

### EXPECTED BEHAVIOUR

Added analog sensor have separated device ids like others and not leads to change other entities names.

### SCREENSHOTS

![image](https://github.com/emsesp/EMS-ESP32/assets/42235373/76f0bc02-feba-43d1-8179-89876a5e6238)
![image](https://github.com/emsesp/EMS-ESP32/assets/42235373/b8b78a5b-7c6f-452b-b478-693160194e3a)

### ADDITIONAL CONTEXT

Discovery topic value for this sensor
`{
  "stat_t": "ems-esp/analogsensor_data",
  "val_tpl": "{{value_json['05'].value if value_json['05'] is defined and value_json['05'].value is defined else wyłączono}}",
  "obj_id": "analogsensor_05",
  "uniq_id": "analogsensor_05",
  "name": "CWU potrzeba grzania",
  "pl_on": "włączono",
  "pl_off": "wyłączono",
  "dev": {
    "name": "CWU potrzeba grzania",
    "ids": [
      "ems-esp"
    ]
  },
  "avty": [
    {
      "t": "ems-esp/status",
      "val_tpl": "{{'online' if value == 'online' else 'offline'}}"
    },
    {
      "t": "ems-esp/analogsensor_data",
      "val_tpl": "{{'online' if value_json['05'] is defined and value_json['05'].value is defined else 'offline'}}"
    }
  ],
  "avty_mode": "all"
}`

**Comment by arturzx** [comment]
Screenshot from HA devices list:
![image](https://github.com/emsesp/EMS-ESP32/assets/42235373/107397d1-a2ef-4891-ab1a-2ff9bd7135ff)

**Comment by proddy** [comment]
See #1528

**Comment by proddy** [comment]
will fix with 1528
