### ISSUE TITLE
Measuring cost of gas etc.

### ISSUE THREAD

**Issue by mediaDS** [emsesp/EMS-ESP32#153]
Hi proddy,

one topic of your wishlist is:

> Measure amount of gas in m3 per day for the hot water vs the central heating, and convert this into cost.

Do you already have ideas on how to do this? I'm planning on programming something in this direction - we already have:

- gas burner on/off
- gas power while the burner is on
- cost of gas
- we also have the time the gas burner is on
- heating or warm water on/off
- solar power activated

We also have the specification of the gas type in terms of efficiency (we have different types of gas here in Germany with different efficiency) which we can find on the monthly or annual bill. Would be nice if we could throw some ideas together.

have fun,
Dieter

**Comment by Bartekn86** [comment]
meyby is better to use an unused input and connect some sensor to a gas meter ?
