### ISSUE TITLE
Unrecognized EMS device (device ID 0x10, no product ID). Please report on GitHub.

### ISSUE THREAD

**Issue by Lizzard44** [emsesp/EMS-ESP32#1531]
Unrecognized EMS device (device ID 0x10, no product ID). Please report on GitHub.

_A clear and concise description of what the problem is._

000+00:55:28.640 E 28: [telegram] Last Tx Read operation failed after 3 retries. Ignoring request: 8B 90 02 00 1B

_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Searched the problem in [issues](https://github.com/emsesp/EMS-ESP32/issues)
- [ ] Searched the problem in [discussions](https://github.com/emsesp/EMS-ESP32/discussions)
- [ ] Searched the problem in the [docs](https://emsesp.github.io/docs/Troubleshooting/)
- [ ] Searched the problem in the [chat](https://discord.gg/3J3GgnzpyT)
- [ ] Provide the output of http://ems-esp.local/api/system :

{
  "System Info": {
    "version": "3.6.5-dev.7",
    "uptime": "000+00:57:48.855",
    "uptime (seconds)": 3468,
    "platform": "Tasmota Arduino v2.0.14",
    "sdk": "4.4.6",
    "free mem": 161,
    "max alloc": 107,
    "used app": 1597,
    "free app": 387,
    "partition": "app0",
    "reset reason": "Power on reset / APP CPU reset by PRO CPU"
  },
  "Network Info": {
    "network": "WiFi",
    "hostname": "ems-esp",
    "RSSI": -45,
    "IPv4 address": "192.168.178.136/255.255.255.0",
    "IPv4 gateway": "192.168.178.2",
    "IPv4 nameserver": "253.0.0.0",
    "BSSID": "set",
    "static ip config": false,
    "enable IPv6": true,
    "low bandwidth": false,
    "disable sleep": false,
    "enable MDNS": true,
    "enable CORS": false,
    "AP provision mode": "disconnected",
    "AP security": "wpa2",
    "AP ssid": "ems-esp"
  },
  "NTP Info": {
    "NTP status": "connected",
    "enabled": true,
    "server": "192.168.178.2",
    "tz label": "Europe/Berlin"
  },
  "OTA Info": {
    "enabled": false,
    "port": 8266
  },
  "MQTT Info": {
    "MQTT status": "connected",
    "MQTT publishes": 545,
    "MQTT queued": 0,
    "MQTT publish fails": 0,
    "MQTT connects": 1,
    "enabled": true,
    "client id": "ems-esp",
    "keep alive": 60,
    "clean session": false,
    "entity format": 1,
    "base": "ems-esp",
    "discovery prefix": "homeassistant",
    "discovery type": 0,
    "nested format": 2,
    "ha enabled": true,
    "mqtt qos": 0,
    "mqtt retain": false,
    "publish time heartbeat": 60,
    "publish time boiler": 10,
    "publish time thermostat": 10,
    "publish time solar": 10,
    "publish time mixer": 10,
    "publish time other": 10,
    "publish time sensor": 10,
    "publish single": false,
    "publish2command": false,
    "send response": true
  },
  "Syslog Info": {
    "enabled": true,
    "syslog started": true,
    "syslog level": "notice",
    "syslog ip": "192.168.178.3",
    "syslog queue": 0
  },
  "Sensor Info": {
    "analog sensors": 0,
    "analog sensor reads": 0,
    "analog sensor fails": 0
  },
  "API Info": {
    "API calls": 2,
    "API fails": 0
  },
  "Bus Info": {
    "bus status": "connected, tx issues - try a different Tx Mode",
    "bus protocol": "HT3",
    "bus telegrams received (rx)": 841,
    "bus reads (tx)": 0,
    "bus writes (tx)": 0,
    "bus incomplete telegrams": 12,
    "bus reads failed": 85,
    "bus writes failed": 0,
    "bus rx line quality": 100,
    "bus tx line quality": 0
  },
  "Settings": {
    "board profile": "CUSTOM",
    "locale": "de",
    "tx mode": 1,
    "ems bus id": 11,
    "shower timer": false,
    "shower alert": false,
    "phy type": 0,
    "rx gpio": 23,
    "tx gpio": 5,
    "dallas gpio": 0,
    "pbutton gpio": 0,
    "led gpio": 2,
    "hide led": false,
    "notoken api": false,
    "readonly mode": true,
    "fahrenheit": false,
    "dallas parasite": false,
    "bool format": 2,
    "bool dashboard": 2,
    "enum format": 1,
    "analog enabled": true,
    "telnet enabled": true,
    "max web log buffer": 50,
    "web log buffer": 50
  },
  "Devices": [
    {
      "type": "boiler",
      "name": "Condens 2500/Logamax/Logomatic/Cerapur Top/Greenstar/Generic HT3",
      "device id": "0x08",
      "product id": 95,
      "version": "18.04",
      "entities": 67,
      "handlers received": "0x14 0x1C 0x18 0x19 0x34 0x2A 0x04",
      "handlers fetched": "0x16 0x33",
      "handlers pending": "0xBF 0x10 0x11 0xC2 0x15 0x1A 0x35",
      "handlers ignored": "0x03 0x05"
    },
    {
      "type": "controller",
      "name": "Generic Controller",
      "device id": "0x09",
      "product id": 0,
      "version": "00.00",
      "entities": 0
    }
  ]
}

```
every 10 Sec.

_Steps to reproduce the behavior:_

start device

**Comment by proddy** [comment]
the version and product info from EMS devices are fetched by a read command. It looks like your Tx is not working - either faulty hardware or cables. I would check that first.

**Comment by proddy** [comment]
if it's a standard BBQKees board try choosing the board profile that matches (in your config it shows as CUSTOM). Also as the message says try different EMS TxModes depending if you have Buderus or Worcester/Junkers

**Comment by bbqkees** [comment]
Can you show us a clear picture of how exactly you have connected the EMS interface board to your ESP32 board?
Most mistakes are due to wiring the wrong pins.

![image](https://github.com/emsesp/EMS-ESP32/assets/10775682/b49204a1-80db-49e8-98f2-00f78a03dee3)

According to your custom board profile info you gave above RX of the EMS interface board should go to GPIO23 and TX of the board should go to GPIO05.

You also need to connect GND and 3V3 of the ESP32 board to the EMS interface board.

Also the info is not showing the thermostat, check if it connected to the BB terminal or to the 3 wire older bus next to it.
If so, you are rewire it the the BB terminal so it can be seen on the EMS bus.

**Comment by bbqkees** [comment]
Can you check if you have read only mode on by mistake?
![image](https://github.com/emsesp/EMS-ESP32/assets/10775682/40b8e0b8-5fdf-47bf-a4f8-baf48aa98a33)

Then TX is not active.

In your config it is set to true:
`"readonly mode": true`
