### ISSUE TITLE
Set Boiler ww activated via HomeAssist

### ISSUE THREAD

**Issue by krombel** [emsesp/EMS-ESP32#154]
**Is your feature request related to a problem? Please describe.**
I can deactivate the warm water system via WebUI of EMS-ESP but in Homeassist this field is only presented as read only. 

**Why I would like that feature**
I have solar panels on the roof I sometimes turn of the warm water system in the morning as I expect it be heated in the evening either way. For now I look in home assist for the current temperature and need to enable VPN and open a browser when on the go. 

**Describe the solution you'd like**
I wohl like it to be a switch in HomeAssist as well

**Describe alternatives you've considered**
Setting it via Web-UI all the time which is just inconvenient.

**Comment by proddy** [comment]
EMS-ESP exposes all the device values it captures from EMS devices as sensor entities in HA. It's up to the user to create Lovelace dashboard UIs in Home Assistant. There are two ways of doing this, via MQTT or using the RESTful API which is described in  https://emsesp.github.io/docs/#/Home-Assistant?id=home-assistant. 

If you want a switch in HA, go and create one. In your example, I would advise using the API directly.
