### ISSUE TITLE
Progress bar on upload

### ISSUE THREAD

**Issue by MichaelDvP** [emsesp/EMS-ESP32#1564]
In the latest 3.6.4-dev9 the upload progress starts with 350% and counts down to 100%, the bar runs from right to left showing the range 200% - 100%. Only cosmetic, no functioal issue. I have not found a change that causes this. Maybe a updated package?

![grafik](https://github.com/emsesp/EMS-ESP32/assets/59284019/d43ef8b1-5b7c-4dd1-8128-015dbd82a182)

**Comment by proddy** [comment]
hmm, not sure which package but I'll check.

**Comment by MichaelDvP** [comment]
Seems the progress.total and progress.loaded are mixed. Tried to go back to alova 2.16.2, but no luck. I've made a workaround and check what value is greater to calculate the percentage. This works in my tests, but it's better to fix the root cause.

**Comment by proddy** [comment]
thanks, I'll investigate and try and find what has changed. the workaround is perfect for the time being

**Comment by proddy** [comment]
I'm still seeing this error, now and then. I'll re-open and spend some time fixing it. the latest alova lib now exposes event listeners to the upload progress

**Comment by MichaelDvP** [comment]
> I'm still seeing this error, now and then

I think this is due to the cache setting you've added a few days ago. I've commented it out for me, because i often change the versions and get confsed if changes don't show up.

**Comment by proddy** [comment]
good point, will look into that and rollback

**Comment by proddy** [comment]
I've removed the cache, will be in next PR. Let's see if it resolves the issue.

**Comment by proddy** [comment]
I added an etag for better cache management. But this issue with the progress bar is still there, on Mac OSX (edge) so I need to look into the Alova code again.

**Comment by MichaelDvP** [comment]
After updating to alova 2.20.0 the progressbar is not shown anymore.

**Comment by proddy** [comment]
I'll fix

**Comment by proddy** [comment]
I've logged an issue with the Alova team

**Comment by proddy** [comment]
> I've logged an issue with the Alova team

I'm seeing the same problem with earlier versions of Alova, so I suspect its something else that broke the hook. I'm investigating...

**Comment by proddy** [comment]
Alova team have a fix, waiting for the next release.

**Comment by MichaelDvP** [comment]
v2.20.2 is out and working. 
But still `loaded `and `total` are exchanged. The percentage is only shown right for `(total * 100) / loaded`.

**Comment by proddy** [comment]
I'll test as well

**Comment by proddy** [comment]
looks ok to me, I see the progress go from 0 to 100? What am I missing?

**Comment by MichaelDvP** [comment]
The fix for the wrong direction was this check (same for the % number):
https://github.com/emsesp/EMS-ESP32/blob/1487f30c433e6fc87ecbba42c04f9f9ea483dd4f/interface/src/components/upload/SingleUpload.tsx#L91-L93
Works, but would be nice if names `total` and `loaded` match the meaning.

**Comment by proddy** [comment]
ah yes, I remember we had to hack that. I'll report it Alova.

**Comment by proddy** [comment]
I'll make a PR
