### ISSUE TITLE
API get single values (api_data) returns NULL

### ISSUE THREAD

**Issue by MichaelDvP** [emsesp/EMS-ESP32#1565]
With the ArduinoJson v7 the following sequence outputs null to api_data:
```
                    JsonVariant data = json[attribute_s];
                    output.clear();
                    output["api_data"] = data;
```
because the JsonVariant is cleared too.
Changing to 
```
                    String data = json[attribute_s].as<String>();
                    output.clear();
                    output["api_data"] = data;
```
works, because the string is stored separate. I think we always send the `api_data` as string to web and console.  Do i miss something? I can make a PR.

**Comment by proddy** [comment]
no you're correct, that's the only piece I didn't change

**Comment by proddy** [comment]
There's also a bug fix in ArduinoJson 7.0.2 today for document.clear() but not sure if its related. 

https://github.com/bblanchon/ArduinoJson/blob/v7.0.2/CHANGELOG.md

**Comment by MichaelDvP** [comment]
Tested with 7.0.2, but same issue. Seems the JsonVariant is now only a reference to the json document and is deleted on doc.clear(). 
I've changed to String and make a PR.

**Comment by proddy** [comment]
@MichaelDvP yes, JsonVariant is also a reference. I should have spotted this as I had asked before - https://github.com/bblanchon/ArduinoJson/discussions/2023#discussioncomment-8046413
