### ISSUE TITLE
Missing virtual RC100H data entries in 3.6.5-dev.10

### ISSUE THREAD

**Issue by Nxtway** [emsesp/EMS-ESP32#1576]
### PROBLEM DESCRIPTION

I upgrade from 3.6.5-dev.9 to 3.6.5-dev.10, After upgrade in the ems-esp control panel the virtual RC100H is shown, but without any entry. I miss the temperature, humidity and the third entry. After downgrade to 3.6.5-dev.9 to entries are shown and again upgrade to 3.6.5-dev.10 they are missing (meaning the issue is reproducible).
![image](https://github.com/emsesp/EMS-ESP32/assets/82314801/2916b52f-91e1-456e-ae6a-f80f5d2fc14f)

Attached are the logfiles with the working functionality in 3.6.5-dev.9 and same log with the issue in 3.6.5-dev.10
[log_3.6.5-dev.9.txt](https://github.com/emsesp/EMS-ESP32/files/14008931/log_3.6.5-dev.9.txt)
[log_3.6.5-dev.10.txt](https://github.com/emsesp/EMS-ESP32/files/14008933/log_3.6.5-dev.10.txt)

### TO REPRODUCE

_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR

_A clear and concise description of what you expected to happen._

### SCREENSHOTS

_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT

_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by harvey637** [comment]
hi,
same reason I guess;
also humidity and dewpoint is missing in latest builds (....-10)
cu
Harvey

**Comment by MichaelDvP** [comment]
Please try with https://github.com/MichaelDvP/EMS-ESP32/releases/tag/test

**Comment by Nxtway** [comment]
Also in the 3.6.5-test.10 the RC100H node has no entries. 
But yes the entries temperature + humidity are moved into the RC310 node.

![image](https://github.com/emsesp/EMS-ESP32/assets/82314801/92f38fd3-fefd-46f8-9117-d741b08072dc)

**Comment by MichaelDvP** [comment]
Sorry, here was a typo,now it should show up again.

**Comment by MichaelDvP** [comment]
The test and dev builds are different in some changes, It takes some time to add verified changes from test to dev.

**Comment by Nxtway** [comment]
Thanks, the issue is now also fixed in dev build 3.6.5-dev.12
