### ISSUE TITLE
not able to set thermostat/datetime

### ISSUE THREAD

**Issue by SSSlee** [emsesp/EMS-ESP32#1586]
I tried several types of formats to change date and time of my thermostat but all of them result an error messesage because of their length: 

<img width="1689" alt="image" src="https://github.com/emsesp/EMS-ESP32/assets/153392645/7812b320-1a67-4724-9def-175181c8e030">

results: 

<img width="587" alt="image" src="https://github.com/emsesp/EMS-ESP32/assets/153392645/676f0569-17a6-4117-923d-b14c574b8f33">

I'm not sure if that's a bug or it's my fault at the end

**Comment by MichaelDvP** [comment]
As mentioned in the helptext of the input box: 
`< NTP | dd.mm.yyyy-hh:mm:ss-day(0-6)-dst(0/1) >`
The thermostat needs a setting of day-of-week and daylight-saving. Bosch day-of-week is Mo-0, Su-6, not like unix-time
If you have enabled NTP you can just enter "NTP" and the ntp time is set to the thermostat. 
With ntp enabled the thermostat clock is also automaticly set by ems-esp if it differs from ntp.

**Comment by SSSlee** [comment]
Great, works as described by you:

<img width="501" alt="image" src="https://github.com/emsesp/EMS-ESP32/assets/153392645/cac8ac48-eff4-4bff-9130-82dac021b620">

**Comment by proddy** [comment]
I've added some help text to the documentation
