### ISSUE TITLE
MQTT discovery of custom entity  doesn't consider type of data 

### ISSUE THREAD

**Issue by SSSlee** [emsesp/EMS-ESP32#1587]
The datatype of a customized entity isn't mentioned in the belonging MQTT Discovery:

<img width="838" alt="image" src="https://github.com/emsesp/EMS-ESP32/assets/153392645/6578549a-e1d6-4fc6-9a24-182ddbe6eaba">

### Corresponding MQTT discovery: 

{
  "stat_t": "ems-esp/custom_data",
  "val_tpl": "{{value_json['RFM200'] if value_json['RFM200'] is defined}}",
  "obj_id": "custom_RFM200",
  "uniq_id": "custom_RFM200",
  "name": "RFM200",
  "dev": {
    "name": "ems-esp Custom",
    "mf": "EMS-ESP",
    "mdl": "Custom",
    "via_device": "ems-esp",
    "ids": [
      "ems-esp-custom"
    ]
  }
  "avty": [
    {
      "t": "ems-esp/status",
      "val_tpl": "{{'online' if value == 'online' else 'offline'}}"
    },
    {
      "t": "ems-esp/custom_data",
      "val_tpl": "{{'online' if value_json['RFM200'] is defined else 'offline'}}"
    }
  ],
  "avty_mode": "all"
}`

### Discovery for a temperature datatype (in comparsion): 

{
  "uniq_id": "thermostat_dampedoutdoortemp",
  "obj_id": "thermostat_dampedoutdoortemp",
  "stat_t": "ems-esp/thermostat_data",
  "name": "Damped outdoor temperature",
  **"unit_of_meas": "°C",**
  "val_tpl": "{{value_json.dampedoutdoortemp if value_json.dampedoutdoortemp is defined else 0}}",
  **"stat_cla": "measurement",
  "dev_cla": "temperature",**
  "dev": {
    "ids": [
      "ems-esp-thermostat"
    ],
    "name": "ems-esp Thermostat"
  },
  "avty": [
    {
      "t": "ems-esp/status",
      "val_tpl": "{{'online' if value == 'online' else 'offline'}}"
    },
    {
      "t": "ems-esp/thermostat_data",
      "val_tpl": "{{'online' if value_json.dampedoutdoortemp is defined else 'offline'}}"
    }
  ],
  "avty_mode": "all"
}

**Comment by proddy** [comment]
looks like we need to add both "unit_of_meas" and the "stat_cla"

**Comment by proddy** [comment]
@SSSlee if you add those two manually to the discovery topic (using MQTT Explorer) does it fix your issue? Worth trying before I change the EMS-ESP code and unintentionally break something else.

**Comment by proddy** [comment]
fixed in dev13

**Comment by mattblonski** [comment]
Hi,
Noticed in v. 3.6.5 MQTT discovery of external temperature sensor for HA is missing "stat_cla" attribute. So this entity is not recored, nor cannot be added to any statistics card.
![image](https://github.com/emsesp/EMS-ESP32/assets/149416340/7179e68e-a7de-427e-a178-30c5d11522ec)
I added the attribute manually via MQTT Explorer and HA starts recording it.
![image](https://github.com/emsesp/EMS-ESP32/assets/149416340/0f453d7d-8bdb-4016-98a9-5bf66a949724)

**Comment by proddy** [comment]
thanks, created new bug for this
