### ISSUE TITLE
ESP32 brownout detector - could it help us?

### ISSUE THREAD

**Issue by glitter-ball** [emsesp/EMS-ESP32#159]
**Is your feature request related to a problem? Please describe.**
Every now and then issues are reported that turn out to be due to powering issues. When I recently re-flashed my ESP32, I noticed "Brownout detector operated" flash up when the controller restarted using my PC's USB port. Could this feature appearing on the EMS-ESP32 dashboard act as an aid to fault-finding?

**Describe the solution you'd like**
Have a flag on the Dashboard page which shows if the brownout detector has been triggered or a count of operations. More useful might be logging this, under a suitable log-level.

**Describe alternatives you've considered**
Didn't realise it existed until recently - could be useful.

**Additional context**
Lots of online resources discuss the BOD and how it can be used.

**Comment by glitter-ball** [comment]
Yes - don't remember seeing the BOD warning before. I was using a good cable, too. Maybe my ESP32 is poorly which is linked to the restarts and RX Fails seen elsewhere?

**Comment by proddy** [comment]
Michael added the ESP restart reason in the last dev build.
