### ISSUE TITLE
ems-esp returns an error when sending a broadcast message 

### ISSUE THREAD

**Issue by SSSlee** [emsesp/EMS-ESP32#1590]
Oh, this is a bug. Ems-esp checks reads for the reply and writes for `<ack>/<nack>` from the destination. The broadcast is wrongly handled as write and there is no ack.

_Originally posted by @MichaelDvP in https://github.com/emsesp/EMS-ESP32/issues/1588#issuecomment-1916141156_

**Comment by MichaelDvP** [comment]
Fixed in my builds and made a PR.
