### ISSUE TITLE
The consumption calculation is probably wrong

### ISSUE THREAD

**Issue by pavelkonir** [emsesp/EMS-ESP32#1595]
If it will be 100% at 24 kW nominal power, then in 1 hour the consumption must be 24 kWh. But, because it is multiplied in the formula 100x24, the wrongly calculated consumption is 2400kWh.

Percentages should be correctly divided by 100.

file boiler.cpp line 1075

`// store in units of 0.01 kWh, resolution needed: 0.01 Wh = 0.01 Ws / 3600  = (% * kW * ms) / 3600
nrgHeatF_ += ((double)((uint32_t)heatBurnPow * nomPower_ * (uuid::get_uptime() - powLastReadTime_)) / 3600) / 1000UL;`

**Comment by proddy** [comment]
is this a problem we need to fix or enhance in EMS-ESP?
