### ISSUE TITLE
Unrecognized EMS device (device ID 0x17, product ID 65) - Thermostat Buderus, RC 10

### ISSUE THREAD

**Issue by karoti4** [emsesp/EMS-ESP32#160]
I bought a  BBQkees gateway S32 a few days ago. I connected the gateway to the boiler (Buderus Logamax Plus GB022) and the following problems occurred. Please help.

1. Thermostat Buderus RC 10 is not recognized.  I don't know if it's a software/ library problem or a hardware problem?
2. Tx - LOW (67%) boiler is connected via EMS screw terminal  - I tried to set all Tx modes with no result.  I tried to connect a thermostat, with different cables of different lengths with no result (Tx line quaility was 65 - 75%).
![image](https://user-images.githubusercontent.com/92604547/137641704-a06e095a-1aca-45fd-9e38-7a1786930571.png)
3. Tx Errors - mostly:
![image](https://user-images.githubusercontent.com/92604547/137641144-9c7f0742-4b7d-4b58-880f-9e4be76bd686.png)

Is it possible that points 2 and 3 are related to point 1? 

RC 10 - label screenshot:
![image](https://user-images.githubusercontent.com/92604547/137641172-2b4cf7ad-598f-4297-9be0-9ddfe08cbff7.png)

[log.txt](https://github.com/emsesp/EMS-ESP32/files/7360679/log.txt)
[emsesp_system_info (5).txt](https://github.com/emsesp/EMS-ESP32/files/7360682/emsesp_system_info.5.txt)
[emsesp_system_settings (4).txt](https://github.com/emsesp/EMS-ESP32/files/7360684/emsesp_system_settings.4.txt)

**Comment by proddy** [comment]
Thanks for the clear write-up! I'm not sure points 2 and 3 are related but I've added your thermostat to the [latest dev build](https://github.com/emsesp/EMS-ESP32/releases/tag/latest) (version 3.2.2b12) so give that a try and we'll take it from there.

**Comment by karoti4** [comment]
> Thanks for the clear write-up! I'm not sure points 2 and 3 are related but I've added your thermostat to the [latest dev build](https://github.com/emsesp/EMS-ESP32/releases/tag/latest) (version 3.2.2b12) so give that a try and we'll take it from there.

Thank you, for a quick response.

I uploaded a new firmware and now this message pops up:
![image](https://user-images.githubusercontent.com/92604547/137643168-4dd091c7-d0ee-4f2c-8193-ff08c4481b93.png)

[log (1).txt](https://github.com/emsesp/EMS-ESP32/files/7360752/log.1.txt)
[emsesp_system_info (8).txt](https://github.com/emsesp/EMS-ESP32/files/7360753/emsesp_system_info.8.txt)
[emsesp_system_settings (7).txt](https://github.com/emsesp/EMS-ESP32/files/7360754/emsesp_system_settings.7.txt)

**Comment by proddy** [comment]
maybe the old version is cache. to be sure do a ctrl-shift-R in the web page. Also set your tx mode to EMS (1)

**Comment by karoti4** [comment]
The cache is clearedm EMS set to 1 - with no change.

**Comment by MichaelDvP** [comment]
Seems to be a uncommon boiler/contoller, not responding to 10, 11, 1C, 14 telegrams. The 14 is fetched every minute, but normally also broadcasted, i think we can skip the fetch to reduce tx-errors. 

I think the missing devices communication with dev is the waiting for master-poll of KM200 (0x48 device) and this boiler/controller does not send it. We should add a timeout for the send delay if there is no 0x48 in a minute. 

@proddy Should i fix it and push, or do you have other changes in pipeline?

**Comment by proddy** [comment]
@MichaelDvP how did you know about the KM200 controller? I couldn't see if from the logs. Your fix makes sense if the KM200 is not returning a poll. I'm only working on the network code (#161)

**Comment by karoti4** [comment]
> > how did you know about the KM200 controller? I couldn't see if from the logs. Your fix makes sense if the KM200 is not returning a poll.
> 
> @proddy This was the change from #90, we are only waiting for the poll from master to 0x48, not for the reply of km200. But it seems this boiler is older than km200/modem devices and does not send out this poll.
> 
> @karoti4 Please check with new dev (version unchanged) if my assumption was right.

@MichaelDvP OK, thank you,  I'll try it in the evening.

**Comment by karoti4** [comment]
I appreciate and thank you for your quick feedback and help.

Actual state after uploading last EMS-ESP Version v3.2.2b13 is:

1) Tx is OK 👍 
![image](https://user-images.githubusercontent.com/92604547/137785128-9f0a2473-2874-4c8d-b347-b107c6cbe524.png)

2) Thermostat RC10 is recognized, but there are no data available for this device (for me mainly temperature): 
![image](https://user-images.githubusercontent.com/92604547/137785933-a8149e75-fc10-4c95-b5f0-86317e325fd3.png)

3) I tried change few editable boiler parameters - some of them works, some not - maybe the parameters that do not work are related to the thermostat (but there is no data) or my boiler does not support them. 

[emsesp_system_info (10).txt](https://github.com/emsesp/EMS-ESP32/files/7367754/emsesp_system_info.10.txt)
[log (2).txt](https://github.com/emsesp/EMS-ESP32/files/7367755/log.2.txt)
[emsesp_system_settings (9).txt](https://github.com/emsesp/EMS-ESP32/files/7367756/emsesp_system_settings.9.txt)

**Comment by proddy** [comment]
telnet (use telnet on wsl/linux or ptty on windows) to ems-esp.local and then type `watch 17`. Grab about 50-100 lines and post it here

**Comment by karoti4** [comment]
OK - here is the log:

[watch_17_log.txt](https://github.com/emsesp/EMS-ESP32/files/7375293/watch_17_log.txt)

**Comment by MichaelDvP** [comment]
Looks like this thermostat is sending telegram 0xAE and is compatible with RC20_N, not with RC10. I've changed it in database, @karoti4 please check.

**Comment by proddy** [comment]
> Seems to be a uncommon boiler/contoller, not responding to 10, 11, 1C, 14 telegrams. The 14 is fetched every minute, but normally also broadcasted, i think we can skip the fetch to reduce tx-errors.

@MichaelDvP the 0x14 isn't broadcasted on some boiler systems (not mine which is a Nefit CR20). It was also reported by a user "Project" in Discord this morning. So I'll add it back.

**Comment by projectile25** [comment]
Hi , that was me on Discord . When helps  the system is Buderus Logamax plus GB132 with RC35.

**Comment by MichaelDvP** [comment]
No problem anymore, we can fetch this telegram and if karoti4s boiler does not reply, the telegram fetch is toggled (because of  [this](https://github.com/emsesp/EMS-ESP32/commit/0e480bbd94a8d17d5d44b9006cbaa14988337cf7)). The log is not flooded with tx-errors and boilers with telegram 14 like GB132 are polled.
