### ISSUE TITLE
Missing heatpump energy meter for hotwater

### ISSUE THREAD

**Issue by Nxtway** [emsesp/EMS-ESP32#1609]
### PROBLEM DESCRIPTION

I miss the energy meter for hot water of my heatpump.

Please can you add the following code in the file heatpump.cpp:
![image](https://github.com/emsesp/EMS-ESP32/assets/82314801/a29ad1fa-2b85-447b-b9fb-9bf00ee77d4c)

The result might looks like:
![image](https://github.com/emsesp/EMS-ESP32/assets/82314801/a84d9fef-a7e3-4cfe-afe7-e8c6023d8ef6)

Thanks a lot and best regards Martin

**Comment by Nxtway** [comment]
I tried the new test build 3.6.5-test.12a, but the meter value for hotwater is still missing:
![image](https://github.com/emsesp/EMS-ESP32/assets/82314801/58005f68-ccaa-4fdc-8c3c-bb53723c8e47)

**Comment by MichaelDvP** [comment]
Oh, only added to 0x08 devices, now it should work.

**Comment by Nxtway** [comment]
works well in 3.6.5-test.12b
