### ISSUE TITLE
error reading KM200 gateway information (wrong passwords please re-enter) but the passwords are correct

### ISSUE THREAD

**Issue by SkorpionMB** [emsesp/EMS-ESP32#1616]
i get this error message since i try to change over from km200 adapter to ems-esp adapter 
error reading KM200 gateway information (wrong passwords please re-enter) - stop km200 read
i changed the personal password several times and re enered the gatway password but always the same error message 
i typed in the gateway password complete the same way as on the sticker (same as in the km200 adapter)
on the old km200 adapter all worked fine
i changed the log mode of the adapter to all but no addittional messages about the connection attemp
ems-esp v2.6.3
admin v6.13.16
node v 18.18.2
npm v9.8.1
system raspberry 4
heating Bosch mblan2:
software 4.8.2
hardware v1

**Comment by proddy** [comment]
Are you really using version 2.6.3 or is that a typo?

**Comment by MichaelDvP** [comment]
I guess this is a ioBroker releated question, @SkorpionMB  please check https://github.com/tp1de/ioBroker.ems-esp
(@proddy  ems-esp v2.2.3b0 was the latest V2, i think a typo, but also outdated.)

**Comment by SkorpionMB** [comment]
sorry yes it was about  the iobroker adapter
