### ISSUE TITLE
es73 set date and time does not work

### ISSUE THREAD

**Issue by SpaceTeddy** [emsesp/EMS-ESP32#162]
dear all,
I tried to update the date/time setting (type 0x06) via web interface first time. I noticed, that my Sieger es73 controller does not save the change.
Attached log of changing date/time setting.

May somebody check if the date / time change basically works, or is it a problem with my Thermostat controller? Thanks a lot. 

`001+22:23:12.595 I 235: [command] Calling thermostat command 'datetime', value 09:12:19 18/10/2021, id is default
001+22:23:12.595 I 236: [thermostat] Date and time: 18.10.2021-09:12:19
001+22:23:12.595 I 237: [thermostat] Setting date and time
001+22:23:12.663 D 238: [telegram] Sending write Tx [#144], telegram: 0B 10 06 00 15 0A 09 12 0C 13 48 7F
001+22:23:12.707 D 239: [emsesp] Last Tx write successful
001+22:23:12.707 D 240: [telegram] Sending post validate read, type ID 0x06 to dest 0x10
001+22:23:13.334 D 241: [telegram] Sending read Tx [#145], telegram: 0B 90 06 00 20
001+22:23:13.484 D 242: [emsesp] Last Tx read successful`

**Comment by SpaceTeddy** [comment]
no, please do not change it.
i changed `{ 76, DeviceType::THERMOSTAT, F("ES73"), DeviceFlags::EMS_DEVICE_FLAG_RC35}, // 0x10`  to `{ 76, DeviceType::THERMOSTAT, F("ES73"), DeviceFlags::EMS_DEVICE_FLAG_RC30}, // 0x10`
but after that I do receive only date time and error codes. nothing else.

**Comment by SpaceTeddy** [comment]
I did this as well. I received all messages, but Time and dates is not writable via web interface.

**Comment by MichaelDvP** [comment]
boiler_data_ubauptime is no thermostat value and is not influenced by thermostat setting.
> Time and dates is not writable via web interface.

Yes, because RC30 does not accept writing the time (like your ES73), it's useless and misleading to implement a command that does not work. But RC30 have some other settings not in RC35, one is clock calibration value. Maybe this can be used. I dont know how it works.
