### ISSUE TITLE
missing datapoint Solar

### ISSUE THREAD

**Issue by dingeberlin** [emsesp/EMS-ESP32#164]
Hello to all of you,

This is my first Issue here at Github so please excuse my lack of knowledge.
I have an BBQkees gateway E32.
I have the following configuration of components.
All components from Buderus.
SM200 + SM100 as additional for second colektor and a differential control for a chimney.
For warm water i use a MS100.
This to my configuration.

The Problem is that there are missing the data points for the second colektor and the wrm water. 
The gateway find all components. See below.
![grafik](https://user-images.githubusercontent.com/44316642/137706493-e49df12e-34a4-44be-bc8f-fb3ea8c5bac5.png)

In the dashboard only the data for the SM200 is visible. At the end of the datalist from the SM200 are some values from warm water. All values with 1°C or 0°C.
In my youthful recklessness i think the gatway recognizes the additional SM100 as an MS100 for warm water. And then the data collides with the original MS100.
Maybe there is an possibility to say the aditional SM100 (when same handlers as SM200) that is is exactly an SM100?
Can anybody help me to find all available values? In the RC310 everything is fine. So all data must be sent via the bus.
Only the assignment does not seem to fit.

Sorry for my bad english..

Thomas

**Comment by dingeberlin** [comment]
Hey MichaelDvP

thx for your fast respons.
Can you give me a short explanation how to get to te terminal?
Think i will use Putty. When i use it there seems to be a debug mode because there comes new statements every second.
Thanks for your help!

**Comment by dingeberlin** [comment]
@MichaelDvP 
thx for the new iteration.
I have made two logs. First one Pump2 is off. Second one Pump 2 is on.
Maybe i can make a log and go into the manual mode an change the Pump mode between off an 30% or something like that
[log-29.10.21-9-17.txt](https://github.com/emsesp/EMS-ESP32/files/7446071/log-29.10.21-9-17.txt)
[log-29.10.21-10-46.txt](https://github.com/emsesp/EMS-ESP32/files/7446072/log-29.10.21-10-46.txt)

There is a mistake with the numbers:
Collector 2 is not TS4 -> TS7
Cylinder middle is not TS14 -> TS3
Return Temperature is not TS15 -> TS4

Do you have an explanation to built a bin File?

Thomas

.

**Comment by MichaelDvP** [comment]
> Second one Pump 2 is on.

Ok, looks like pump2 modulation is here: `30(0x30) -> All(0x00), ?(0x364), data: 13 (offset 4)` and pump2 flag is in 0x36A, offset 1 `Solar(0x30) -> All(0x00), SM100Status2(0x36A), data: 03 04 03 03 03 03 03 03 03 03 03 03`
> There is a mistake with the numbers:

Renamed. 
[EMS-ESP_solar-3_2_2b14-ESP32.zip](https://github.com/emsesp/EMS-ESP32/files/7446192/EMS-ESP_solar-3_2_2b14-ESP32.zip)
> Do you have an explanation to built a bin File?

[https://emsesp.github.io/docs/#/Building-firmware](https://emsesp.github.io/docs/#/Building-firmware)
(You dont need command line in step 5 if you integrate platformIO in your IDE ([see here](https://platformio.org/install/integration)))

For the settings of solar circuit 2 there should be an extra telegram. [Telegram 0x35A](https://github.com/emsesp/EMS-ESP32/blob/ft_solar/src/devices/solar.cpp#L304-L319) holds only the parameters for circuit 1, but these setting-telegrams are only published on change. Please change one (or more) of the parameters of circuit 2 (e.g. collectormaxtemp or pumpkick) while logging, then we should see this change in the log.

**Comment by dingeberlin** [comment]
@MichaelDvP 

i have made some coments in the api/solar output.
![Unbenannt](https://user-images.githubusercontent.com/44316642/139580101-ee79ab32-672e-420d-9119-d67a86904d44.JPG)
[2021-10-31 commented Solar Data.txt](https://github.com/emsesp/EMS-ESP32/files/7448613/2021-10-31.commented.Solar.Data.txt)

Think we know eyerything..  Thats very great..
If look for something more i will give a sign..

**Comment by dingeberlin** [comment]
Think heatassist valve and heatassist power both good!!
Seen some minutes ago..

**Comment by MichaelDvP** [comment]
@dingeberlin What about the settings-telegram, have you logged it?

**Comment by dingeberlin** [comment]
@MichaelDvP 
here comes the changing protokol.
[changes.txt](https://github.com/emsesp/EMS-ESP32/files/7452241/changes.txt)

some notes with nearly time in minutes:
2.50: kick 2 yes>no - no>yes
5 Einschaltdifferent Differenzregelung 6>7  - 7>6
6 Einschaltdifferenz Heizungsunterstützung 6>8 - 8>6
6:50 Einschaltdifferenz Col2 12,4 > 15,6  -  15,6 > 12,4
7:50 MaxTemp Warm Water 60>70 - 70>60
       Warm Water Temp 50 > 45
       reduzierte warm Water temp 45 - 40
       Warm Water Temp 45 > 46
10 Zirkulation 3/h > permanent - permanent > 3/h
11 Zirkulation Impuls off>on - on>off

Think thats enough for the moment..
If you want i can go to every point and change values, but this takes a long time i think..
But when its helpful i will do..

Thomas

**Comment by dingeberlin** [comment]
in the changing telegram is there only one or all values for this module?

**Comment by MichaelDvP** [comment]
OK, we have telegram 0x35D for collector 2 params, 0x35C for the heat assistance, 0x361 for differential control.
Also 0x7A6 for ww-parameters and 0x7A5 for circulation.
```
kick off: 	000+00:02:58.390 T 1421: [emsesp] Thermostat(0x10) -> Solar(0x30), ?(0x35D), data: 00
kick on:	000+00:03:10.765 T 1546: [emsesp] Thermostat(0x10) -> Solar(0x30), ?(0x35D), data: FF
on diff: 7.0:	000+00:04:51.306 T 2099: [emsesp] Thermostat(0x10) -> Solar(0x30), ?(0x361), data: 46 (offset 4)
on diff: 6.0:	000+00:05:24.797 T 2356: [emsesp] Thermostat(0x10) -> Solar(0x30), ?(0x361), data: 3C (offset 4)
heat assi: 8.0:	000+00:05:48.395 T 2457: [emsesp] Thermostat(0x10) -> Solar(0x30), ?(0x35C), data: 50
heat assi: 6.0:	000+00:06:07.196 T 2591: [emsesp] Thermostat(0x10) -> Solar(0x30), ?(0x35C), data: 3C
col2 on: 12.4:	000+00:06:53.024 T 2792: [emsesp] Thermostat(0x10) -> Solar(0x30), ?(0x35D), data: 7C (offset 4)
col2 on: 15.6:	000+00:06:58.850 T 2821: [emsesp] Thermostat(0x10) -> Solar(0x30), ?(0x35D), data: 9C (offset 4)
col2 on: 12.4:	000+00:07:20.927 T 3016: [emsesp] Thermostat(0x10) -> Solar(0x30), ?(0x35D), data: 7C (offset 4)
wwMaxTemp 70:	000+00:07:53.726 T 3145: [emsesp] Thermostat(0x10) -> Solar(0x2A), ?(0x7A6), data: 46 (offset 8)
wwMaxTemp 60:	000+00:08:23.840 T 3339: [emsesp] Thermostat(0x10) -> Solar(0x2A), ?(0x7A6), data: 3C (offset 8)
wwTemp: 45:	000+00:08:36.452 T 3409: [emsesp] Thermostat(0x10) -> Solar(0x2A), ?(0x7A6), data: 2D (offset 9)
wwredTemp: 40:	000+00:08:58.377 T 3510: [emsesp] Thermostat(0x10) -> Solar(0x2A), ?(0x7A6), data: 28 (offset 10)
wwredTemp: 45:	000+00:09:16.228 T 3679: [emsesp] Thermostat(0x10) -> Solar(0x2A), ?(0x7A6), data: 2D (offset 10)
wwTemp: 46:	000+00:09:21.755 T 3709: [emsesp] Thermostat(0x10) -> Solar(0x2A), ?(0x7A6), data: 2E (offset 9)
circ cont:	000+00:10:05.804 T 3887: [emsesp] Thermostat(0x10) -> Solar(0x2A), ?(0x7A5), data: 07 (offset 3)
circ 3x:	000+00:10:40.756 T 4127: [emsesp] Thermostat(0x10) -> Solar(0x2A), ?(0x7A5), data: 03 (offset 3)
circ on:	000+00:10:56.207 T 4201: [emsesp] Thermostat(0x10) -> Solar(0x2A), ?(0x7A5), data: FF
circ off:	000+00:11:03.432 T 4272: [emsesp] Thermostat(0x10) -> Solar(0x2A), ?(0x7A5), data: 00
```
Now we can check each of these telegrams in terminal with `read 30 35d`, `read 30 35c`, etc. 
If we have the whole telegram we can check if a value fits to another parameter.
If a value is in doubt you have to log and change. 
> in the changing telegram is there only one or all values for this module?

a module have different telegrams and each hold different values, mostly sorted by topic.

**Comment by MichaelDvP** [comment]
Ok, i have implemented these values. Check names and try to catch the other values
[EMS-ESP-3_2_2b14-ESP32.zip](https://github.com/emsesp/EMS-ESP32/files/7454788/EMS-ESP-3_2_2b14-ESP32.zip)
.

**Comment by PhillyGilly** [comment]
@MichaelDvP would it help if I uploaded this version too?

**Comment by MichaelDvP** [comment]
@PhillyGilly Yes, thanks, more checks are always better.

**Comment by PhillyGilly** [comment]
All good at MQTT and Telnet.
And it's a lovely sunny day here too!
![image](https://user-images.githubusercontent.com/56273663/139836140-c2f3a23d-89d6-4159-87c4-4f2b25d37915.png)

**Comment by dingeberlin** [comment]
hey @MichaelDvP 

i will make a big log at the weekend.
i have no time before..

thomas

**Comment by dingeberlin** [comment]
@MichaelDvP 
I am sorry!! There was no time to make the log..  I will bring it to here when the job gets a bit slower.
Greatings
Thomas
