### ISSUE TITLE
MQTT Request on individual topic ignored after restart of ESP

### ISSUE THREAD

**Issue by ODINServ** [emsesp/EMS-ESP32#166]
**Bug description**
Requests to individual topics for example: ```ems2mqtt/boiler/burnmaxpower``` is ignored, but it is accepted after i toggle the ```Enable MQTT``` to OFF and ON again.

**Steps to reproduce**
* Reset the device using the webinterface
* Publish a message to: ```ems2mqtt/boiler/burnmaxpower``` with data ```40```
* * Observe on telnet that nothing related to the request happens
* Toggle MQTT OFF and ON in webinterface
* Publish a message to: ```ems2mqtt/boiler/burnmaxpower```  with data ```40```
* * Observe on telnet that ```[mqtt] Received boiler => 23 (length 2)``` is printed and EMS request is send

I noticed that when i publish ```{ "cmd": "burnmaxpower", "data": 40 }``` to ```ems2mqtt/boiler``` the request is handled.

**Expected behavior**
* EMS Message is send when publishing to individual topics

**Device information**
{
  "System": {
    "version": "3.2.2b2",
    "uptime": "000+00:16:11.846",
    "uptime_sec": 971,
    "freemem": 124
  },
  "Status": {
    "bus": "connected, instable tx",
    "bus protocol": "Buderus",
    "telegrams received": 913,
    "read requests sent": 202,
    "write requests sent": 2,
    "incomplete telegrams": 0,
    "tx fails": 87,
    "rx line quality": 100,
    "tx line quality": 57,
    "MQTT publishes": 398,
    "MQTT publish fails": 0,
    "dallas sensors": 0,
    "dallas reads": 0,
    "dallas fails": 0
  },
  "Devices": [
    {
      "type": "Boiler",
      "name": "Nefit GBx72/Trendline/Cerapur/Greenstar Si/27i (DeviceID:0x08 ProductID:123, Version:07.00)",
      "handlers": "0x10 0x11 0x14 0x15 0x1C 0x18 0x19 0x1A 0x35 0x16 0x33 0x34 0x26 0x2A 0xD1 0xE3 0xE4 0xE5 0xE6 0xE9 0xEA"
    },
    {
      "type": "Thermostat",
      "name": "RC300/RC310/Moduline 3000/1010H/CW400/Sense II (DeviceID:0x10, ProductID:158, Version:74.01)",
      "handlers": "0xA3 0x06 0xA2 0x12 0x2A5 0x2B9 0x2AF 0x29B 0x2A6 0x2BA 0x2B0 0x29C 0x2A7 0x2BB 0x2B1 0x29D 0x2A8 0x2BC 0x2B2 0x29E 0x2F5 0x31B 0x31D 0x31E 0x23A 0x267 0x240"
    },
    {
      "type": "Controller",
      "name": "BC10 (DeviceID:0x09, ProductID:190, Version:01.04)",
      "handlers": ""
    }
  ]
}

NOTE: My TX seems to be unstable, but that is unrelated to this issue since the request is just not send at all
Also i have no clue why it is unsable

**Additional context**
Backgound:
I've just received my EMS and have it integrated in my OpenHAB setup using a dedicated mosquitto mqtt broker, i am not using the Home Assisted MQTT discovery.

My MQTT settings:
Base name changed to: ems2mqtt
Set Clean Session: enabled
Use Retain Flag: enabled
Topic/Payload format: As individual topics 
Subscribe format: Individual topics, main heating circuit

I guess i am running a beta, but this is how i received my esp i did not update it my self.

**Comment by proddy** [comment]
I don't think there have been any changes between b2 and b13 related to this.

When you say "reset the device using the webinterface" you mean "restart" correct, and not a factory reset? I'll see if I can reproduce it here.

**Comment by ODINServ** [comment]
> I don't think there have been any changes between b2 and b13 related to this.
> 
> When you say "reset the device using the webinterface" you mean "restart" correct, and not a factory reset? I'll see if I can reproduce it here.

Yes indeed restart, not a factory reset

> your Tx looks really unstable yes. It could be a wiring problem or you're using the wrong Tx Mode. What model and brand is your boiler?

I have a (new it is installed like two months) Nefit Trendline II, i've tested EMS settings on EMS and EMS+ seems not to matter. (Currently on EMS+)
The ESP is connected via the service connector with the jack-plug which was in the box

**Comment by ODINServ** [comment]
> ok, I found the bug so will fix it (for the MQTT). For your Tx issues best if you create a new issue, or use Discord to keep this issue clean. I'm using a Trendline too (so is BBQKees) so we should be able to compare

Ok, nice to help :), i will join Discord indeed for the tx issues.

Not sure to ask but my assumption is that when i set
Formatting to: Topic/Payload Format "As individual topics" i do get individual topics like boiler/burnmaxpower aswell is that correct?

![topics](https://user-images.githubusercontent.com/10348749/138316035-2d2febbc-cd74-4081-9f20-2a4e5a4b57fb.png)

I dont see that in mqtt explorer, could that be related, or is this just expected.
