### ISSUE TITLE
Refresh UI - moving settings to one location

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#1665]
Moving some of the web screens around, so focus is on dashboards and settings are all behind one section.

**Comment by proddy** [comment]
![image](https://github.com/emsesp/EMS-ESP32/assets/1230712/77d8ddf3-cb8d-4277-b895-2fbf5f4ded7c)

**Comment by proddy** [comment]
![image](https://github.com/emsesp/EMS-ESP32/assets/1230712/a1a1ca1c-263b-41a7-b84e-5c1cc9b824de)

**Comment by bbqkees** [comment]
Looks great. Now that I think of it it makes more sense to do it this way.
Did you 'dock' the Devices tabs back?

**Comment by proddy** [comment]
That's a good idea, @MichaelDvP—having all the Statuses in one place. I'll think of an elegant way to do that.
yes @bbqkees the Devices and Sensors are no longer tabs, so just one click away

**Comment by proddy** [comment]
Latest is in a PR - https://github.com/emsesp/EMS-ESP32/pull/1667
