### ISSUE TITLE
WWmode

### ISSUE THREAD

**Issue by Bingo2023** [emsesp/EMS-ESP32#1671]
WWmode is broken again see:
https://github.com/emsesp/EMS-ESP32/issues/1452

Thermostat | Rego 3000/UI800/WSW196i/BC400
![image](https://github.com/emsesp/EMS-ESP32/assets/61052575/ab0fb846-4c2c-4658-8a91-98593fa73ef4)

Yesterdays official Version:
EMS-ESP Version
**3.6.5**

**Comment by proddy** [comment]
BC400 never made it to the dev branch (wasn't tagged to 3.6.5 either), so it didn't make the cut to production/stable. It'll be added to the 3.7.0 dev.
