### ISSUE TITLE
Improvemt: Add power off/on possibility for the heatpump(bosch compress 3800i ew)

### ISSUE THREAD

**Issue by mattfro** [emsesp/EMS-ESP32#1696]
I made a custom entity from the message when I turned off/on the heatpump.
![image](https://github.com/emsesp/EMS-ESP32/assets/46936922/37eb90af-3188-4796-8cd8-e7967b915f28)

Value 1 turns off the pump, value 0 turns on the pump. Possible to add it as an entity?

**Comment by MichaelDvP** [comment]
I think using bool as on/off is better, but with we have only 1=on/0=off, so we have to find a name that makes clear the option on/true/1 shuts the heatpump down. What about `shutdown` as name?

**Comment by mattfro** [comment]
Shutdown is fine.
Not possible to invert bool, I mean like have a tag in ems-esp that you want to invert it? Maybe only for one situation it's too much work. Of course I can always do that in hass... so for me it's not a big deal.

**Comment by proddy** [comment]
@MichaelDvP we could ENUM as a new type, with a list of options, in this case it would be '1, 0'

**Comment by MichaelDvP** [comment]
> Not possible to invert bool,

Sure, we can add a new type BOOL_INV, but is it worth for a single entity?
> we could ENUM as a new type

Yes, this should work, but still a bit confusing when using enum as number option, then it's the only entity with on=0. 
Also i think `power_onoff` is not a good name, it's not switching the power, it just stops the pump. For modules we have always the `enable` entity, maybe here we can use `disable`? 
@mattfro What is the Bosch name in manual and UI of the thermostat for this option?

**Comment by mattfro** [comment]
> > Not possible to invert bool,
> 
> Sure, we can add a new type BOOL_INV, but is it worth for a single entity?
> 
Yeah, that is the question :)
> 
> Yes, this should work, but still a bit confusing when using enum as number option, then it's the only entity with on=0. Also i think `power_onoff` is not a good name, it's not switching the power, it just stops the pump. For modules we have always the `enable` entity, maybe here we can use `disable`? @mattfro What is the Bosch name in manual and UI of the thermostat for this option?


Hmm... bosch name in manual, what thermostat option are you thinking about? Not sure If I understand what you mean...
Are you talking what it's called when I turn off the pump?
If that is the case, it's: "Turn off the heatpump" and then when it's turned off, it ask "turn on the heatpump?"

**Comment by MichaelDvP** [comment]
>  it's: "Turn off the heatpump" and then when it's turned off, it ask "turn on the heatpump?"

Changing the entity name is not possible for us, this will give a lot of issues with homeassistant. I prefere a bool state with name `disable` or `shutdown`, what is your preference or suggestion? Also you can rename the entity later in the customization., but for a bool the state `on` will be send a one to the bus and stops the heatpump.

**Comment by mattfro** [comment]
In Swedish, basically: Shut down heatpump
![image](https://github.com/emsesp/EMS-ESP32/assets/46936922/a6174849-e8fa-4f4c-b0c6-cd12b07a6252)
And the next, Turn off(No/Yes), When heatpump is turned off, heatpump and display will turn off. In off state the antifreeze??prevention is going to be off. To reactivate it touch the display. 
![image](https://github.com/emsesp/EMS-ESP32/assets/46936922/1f1c47e8-e373-479b-b969-77a3adc831a4)
Something like that :)

So when it's off, similar window will popup and ask if you want to start the heatpump(yes/no)

**Comment by mattfro** [comment]
So will this be in, in 3.7?
In that case we can close this ticket... 
I can see shutdown entity, but it's hidden. I guess it's because it has no value or am I mistaken?

Found when using customize entity
![image](https://github.com/emsesp/EMS-ESP32/assets/46936922/f422fde8-15a8-42e6-b38d-d37226b39d7a)

**Comment by proddy** [comment]
Entities were initially designed in EMS-ESP for both reading and/or writing. Then we introduced commands like 'reset'. In this case the shutdown is a command (there is no value to read). 

@MichaelDvP shall we introduce a new type in the WebUI for commands (`DeviceValueType::CMD`)?

**Comment by MichaelDvP** [comment]
It is in 3.7dev and telegram 484 is fetched and has other values. It is not a command telegram. The value should show up.

@proddy For DeviceValueType::CMD we need to know the byte length. Custom entities show in dashboard when writeable, also without value to match such a case we need a cmd only.

**Comment by proddy** [comment]
@mattfro are you still not seeing a value for hpshutdown ?

**Comment by mattfro** [comment]
@proddy  yep...
![image](https://github.com/emsesp/EMS-ESP32/assets/46936922/9aca6ed2-53f7-4a3f-9441-76091a531423)

**Comment by proddy** [comment]
@MichaelDvP what shall we do here? It looks like shutdown is an entity with no value set, so it can't be invoked.

**Comment by MichaelDvP** [comment]
We can change the type to DeviceValueType::CMD

**Comment by mattfro** [comment]
@MichaelDvP I tried your latest build, it just seems to restart all the time. The one you build 10-15 min ago.

**Comment by MichaelDvP** [comment]
Can not reproduce, downloaded both bin-files (esp32 and esp32S3) from github and flashed them, both working here. 
Try power-on-reset. If not successful check with serial terminal the boot messages.

**Comment by mattfro** [comment]
Did not see anything else the few seconds I have... only something about ipv6. 
If I manage to load the official dev.10 it works again. Need to see if I can get serial connection...
![image](https://github.com/emsesp/EMS-ESP32/assets/46936922/b02ac339-3372-4ac1-87b0-e4877590994e)
it just reboot's without any information.
![image](https://github.com/emsesp/EMS-ESP32/assets/46936922/af17f82d-089a-4dd4-a4cc-3724740edf1c)

**Comment by proddy** [comment]
it's either an out of bounds error or out of memory error that is causing the EMS-ESP to crash and restart.

**Comment by MichaelDvP** [comment]
Looks like normal boot, i can not see a reboot with stack registers. 
Does the crash happen after the 7 sec uptime? 
Could only be the register of bool CMD `shutdown`, have to check, my boiler does not have this entity.

**Comment by mattfro** [comment]
yes it looks exactly like that... it would just be a reboot without any reason. It's no exactly 7 seconds, sometimes a bit longer sometimes shorter. @MichaelDvP could you make a new build without shutdown of the latest? Just to be sure it's not that. Which is a bit strange if it would cause it to reboot.

**Comment by MichaelDvP** [comment]
Yes it is, i've found the typo in the shutdown registering. Will push a new build.

**Comment by mattfro** [comment]
Much better, thanks @MichaelDvP :)
Shutdown also works, on= shuts down the pump and off= turns it on. :)

**Comment by mattfro** [comment]
So, it's time to close this one also then? ;)

**Comment by proddy** [comment]
yes!
