### ISSUE TITLE
Rename INT, UINT, SHORT, USHORT, LONG to match the standards (like stdint.h)

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#1706]
INT and UINT (for unsigned) are both 1 byte/length with different ranges. It's int8 and uint8 in C/Java
SHORT/USHORT are 2 bytes (int16/uint16)
BOOL is 1 byte (uint8)
LONG is 3 bytes on the EMS bus, but stored as 4 in the ESP32 memory as an unsigned long (uint32)

Should we rename for the custom entities to int8, uint8, int16, uint16, uint24 and add a uint32?
Maybe better to understand and the newer heatpumps have 4byte values for energy and time.

_Originally posted by @MichaelDvP in https://github.com/emsesp/EMS-ESP32/discussions/1700#discussioncomment-9166253_

**Comment by MichaelDvP** [comment]
Ok, i'll make a PR and also rename all DeviceValueType:: to same scheme.
UINT32 for custom entities should work, a problem are the NOTSET for device-entities, UINT24 and UINT32 are both stored as 32 bit types and handles identical.

**Comment by MichaelDvP** [comment]
I think we can close this? 
There is a small issue left, UINT24 and UINT32 are both stored 32 bit and handled by the same `not_set` helper function. For 32 bit values like energy counters in heatpumps they will hide the value if exacly 0x00FFFFFF and reshow from 0x0100000 to 0xFFFFFFFE. But i think it does not matter.

**Comment by proddy** [comment]
Thanks for the quick implementation Michael
