### ISSUE TITLE
Moduline 400: Missing holiday settings

### ISSUE THREAD

**Issue by sciurius** [emsesp/EMS-ESP32#1712]
### PROBLEM DESCRIPTION

The Moduline400 thermostat has settings for holidays, however these are not shown in the UI.

Searching the docs and discussions indicate they are implemented by now (3.7.0-dev4).

### REQUESTED INFORMATION

- [x] Provide the output of http://ems-esp.local/api/system :

```lua
{
   "API Info" : {
      "API calls" : 1,
      "API fails" : 0
   },
   "Bus Info" : {
      "bus incomplete telegrams" : 0,
      "bus protocol" : "Buderus",
      "bus reads (tx)" : 83,
      "bus reads failed" : 0,
      "bus rx line quality" : 100,
      "bus status" : "connected",
      "bus telegrams received (rx)" : 255,
      "bus tx line quality" : 100,
      "bus writes (tx)" : 0,
      "bus writes failed" : 0
   },
   "Devices" : [
      {
         "device id" : "0x08",
         "entities" : 76,
         "handlers fetched" : "0x14 0x16 0x33",
         "handlers pending" : "0xBF 0xC2 0x1A 0x35 0x2A 0xD1 0xE3 0xE4 0xE5 0xE9",
         "handlers received" : "0x10 0x11 0x15 0x1C 0x18 0x19 0x34 0x04",
         "name" : "Topline/GB162",
         "product id" : 115,
         "type" : "boiler",
         "version" : "03.06"
      },
      {
         "device id" : "0x10",
         "entities" : 33,
         "handlers fetched" : "0x41 0xA7 0x40 0x3F 0x3A",
         "handlers pending" : "0x12 0x13",
         "handlers received" : "0xA3 0x06 0xA2",
         "name" : "Moduline 400",
         "product id" : 78,
         "type" : "thermostat",
         "version" : "03.01"
      },
      {
         "device id" : "0x09",
         "entities" : 0,
         "name" : "BC10",
         "product id" : 114,
         "type" : "controller",
         "version" : "01.03"
      }
   ],
   "MQTT Info" : {
      "MQTT connects" : 1,
      "MQTT publish fails" : 0,
      "MQTT publishes" : 181,
      "MQTT queued" : 0,
      "MQTT status" : "connected",
      "base" : "ems-esp",
      "clean session" : true,
      "client id" : "ems-esp",
      "discovery prefix" : "homeassistant",
      "discovery type" : 0,
      "enabled" : true,
      "entity format" : 1,
      "ha enabled" : true,
      "keep alive" : 60,
      "mqtt qos" : 0,
      "mqtt retain" : false,
      "nested format" : 1,
      "publish single" : false,
      "publish time boiler" : 10,
      "publish time heartbeat" : 60,
      "publish time mixer" : 10,
      "publish time other" : 10,
      "publish time sensor" : 10,
      "publish time solar" : 10,
      "publish time thermostat" : 10,
      "publish time water" : 10,
      "publish2command" : false,
      "send response" : false
   },
   "NTP Info" : {
      "NTP status" : "connected",
      "enabled" : true,
      "server" : "ntp.squirrel.nl",
      "tz label" : "Europe/Amsterdam"
   },
   "Network Info" : {
      "AP provision mode" : "disconnected",
      "AP security" : "wpa2",
      "AP ssid" : "ems-esp",
      "RSSI" : -60,
      "TxPower setting" : 78,
      "disable sleep" : false,
      "enable CORS" : false,
      "enable IPv6" : true,
      "enable MDNS" : true,
      "hostname" : "ems-esp",
      "low bandwidth" : false,
      "network" : "WiFi",
      "static ip config" : false
   },
   "OTA Info" : {
      "enabled" : true,
      "port" : 8266
   },
   "Sensor Info" : {
      "temperature sensor fails" : 0,
      "temperature sensor reads" : 0,
      "temperature sensors" : 0
   },
   "Settings" : {
      "analog enabled" : false,
      "board profile" : "S32",
      "bool dashboard" : 1,
      "bool format" : 1,
      "dallas parasite" : false,
      "ems bus id" : 11,
      "enum format" : 1,
      "fahrenheit" : false,
      "hide led" : false,
      "locale" : "en",
      "max web log buffer" : 100,
      "notoken api" : true,
      "readonly mode" : false,
      "shower alert" : false,
      "shower timer" : true,
      "telnet enabled" : true,
      "tx mode" : 1,
      "web log buffer" : 15
   },
   "Syslog Info" : {
      "enabled" : true,
      "syslog ip" : "192.168.1.251",
      "syslog level" : "info",
      "syslog queue" : 0,
      "syslog started" : true
   },
   "System Info" : {
      "arduino" : "Tasmota Arduino v2.0.15",
      "free app" : 372,
      "free caps" : 115,
      "free mem" : 165,
      "max alloc" : 107,
      "partition" : "app1",
      "platform" : "ESP32",
      "reset reason" : "Software reset CPU / Software reset CPU",
      "sdk" : "4.4.7.240312",
      "uptime" : "000+00:03:54.172",
      "uptime (seconds)" : 234,
      "used app" : 1612,
      "version" : "3.7.0-dev.4"
   }
}
```

[log.txt](https://github.com/emsesp/EMS-ESP32/files/15092234/log.txt)

### ADDITIONAL CONTEXT

In Settings > Customizations, there are entries for holidays and vacations but these have no values and are not displayed on the dashboard.

![scrot20240424114443](https://github.com/emsesp/EMS-ESP32/assets/1118804/2ef880e6-f3d7-4fb4-b33d-89af80cc2240)

_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by proddy** [comment]
@sciurius could you find out?

**Comment by sciurius** [comment]
I must admit I am not familiar with this. All I can do is make some changes in the vacation program settings and include the resultant logging. Is it only the `RC30Timer` messages you are interested in?

BTW: What would be the difference between vacation and holidays? The thermostat only has one setting "Vakantie" (=vacation).

**Comment by MichaelDvP** [comment]
Yes, log all and change the vacation dates on the RC30. 

In RC35 vacation is "away from home" (use night temp) and holiday is "at home" (use day temp).

**Comment by sciurius** [comment]
Attached is a logfile fragment consisting of some normal message sequences. I entered a vacation (program 1, from 30.04.24 to 01.05.24) and then the `?(0xA9)` messages appeared.

[ems1.log](https://github.com/emsesp/EMS-ESP32/files/15153880/ems1.log)

**Comment by sciurius** [comment]
Was this useful? Anything else I can do?

**Comment by MichaelDvP** [comment]
So you have up to 8 vacation periods. Is it useful to add 8 entities for this? RC30 has only one hc, so we do not run out of memory. 
Or add it like the switchtimes, use only one entity with no,command `0:01.05.2024-10.05-2024`, etc. and command with single switches the index? For first test i've added only read/write first vacation-period.

**Comment by sciurius** [comment]
As opposed to switchtimes, vacation periods are explicitly numbered (1..7) so it is probably better to use `vacation1`, `vacation2`, ...

**Comment by sciurius** [comment]
With 3.7.0-dev.10 I can now see and change the vacation dates. Date 4 is missing (typo? glitch?).

![scrot20240513134145](https://github.com/emsesp/EMS-ESP32/assets/1118804/e3d1637b-dd02-4322-bf33-f22378153ef8)
![scrot20240513134331](https://github.com/emsesp/EMS-ESP32/assets/1118804/d23780bd-3c72-48c6-a750-e27fb19da932)

**Comment by proddy** [comment]
fixed by Michael in dev

**Comment by proddy** [comment]
all the time?

**Comment by sciurius** [comment]
It is not related to the vacation enhancements. Several values from other devices are missing as well, and it seems to affect FireFox only.

I can reproduce this as follows.

* Open a tab and type "http://ems-gw1.squirrel.nl"
* The tab opens, and is redirected to "http://ems-gw1.squirrel.nl/devices"
* Choose boiler, several values are missing
* Choose thermostat, same. Always the same set of values.
* [REFRESH] no change
* Ctrl-R goes back to "http://ems-gw1.squirrel.nl/devices".
* Choose boiler, all values are present.
* Choose thermostat, same.

Interesting is that when I open the tab and type "http://ems-gw1.squirrel.nl/devices", all values are there.

**Comment by sciurius** [comment]
I suspect it is one of my extensions that gets in the way. Let's ignore this for the time being.

**Comment by proddy** [comment]
I've opened a new issue anyway, and closing this one.
