### ISSUE TITLE
Add fan/ventilation speed support for Bosch compress 3800i/IVT Vent 402

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#1724]
### Discussed in https://github.com/emsesp/EMS-ESP32/discussions/1690

<div type='discussions-op-text'>

<sup>Originally posted by **mattfro** April 10, 2024</sup>
Add fan control support. On this device I think you cannot turn off the fan and the min value is 20% and max 100%
I was trying to understand ems messages so(but I have no idea), if I guess correct, 40% should be 28 and 41% should be 29?
If that is the case, I think I fetched when I was changing the value in the pump between 40 and 41.
[K000+00:45:56.777 T 9959: [emsesp] controller(0x09) -W-> boiler(0x08), ?(0x04A5), data: 29 (offset 9)
[K000+00:46:01.127 T 9997: [emsesp] controller(0x09) -W-> boiler(0x08), ?(0x04A5), data: 28 (offset 9)
[K000+00:46:06.064 T 10064: [emsesp] controller(0x09) -W-> boiler(0x08), ?(0x04A5), data: 29 (offset 9)
[K000+00:46:08.889 T 10103: [emsesp] controller(0x09) -W-> boiler(0x08), ?(0x04A5), data: 28 (offset 9)
[K000+00:46:11.627 T 10146: [emsesp] controller(0x09) -W-> boiler(0x08), ?(0x04A5), data: 29 (offset 9)
**[K000+00:46:15.552 T 10191: [emsesp] controller(0x09) -W-> boiler(0x08), ?(0x04A5), data: 28 (offset 9)**
Last value I left it on was 40%</div>

**Comment by MichaelDvP** [comment]
It's already in the dev.
https://github.com/emsesp/EMS-ESP32/blob/13e7a53e5e70e77eab2e59d81dc04bba30ad40c3/src/devices/boiler.cpp#L805
