### ISSUE TITLE
Status …Loading…

### ISSUE THREAD

**Issue by RalfLuig** [emsesp/EMS-ESP32#1732]
As soon if I try to see the status of the EMS bus I am getting into an endless „loading“ loop. I am using the „dev 7“ version of EMS-ESP.

![IMG_7317](https://github.com/emsesp/EMS-ESP32/assets/71794326/e0b71913-70bf-44d9-8216-0c5ca5d25102)

**Comment by MichaelDvP** [comment]
This is from v3.6.5 in your browser cache. Press reload (ctrl-R) to refresh.

**Comment by RalfLuig** [comment]
This problem seems to be only in Apple`s Safari Browser on a mobile device. If I use another browser like Chrome, I don't see the problem.

**Comment by MichaelDvP** [comment]
Try with clear cache in safari (for ems-esp pages).

**Comment by RalfLuig** [comment]
I already did that...

**Comment by proddy** [comment]
I can't reproduce on my iPhone using safari. I'll keep testing

**Comment by RalfLuig** [comment]
I found the problem. I opened the web interface via shortcut on the home screen. I removed the shortcut and created a new one.
