### ISSUE TITLE
New version 3.3.0b0 crashes on api calls

### ISSUE THREAD

**Issue by tp1de** [emsesp/EMS-ESP32#176]
@proddy @MichaelDvP 

I tried loading 3.3.0b0 version. While using the api calls from my ioBroker adapter the ems-esp crashes by issuing the api call
`ems-esp/api/boiler`. The ems-esp device is not reachable anymore by web-ui or telnet. After a hard reboot web-ui and dashboard is working again but on next api call the system crashes again.

I went back to 3.2.2b14 from a week ago ....

**Comment by proddy** [comment]
which API call is causing the crash?

**Comment by tp1de** [comment]
ems-esp/api/boiler

**Comment by tp1de** [comment]
I will test again ... if this API call will to the crash or the number of following API calls for detailed fields.
Could it be a memory allocation problem?

**Comment by proddy** [comment]
no, probably a parsing error but I did try and test for every scenario. a GETto http://ems-esp.local/api/boiler works fine for me.  if you can help drill down to the exact call that causes the crash it would help.

**Comment by tp1de** [comment]
> no, probably a parsing error

I agree but I need to adjust my adapter slightly to get the respective API call which gives the crash.
I think it will be one of the API call per field to get the attributes ...

**Comment by tp1de** [comment]
I reloaded 3.3.0b0 again. telnet shows an error on startup:

![image](https://user-images.githubusercontent.com/36480251/139858868-5d7bee5e-8726-425e-9340-bf8242cf9d7a.png)

I just recognized that API calls per device now return long names and not short names anymore. (rettemp is now return temperature)
The API calls per field does not seam to work anymore: ems-esp/api/boiler/gas makes the ems-esp to reboot !

**Comment by proddy** [comment]
ok, the latest build from 30mins ago should have improved error reporting so try that if you can. The short-names I was wondering about that myself, and will fix. I'll also try locate the cause of the crash after a ems-esp/api/boiler/gas

**Comment by tp1de** [comment]
I will wait until short names will be available again. Otherwise I will create new duplicate data fields with long names and my ioBroker adapter and the respective datafiles / diagrams will not work anymore.
Just tell me when short names will be fixed ...

> I'll also try locate the cause of the crash after a ems-esp/api/boiler/gas

The original data field was burngas and gas the long name !

**Comment by proddy** [comment]
ok - found the issue and working on an improvement. I'll let you know, thanks again for testing

**Comment by proddy** [comment]
ok firmware is building, perhaps wait until 16:10 and then grab it from the releases page

**Comment by tp1de** [comment]
@proddy 
devices work now but `ems-esp/api/system`  returns no info: 
```
{
  "message": "invalid command 'list'"
}
```

**Comment by tp1de** [comment]
BTW: was working before ...

**Comment by proddy** [comment]
ok, new build ready for testing

**Comment by tp1de** [comment]
Everything seems to be ok now. But I will observe until tomorrow....
