### ISSUE TITLE
WebUI data missing on Firefox

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#1764]
_Originally posted by @sciurius in https://github.com/emsesp/EMS-ESP32/issues/1712#issuecomment-2112296352_
           
I can reproduce this as follows.

* Open a tab and type "http://ems-gw1.squirrel.nl"
* The tab opens, and is redirected to "http://ems-gw1.squirrel.nl/devices"
* Choose boiler, several values are missing
* Choose thermostat, same. Always the same set of values.
* [REFRESH] no change
* Ctrl-R goes back to "http://ems-gw1.squirrel.nl/devices".
* Choose boiler, all values are present.
* Choose thermostat, same.

Interesting is that when I open the tab and type "http://ems-gw1.squirrel.nl/devices", all values are there.

**Comment by proddy** [comment]
Possible a caching issue, I'll try and reproduce and fix.

**Comment by sciurius** [comment]
I suspect one of my firefox extensions is getting in the way. Please stall this issue until I know more.

**Comment by MichaelDvP** [comment]
Try to delete cache and website settings for this page in firefox. I've see some strange effects after updates. 
I suspect the last-modified is updated by frefox and from here https://github.com/emsesp/EMS-ESP32/blob/1487f30c433e6fc87ecbba42c04f9f9ea483dd4f/lib/framework/ESP8266React.cpp#L32  it always uses cached page.

**Comment by sciurius** [comment]
That did, indeed, fix it...

**Comment by proddy** [comment]
the 'last-modified' is only used for the static pages, which is ok. Things like the images and library functions.

The API data shouldn't be cached and report back a 304 so I think there is something else strange I need to look at. I first need to try and reproduce. Perhaps its here:
https://github.com/emsesp/EMS-ESP32/blob/ab9241376be7097a2239c3dcc3f7f716224c2248/interface/src/api/endpoints.ts#L12

**Comment by tp1de** [comment]
I am using Firefox as well and I can't reproduce. Everything is working fine.

**Comment by proddy** [comment]
> I am using Firefox as well and I can't reproduce. Everything is working fine.

thanks Thomas

**Comment by proddy** [comment]
will close for now and re-open if this is a common occurrence with other users.
