### ISSUE TITLE
boiler.nrgtotal with spikes and wrong value after update 

### ISSUE THREAD

**Issue by tp1de** [emsesp/EMS-ESP32#1765]
nrgtotal has spikes within timeline. 
on system 1 (ems 2.0) it looks like this:

![grafik](https://github.com/emsesp/EMS-ESP32/assets/36480251/2d0c25b4-66c3-471b-ba97-f516ecb5ae73)

On May 10th I did a firmware upgrade from 3.6.5 to 3.7.0-dev.10. The nrgtotal value was wrongly calculated. Most probably the ww part was missing.

on system 2 (ems+) ist looks like this:

![grafik](https://github.com/emsesp/EMS-ESP32/assets/36480251/b5f36635-50bd-4fae-9e00-c60cc647dd7b)

Firmware upgrade on May 3rd and spikes are positive not negative - looks strange.

As a result the home assistant energy statistics  are complete wrong and the statistic records needs to be corrected manually.

**Comment by proddy** [comment]
don't know what the problem is. any ideas?

**Comment by tp1de** [comment]
I can see spikes within HA (mqtt) for boiler.curburnpow (modulation) on same time when nrgheat / nrgtotal spikes happen:
![grafik](https://github.com/emsesp/EMS-ESP32/assets/36480251/49e49a85-7715-4b75-b3d8-b6b88cb085cb)

Just one datapoint. On API (ioBroker) with polling every 15 seconds I do not see these spikes,
Within HA states (database) I see one entry with undefined value. 
This results in statistics with a high positive value and direct afterwars with a corresponding negative value.

Something strange. There should be no mqtt messages without any value. Please check.

**Comment by proddy** [comment]
I'm see spikes with `curburnpow` as well, since May 26th

![image](https://github.com/emsesp/EMS-ESP32/assets/1230712/2f7aacac-edff-4b08-9ada-d18e80140858)

I'll look into it

**Comment by tp1de** [comment]
Within ha I see states without any value. Only one state within database. Before and afterwards correct values. I assume that values are populated by mqtt.

**Comment by proddy** [comment]
I'm not seeing states without values on my system

**Comment by tp1de** [comment]
The states without value can only be seen with a database tool. I use MariaDB for HA and with MySQL Workbench I can analyse the states. E.g. for boiler_nrgheat there are a lot of states with current state value "unavailable":

![image](https://github.com/emsesp/EMS-ESP32/assets/36480251/fa27d884-4636-4457-b633-2eba20545283)

For boiler_nrgww there are no "unavailable" states records at all. Could it be related to mqtt settings?:
![image](https://github.com/emsesp/EMS-ESP32/assets/36480251/7b1914ae-6d32-4f2a-9888-f20f6d5fb6aa)

**Comment by tp1de** [comment]
But I do not know if this "unavailable" states are the root cause for the spikes in statistics?
