### ISSUE TITLE
Worcester-Bosch Greenstar Summer Mode temp value upper limit too low

### ISSUE THREAD

**Issue by V4ler1an** [emsesp/EMS-ESP32#1767]
### PROBLEM DESCRIPTION

The 'Summer Mode' temperature setting in the Worcester Bosch Greenstar Weather Compensation settings currently has an upper limit of only 30 degrees C. When the Weather Compensation feature is enabled on the boiler and the 'Boiler Outside Temperature' thermostat value meets or exceeds this 'Summer Mode' temperature value, the boiler will disable any response to central heating demand - as designed.

The problem (at least for the way my boiler is installed), is that activation of Summer Mode will also prevent the boiler from heating my hot water tank. This appears to be because the boiler has not been connected up to use its proper designed DHW features. These are all unused in the boiler settings. Intead if has a setup which relies on the central heating features and (presumably) some sort of separate hot water tank valve which opens when the Hive Home smart controls demand hot water.

Long story short, the upper summer mode temp limit will mean that for certain periods in the summer, if the outside temp reaches or exceeds 30 degrees C, I won't be able to heat any hot water. The workaround required would be to disable the weather compensation curve feature entirely, which disables Summer Mode.

Could I please have the 'boiler summertime temperature' value limit increased to 45 degrees C?

### TO REPRODUCE

Attempt to increase the 'boiler summertime temperature' value above 30 degrees C.

### EXPECTED BEHAVIOUR

Current behaviour is as expected but undesirable.

### SCREENSHOTS

Home Assistant automation failure due to Summertime Mode temperatire value limit exceeded:
![image](https://github.com/emsesp/EMS-ESP32/assets/134781183/8c0709a7-21e8-497e-9bce-4935077ffb0c)

### ADDITIONAL CONTEXT
I appreciate that had the central heating installers installed my boiler to use its built-in water heating (DHW) features to the full, hot water would be heated separately from central heating water. Tbh, I don't know the reasons for installing it this way. Nevertheless, as I see it, increasing the Summer Mode value limit shouldn't really cause any problems.

Note: this Summer Mode feature was introduced to the EMS-Bus Gateway firmware several months ago when I requested that you add support for the official Worcester Bosch weather compensation add-on in this issue I raised: 

https://github.com/emsesp/EMS-ESP32/issues/1642

**Comment by proddy** [comment]
that's like a 2 second change. I'll do it ASAP

**Comment by proddy** [comment]
in dev11. Max is 45

**Comment by V4ler1an** [comment]
Brilliant, thank you.

**Comment by V4ler1an** [comment]
Ah... a problem. It seems the boiler's weather comp settings also limits the value to 30. My automation no longer errors but the boiler puts it back to 30. Is there any way around that do you think?

**Comment by proddy** [comment]
hmm, not sure. it's it similar to https://emsesp.github.io/docs/Troubleshooting/#changing-a-value-works-at-first-but-is-then-reset-to-its-original-value ?

**Comment by V4ler1an** [comment]
Side note: since applying the beta firmware, i've been seeing this. Just keeps spinning:
![image](https://github.com/emsesp/EMS-ESP32/assets/134781183/cbb84aca-8837-4f0b-a9ab-79ff0ae4d798)

**Comment by proddy** [comment]
> Side note: since applying the beta firmware, i've been seeing this. Just keeps spinning: ![image](https://private-user-images.githubusercontent.com/134781183/331815330-cbb84aca-8837-4f0b-a9ab-79ff0ae4d798.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTE3NDksIm5iZiI6MTcxNzQ5MTQ0OSwicGF0aCI6Ii8xMzQ3ODExODMvMzMxODE1MzMwLWNiYjg0YWNhLTg4MzctNGYwYi1hOWFiLTc5ZmYwYWU0ZDc5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQwODU3MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODAzNjA2NzljY2QyNTI3NGUwZTQ0ZmFmOTcxMTQwZWQyNzFmMWJkZDcwNmRjYzNhZDljNjVkMTQ5MWUxMTZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mHCTLE9jk_3LalARH9qcSGDl7V8nI5bugKOa3Yg_Jl8)

refresh browser cache help?

**Comment by V4ler1an** [comment]
Yes might have needed it. Seem ok now.

**Comment by undulanti** [comment]
@V4ler1an - Your suspicions about how your system was installed are correct - it's really rare to have boilers installed with hot water diverter kits here. In any event, I think this video might help you: https://www.youtube.com/watch?v=RJCGOtDLuNQ.

**Comment by V4ler1an** [comment]
Thanks, I had seen Tom's video actually. I'm not sure if that method will ensure my boiler's weather compensation add-on kit will continue to work, it may do. Any way, I decided to stick with using my EMS-Bus gateway with Home Assistant automations because it lets me run two weather curves - one low, one high. The boiler's primary heating curve is set really low: 35 to 45 deg. Then when needed, either for hot water demand or to warm up a room that's too cold, the curve is temporarily boosted to 60 to 75 deg. Gives a nice combo of very efficient flow temps 95% of the time then very rapid warm up if a room was unoccupied and the heating was off. E.g. my bedroom is off all day in winter but it will warm up as much as 5 degrees in only an hour, just before I go to bed.
