### ISSUE TITLE
Modbus UI not working correctly

### ISSUE THREAD

**Issue by mheyse** [emsesp/EMS-ESP32#1771]
### PROBLEM DESCRIPTION

When enabling Modbus in Settings/Application only the port is pre-filled with the correct default value (502) - "Max Clients" and "Timeout" are empty.

### REQUESTED INFORMATION

Built from commit 0c52fa14eaaa0b503499af509adf0fe6c76faa32 with

```
cd interface
yarn install
yarn typesafe-i18n --no-watch
yarn build
yarn webUI
cd ..
pio run -e esp32_16M
```

### TO REPRODUCE

_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR

Max Clients should be pre-filled with 10, Timeout with 1000 ms.

### SCREENSHOTS

![image](https://github.com/emsesp/EMS-ESP32/assets/5389978/e04643cd-b433-4d14-9fb2-7735ae2d8799)

**Comment by proddy** [comment]
I'll take a look.

**Comment by proddy** [comment]
merged with latest dev
fixed the UI settings (changed maxClient and timeoutMillis also in C code)
made standalone compile
