### ISSUE TITLE
No HTTP interface "ERR_CONNECTION_TIMED_OUT"

### ISSUE THREAD

**Issue by fredkaauw** [emsesp/EMS-ESP32#1773]
Hi all,

I just updated my EMS-ESP V2 to version 3.5.0
"Reason MQTT connection problems with HA. A lot of disconnections where visable in the history charts"
After the update to 3.5.0 I see there is a connection with HA and the values are updated as expected "No connection loss through MQTT anymore".

But.....
I cannot connect to the ESP through the webinterface over port 80?
I get the message "ERR_CONNECTION_TIMED_OUT" 

What is wrong?

**Comment by proddy** [comment]
Version 3.5.0 is more than a year old and hundreds of updates behind the latest 3.6.5 or 3.7 releases. Update to either one of those and try again.
