### ISSUE TITLE
EMS bus disconnected

### ISSUE THREAD

**Issue by wojtulab** [emsesp/EMS-ESP32#1775]
Hello, 
I've received the S3 Standard Wifi Version.  I have connected via service jack to Buderus GB022 and receive the information: 
"EMS bus disconnected. If this warning still persists after a few seconds please check settings and board profile"
![image](https://github.com/emsesp/EMS-ESP32/assets/14801148/95279b09-c8d5-48ec-bc7a-6e8356b78bfb)

I have read the official guide and issues on github. Unfortunately I am unable to fix it. Does anyone know how to fix it?

Board profile is: BBQKees Gateway S3
TX mode: EMS
Device: Buderus GB022

My config:
![image](https://github.com/emsesp/EMS-ESP32/assets/14801148/873be1c2-313d-4067-a7b6-e92e21e2add5)

System log:
![image](https://github.com/emsesp/EMS-ESP32/assets/14801148/7327f35d-fa64-482e-ade9-25aa497334bd)

**Comment by wojtulab** [comment]
I have changed the method of connection. The service jack has been replaced by BUS: 12VDC together with two BUS lines. The furnace and the RC310 controller have been found and can be seen in the dashboard.

![image](https://github.com/emsesp/EMS-ESP32/assets/14801148/08d5ec6a-7097-4517-bb38-52388b825c4d)

**Comment by proddy** [comment]
glad it works.

@bbqkees do you know why it wouldn't work with the service connector jack? Need to update https://bbqkees-electronics.nl/wiki/gateway/connecting-to-specific-boilers-and-heatpumps.html#connecting-the-gateway-to-specific-boilers-and-heatpumps ?
