### ISSUE TITLE
Feature: external modules

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#1778]
Created an extension where external modules can be coded, compiled and the library file (.a) dropped into EMS-ESP which will pick it up automatically. This allows 3rd parties to build on top of EMS-ESP safely.

The first prototype is done at https://github.com/emsesp/EMS-ESP-Modules and I'll include in v3.7 but won't have them as activated.

The extra module uses 900 bytes of extra Flash, so it's not intrusive either. 

The feature branch is https://github.com/emsesp/EMS-ESP32/tree/feat_modules

**Comment by proddy** [comment]
![image](https://github.com/emsesp/EMS-ESP32/assets/1230712/82740235-66a8-4613-a71d-c207058a49e4)

**Comment by proddy** [comment]
Added the license manager and optimized a few things. I think this is ready to be merged into dev.

**Comment by MichaelDvP** [comment]
Seems to be broken in github actions:
```
linking .pio/build/ci/firmware.elf
/home/runner/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pio/build/ci/src/web/WebModulesService.cpp.o:(.literal._ZN6emsesp10WebModules4readERS0_N11ArduinoJson8V710PB2210JsonObjectE+0x18): undefined reference to `ModuleLibrary::list(ArduinoJson::V710PB22::JsonObject)'
/home/runner/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pio/build/ci/src/web/WebModulesService.cpp.o: in function `ArduinoJson::V710PB22::detail::VariantTo<ArduinoJson::V710PB22::JsonObject>::type ArduinoJson::V710PB22::JsonDocument::to<ArduinoJson::V710PB22::JsonObject>()':
/home/runner/work/EMS-ESP32/EMS-ESP32/.pio/libdeps/ci/ArduinoJson/src/ArduinoJson/Document/JsonDocument.hpp:150: undefined reference to `ModuleLibrary::list(ArduinoJson::V710PB22::JsonObject)'
collect2: error: ld returned 1 exit status
*** [.pio/build/ci/firmware.elf] Error 1
```

**Comment by proddy** [comment]
Thanks. It's because the ArduinoJson namespace's don't match, which are dynamically generated (like V710PB22). I'm not sure why it's broken again. I'll look into it.

**Comment by proddy** [comment]
fixed.

**Comment by MichaelDvP** [comment]
A few days ago compile failed for esp32C3 because of missing modules lib. 
The c3 is always 4M, maybe we can skip the modules. But than we need a define to exclude from code.
For esp32, esp32s2 and esp32s3 it seems to work, it's all Xtensa code, but LX6 for esp32 and LX7 for S2/S3

**Comment by proddy** [comment]
I need to think of a way to do that. I can compile to C3 and add include it, or just skip the linking for 4MB variants. 

I was only focused on the two BBQKees boards - the ESP32 16M and the ESP32-S3 16M

**Comment by proddy** [comment]
think it should work now. I build libs for each BOARD_MCU
