### ISSUE TITLE
Reboot Loop with latest development build 22

### ISSUE THREAD

**Issue by RalfLuig** [emsesp/EMS-ESP32#1849]
I flashed the latest development build yesterday. The device is connecting to the EMS bus and I see the entities coming back from my
heating system. After couple seconds there might be a reset and it is startting again discovering the entities.

I moved back to development build 19 and this beavior disapeared.

My heating system is a Bosch Condens 8000if.

Gateway E32 V2 (Ethernet + WiFi Edition V2)

**Comment by MichaelDvP** [comment]
Discussed on discord, a PR is on the way, disable HA discovery until dev.23 is out.

**Comment by proddy** [comment]
thanks @RalfLuig for helping out. It was a tricky one.

**Comment by RalfLuig** [comment]
you are welcome, thanks :-)

**Comment by RalfLuig** [comment]
Now there is another issue with development build 23. MQTT is not working anymore. I don‘t see any previous topics in MQTT Explorer and Home Assistant, with development build 19 everything is ok.

**Comment by proddy** [comment]
> Now there is another issue with development build 23. MQTT is not working anymore. I don‘t see any previous topics in MQTT Explorer and Home Assistant, with development build 19 everything is ok.

please send system info

**Comment by RalfLuig** [comment]
Problem solved - I had to clear all MQTT topics in HA - reboot the EMS-ESP. Now everything is  working as expected.
