### ISSUE TITLE
New Bosch HP only recognizes CR10/CR11, CR10H/CR11H, CR20RF, RT800 as remote thermostats

### ISSUE THREAD

**Issue by christic73** [emsesp/EMS-ESP32#1867]
I have a new Bosch heat pump (compress 6800i AW) with a UI800 user interface. I also got a RT800 remote interface on top, which is currently not connected.
This HP apparently only accepts CR10/CR11, CR10H/CR11H, CR20RF, RT800 as remote thermostats. However I only can select RC100, RC100H, RC120RF or RC220 in EMS-ESP.

If I select RC100H in EMS-ESP and send remotetemp and remotehum periodically via scheduler, then the HP shows CR10H as remote thermostat, together with an error code 3111 (wrong remote configuration).

Is there anything I can do to solve the issue? Do you want me to share some logs of the RT800?

Thanks for looking into this :-)

[log.txt](https://github.com/user-attachments/files/16248789/log.txt)
[IMG_20240716_125457](https://github.com/user-attachments/assets/a3fd7cbe-4432-46b0-8753-3d4024d6614d)

(used EMS-ESP version 3.7.0-dev.25)

**Comment by christic73** [comment]
I added a log of RT800 remote thermostat. Maybe this is of interest
[log_RT800.txt](https://github.com/user-attachments/files/16249357/log_RT800.txt)

**Comment by MichaelDvP** [comment]
> I added a log of RT800 remote thermostat. Maybe this is of interest

Yes, this helps much. Could you please also upload the support info.

From the log i can see that:
- control is set to 6, so ems-esp shows RC220, we can change this text to RT800.
- version of RT800 is v21.03 with no subversion and  profduct-id 03
- temperature telegram is longer than known. Two bytes at the end read `01 09`. Don't know what this is, but we can trywith fixed numbers.
- humidity telegram is as know from RC100H with humidity and dewpoint.

I'll prepare a RT800 emulation to test...Takes a bit... 

BTW: You have a connect module 0x50, What is this for? We have seen such modules as RF base for RF-sensors and RF-thermostats, but no logs for this.

**Comment by MichaelDvP** [comment]
Please test: https://github.com/MichaelDvP/EMS-ESP32/releases

**Comment by christic73** [comment]
> > I added a log of RT800 remote thermostat. Maybe this is of interest
> 
> Yes, this helps much. Could you please also upload the support info.
> 
> From the log i can see that:
> 
> * control is set to 6, so ems-esp shows RC220, we can change this text to RT800.
> * version of RT800 is v21.03 with no subversion and  profduct-id 03
> * temperature telegram is longer than known. Two bytes at the end read `01 09`. Don't know what this is, but we can trywith fixed numbers.
> * humidity telegram is as know from RC100H with humidity and dewpoint.
> 
> I'll prepare a RT800 emulation to test...Takes a bit...
> 
> BTW: You have a connect module 0x50, What is this for? We have seen such modules as RF base for RF-sensors and RF-thermostats, but no logs for this.

There is a module, which is inserted into the HP. On the manual not is called "K 30 RF". It delivers a "Gateway Module" (0x48) and a "Connect Module" (0x50)

![image](https://github.com/user-attachments/assets/1770027b-95fb-4f21-bea9-4d924a7c16fd)

**Comment by christic73** [comment]
> > > I added a log of RT800 remote thermostat. Maybe this is of interest
> > 
> > 
> > Yes, this helps much. Could you please also upload the support info.
> > From the log i can see that:
> > 
> > * control is set to 6, so ems-esp shows RC220, we can change this text to RT800.
> > * version of RT800 is v21.03 with no subversion and  profduct-id 03
> > * temperature telegram is longer than known. Two bytes at the end read `01 09`. Don't know what this is, but we can trywith fixed numbers.
> > * humidity telegram is as know from RC100H with humidity and dewpoint.
> > 
> > I'll prepare a RT800 emulation to test...Takes a bit...
> > BTW: You have a connect module 0x50, What is this for? We have seen such modules as RF base for RF-sensors and RF-thermostats, but no logs for this.
> 
> There is a module, which is inserted into the HP. On the manual not is called "K 30 RF". It delivers a "Gateway Module" (0x48) and a "Connect Module" (0x50)
> 
> ![image](https://private-user-images.githubusercontent.com/175709282/349225717-1770027b-95fb-4f21-bea9-4d924a7c16fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNTM4MTEsIm5iZiI6MTcyMTE1MzUxMSwicGF0aCI6Ii8xNzU3MDkyODIvMzQ5MjI1NzE3LTE3NzAwMjdiLTk1ZmItNGYyMS1iZWE5LTRkOTI0YTdjMTZmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQxODExNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Mzg3MmU2ZmVjMDNjMGMxNWE2MjA1NDY4ZWUxM2FlYjkyNGI3MDg3ZjY3YTA2YmUyYjRjNTExYzIyMTZlNDZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dRZE2nqmohNnXO3-eJ5rnFVVGXF26b_KPRC8VfGbPUc)

I

> > I added a log of RT800 remote thermostat. Maybe this is of interest
> 
> Yes, this helps much. Could you please also upload the support info.
> 
> From the log i can see that:
> 
> * control is set to 6, so ems-esp shows RC220, we can change this text to RT800.
> * version of RT800 is v21.03 with no subversion and  profduct-id 03
> * temperature telegram is longer than known. Two bytes at the end read `01 09`. Don't know what this is, but we can trywith fixed numbers.
> * humidity telegram is as know from RC100H with humidity and dewpoint.
> 
> I'll prepare a RT800 emulation to test...Takes a bit...
> 
> BTW: You have a connect module 0x50, What is this for? We have seen such modules as RF base for RF-sensors and RF-thermostats, but no logs for this.

I'm sorry, I'm new here... Could you tell me what do you mean with "support info"?

**Comment by proddy** [comment]
there's a link in the box at the bottom of this page: https://emsesp.github.io/docs/Support/

**Comment by christic73** [comment]
sorry 
[support.info.txt](https://github.com/user-attachments/files/16254987/support.info.txt)

**Comment by christic73** [comment]
> Please test: https://github.com/MichaelDvP/EMS-ESP32/releases

thanks for the version!

- I successfully selected in "RT800" in EMS-ESP
- I successfully set a Temperature and Humidity value in EMS-ESP
- In the Bosch-HP User Interface I could see, that "RT800" has been set
- In the Bosch-HP User Interface I could see, that set temp and hum has been accepted from virtual thermostat
- The Bosch-HP didn't trough any error message (so far)

many thanks! you are awesome!!
