### ISSUE TITLE
different information of mm100 modules in EMS network 

### ISSUE THREAD

**Issue by Seziksezik** [emsesp/EMS-ESP32#1887]
2.65 software version. I have 2 mm100 in network. 

But can see onlyb4 parameters inside first module. And 7 inside second. They are almost the same.

![Screenshot_20240723_161928_Chrome](https://github.com/user-attachments/assets/c839d742-ba14-47ef-b5aa-cb88762cbf4f)
![Screenshot_20240723_161923_Chrome](https://github.com/user-attachments/assets/b9efcd5f-fe4c-40bf-b911-e2221ea209b9)
![Screenshot_20240723_161754_Chrome](https://github.com/user-attachments/assets/488709f0-c72c-495b-af26-e2ad73fa3309)

### PROBLEM DESCRIPTION

_A clear and concise description of what the problem is._

### REQUESTED INFORMATION

_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Searched the problem in [issues](https://github.com/emsesp/EMS-ESP32/issues)
- [ ] Searched the problem in [discussions](https://github.com/emsesp/EMS-ESP32/discussions)
- [ ] Searched the problem in the [docs](https://emsesp.github.io/docs/Troubleshooting/)
- [ ] Searched the problem in the [chat](https://discord.gg/3J3GgnzpyT)
- [ ] Provide the output of http://ems-esp.local/api/system :

```lua
  System information output here:


```

### TO REPRODUCE

_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR

_A clear and concise description of what you expected to happen._

### SCREENSHOTS

_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT

_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by proddy** [comment]
I'm not sure which version you're using, but it looks very old. Try and upgrade to the latest 3.7.0. Also please provide your system info.

**Comment by Seziksezik** [comment]
There. 





Yahoo Почта: Поиск, организация, успех 
 
  вт, 23 июл. 2024 в 17:07 ***@***.***> написал(-а):   


I'm not sure which version you're using, but it looks very old. Try and upgrade to the latest 3.7.0. Also please provide your system info.

**Comment by proddy** [comment]
Upgrade and try again.

**Comment by Seziksezik** [comment]
3.7 is ok..Both are 7 items..




Yahoo Почта: Поиск, организация, успех 
 
  вт, 23 июл. 2024 в 18:07 ***@***.***> написал(-а):   


Upgrade and try again.
