### ISSUE TITLE
Updates to webUI

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#1920]
I'm planning to make some changes to the WebUI, and noting them down here so I don't forget

- [x] upgrade Alova from version 2 to 3. This is done, but there's a bug in Alova (rendering with preact) that is blocking the PR
- [x] refactor all the updateState() to use methods
- [x] use AutoRefreshRequest() in devices, sensors, custom entities, status (activity, network, hardware, mqtt, ntp, ap) and remove the Refresh button where appropriate.
- [x] uppercase "Never" "Always" etc in the AP, to make it consistent
- [x] Rename Customization to Customizations in .tsx filenames to be consistent with naming in UI
- [x] Remove the RemoveTrailingSlashes code, which router-dom does now
- [x] Add translations for Immediate, used in the Scheduler
- [x] Remove history package
- [x] Replace Functional Components (FC) with normal JSX functions if we're not passing down children props
- [x] Set initial data for `psram` in ApplicationSettings.tsx to prevent error when page is loaded and data not fetched from hardarestatus endpoint
- [x] Fix download URLs (e.g. S3 would try and find EMS-ESP-3_7_0-dev_30-ESP32_S3_16M.bin)
- [x] Prevent signIn username from forcing capslock on for first input character (on ios)
- [x] replace range() function used in APSettings to get rid of lodash library and save .9KB
- [x] prevent changing board profile if pre-loaded with BBQKees (in NVS)
- [x] Tidy up Application settings, moving to sections like Hardware, Formatting, Services

**Comment by mattreim** [comment]
And maybe a few more translations.

**Comment by proddy** [comment]
> And maybe a few more translations.

that would be nice. We really leave it up to the community to do the translations (I'm not fluent in 10 languages, unfortunately!). 

I'll do a broadcast and ask for people to help.

**Comment by proddy** [comment]
Looks like Alova 3 is working again so I'll make a PR. Only remaining issue seems to be the Upload progress bar.

**Comment by proddy** [comment]
For the Application page I was thinking 

```
Services
 - API
   - Bypass Access Token
 - Telnet (on/off)
 - Modbus (on/off)
   - Max Clients, Port, Timeout
 - Syslog (on/off)
   - Host, Port, Log level, Mark interval
 - Sensors
	- enable Analog Sensors
	- enable Temperature parasite power
 - Shower Timer
	- Wait time
	- enable shower alert
	  - Trigger Time, Cold shot duration
 
Formatting Options
 - Language (for device entities)
 - Boolean Format Dashboard (change Dashboard to Web)
 - Boolean Format API/MQTT
 - Enum Format format
 - Convert temperature values to Fahrenheit
 - Log EMS in hex

Hardware Options
 - Board profile
 - EMS Tx Mode
 - EMS BUS ID
 - Enable read-only
 - Hide LED
 - underclock CPU speed

Other Options
 - Start boiler forced heating off
 - Disable remote on missing roomtemperature (..and fixing the spacing here)
 ```

**Comment by bbqkees** [comment]
Looks good but I would put the shower timer in the Other Options as the logic is generated in EMS-ESP like the 'start boiler forced heating off''

And Sensors maybe its own header?
Also maybe change 'enable Temperature parasite power' to something like 'enable temperature sensor 1-Wire Parasite-Power'', as that's the official term for clarity.
![image](https://github.com/user-attachments/assets/6cffc672-08b0-4a5e-80ff-3d00977cdbb7)

**Comment by proddy** [comment]
@bbqkees can you review the latest changes to the application settings page at https://demo.emsesp.org/settings/application

**Comment by proddy** [comment]
I'll add some code to automatically download and update the firmware from the GitHub assets.

**Comment by proddy** [comment]
> I'll add some code to automatically download and update the firmware from the GitHub assets.

Created this PR https://github.com/emsesp/EMS-ESP32/pull/1951 but still not 100% working from the WebUI.
