### ISSUE TITLE
Devices tab - count of entities in different column

### ISSUE THREAD

**Issue by HansRemmerswaal** [emsesp/EMS-ESP32#1944]
The description in the Devices tab is sometimes so long that you can't read the count of entities at the end of the line.
Maybe you can move these to a separate column? 
Absolutely not critical, on a bigger screen I can see the count, more a nice improvement if you have some time left 😄 

The screenshot below is made on my iPhone in landscape mode.

![WhatsApp Image 2024-08-16 at 16 16 54](https://github.com/user-attachments/assets/73d1568e-c692-40c9-9f8f-0648ba290d00)

**Comment by MichaelDvP** [comment]
In customization you can rename/shorten the device-description

**Comment by HansRemmerswaal** [comment]
Ah yes, that is also a good idea!

**Comment by proddy** [comment]
I think that's the nicest way.
