### ISSUE TITLE
[3.7.0-dev.32] virtual remote w/ RC220

### ISSUE THREAD

**Issue by Bingo2023** [emsesp/EMS-ESP32#1955]
EMS-ESP Version
3.7.0-dev.32

hello,
any idea why the virtual remote with RC220 is not accepted, see log ?

It is running somehow but not so stable...

![2024-08-18_23h20_26](https://github.com/user-attachments/assets/427c8405-9483-4903-a2a7-85e529461dca)
![2024-08-18_23h21_02](https://github.com/user-attachments/assets/133adb9e-5fcc-4d00-a2df-60b4a3937f73)

**Comment by Bingo2023** [comment]
here is a screenshot from MQTT Explorer from that message:
![image](https://github.com/user-attachments/assets/3608b69f-6268-4950-a404-3d192ad2acc3)

**Comment by Bingo2023** [comment]
how to extend ? Logging-level "all" does not increase...

**Comment by proddy** [comment]
I think we would need to give you a DEBUG compiled build which has more info

**Comment by MichaelDvP** [comment]
- control-command does not have the option RC220, check /api/thermostat/hc/control for valid options. [1]
- RC200 only provides temperaature, it does not support humidity
- i don't know how Bosch manages writes to flash/eeprom stored elements, but it's always a very bad idea to write such values in a high frequency.

footnotes: 
[1] some versions ago there was the option control:RC220, but no thermostat emulation for this. We renamed when developing the RT800 emulation. So this could have never worked.
