### ISSUE TITLE
Feature: Dashboard showing all data (favourites, sensors, custom)

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#1958]
> personally, I would call it Dashboard and have it above the menu options Devices & Sensors. It would only show favourite entities and all sensors that are enabled and have values. No edits and no click-throughs. Just keeping it simple for now. And this could be the default page when the app is loaded instead of /devices

Cant describe it any better...that way around would be optimal to my eyes.

_Originally posted by @dleding in https://github.com/emsesp/EMS-ESP32/discussions/1911#discussioncomment-10223260_

**Comment by proddy** [comment]
Moving this idea fro m the Discussions to Issues so we refine the requirements and build it. 

As described above it
 - a single table with columns Name and Value
 - showing all EMS device entities that are tagged as favourite
 - showing all Sensors (I'm assuming these are important)
 - showing all Custom Entities (I'm assuming these are also important)
 - if there is no value, leave the Value blank
 - show an icon on the left to show the Device type (boiler, thermostat, sensor etc)
 - clicking on a row will take you to the /devices, /sensors or /customentities page. But not focus on the entity.
 - table is sortable
 - perhaps add a Search like we do with Customizations
 - perhaps add an export to CSV (nice to have)

**Comment by proddy** [comment]
<img width="685" alt="image" src="https://github.com/user-attachments/assets/fda0460b-48b5-41db-af67-ceaf13daf87e">

**Comment by proddy** [comment]
<img width="497" alt="image" src="https://github.com/user-attachments/assets/8908d490-cab7-4433-83ac-6f3aa47c1c36">

**Comment by dleding** [comment]
cant find an other word for it than just a single "wow!"

thank you two! (and maybe others?)

**Comment by proddy** [comment]
This is all you. Thanks for the great idea!
