### ISSUE TITLE
module doesnt restart

### ISSUE THREAD

**Issue by alexdan-77** [emsesp/EMS-ESP32#1965]
When i call 
/api/system/restart

i get error:
2024-08-28 16:31:49.193 E 67: [system] Partition '' not found

and device doesn't restart

what do i do? please help!

**Comment by proddy** [comment]
which version are you using?

**Comment by alexdan-77** [comment]
The latest official release is 3.6.5 - my version now

**Comment by alexdan-77** [comment]
what kind of system info else?
I gave all that my system shows.
![изображение](https://github.com/user-attachments/assets/51bce741-b593-45e2-ab67-21ccc039bb58)

**Comment by proddy** [comment]
When creating a GitHub issue we always ask for the system info (read https://emsesp.org/Support/)

I don't know why the system restart is not working. I suggest making a backup copy of your settings and custom entities, customizations etc and then formatting the ESP32 and uploading the latest dev version. You can use the Flash tool for this. The firmware is https://github.com/emsesp/EMS-ESP32/releases/download/latest/EMS-ESP-3_7_0-dev_32-ESP32-16MB+.bin

However we're making changes to the restart service so you may want to wait until tonight and grab the next dev version, dev-33

**Comment by alexdan-77** [comment]
just installed 3.7.0-dev.32. 
Reboot now works.

**Comment by proddy** [comment]
thanks.
