### ISSUE TITLE
version  3.3.0b7: I cannot change temperatures via the web interface.

### ISSUE THREAD

**Issue by zibous** [emsesp/EMS-ESP32#199]
**Bug description**
I cannot change temperatures via the web interface. 
If I delete the existing entry and then want to enter a number, "NAN" always appears in the input field.

**Steps to reproduce**
Open web console dashboard. Select thermostat.
Try to change the value for hc1 eco temperature...

**Screenshots**

![Bildschirmfoto 2021-11-16 um 13 07 09](https://user-images.githubusercontent.com/30198737/141983616-1a7e1e8f-686f-481e-9a95-3da767eb2823.png)

**Device information**
{
  "System": {
    "version": "3.3.0b7",
    "uptime": "000+19:11:06.409",
    "uptime (seconds)": 69066,
    "freemem": 142,
    "reset reason": "Software reset CPU / Software reset CPU",
    "Dallas sensors": 0
  },
  "Status": {
    "bus": "connected",
    "bus protocol": "Buderus",
    "telegrams received": 39341,
    "read requests sent": 1379,
    "write requests sent": 4,
    "incomplete telegrams": 5,
    "tx fails": 73,
    "rx line quality": 100,
    "tx line quality": 95,
    "MQTT": "connected",
    "MQTT publishes": 22037,
    "MQTT publish fails": 0,
    "Dallas reads": 0,
    "Dallas fails": 0
  },
  "Devices": [
    {
      "type": "Boiler",
      "name": "Buderus GBx72/Trendline/Cerapur/Greenstar Si/27i (DeviceID:0x08 ProductID:123, Version:07.00)",
      "handlers": "0x10 0x11 0xC2 0x14 0x15 0x1C 0x18 0x19 0x1A 0x35 0x16 0x33 0x34 0x26 0x2A 0xD1 0xE3 0xE4 0xE5 0xE6 0xE9 0xEA"
    },
    {
      "type": "Thermostat",
      "name": "RC300/RC310/Moduline 3000/1010H/CW400/Sense II (DeviceID:0x10, ProductID:158, Version:74.02)",
      "handlers": "0xA3 0x06 0xA2 0x12 0x2A5 0x2B9 0x2AF 0x29B 0x471 0x2A6 0x2BA 0x2B0 0x29C 0x472 0x2A7 0x2BB 0x2B1 0x29D 0x473 0x2A8 0x2BC 0x2B2 0x29E 0x474 0x2F5 0x31B 0x31D 0x31E 0x23A 0x267 0x240"
    },
    {
      "type": "Controller",
      "name": "BC25 (DeviceID:0x09, ProductID:125, Version:03.05)"
    }
  ]

**Comment by proddy** [comment]
Oops. I'll take a look
