### ISSUE TITLE
Auto discovery fro Home Assistant is not consistent for Dallas sensors

### ISSUE THREAD

**Issue by FauthD** [emsesp/EMS-ESP32#2]
**Bug description**
esp32_dev 58067d1
 
**Steps to reproduce**
Connect at least one DS18B20 sensor,
reboot and watch results in HA.
No temperature values are parsed (but MQTT messages are being sent)

**Expected behavior**
Temperature values visible in HA.

**Screenshots**
Not yet and probably not helpful anyways.

**Device information**
*Copy-paste here the information as it is outputted by the device. You can get this information by from http://ems-esp/api?device=system&cmd=info*
`{
  "System": {
    "version": "3.0.0b1",
    "uptime": "000+00:35:42.679"
  },
  "Status": {
    "bus": "connected",
    "bus protocol": "Buderus",
    "#telegrams received": 2206,
    "#read requests sent": 556,
    "#write requests sent": 0,
    "#incomplete telegrams": 1,
    "#tx fails": 0,
    "rx line quality": 100,
    "tx line quality": 100,
    "#MQTT publish fails": 0,
    "#dallas sensors": 7,
    "#dallas fails": 2
  },
  "Devices": [
    {
      "type": "Boiler",
      "name": "GB125/MC10 (DeviceID:0x08, ProductID:72, Version:03.05)",
      "handlers": "0x10 0x11 0x14 0x15 0x16 0x18 0x19 0x1A 0x1C 0x2A 0x33 0x34 0x35 0xD1 0xE3 0xE4 0xE5 0xE6 0xE9 0xEA 0x494 0x495"
    },
    {
      "type": "Thermostat",
      "name": "RC300/RC310/Moduline 3000/1010H/CW400/Sense II (DeviceID:0x10, ProductID:158, Version:11.08)",
      "handlers": "0xA3 0x06 0xA2 0x12 0x2A5 0x2B9 0x2AF 0x29B 0x2A6 0x2BA 0x2B0 0x29C 0x2A7 0x2BB 0x2B1 0x29D 0x2A8 0x2BC 0x2B2 0x29E 0x2F5 0x31B 0x31D 0x31E 0x23A 0x267 0x240"
    },
    {
      "type": "Controller",
      "name": "BC10/RFM20 (DeviceID:0x09, ProductID:68, Version:02.03)",
      "handlers": ""
    }
  ]
}`

**Additional context**
Some analysis showed that the strings sent by auto discovery are not describing the payload.
The auto discovery shows 
`"uniq_id":"dallas_28-A813-7806-0000"`
Payload is:
`ems-esp/dallassensor_data {"28-A813-7806-0000":34.6,.....`

I removed the "dallas_" , deleted the items in HA, but it did not help so far.
Perhaps I do not fully understand the details here.

Next test:
The esp32_dev enforces the use of the "by sensor ID", the esp8266_dev branch does not.
For a test I changed that so I can use "by Number" even when HA discovery is enabled.
Now the temperature values show up in HA (string portion "dallas_" still removed).

Perhaps some change in HA needs adjustments here?
I use "Home Assistant 2021.1.5"

[dallassensor.cpp.txt](https://github.com/proddy/EMS-ESP/files/5975681/dallassensor.cpp.txt)

**Comment by proddy** [comment]
@FauthD could do that PR again on this repo branch?
