### ISSUE TITLE
FW120 : report wrong value for room influence factor

### ISSUE THREAD

**Issue by xavp06** [emsesp/EMS-ESP32#2011]
the FW120 "hc1 room influence factor" is showing 3% in EMS-ESP, but the real FW120 thermostat menu is showing 30%. I guess just a factor to be corrected ?

**Comment by xavp06** [comment]
Thermostat.cpp, in Thermostat::set_roominfl_factor : the value is *10. I could imagine that is it is a percentage, it should be *100

**Comment by MichaelDvP** [comment]
A bit confusing. For RC300 the factor in emsesp  is DIV10 without uom. For Junkers (FW120) we have uom percent and no scaling factor. To show 30% we have to add MUL10, but a percentage range > 1000% makes no sense.

**Comment by xavp06** [comment]
using v3.7.0-dev32
<img width="889" alt="Capture d’écran 2024-09-15 à 17 36 14" src="https://github.com/user-attachments/assets/c7470df7-1844-4dbb-af00-7b4f3a54f4a7">

**Comment by proddy** [comment]
thanks. we'll figure this one out...

**Comment by xavp06** [comment]
and reporting the same to my mqtt broker and influxdb database
<img width="1190" alt="Capture d’écran 2024-09-15 à 17 48 34" src="https://github.com/user-attachments/assets/d1820adb-d5bc-4fb1-82c3-3ad77c15965a">
