### ISSUE TITLE
MQTT: can we have network status messages (ip address, etc)

### ISSUE THREAD

**Issue by g6094199** [emsesp/EMS-ESP32#202]
Can we have IP (v4/v6) address send via MQTT  plz?
Also if its connected via ethernet or wifi (eg. important for w32-eth devices).

sometimes Gateway and DNS is also usefull for fast debugging (mostly on dhcp).

messages for SSID and MAC address will be a goodie on top.

**Comment by proddy** [comment]
good idea. So add the IPv6 IP, MAC and SSID (if enabled) to the API output of http://ems-esp.local/api/system/settings  

There is a topic called `ems-esp/info` which is sent when EMS-ESP starts with the version and IP address, e.g. `{"event":"start","version":"3.3.0b7","ip":"192.168.1.134"}` . I'll add the MAC and SSID too. Does that work for you?

**Comment by g6094199** [comment]
👍

> good idea. So add the IPv6 IP, MAC and SSID (if enabled) to the API output of http://ems-esp.local/api/system/settings
 I'll add the MAC and SSID too. Does that work for you?

maybe the bssid too  ;-)

**Comment by proddy** [comment]
ok. A bit like the command `show system` from the console does.

**Comment by g6094199** [comment]
in general, yes

**Comment by proddy** [comment]
ok. I meant the URL http://ems-esp.local/api/system (the info command) not settings. I'll add it shortly.

**Comment by proddy** [comment]
pls check 3.3.0b8

**Comment by g6094199** [comment]
whow, that was quick!
but i cant see any new mqtt messages coming in.

![Bildschirmfoto vom 2021-11-18 13-34-09](https://user-images.githubusercontent.com/37833326/142416187-de2a1bdd-11c7-4e6c-8f17-fd521ad634b8.png)

**Comment by proddy** [comment]
it's in the MQTT topic called `info`, not `heartbeat`. The heartbeat is used for dynamically changing data. It's a waste to send the Network details every 60 seconds if it doesn't change, and for Home Assistant to create sensors from them. If you want the information it's best to use the API and do a call to http://ems-esp.local/api/system. If you want to see this information in HA then manually create a sensor:

```yaml
sensor:
  - platform: rest
    resource: http://ems-esp.local/api/system/info
    name: emsesp_MAC
    value_template: "{{ value_json.Network.MAC }}"
```
