### ISSUE TITLE
Can we add Australian models?

### ISSUE THREAD

**Issue by VlastiBroucek** [emsesp/EMS-ESP32#2030]
### DESCRIPTION

This is not a bug or issue! This is just potential improvement, extension... I am in Australia and I doubt there are many users here. 

My boiler is identified as:

_boiler: Condens 2500/Logamax/Logomatic/Cerapur Top/Greenstar/Generic HT3 (DeviceID:0x08, ProductID:95, Version:12.16)_

It is actually Bosch Condens 5000 W (ZWB 37-2 A23)

My room thermostat is identified as:

_thermostat: RC200/CW100 (DeviceID:0x18, ProductID:157, Version:43.02)_

It is actually Bosch CR50

Controller is correctly identified as:

_controller: HT3 (DeviceID:0x09, ProductID:95, Version:12.16)_

### REQUESTED INFORMATION

_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X ] Searched the issue in [issues](https://github.com/emsesp/EMS-ESP32/issues)
- [X ] Searched the issue in [discussions](https://github.com/emsesp/EMS-ESP32/discussions)
- [X ] Searched the issue in the [docs](https://emsesp.org/Troubleshooting/)
- [X ] Searched the issue in the [chat](https://discord.gg/3J3GgnzpyT)
- [X ] Provide the System information in the area below, taken from `http://<IP>/api/system`

```json
  {
    "System Info": {
        "version": "3.6.5",
        "uptime": "002+23:37:10.273",
        "uptime (seconds)": 257830,
        "platform": "ESP32",
        "arduino": "ESP32 Arduino v2.0.14",
        "sdk": "v4.4.6-dirty",
        "free mem": 170,
        "max alloc": 107,
        "used app": 2240,
        "free app": 320,
        "partition": "boot",
        "reset reason": "Power on reset / APP CPU reset by PRO CPU"
    },
    "Network Info": {
        "network": "Ethernet",
        "hostname": "ems-esp",
        "TxPower setting": 0,
        "static ip config": false,
        "enable IPv6": true,
        "low bandwidth": false,
        "disable sleep": false,
        "enable MDNS": true,
        "enable CORS": false,
        "AP provision mode": "disconnected",
        "AP security": "wpa2",
        "AP ssid": "ems-esp"
    },
    "NTP Info": {
        "NTP status": "connected",
        "enabled": true,
        "server": "time.cloudflare.com",
        "tz label": "Australia/Hobart"
    },
    "OTA Info": {
        "enabled": false,
        "port": 8266
    },
    "MQTT Info": {
        "MQTT status": "connected",
        "MQTT publishes": 108000,
        "MQTT queued": 0,
        "MQTT publish fails": 0,
        "MQTT connects": 3,
        "enabled": true,
        "client id": "esp32-d767b4fc",
        "keep alive": 60,
        "clean session": false,
        "entity format": 1,
        "base": "ems-esp",
        "discovery prefix": "homeassistant",
        "discovery type": 0,
        "nested format": 1,
        "ha enabled": true,
        "mqtt qos": 0,
        "mqtt retain": false,
        "publish time heartbeat": 60,
        "publish time boiler": 10,
        "publish time thermostat": 10,
        "publish time solar": 10,
        "publish time mixer": 10,
        "publish time other": 60,
        "publish time sensor": 10,
        "publish single": false,
        "publish2command": false,
        "send response": false
    },
    "Syslog Info": {
        "enabled": false
    },
    "Sensor Info": {
        "temperature sensors": 3,
        "temperature sensor reads": 154689,
        "temperature sensor fails": 0,
        "analog sensors": 0,
        "analog sensor reads": 0,
        "analog sensor fails": 0
    },
    "API Info": {
        "API calls": 0,
        "API fails": 0
    },
    "Bus Info": {
        "bus status": "connected",
        "bus protocol": "HT3",
        "bus telegrams received (rx)": 197547,
        "bus reads (tx)": 47424,
        "bus writes (tx)": 0,
        "bus incomplete telegrams": 0,
        "bus reads failed": 0,
        "bus writes failed": 0,
        "bus rx line quality": 100,
        "bus tx line quality": 100
    },
    "Settings": {
        "board profile": "E32V2",
        "locale": "en",
        "tx mode": 3,
        "ems bus id": 11,
        "shower timer": false,
        "shower alert": false,
        "hide led": false,
        "notoken api": false,
        "readonly mode": false,
        "fahrenheit": false,
        "dallas parasite": false,
        "bool format": 1,
        "bool dashboard": 1,
        "enum format": 1,
        "analog enabled": true,
        "telnet enabled": true,
        "max web log buffer": 100,
        "web log buffer": 27
    },
    "Devices": [
        {
            "type": "boiler",
            "name": "Condens 2500/Logamax/Logomatic/Cerapur Top/Greenstar/Generic HT3",
            "device id": "0x08",
            "product id": 95,
            "version": "12.16",
            "entities": 69,
            "handlers received": "0x10 0x11 0x15 0x1C 0x18 0x19 0x34 0x2A 0x04",
            "handlers fetched": "0x14 0x16 0x33",
            "handlers pending": "0xBF 0xC2 0x1A 0x35 0x26",
            "handlers ignored": "0x23"
        },
        {
            "type": "thermostat",
            "name": "RC200/CW100",
            "device id": "0x18",
            "product id": 157,
            "version": "43.02",
            "entities": 42,
            "handlers received": "0x06 0xA2 0x031D",
            "handlers fetched": "0x02A5 0x02B9 0x02AF 0x029B 0x0291 0x02F5 0x023A",
            "handlers pending": "0xA3 0x12 0x13 0x0471 0x02A6 0x02BA 0x02B0 0x029C 0x0472 0x02A7 0x02BB 0x02B1 0x029D 0x0473 0x02A8 0x02BC 0x02B2 0x029E 0x0474 0x02A9 0x02BD 0x02B3 0x029F 0x0475 0x02AA 0x02BE 0x02B4 0x02A0 0x0476 0x02AB 0x02BF 0x02B5 0x02A1 0x0477 0x02AC 0x02C0 0x02B6 0x02A2 0x0478 0x02CC 0x0467 0x02CE 0x0468 0x02",
            "handlers ignored": "0xBF"
        },
        {
            "type": "controller",
            "name": "HT3",
            "device id": "0x09",
            "product id": 95,
            "version": "12.16",
            "entities": 0
        }
    ]
}


```

**(Please remember to close the issue when it has been addressed)**

**Comment by MichaelDvP** [comment]
We can add, but it's just a name. We use the product-id to identify devices. 
In v3.7.0 you can edit the name on the customization page.

**Comment by VlastiBroucek** [comment]
I agree. I was just thinking that people here in Australia would maybe use it more if they knew that AU branded boilers were supported. When I bought from BBQKees I just took the risk. Being in IT since 1985 I knew I would probably have enough skills to get it working together with you guys, but not everyone can do that.

It's your call, happy whichever way you decide.

BTW, many options in the thermostat are called differently here too, so perhaps not worth of fiddling with it.

**Comment by MichaelDvP** [comment]
Yes it's good to know the compatibility and names of the different devices. I've added the names. 
BBQKees already have your devcies on his list https://bbqkees-electronics.nl/ems-device-compatibility/ I think this is  where new users looks first.
> BTW, many options in the thermostat are called differently here too, so perhaps not worth of fiddling with it.

Also in customization you can rename the options long names. Bosch changes the names often with nearly every device. 
Maybe we should ask users to send us the customization files and collect them, named by device, in a folder here. Then other users can upload a `cr50_en.json` and have the right names.

**Comment by VlastiBroucek** [comment]
Ha, didn't notice he already put it there... Mine is SWB - includes DHW.

Good idea. I will have a look what I can do for CR50. Is there an example json file somewhere? Or just do something like:
CW100 | CR50
hc1 comfort temperature | hc1 heating temperature
hc1 eco temperature | hc1 setback temperature

TBH, I am not sure if this comes from boiler/HT3 or thermostat?

**Comment by MichaelDvP** [comment]
> Is there an example json file somewhere? 

On the customization page edit the entities (name and/or min/max)., save, then go to settings->download and download the customization file. This is the json we need.

**Comment by VlastiBroucek** [comment]
Will do. When do you expect 3.7 to come out to prod? Since I use this more for monitoring than anything else right now (so, no damage if something does not work) I might install the dev and do it under it...
