### ISSUE TITLE
minor issue: search in customizations only searches the english/original names (not the tranlated ones)

### ISSUE THREAD

**Issue by harvey637** [emsesp/EMS-ESP32#2056]
Hi, this is very minor, but noticable:

if set to a language like "DE" in customizations the german names are displayed, ok.
But searching only searches the smaller "original" names.
It is a bit strange at first sight, that searching for all "WWK" (warm water stuff ...) shows: nothing.
But as I typed the first "W" all WarmWater stuff was shown. With the second "WW" no results.

Than I tried the "dhw" for the english names (or the "original" technical names) everything works as expected.

![grafik](https://github.com/user-attachments/assets/97ba7ac7-b555-4da1-b6e0-f0ecc6a629bb)

Not a big deal, but should be explained to novice users or as a popup ... 
No code change requested, just noticed!
cu
Harvey

**Comment by proddy** [comment]
That's actually a really good point, thanks for mentioning it. The search is filtering on the short name only which is the text that is bracketed in light-blue. It should also match the name being displayed. We'll make a change. Thanks!

**Comment by proddy** [comment]
it was because of the case conversion. I'll do a PR
