### ISSUE TITLE
Support for ESP32(-S3) internal temperature sensor

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#2077]
As @bbqkees made me aware, the ESP32(-S3) has an internal temperature sensor. To do

1 - auto-add as a temperaturesensor for this board, so it's shown in the Sensors
2 - write a FAQ on how to use the Scheduler to send an alert if the EMS-ESP board gets too hot

https://docs.espressif.com/projects/esp-idf/en/stable/esp32s3/api-reference/peripherals/temp_sensor.html

**Comment by bbqkees** [comment]
I would classify it as a system sensor as well, next to the free RAM, used flash etc.

**Comment by proddy** [comment]
Yes, adding as a system attribute makes much more sense.

**Comment by MichaelDvP** [comment]
I've tested the sensor, works good. But nasty that ESP32 does not have one and IDF 4.x implementation is different from IDF 5.x. A lot of ' #if' 
Added in mqtt-heartbeat and api/system/info, in web i've added it to hardware status-CPU
![grafik](https://github.com/user-attachments/assets/9e5d7a18-e940-4982-9351-e7804d5a18e4)
Should i add to my dev and make a PR?

**Comment by proddy** [comment]
I think we can add it to 3.7.0 while I finish up the Dashboard

**Comment by proddy** [comment]
works great. a nice addition.
