### ISSUE TITLE
heatingpumpmod always 0 in latest build

### ISSUE THREAD

**Issue by Vippis2000** [emsesp/EMS-ESP32#2081]
Hi,
I have updatet to 3.7.0-dev.43 and found heatingpumpmod to be always 0. Was working in older releases.

Was there any change?

[Kessel_WP_Enviline, Compress 6000AW, Hybrid 3000-7000iAW, SupraEco_Geo 5xx, WLW196i_WSW196i.csv](https://github.com/user-attachments/files/17323167/Kessel_WP_Enviline.Compress.6000AW.Hybrid.3000-7000iAW.SupraEco_Geo.5xx.WLW196i_WSW196i.csv)

**Comment by MichaelDvP** [comment]
I've diff v3.6.5 vs. 3.7.0dev43 and can't see any change in code regarding heatingpumpmod..

**Comment by proddy** [comment]
send us the telegram, and we'll see what the value is.  `read 8 E5`
