### ISSUE TITLE
EMS - Time to next maintenance (difference in EMS app and HA MQTT)

### ISSUE THREAD

**Issue by misa1515** [emsesp/EMS-ESP32#2099]
### DESCRIPTION

Difference showed in attached picture

### REQUESTED INFORMATION

_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Searched the issue in [issues](https://github.com/emsesp/EMS-ESP32/issues)
- [ ] Searched the issue in [discussions](https://github.com/emsesp/EMS-ESP32/discussions)
- [ ] Searched the issue in the [docs](https://emsesp.org/Troubleshooting/)
- [ ] Searched the issue in the [chat](https://discord.gg/3J3GgnzpyT)
- [x] Provide the System information in the area below, taken from `http://<IP>/api/system`

```json

[ApiSystem.txt](https://github.com/user-attachments/files/17390103/ApiSystem.txt)


```

### TO REPRODUCE

Screenshot attached

### EXPECTED BEHAVIOUR

Please correct value in HA MQTT 

### SCREENSHOTS

![2024-10-14_18-03-54](https://github.com/user-attachments/assets/510265ba-1dbd-4148-80d5-b19b67267aae)

![2024-10-14_18-23-16](https://github.com/user-attachments/assets/6ba23ca8-59e6-409f-91d3-ceb7d11ba0e9)

### ADDITIONAL CONTEXT

_Add any other context about the issue here._

**(Please remember to close the issue when it has been addressed)**

**Comment by MichaelDvP** [comment]
The time is stored in hours and also published to mqtt in hours. 
For better readable in webUI we convert to days + hours.

**Comment by misa1515** [comment]
I found 250*24 = 6000 last weekend.
Thank you @MichaelDvP

**Comment by proddy** [comment]
there's an example in the doc [here](https://emsesp.org/Home-Assistant/#solar-pump-working-hour) how to customize an entity in HA
