### ISSUE TITLE
Rename wwheat and other device entities

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#211]
From #198, @FredericMa mentioned :

> MQTT sensor: `wwheat` from the `ems-esp/boiler_data_ww` is `ON`. This indicates the 3-way valve is open towards the tank. @proddy, now I think about it, `wwheat` it is rather a abstract description for a valve and as in this case it also doesn't mean that any heating is still going on. Maybe something like `ww3waytobuffer` or `wwvalvetobuffer` is more clear?

Many of the short names for device entities were made up on the spot, loosely translated from whatever I could find in German, Italian or French. And often corrected by users between the releases.

`wwheat` got to be called "Warm Water Heating" which I agree is it bit dubious. (BTW you can see the complete list on https://emsesp.github.io/docs/#/MQTT?id=boiler)

so happy to change it and any others that need fixing. Keep in mind changing the short name will be breaking change but it's good practice to have the short & long names matching. 

so for `wwheat` it's  `ww3waytobuffer` or `wwvalvetobuffer`? And the long descriptive name is?

**Comment by glitter-ball** [comment]
What's the alternate state? Should probably consider that, or is it just ww... on or off?

**Comment by proddy** [comment]
it's on/off. The type is a Boolean:

http://ems-esp.local/api/boiler/wwheat

```json
{
  "name": "wwheat",
  "fullname": "ww heating",
  "circuit": "ww",
  "value": "on",
  "type": "boolean",
  "writeable": false,
  "ha_entityname": "sensor.boiler_ww_heating"
}
```

**Comment by FredericMa** [comment]
How about `3-way valve towards buffer` or `3-way valve buffer position`? Or is this too long?

**Comment by proddy** [comment]
From the original famous [emswiki](https://emswiki.thefischer.net/doku.php?id=wiki:ems:telegramme#wwbetriebsart) they call it "**3-way valve on WW**" and on [Norbert's excellent HT3 mapping](https://github.com/norberts1/hometop_HT3/blob/master/HT3/docu/HT_EMS_Bus_messages.pdf) he calls it "**3-way valve on storage charge**". We can pick either?

**Comment by FredericMa** [comment]
+1 for "3-way valve on WW"

**Comment by proddy** [comment]
and for the shortname `wwheat` -> `ww3wayon` ?

**Comment by FredericMa** [comment]
Yeah, should be clear enough I guess.

**Comment by proddy** [comment]
ok, since it's a breaking change I'll include in 3.4

**Comment by proddy** [comment]
Also rename wwdisinfect -> wwdisinfecting

**Comment by proddy** [comment]
in 3.4, coming soon to the dev branch

**Comment by proddy** [comment]
@MichaelDvP said "rename of wwdisinfect to wwdisinfecting is right for boiler, but not for thermostat"

**Comment by MichaelDvP** [comment]
For boiler it is the actual state disinfecting, For thermostat it is the command set disinfection on/off with time schedule of day and hour.

**Comment by proddy** [comment]
@MichaelDvP rename `ww3wayon `to  `ww3waycharge` ?

**Comment by MichaelDvP** [comment]
We have for the chargetype the enum: `charge pump` or `3-way valve`, so i would prefere ww3wayvalve, but since i don't have it, i don't care much. Only the setting `ww3wayon off` looks odd to me.

**Comment by proddy** [comment]
> We have for the chargetype the enum: `charge pump` or `3-way valve`, so i would prefere ww3wayvalve, but since i don't have it, i don't care much. Only the setting `ww3wayon off` looks odd to me.

changed to ww3wayvalve in v3.4 and leaving disinfecting to how it is now.
