### ISSUE TITLE
Call read commands from Web

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#2116]
This has been discussed before and not implemented in favour of the `send` command, but I still think it's useful for novice users.

I've added a new setting in Application Settings called `Developer Mode` which we can use to expose more advanced/debug/developer type features. When enabled you'll get a new command icon in the Web Log where you can send write commands like:

![image](https://github.com/user-attachments/assets/59ad591d-9eed-49ac-aa21-2bca7ec87ff9)

**Comment by Delta1977** [comment]
great feature.
i have another Idea:
It would be great if we could do this also via api or mqtt or is this also implemented?

**Comment by proddy** [comment]
> great feature. i have another Idea: It would be great if we could do this also via api or mqtt or is this also implemented?

Yes, possible now. It's a new system command called `read` so you can call it via API and MQTT.  Like

```sh
curl -X POST \
    -H "Authorization: Bearer ${emsesp_token}" \
    -H "Content-Type: application/json" \
    -d '{"value":"8 2"}' \
    ${emsesp_url}/api/system/read
```

**Comment by Delta1977** [comment]
Very cool. Thank you

**Comment by Delta1977** [comment]
@proddy  i tested the MQTT Variant and the Output is logged in EMS-ESP Log, but no return via mqtt.
is a Mqtt-feedback planned? 
Maybe we can publish the complete Logs via MQTT in an logging Topic.

**Comment by proddy** [comment]
> @proddy i tested the MQTT Variant and the Output is logged in EMS-ESP Log, but no return via mqtt. is a Mqtt-feedback planned? Maybe we can publish the complete Logs via MQTT in an logging Topic.

<IP>/settings/version

**Comment by proddy** [comment]
@Delta1977  log output isn't sent over MQTT, it wouldn't be very useful as each log line would be replaced every second and unless you're quick enough to catch it you'll miss half the logs. We use the SysLog protocol for that as it's designed for that. Alternatively, you could tap into the SSE event source, which is over HTTP.  

The idea of this feature is for novice users to type in a simple read command, then watch the single line output, copy & paste into GitHub for the developers to work on.

**Comment by VlastiBroucek** [comment]
I am using 3.7.1-dev.2 and it is not working. Tried it in Edge, Chrome and Firefox on both Windows and in KALI Linux

**Comment by proddy** [comment]
> I am using 3.7.1-dev.2 and it is not working. Tried it in Edge, Chrome and Firefox on both Windows and in KALI Linux

can you be more specific? what doesn't work? what happens? what do you see?

**Comment by VlastiBroucek** [comment]
I put in e.g. 0x18 0x06 hit enter and nothing happens, no output in log at all.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by proddy** [comment]
try just '18 6'

**Comment by VlastiBroucek** [comment]
Oh, that works...
