### ISSUE TITLE
Menu is automatically changing when getting into Download / Upload

### ISSUE THREAD

**Issue by HansRemmerswaal** [emsesp/EMS-ESP32#2118]
I'm using the following firmware:

Version: 3.7.0-dev.46
Platform: ESP32-16MB+
Release: Development

I have the following minor issue...

**Issue:**
1. In EMS-ESP I click on **Status** and the Status menu is opened
2. For the Firmware Version I click on UPDATE to see if there are updates
3. The screen is opened with Download / Upload and what we see is that the highlighting in the menu is changed from **Status** to **Settings**
4. If I now click on the arrow back I end up in the **Settings** menu and not in the **Status** menu

**Requested fix:**
Do not change the menu from Status to Settings when clicking on the UPDATE button for Firmware Version

![image](https://github.com/user-attachments/assets/e750d20b-4525-4b27-b6f0-83cb037ffe9f)

![image](https://github.com/user-attachments/assets/e9ad0191-96dc-46dd-b45b-be1b0ed03cee)

![image](https://github.com/user-attachments/assets/d924ba88-7ffe-477c-b8c5-bfe460a10729)

**Comment by MichaelDvP** [comment]
This is a mix of old browser cache and new web, press ctrl-R.

**Comment by proddy** [comment]
I'm aware of this, one it's a edge case that I hope nobody would notice :-) The code for the 'back' button looks at the URL and steps back, so `/settings/upload` go back to `/settings`. I'll have a think about how best to program this without adding too much extra code. This is the only place it happens

**Comment by HansRemmerswaal** [comment]
This was in Chrome... And the CTR-R didn't solve it.
And  I have the same on my iPad and iPhone using Safari.

What I find strange is that as soon as I get in the Download/Upload the menu bottom left is already changing from Status to Settings

**Comment by HansRemmerswaal** [comment]
Ah.... now I understand. from the status menu you call an option from the setting menu (Download/Upload). And that's why the back button gets confused. I would not spend to much time on this minor issue...

On this page I click on the UPDATE button...
http://192.168.0.239/status

... and that brings me to...
http://192.168.0.239/settings/upload

... then when I press the back I get in...
http://192.168.0.239/settings

... and on the settings menu we have the Download/Upload.

**Comment by proddy** [comment]
Yes, it just traverses back up the tree. I can navigate to the last visited page, but then if you go from say www.google.com to http://192.168.0.239/settings/upload and hit the Back arrow in EMS-ESP, it would take you back to google.com. So also not a good solution. 

I'll start a new discussion on this - need Michael's input on some UI changes inspired by your comment.

**Comment by mattreim** [comment]
> @MichaelDvP I was looking at the UI and proposed these changes. What do you think:
> 
> a - In the Settings page, remove the word 'Settings' from all the options. The word Settings is mentioned 9 times on that page. So 'Application Settings' goes to just 'Settings'. b - Same for the Status page, remove the word 'Status' c - Move the version from Status to Settings. Status is a refreshed page showing live data, but Version is static and doesn't need to be shown all the time. People just want a working system and not bothered by the build number.
> 
> votes?

I think all the ideas (a -c) are very good and there may be another one.

d - The icon already says download, the word download can also be removed in these cases.

![EMS-download](https://github.com/user-attachments/assets/ae031126-89a0-4d40-b197-a4034bfcde65)

![EMS-download-2](https://github.com/user-attachments/assets/3eb3d573-e0bb-4e97-b8a8-4cfc9c583f90)

**Comment by proddy** [comment]
Thanks for the feedback, I'll make the changes today

**Comment by proddy** [comment]
demo at https://demo.emsesp.org

**Comment by mattreim** [comment]
It definitely looks better and is clearer. It's just a matter of getting used to checking for the firmware version and uploading them are now in different places.

Just a reminder.
![EMS-Name](https://github.com/user-attachments/assets/fd655311-aef9-4e2d-97fc-33381343a7f5)

**Comment by proddy** [comment]
clicking on the firmware install button automatically downloads and updates, if that's easier. Most people wont update for months/years so it's really a power-user option for those using the latest dev versions.

I left the Settings and Status in the page titles on purpose, otherwise there would be no context when visiting those pages.

**Comment by mattreim** [comment]
> clicking on the firmware install button automatically downloads and updates, if that's easier. Most people wont update for months/years so it's really a power-user option for those using the latest dev versions.
> 
> I left the Settings and Status in the page titles on purpose, otherwise there would be no context when visiting those pages.

You're absolutely right. Hardly any user will update as often as we do ;)

**Comment by HansRemmerswaal** [comment]
I also think it's more clean now
