### ISSUE TITLE
Emulated RC100H causes many incomplete Rx

### ISSUE THREAD

**Issue by Sbried** [emsesp/EMS-ESP32#2140]
### DESCRIPTION

Normally I don´t see warnings in the log, the system runs stable for long periods. 
Now I´m experimenting with the emulated thermostat RC100H.
I activated it with sending RC100H to `ems-esp/thermostat/hc1/control`. Through the API I send the actual temperature and humidity data to `ems-esp/thermostat/hc1/remotetemp` and `ems-esp/thermostat/hc1/remotehum`. All is recognized well and the HMC310 is showing the correct data.
The issue now is that I receive a lot of incomplete Rx warnings in the log. All sent by the emulated RC100H 0x38 to the thermostat HMC310 0x10.
After a random time between some hours and a day the ems-esp reboots.

I´ve read a lot in the issues/discussions and tried with different Tx protocols EMS and EMS+. Both result in the same. The power supply should be good, I don´t have issues without the emulated RC100H. The ems-esp is connected to the service jack of the heat pump.
There is no correlation between updating the temperature/humidity through the API and the warnings. As I understood the code the temperature/humidity data is sent every 15 sec to the thermostat 0x10. Some of them may end up in a warning being incomplete.

Some lines from the log:
2024-10-26 08:07:45.976 WARNING 10: [telegram] Incomplete Rx: 38 10 FF 00 03 2B 00 FD
2024-10-26 08:25:58.028 WARNING 11: [telegram] Incomplete Rx: 38 10 FF 00 03 7B 0E 8B 0A
2024-10-26 08:35:09.035 WARNING 12: [telegram] Incomplete Rx: 38 10 FF 00 03 2B 00 F2
2024-10-26 08:36:14.049 WARNING 13: [telegram] Incomplete Rx: 38 10 FF 00 03 2B 00 F2
2024-10-26 08:43:46.058 WARNING 14: [telegram] Incomplete Rx: 38 10 FF 00 03 2B 00 F3
2024-10-26 09:06:05.124 WARNING 15: [telegram] Incomplete Rx: 38 10 FF 00 03 2B FE
2024-10-26 09:10:09.132 WARNING 16: [telegram] Incomplete Rx: 38 10 FF 00 03 7B 0E 8B 0A
2024-10-26 09:11:13.110 WARNING 17: [telegram] Incomplete Rx: 38 10 FF 00 03 7B 0E 38 00 8B 0F E7
2024-10-26 09:12:33.135 WARNING 18: [telegram] Incomplete Rx: 38 10 FF 00 03 7B 0E 8B 0A
2024-10-26 09:32:16.547 WARNING 19: [telegram] Incomplete Rx: 38 10 FF 00 03 38 00 8C 0D
2024-10-26 09:35:56.547 WARNING 20: [telegram] Incomplete Rx: 38 10 FF 00 03 E9 F2
2024-10-26 09:37:51.204 WARNING 21: [telegram] Incomplete Rx: 38 10 FF 00 03 7B 0E 8C 0D
2024-10-26 09:45:11.659 WARNING 22: [telegram] Incomplete Rx: 38 10 FF 00 03 E9 F2
2024-10-26 09:48:26.565 WARNING 23: [telegram] Incomplete Rx: 38 10 FF 00 03 2F FE 00 0D
2024-10-26 09:49:31.230 WARNING 24: [telegram] Incomplete Rx: 38 10 FF 00 03 7B 0E 8C 0D
2024-10-26 09:51:07.232 WARNING 25: [telegram] Incomplete Rx: 38 10 FF 00 03 7B 0E 8C 0D
2024-10-26 09:55:14.233 WARNING 26: [telegram] Incomplete Rx: 38 10 FF 00 03 2B 00 F2
2024-10-26 09:58:28.250 WARNING 27: [telegram] Incomplete Rx: 38 10 FF 00 03 2B 00 F2
2024-10-26 10:04:33.257 WARNING 28: [telegram] Incomplete Rx: 38 10 FF 00 03 2B 00 F2
2024-10-26 10:09:42.283 WARNING 29: [telegram] Incomplete Rx: 38 10 02 FE 28 FF 98
2024-10-26 10:20:36.297 WARNING 30: [telegram] Incomplete Rx: 38 10 FF 00 03 7B 0E 38 00 8E 8D
2024-10-26 10:33:49.714 WARNING 31: [telegram] Incomplete Rx: 38 10 02 00 C8 28 04 00 98
2024-10-26 10:35:58.421 WARNING 32: [telegram] Incomplete Rx: 38 10 FF 00 A0 00 E9 F2
2024-10-26 10:44:00.022 WARNING 33: [telegram] Incomplete Rx: 38 10 FF 00 03 7B 0E 38 00 8C 9E
2024-10-26 10:54:42.839 WARNING 34: [telegram] Incomplete Rx: 38 10 02 00 C8 28 04 00 98
2024-10-26 10:54:56.381 WARNING 35: [telegram] Incomplete Rx: 38 10 FF 00 03 2B 00 F0
2024-10-26 11:08:37.164 WARNING 36: [telegram] Incomplete Rx: 38 10 FF 00 03 0E 38 00 8E 0F
2024-10-26 11:15:39.444 WARNING 37: [telegram] Incomplete Rx: 38 10 FF 00 03 2B 00 F0
2024-10-26 11:22:22.452 WARNING 38: [telegram] Incomplete Rx: 38 10 FF 00 03 2B 00 F0
2024-10-26 11:29:49.474 WARNING 39: [telegram] Incomplete Rx: 38 10 FF 00 03 2B 00 F2
2024-10-26 11:40:28.005 WARNING 40: [telegram] Incomplete Rx: 38 10 FF 00 03 7B FE 00 FF E4
2024-10-26 11:47:59.521 WARNING 41: [telegram] Incomplete Rx: 38 10 FF 00 03 2B 00 F0
2024-10-26 11:48:17.013 WARNING 42: [telegram] Incomplete Rx: 38 10 FF 00 A0 0E 38 00 8E 0F
2024-10-26 11:48:49.303 WARNING 43: [telegram] Incomplete Rx: 38 10 FF 00 03 7B 0E 38 00 8E 89
2024-10-26 11:52:54.531 WARNING 44: [telegram] Incomplete Rx: 38 10 FF 00 03 7B 0E 8E 0F
2024-10-26 12:08:38.571 WARNING 45: [telegram] Incomplete Rx: 38 10 FF 00 03 2B 00 F0
2024-10-26 12:20:02.052 WARNING 46: [telegram] Incomplete Rx: 38 10 FF 00 A0 0E 38 00 8C 0D
2024-10-26 12:30:59.624 WARNING 47: [telegram] Incomplete Rx: 38 10 FF 00 03 2B 00 F2
2024-10-26 12:31:16.624 WARNING 48: [telegram] Incomplete Rx: 38 10 FF 00 03 2B 00 F2
2024-10-26 12:33:26.758 WARNING 49: [telegram] Incomplete Rx: 38 10 FF 00 03 7B 0E 38 00 8C 89
2024-10-26 12:36:56.644 WARNING 50: [telegram] Incomplete Rx: 38 10 FF 00 03 2B 00 F2
2024-10-26 12:55:25.700 WARNING 51: [telegram] Incomplete Rx: 38 10 02 00 28 04 00 FF 98
2024-10-26 12:59:15.701 WARNING 52: [telegram] Incomplete Rx: 38 10 FF 00 03 7B 0E 89 34
2024-10-26 13:00:53.703 WARNING 53: [telegram] Incomplete Rx: 38 10 FF 00 03 7B 0E 89 34

### REQUESTED INFORMATION

_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Searched the issue in [issues](https://github.com/emsesp/EMS-ESP32/issues)
- [x] Searched the issue in [discussions](https://github.com/emsesp/EMS-ESP32/discussions)
- [x] Searched the issue in the [docs](https://emsesp.org/Troubleshooting/)
- [x] Searched the issue in the [chat](https://discord.gg/3J3GgnzpyT)
- [x] Provide the System information in the area below, taken from `http://<IP>/api/system`

```json
  {
    "system": {
        "version": "3.7.0-dev.48",
        "uptime": "000+05:34:50.391",
        "uptimeSec": 20090,
        "platform": "ESP32",
        "cpuType": "ESP32-D0WD-V3",
        "arduino": "ESP32 Arduino v2.0.17",
        "sdk": "v4.4.7-dirty",
        "freeMem": 147,
        "maxAlloc": 107,
        "freeCaps": 4163,
        "usedApp": 2375,
        "freeApp": 3321,
        "partition": "app0",
        "resetReason": "Software reset CPU / Software reset CPU",
        "psram": true,
        "psramSize": 4093,
        "freePsram": 4051,
        "model": "BBQKees Gateway Model EMS Gateway E32 V2 v2.0/2024071"
    },
    "network": {
        "network": "Ethernet",
        "hostname": "ems-esp",
        "TxPowerSetting": 0,
        "staticIP": false,
        "lowBandwidth": false,
        "disableSleep": true,
        "enableMDNS": true,
        "enableCORS": false,
        "APProvisionMode": "disconnected",
        "APSecurity": "wpa2",
        "APSSID": "ems-esp"
    },
    "ntp": {
        "NTPStatus": "connected",
        "enabled": true,
        "server": "fritz.box",
        "tzLabel": "Europe/Amsterdam"
    },
    "mqtt": {
        "MQTTStatus": "connected",
        "MQTTPublishes": 4600,
        "MQTTQueued": 0,
        "MQTTPublishFails": 0,
        "MQTTConnects": 1,
        "enabled": true,
        "clientID": "esp32-2cb865e4",
        "keepAlive": 60,
        "cleanSession": false,
        "entityFormat": 0,
        "base": "ems-esp",
        "discoveryPrefix": "homeassistant",
        "discoveryType": 0,
        "nestedFormat": 1,
        "haEnabled": true,
        "mqttQos": 0,
        "mqttRetain": false,
        "publishTimeHeartbeat": 60,
        "publishTimeBoiler": 10,
        "publishTimeThermostat": 10,
        "publishTimeSolar": 10,
        "publishTimeMixer": 10,
        "publishTimeWater": 10,
        "publishTimeOther": 10,
        "publishTimeSensor": 10,
        "publishSingle": false,
        "publish2command": false,
        "sendResponse": false
    },
    "syslog": {
        "enabled": false
    },
    "sensor": {
        "temperatureSensors": 0,
        "temperatureSensorReads": 0,
        "temperatureSensorFails": 0,
        "analogSensors": 0,
        "analogSensorReads": 0,
        "analogSensorFails": 0
    },
    "api": {
        "APICalls": 168,
        "APIFails": 0
    },
    "bus": {
        "busStatus": "connected",
        "busProtocol": "Buderus",
        "busTelegramsReceived": 78985,
        "busReads": 17778,
        "busWrites": 3,
        "busIncompleteTelegrams": 50,
        "busReadsFailed": 0,
        "busWritesFailed": 0,
        "busRxLineQuality": 100,
        "busTxLineQuality": 100
    },
    "settings": {
        "boardProfile": "E32V2",
        "locale": "de",
        "txMode": 1,
        "emsBusID": 11,
        "showerTimer": false,
        "showerMinDuration": 180,
        "showerAlert": false,
        "hideLed": false,
        "noTokenApi": false,
        "readonlyMode": false,
        "fahrenheit": false,
        "dallasParasite": false,
        "boolFormat": 5,
        "boolDashboard": 1,
        "enumFormat": 1,
        "analogEnabled": true,
        "telnetEnabled": true,
        "maxWebLogBuffer": 50,
        "webLogBuffer": 50,
        "modbusEnabled": false,
        "forceHeatingOff": false,
        "developerMode": false
    },
    "devices": [
        {
            "type": "boiler",
            "name": "Enviline, Compress 6000AW, Hybrid 3000-7000iAW, SupraEco/Geo 5xx, WLW196i/WSW196i",
            "deviceID": "0x08",
            "productID": 172,
            "brand": "",
            "version": "02.02",
            "entities": 155,
            "handlersReceived": "0xBF 0xC2 0xD1 0xE3 0xE4 0xE5 0xE9 0x0494 0x0495 0x048F",
            "handlersFetched": "0x14 0xE6 0xEA 0x048D 0x048A 0x04A2 0x0485 0x0486 0x0492 0x0488 0x0484 0x048B 0x0491 0x0499 0x049C 0x049D 0x02CC 0x04AA 0x02D6",
            "handlersPending": "0x10 0x11 0x15 0x1C 0x18 0x19 0x1A 0x35 0x16 0x33 0x34 0x26 0x2A 0x28 0x04AE 0x04AF 0x04A5 0x04A7",
            "handlersIgnored": "0x0240 0xF7 0x049F 0x04A0 0x04A3 0x0497 0xE7 0x02E0 0x02EA 0x061E 0x2E 0x3B 0x17 0x36"
        },
        {
            "type": "thermostat",
            "name": "RC3*0, Moduline 3000/1010H, CW400, Sense II, HPC410",
            "deviceID": "0x10",
            "productID": 158,
            "brand": "",
            "version": "73.04",
            "entities": 68,
            "handlersReceived": "0x06 0x02BA 0x02BB 0x02BC 0x02BD 0x02BF 0x02C0 0x031D 0x0267",
            "handlersFetched": "0x02A5 0x02B9 0x02AF 0x029B 0x0471 0x02CC 0x0467 0x0291 0x0292 0x0293 0x0294 0x02F5 0x023A 0x0240 0xBB 0x023E 0x0269",
            "handlersPending": "0xA3 0xA2 0x12 0x13 0x02A6 0x02B0 0x029C 0x0472 0x02A7 0x02B1 0x029D 0x0473 0x02A8 0x02B2 0x029E 0x0474 0x02A9 0x02B3 0x029F 0x0475 0x02AA 0x02BE 0x02B4 0x02A0 0x0476 0x02AB 0x02B5 0x02A1 0x0477 0x02AC 0x02B6 0x02A2 0x0478 0x02CE 0x0468 0x02D0 0x0469 0x02D2 0x046A 0x02F6 0x031B 0x031E",
            "handlersIgnored": "0xF7 0x0239 0x0508 0x0509 0x050A 0x0507 0xF6 0xBF 0x042B"
        },
        {
            "type": "thermostat",
            "name": "RC100H, CR10H",
            "deviceID": "0x38",
            "productID": 200,
            "brand": "",
            "version": "40.04",
            "entities": 3,
            "handlersReceived": "0x042B 0x047B",
            "handlersPending": "0x0273 0x0A6A"
        },
        {
            "type": "gateway",
            "name": "WiFi module",
            "deviceID": "0x48",
            "productID": 252,
            "brand": "Buderus",
            "version": "08.02",
            "entities": 0,
            "handlersIgnored": "0x2040 0x0495 0x0494 0x3B 0xE5 0xE9 0xF9"
        }
    ]
}
```

### TO REPRODUCE

Maybe also others can reproduce it by setting up an emulated thermostat.
I can reproduce it by removing the emulated RC100H (no more warnings in the log) and setting the RC100H again (log warning start again)

### EXPECTED BEHAVIOUR

Emulated thermostat does not cause incomplete Rx

### SCREENSHOTS

na

### ADDITIONAL CONTEXT

na

**(Please remember to close the issue when it has been addressed)**

**Comment by proddy** [comment]
I can't explain the restarts. Next time it happens see if you capture the log as it'll show the 'reason'.

@MichaelDvP any idea on those short Rx telegrams?

**Comment by MichaelDvP** [comment]
For the reboots: was it #2122, i can see that now you're using dev48 and uptime is > 5 days.

The incompletes are difficult. As you've found it sends the message every 15 sec, the wrong readback is one in 5-10 min, so it's only 3% of the telegrams sent, that have issue with readback. Also the master thermostat detect the remote constantly, so maybe only the readback in emsesp have problems. For sendings from ems-esp-device-address we do not show the readback, maybe there are also issues. The messages do not affect operation.
Sending and receiving the same time is difficult because the sending (drain current from bus) can effect a local drop in bus voltage, resulting in a read-error only on the sending device. 
Try with tx-mode EMS+, that has more delay after sending, helping to stabilize the bus-voltage.

**Comment by Sbried** [comment]
Actually the uptime was >5 hrs from the system info above but anyhow - it is running till now, > 2 days. The dev48 seemed to fix the reboots.
I had the EMS+ tx-mode before and also had a lot of incomplete messages. Maybe not so many, I didn´t make statistics about it. 
If it is hardware related, maybe not showing the readback is also a solution. Then the emulated remote thermostat should have a special marker to detect it´s emulated or a real device. Maybe a special SW version for the emulated one.

**Comment by MichaelDvP** [comment]
I have to correct me, we show the echos of emsesp sending (it was an early version that suppress the echos).

Can you make a full log of the telegram to see in which context the errors happen. I suspect that this is not the normal 15 sec sending but an answer to a query, maybe with offset/length different from answer (the emulation always send the complete telegram).

**Comment by MichaelDvP** [comment]
Yes, they do not give a warning or tx-error count, but in full log they are shown with loglevel trace (T).

**Comment by MichaelDvP** [comment]
Could you post a full log (log all) to see if the incompletes are only for thermostat or also for other emsesp sendings.

**Comment by Sbried** [comment]
Attached is an 8 minutes log all.
[logall.txt](https://github.com/user-attachments/files/17578999/logall.txt)
It contains 10 incomplete messages. One is from the emulated RC100H (0x38), the other 9 are from EMS-ESP (0x0B). But the incompletes from EMS-ESP itself do not show up in the warnings, they go only in the trace.
This is what I also would like for the emulated RC100H (and other emulated things) too.

**Comment by MichaelDvP** [comment]
> This is what I also would like for the emulated RC100H (and other emulated things) too.

This should work with my build https://github.com/MichaelDvP/EMS-ESP32/releases/tag/latest Please check, In my system i don't have incompletes for own sendings.

How is your emsesp connected to bus? Try if it get's better with a shorter/thicker bus-cable.

**Comment by mattreim** [comment]
Hello everyone, I have now finished my tests with dev.1 and dev.3. Over 1 million telegrams were transmitted in just under 6 days.

3.7.1-dev.1:
![EMS-Fehler-3 7 1-dev 1](https://github.com/user-attachments/assets/67b029ec-e14b-4342-b95b-e4a52463a3e7)

3.7.1-dev.3:
![EMS-Fehler-3 7 1-dev 3](https://github.com/user-attachments/assets/f82db099-34c1-414c-ac0c-4c4f6b379f56)

I think a reduction from 98 to 10 incompletes errors is very good.

```
CPU: ESP32-D0WD-V3
Platform: ESP32-4MB
EMS Tx mode: EMS
Emulated remote: RC100H
```
