### ISSUE TITLE
Missing attributes in MQTT Discovery Message

### ISSUE THREAD

**Issue by der-seemann** [emsesp/EMS-ESP32#2149]
### DESCRIPTION

MQTT Discovery for Homeassistant. The "number" entitys miss "unit_of_meas", "stat_cla" and "dev_cla".
I can resend the messages with these attributes, and they are correctly recived by Homeassistant (Mosquitto broker).

### REQUESTED INFORMATION

{"system":{"version":"3.7.0","uptime":"000+21:45:51.777","uptimeSec":78351,"platform":"ESP32","cpuType":"ESP32-D0WD-V3","arduino":"Tasmota Arduino v2.0.17","sdk":"4.4.8.240628","freeMem":152,"maxAlloc":79,"freeCaps":103,"usedApp":1730,"freeApp":254,"partition":"app1","resetReason":"Software reset CPU / Software reset CPU","psram":false,"model":""},"network":{"network":"WiFi","hostname":"ems-esp","RSSI":-86,"TxPowerSetting":0,"staticIP":false,"lowBandwidth":false,"disableSleep":true,"enableMDNS":true,"enableCORS":false,"APProvisionMode":"disconnected","APSecurity":"wpa2","APSSID":"ems-esp"},"ntp":{"NTPStatus":"connected","enabled":true,"server":"time.google.com","tzLabel":"Europe/Amsterdam"},"mqtt":{"MQTTStatus":"connected","MQTTPublishes":22748,"MQTTQueued":0,"MQTTPublishFails":0,"MQTTConnects":69,"enabled":true,"clientID":"esp32-412a13d8","keepAlive":60,"cleanSession":false,"entityFormat":1,"base":"ems-esp","discoveryPrefix":"homeassistant","discoveryType":0,"nestedFormat":1,"haEnabled":true,"mqttQos":0,"mqttRetain":true,"publishTimeHeartbeat":60,"publishTimeBoiler":10,"publishTimeThermostat":10,"publishTimeSolar":10,"publishTimeMixer":10,"publishTimeWater":10,"publishTimeOther":10,"publishTimeSensor":10,"publishSingle":false,"publish2command":false,"sendResponse":true},"syslog":{"enabled":false},"sensor":{"temperatureSensors":0,"temperatureSensorReads":0,"temperatureSensorFails":0},"api":{"APICalls":6,"APIFails":0},"bus":{"busStatus":"connected","busProtocol":"Buderus","busTelegramsReceived":89528,"busReads":22130,"busWrites":9,"busIncompleteTelegrams":1227,"busReadsFailed":0,"busWritesFailed":0,"busRxLineQuality":100,"busTxLineQuality":100},"settings":{"boardProfile":"CUSTOM","locale":"de","txMode":1,"emsBusID":11,"showerTimer":false,"showerMinDuration":180,"showerAlert":false,"phyType":0,"rxGPIO":4,"txGPIO":5,"dallasGPIO":14,"pbuttonGPIO":0,"ledGPIO":2,"hideLed":false,"noTokenApi":false,"readonlyMode":false,"fahrenheit":false,"dallasParasite":false,"boolFormat":1,"boolDashboard":1,"enumFormat":1,"analogEnabled":false,"telnetEnabled":false,"maxWebLogBuffer":25,"webLogBuffer":25,"modbusEnabled":false,"forceHeatingOff":false,"developerMode":false},"devices":[{"type":"boiler","name":"Logano GB1*5, Logamatic MC10","deviceID":"0x08","productID":72,"brand":"","version":"03.03","entities":64,"handlersReceived":"0x10 0x11 0x14 0x15 0x1C 0x18 0x19 0x34 0x04","handlersFetched":"0x16 0x33","handlersPending":"0xBF 0xC2 0x1A 0x35 0x2E 0x3B","handlersIgnored":"0x03 0xFD 0xFE 0x1F 0x20"},{"type":"thermostat","name":"RC3*0, Moduline 3000/1010H, CW400, Sense II, HPC410","deviceID":"0x10","productID":158,"brand":"","version":"11.05","entities":48,"handlersReceived":"0x06 0xA2 0x02BA 0x02BB 0x02BC 0x031D 0x0267","handlersFetched":"0x02A5 0x02B9 0x02AF 0x029B 0x0291 0x0292 0x0293 0x0294 0x02F5 0x02F6 0x023A 0x0240 0x0269","handlersPending":"0xA3 0x12 0x13 0x0471 0x02A6 0x02B0 0x029C 0x0472 0x02A7 0x02B1 0x029D 0x0473 0x02A8 0x02B2 0x029E 0x0474 0x02A9 0x02BD 0x02B3 0x029F 0x0475 0x02AA 0x02BE 0x02B4 0x02A0 0x0476 0x02AB 0x02BF 0x02B5 0x02A1 0x0477 0x02AC 0x02C0 0x02B6 0x02A2 0x0478 0x02CC 0x0467 0x02CE 0x0468 0x02D0 0x0469 0x02D2 0x046A 0x031B 0x031E 0xBB 0x023E","handlersIgnored":"0x025E 0x0453 0x0454 0x0455 0x0456 0x0457 0x0458 0x0459 0x045A 0xF7 0xC4 0xBF"},{"type":"controller","name":"BC10, RFM20","deviceID":"0x09","productID":68,"brand":"","version":"02.03","entities":0,"handlersIgnored":"0x04 0x15 0x34 0x16 0x33 0x29"}]}

### TO REPRODUCE

use MQTT Discovery with homeassistant /  Mosquitto broker .
The numer entitys will not have  "unit_of_meas", "stat_cla" and "dev_cla" attributes, so all data is displayed as simple numbers in the history tab.

### EXPECTED BEHAVIOUR

The entitys should have the missing attributes, so that for example all temperature settings and temperatur sensors are displayed in one graph in homeassistant history.

### SCREENSHOTS

_If applicable, add screenshots to help explain your issue._

### ADDITIONAL CONTEXT

As a workaround i made a json file with the missing attributes. with a simple bash command i can publish the messages and the entitys are displayed correctly.
See the attached json file.
here the command i used for workaround: 
`
jq -c '.[]' ha_mqtt_config.json | while read -r line; do topic=$(echo "$line" | jq -r '.topic'); payload=$(echo "$line" | jq -c '.payload'); mosquitto_pub -h 192.168.2.154 -p 1883 -u "mqtt-user-name" -P "mqtt-password" -t "$topic" -m "$payload"; done

`

**(Please remember to close the issue when it has been addressed)**
[ha_mqtt_config.json](https://github.com/user-attachments/files/17540240/ha_mqtt_config.json)

**Comment by proddy** [comment]
Fixed in 3.7.1-dev-1
