### ISSUE TITLE
Update to Development Build v3.7.1-dev.1: Undefined behavior 

### ISSUE THREAD

**Issue by NongJoWo** [emsesp/EMS-ESP32#2152]
I have just updated to the 3.7.1 dev.1 version and at first glance everything looked fine. Now I've noticed that the upload/download and System Memory window always says "loading". A Roobot isn't possible either. It says "not found". A roobot with power off didn't help either. What can I do? Many thanks!

![image](https://github.com/user-attachments/assets/b544a538-ec21-4cbf-850b-c0b7fbe3cc2d)

![image](https://github.com/user-attachments/assets/f1538c35-7b1b-421f-8e5f-7e0ee2a80a5b)

![image](https://github.com/user-attachments/assets/192727f9-3acc-4d80-8df4-600c596dd4bc)

**Comment by NongJoWo** [comment]
That was the file I have used: EMS-ESP-3_7_1-dev_1-ESP32_S3.bin

**Comment by proddy** [comment]
which version did you upgrade from?

**Comment by NongJoWo** [comment]
3.7.0-dev.17

**Comment by proddy** [comment]
ctrl-R to refresh browser cache?

**Comment by NongJoWo** [comment]
Yes, that was the solution. It can be so easy ;-)) Thank you for the quick support!

**Comment by NongJoWo** [comment]
But I am not sure if that is normal in log file

![image](https://github.com/user-attachments/assets/4ce79b05-7883-4c8f-82c6-239311c79a85)

**Comment by proddy** [comment]
some errors are normal, its due to noise on the EMS bus line. What's important is the quality - check the Rx/Tx quality in the Data Traffic page. Anything less than 100% is a concern

**Comment by NongJoWo** [comment]
Rx/Tx quality in the Data Traffic page all by 100%.
What I am struggling now with are some sensos:

Name: ems-esp Boiler Sollwert Vorlauftemperatur
sensor.boiler_setflowtemp: Not available 
(Is used in my dasboard to display target flow temperature of heating)

FYI:
sensor.boiler_setburnpow: Not available
sensor.boiler_wwsetpumppower: Not available

**Comment by NongJoWo** [comment]
Never touch a running system :-((

The Version 3.7.0-dev.17 was running without any issues on my system. Does it make sense to donwgrade? If yes where can I find it?

**Comment by NongJoWo** [comment]
All ESP MQTT devices in HA deleted an ESP rebooted. Now all entities are there without unavailables. 
But I am not sure which entity I can now use for "target flow temperature of heating"

I could only find 2 entities with "flowtemp"
- number.boiler_selflowtemp
- sensor.thermostat_hc1_targetflowtemp

Anyone an idea?

**Comment by proddy** [comment]
can you send over the System Info so we can see the system, and help you. Don't know which thermostat you have, or whether its a boiler, heatsource, mixer, heatpump etc...

**Comment by NongJoWo** [comment]
Buderus GB172-24K with RC310 thermostat installed inside the boiler.

sensor.thermostat_hc1_targetflowtemp
Seems to provide useful data.

**Comment by NongJoWo** [comment]
The name was “sensor.boiler_setflowtemp”.
I have just compared it with “sensor.thermostat_hc1_targetflowtemp” and both had the same values in the past.

**Comment by MichaelDvP** [comment]
We have removes some dublicate values, setflowtemp was the same value as selflowtemp, but received from a different telegram. (setflowtemp: command to the boiler, selflowtemp: value stored in the boiler) Same for setburnpower and some more.
And yes, thermostat targetflowtemp is the same value sent from thermostat to the boiler.

**Comment by NongJoWo** [comment]
Many thanks for confirmation. Everything looks ok now…
