### ISSUE TITLE
Bug in EMS-ESP Web GUI

### ISSUE THREAD

**Issue by Vippis2000** [emsesp/EMS-ESP32#2161]
I have upgraded to 3.7.1dev2 today and when I try to open a device in Web GUI I get this error:

![grafik](https://github.com/user-attachments/assets/bdbfd7c3-1de1-446d-9b32-88542ffcf30d)

**Comment by proddy** [comment]
which version did you upgrade from? Does CTRL+R (F5) in the browser make a difference? I haven't tested yet personally, could very well be a bug!

**Comment by Vippis2000** [comment]
Refreshing solved it, thank you!

**Comment by proddy** [comment]
np.

I added a note to https://emsesp.org/Troubleshooting/ and also created #2162
