### ISSUE TITLE
EMS-ESP s32 v2.0 (2022) bricked after Firmware Update

### ISSUE THREAD

**Issue by teabox93-git** [emsesp/EMS-ESP32#2206]
### DESCRIPTION

I have EMS-ESP s32 v2.0 (2022) and I have tried to update it via WEB UI, downloaded firmware that showed up after checking new version (it is 3_7_0 16MB). It started the update.
Since then the device does not stand up, reconnecting it to the cable is not showing blue LED.

I have tried to connect it via USB and upload firmware from PC, but it is not recognized by PC, no serial port is showing up.

**Comment by proddy** [comment]
What version did you upgrade from?

**Comment by MichaelDvP** [comment]
> but it is not recognized by PC, no serial port is showing up.

Try another usb cable and check usb/serial driver. The usb is a CH340 chip. Independend of the processor state it should show up on USB.

**Comment by teabox93-git** [comment]
Guys, the issue was the cable. On different cable I can flash the firmware. @Proddy sorry I don't remember the original version but I think it was 3.6.0.

Now I have flashed the 3.6.0, 3.6.5 and 3.7.0, on every version I have the same issue. When I connect my external temperature sensor - controller (Bosch) to the bus, the EMS-ESP goes down, led goes down and website is down like there is no power. When I connect only ESP-EMS to my Buderus all is working.

It seems that it cannot power up together with sensor connected to the bus. It was working fine before the firmware upgrade so it is not a power issue. Maybe I need to set some settings? Can you please help? On board there is S32 V 2.0

**Comment by teabox93-git** [comment]
![IMG_8222](https://github.com/user-attachments/assets/8dea8b7c-ba5d-4a30-8dda-bed9be22e88d)
![IMG_8221](https://github.com/user-attachments/assets/23cb7ce1-f2a8-467c-a029-89655d46fa5a)
![IMG_8220](https://github.com/user-attachments/assets/445309df-8015-4e87-b203-989bd1a1f316)

**Comment by MichaelDvP** [comment]
You have a S32 gateway not a E32, to set board profile to S32.

**Comment by proddy** [comment]
he got it working - it was a bad connection
