### ISSUE TITLE
Docs: Download the firmware source

### ISSUE THREAD

**Issue by sciurius** [emsesp/EMS-ESP32#221]
When I follow the instructions on documentation page https://emsesp.github.io/docs/#/Building-firmware, step 5 gives an error "Not a PlatformIO project. `platformio.ini` file has not been found".

This may sound trivial, but it would be nice if there was an additional step, between 3 and 4:

Download the firmware source from Github

    git clone  https://github.com/emsesp/EMS-ESP32
    cd EMS-ESP32

If you want to use the development version, issue

    git checkout dev

Thanks.

**Comment by proddy** [comment]
thanks! added.
