### ISSUE TITLE
HM200 0x53 missing entities, HP heating starts /HP dhw starts  (ems-esp 3.7.0)

### ISSUE THREAD

**Issue by TobiRabid** [emsesp/EMS-ESP32#2220]
The HM200 provides (like the boiler _heatstarts_ and _dhw/starts_ ) statistic values for the heatpump starts (heating/dhw).
Attached a screenshoot from mybuderus app with this values (3626 for heating starts, 184 for dhw starts)

I tried to provoke to increase the counter during the watch command via sg-ready stop ( the hp stoped,but not sure that the values just in time changed. The app shows the old values, but there is a cloud backend between...)

Atached also the watch file

It would be very nice to have this entities in one of the next versions

regards

![IMG_2621](https://github.com/user-attachments/assets/44584f4c-5213-4d9f-8535-fcd0d4c9296a)
[ems-esp watch on 0x53-hp-stop-sg-ready.txt](https://github.com/user-attachments/files/17804182/ems-esp.watch.on.0x53-hp-stop-sg-ready.txt)

atached a second very long  watch file.. i released the blocking of the hp via sgready signal, the boiler stops immediately and the hp starts after 11 minutes.... the counter for hp heating start increased +1 to 3627 in the app

[hp-start-after-blocking.txt](https://github.com/user-attachments/files/17805463/hp-start-after-blocking.txt)

**Comment by proddy** [comment]
@TobiRabid can you check the latest 3.7.1 dev release?

**Comment by TobiRabid** [comment]
The starts counter values are visible, but the discribtion is swapped

<img width="1603" alt="2024-11-22_10h02_17" src="https://github.com/user-attachments/assets/3f91c786-c8b5-44e1-b910-c2a457be2fbf">

**Comment by TobiRabid** [comment]
thx
