### ISSUE TITLE
Shower time

### ISSUE THREAD

**Issue by sciurius** [emsesp/EMS-ESP32#223]
**Question**
The EMS-ESP32 gateway can report shower time. How is this determined?

I have a shower, a bath tub and a sink faucet. How can the controller know it was the shower?

**Comment by proddy** [comment]
it doesn't. It just times how long the hot water has been running. I got the idea from one of Nefit Easy mobile application's which did the same with their smart thermostat. But could never figure out how they tell between bath, shower, hot tap etc...

**Comment by glitter-ball** [comment]
The secret spy camera in the front of the boiler, watching traffic to/from your bathroom! *8)
