### ISSUE TITLE
Settings security tabs broken in 3.7.2-dev0

### ISSUE THREAD

**Issue by MichaelDvP** [emsesp/EMS-ESP32#2264]
Navigating to settings security is broken. Selecting a tab seems to redirect endless to security/settings/settings/settings/.....
Used original bin from emsesp, esp32S3

![grafik](https://github.com/user-attachments/assets/5bae5c6c-e61d-45f7-9034-d135bd0a6d19)

Same for network settings

**Comment by proddy** [comment]
fixed in 3.7.2-dev.1. I'll back port it to 3.7.1/main/stable
