### ISSUE TITLE
Typo in State "Kesselpumpen Minmalleistung"

### ISSUE THREAD

**Issue by unstressable** [emsesp/EMS-ESP32#2269]
State in german is wrong written: "Kesselpumpen Minmalleistung"

Correct is: "Kesselpumpen Minimalleistung"

**Comment by MichaelDvP** [comment]
Fixed 3 month ago in https://github.com/emsesp/EMS-ESP32/commit/9daae873ea1077a5a01f079e421ff657ecc06c9f
