### ISSUE TITLE
modbus write permission

### ISSUE THREAD

**Issue by GLT-IN** [emsesp/EMS-ESP32#2276]
### DESCRIPTION

Hi,
writing of a single entity per request doesn´t work for Buderus Topline GB162, RC35 and MM10

Reading works.
Do I need to catch up a write permission first?
How does it work?

Best regards,
Markus

### REQUESTED INFORMATION

_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Searched the issue in [issues](https://github.com/emsesp/EMS-ESP32/issues)
- [x] Searched the issue in [discussions](https://github.com/emsesp/EMS-ESP32/discussions)
- [x] Searched the issue in the [docs](https://docs.emsesp.org/Troubleshooting/)
- [x] Searched the issue in the [chat](https://discord.gg/3J3GgnzpyT)
- [x] Provide the System information in the area below, taken from `http://<IP>/api/system`

```json
  platform ESP32-16MB+
  version 3.7.2-dev.2


```

### TO REPRODUCE

request
FF 00 00 00 00 06 06 06 03 E8 00 0A

answer with exception
FF 00 00 00 00 03 06 86 03

### EXPECTED BEHAVIOUR

hc1 selected room temperature will be 20°

**Comment by proddy** [comment]
@mheyse , any idea?

**Comment by mheyse** [comment]
There should be an error in the log, could you please post it?

**Comment by GLT-IN** [comment]
![Screenshot 2024-12-04 124005](https://github.com/user-attachments/assets/78fedaf0-c1cf-40b7-8e1a-f8c28ebbc2ce)

**Comment by MichaelDvP** [comment]
Oh, seems modbus is hardcoded to use mqtt-base `ems-esp`, we should better use `path = std::string("api/") + ` here:
https://github.com/emsesp/EMS-ESP32/blob/473cf7c8af7a3502bb187ad60d7d37e3177fe9b8/src/modbus.cpp#L417-L419

@GLT-IN As workaround set back in mqtt settings the base to `ems-esp`

**Comment by MichaelDvP** [comment]
@GLT-IN Please try with https://github.com/MichaelDvP/EMS-ESP32/releases/tag/latest
Check and adapt in application setting the modbus timeout, this is changed to seconds (instead of milliseconds).
