### ISSUE TITLE
int24/uint24 data format

### ISSUE THREAD

**Issue by GLT-IN** [emsesp/EMS-ESP32#2279]
### DESCRIPTION

Hi,
standard Modbus does not natively support int24 and uint24 data format.
Is it possible to change the datatype to next suitable datatype like int32/uint32?

In combination with other modbus participants there are some interpretation errors regarding non uniform datatypes

Best regards,
Markus

### REQUESTED INFORMATION

_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Searched the issue in [issues](https://github.com/emsesp/EMS-ESP32/issues)
- [x] Searched the issue in [discussions](https://github.com/emsesp/EMS-ESP32/discussions)
- [x] Searched the issue in the [docs](https://docs.emsesp.org/Troubleshooting/)
- [x] Searched the issue in the [chat](https://discord.gg/3J3GgnzpyT)
- [x] Provide the System information in the area below, taken from `http://<IP>/api/system`

```json
  Paste System information here....


```

**Comment by MichaelDvP** [comment]
The values are stored in 32 bit, only reading the bus is 3 bytes, so value range is limited to 24 bit, the upper 8 bit are always zero.
