### ISSUE TITLE
Missing Entity "Absenkschwelle" for switchPrograms with mode "Absolute"

### ISSUE THREAD

**Issue by tp1de** [emsesp/EMS-ESP32#2288]
@Marcwa19197 mentioned a missing entity within #1594

Within switchprogmode 2 modes can be selected: "Levels" and "Absolute".

Using exact temperatures ("Absolute") you need to also define the "Absenkschwelle" under which temperature nightmode / reduced mode will be activated. This value is also missing right now in EMS-ESP, 

![394187448-8e976bae-d4eb-4c8e-87cb-355fd3e9a5f2](https://github.com/user-attachments/assets/1c9da05c-2557-479d-ab08-d184aeda35d6)

**Comment by MichaelDvP** [comment]
We need device, telegram, offset, type, name to implement.
- help-page: support-info download button, attach it here
- status-logger: log all for more than a minute
- change the `Absenkschwelle` while logging
- attach the log here.

**Comment by Marcwa19197** [comment]
1.)
[emsesp_system_info.json](https://github.com/user-attachments/files/18115067/emsesp_system_info.json)

2.)
[log.txt](https://github.com/user-attachments/files/18115091/log.txt)

i changed Absenkschwelle from 20 to 19.5 and back to 20.

**Comment by MichaelDvP** [comment]
Looks good, try if this works:
![grafik](https://github.com/user-attachments/assets/e67d6d93-0c4f-4c10-9d38-b26484f08fb6)

If this is ok we'll add it to thermostat.

**Comment by Marcwa19197** [comment]
Works! Thank you very much!

**Comment by Marcwa19197** [comment]
min. Value is 12
max. Value is 22

**Comment by proddy** [comment]
Think we just need to add the mix/max values and this issue can be closed.
