### ISSUE TITLE
int8 data type (Modbus)

### ISSUE THREAD

**Issue by GLT-IN** [emsesp/EMS-ESP32#2294]
### DESCRIPTION

Hi,
int8 values are difficult to interpret by second devices, because they are transmitted as int16.
For example minexttemp (register offset: 51) with value "-16" is transmitted as 00 F0, but interpreted as "240".
Is it possible to send int8 as full int16?

### REQUESTED INFORMATION

_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Searched the issue in [issues](https://github.com/emsesp/EMS-ESP32/issues)
- [x] Searched the issue in [discussions](https://github.com/emsesp/EMS-ESP32/discussions)
- [x] Searched the issue in the [docs](https://docs.emsesp.org/Troubleshooting/)
- [x] Searched the issue in the [chat](https://discord.gg/3J3GgnzpyT)
- [x] Provide the System information in the area below, taken from `http://<IP>/api/system`

```json
  Paste System information here....


```

### EXPECTED BEHAVIOUR

_A clear and concise description of what you expected to happen._

### SCREENSHOTS

![image](https://github.com/user-attachments/assets/3da1f769-eb80-4ecc-b8da-9b24946c4d64)

**Comment by MichaelDvP** [comment]
I think it's only one small change, please try https://github.com/MichaelDvP/EMS-ESP32/releases/tag/latest
and check if all is solved.

**Comment by GLT-IN** [comment]
Hi,
int8 values are represented correctly now, but the whole system does not run stable.
Devices and entities getting lost and found randomly.

**Comment by GLT-IN** [comment]
every minute the device restarts with v3.7.2-dev.5

**Comment by MichaelDvP** [comment]
Do the restarts happen only in my version, or also in official v3.7.2-dev.5? 
What happen every minute? Commands/reads sent to emsesp?

**Comment by GLT-IN** [comment]
it happens in both versions
![image](https://github.com/user-attachments/assets/811fb2ff-a355-4843-9c7e-5633df7a700c)

**Comment by GLT-IN** [comment]
i changed the register addresses and there are no device restarts any more

**Comment by GLT-IN** [comment]
Thank you!

**Comment by MichaelDvP** [comment]
> i changed the register addresses and there are no device restarts any more

Wrong address or length should only give an errormessage, but no crash. 
I'v found a candidate, but not sure if it is fixed now.
Please report if you see this crash again.
