### ISSUE TITLE
Unexpected Application Error! - date value is not finite in DateTimeFormat format()

### ISSUE THREAD

**Issue by HansRemmerswaal** [emsesp/EMS-ESP32#2309]
When clicking on **Status** I'm getting the following error;

![F4B1AC8E-32FA-4FED-9A65-B5ABD5741B4E](https://github.com/user-attachments/assets/f9b37dca-6f54-4458-becf-ccd4dc909981)

The same issue happens on my iPhone, iPad, Mac and Windows machine. Same issue when using different browsers, Safari and Chrome. I have restarted the EMS-ESP but the issue is still there

I'm using 3.7.2-dev.6, see attached emsesp_system_info for more details

[emsesp_system_info.json](https://github.com/user-attachments/files/18267896/emsesp_system_info.json)

**Comment by proddy** [comment]
it could be an error left over from dev.5. Have you tried refreshing the cache. In Chrome it's CTR + R then CTRL + F5. Or just removing the cache with `chrome://settings/clearBrowserData`

**Comment by HansRemmerswaal** [comment]
What I did this morning;

- I cleared the cache and the issue was still there
- I took the power off from the EMS-ESP and after about 30 sec I put the power on again, the issue was still there
- I downgraded to version 3.7.1 and the issue was gone
- I upgraded to version 3.7.2 dev 6 and the issue is still gone

So somehow downgrading and upgrading has solved the problem...

**Comment by HansRemmerswaal** [comment]
Closing the issue as it's resolved for me, but the root cause is unknown.

**Comment by HansRemmerswaal** [comment]
The only data time in the Status tab is the NTP. So I guess that somehow there was an invalid date...?

**Comment by MichaelDvP** [comment]
dev6 was published with the bug, a few hours later this was reported in #2304 and fixed without counting up the dev number, so actual dev6 is the fixed version.
