### ISSUE TITLE
Make climate entity configurable or disable climate entity in WebUI (Home Assistant)

### ISSUE THREAD

**Issue by tschamm** [emsesp/EMS-ESP32#237]
**Is your feature request related to a problem? Please describe.**
I have two heating circuits in my boiler. While one is reporting the current room temperature, the other does not have a room temp associated. 

**Describe the solution you'd like**
A feature to configure the climate entities in the WebUI would allow to either disable a climate entity related to a heating circuit or to configure the current temperature to a value reported by EMS (e.g. boiler current flow temp). 

**Describe alternatives you've considered**
Disabling the climate entity in home assistant.

**Additional context**
![image](https://user-images.githubusercontent.com/31720/144720685-c36b1262-ed0b-4f2c-8ec1-827c5ceb0f3f.png)
Attached a screenshot with two heat circuits, one which does not has a current room temp because it is connect to a buffer water tank, the other one is a mixed heat circuit.

**Comment by proddy** [comment]
@tschamm if you use MQTTExplorer or something similar, how many entries do you have under `homeassistant/climate/ems-esp`? Is it showing you two config entries for each of the heating circuits?

**Comment by tschamm** [comment]
Two config entries are listed, one for each hc.

**Comment by proddy** [comment]
ok thanks. Just thinking of what the best way forward is here.

**Comment by proddy** [comment]
@tschamm if you want to try it, build the latest from the v3.4 branch or grab the binary from Discord

**Comment by tschamm** [comment]
Thanks, works fine for me!
