### ISSUE TITLE
command interface shows info messages for call commands.

### ISSUE THREAD

**Issue by tp1de** [emsesp/EMS-ESP32#253]
Telnet command interface shows all call commands. They have have to be disabled by increasing log level - e.g. log warning,

Since I have the ioBroker adapter running which issues a lot of API commands, my console is full of messages:

![image](https://user-images.githubusercontent.com/36480251/146948931-68f112a3-a775-45b7-83c6-c3d600452dd8.png)

I believe that log-level of this messages should be changed so that by login in console they are not shown.

**Comment by proddy** [comment]
as I mentioned, is changed in 3.4. I'll push it to dev soon along with a hundred other new bugs ;-)
