### ISSUE TITLE
Upgrade from 3.2.1 to 3.3.0 or higher not possible

### ISSUE THREAD

**Issue by Chaot1** [emsesp/EMS-ESP32#267]
When i try to upgrade the firmware i get a Error 500 "invalid Status Code"

![esp1](https://user-images.githubusercontent.com/37418118/147385368-5c49086c-d115-4d0b-b43a-693ef6b7d84a.jpg)

![esp2](https://user-images.githubusercontent.com/37418118/147385370-69970ffd-3fe0-430a-94fb-d177200e2abd.jpg)

**Comment by proddy** [comment]
Try with ota or usb
