### ISSUE TITLE
Enhancement - Boiler GC7000F

### ISSUE THREAD

**Issue by wt19** [emsesp/EMS-ESP32#270]
Dears, I am using EMS-ESP with a CW400 thermostat and a GC7000F Boiler from Bosch. CW400 works really great!
GC7000F Boiler is not (yet) supported. I would like use this enhancement issue to share my console output that you already have some data where you could look in for future enhancements.

Just let me know if you you need additional data/ support from my end.

show:
`Unknown: Junkers unknown (DeviceID:0x08 ProductID:132, Version:01.44)`

watch on 0x08:
[log.txt with more informations than shared below](https://github.com/emsesp/EMS-ESP32/files/7785469/log.txt)
`000+00:18:21.352 N 0: [emsesp] Unknown(0x08) -> All(0x00), ?(0xE4), data: 10 20 2D 48 00 C8 2B 01 B7 64 25 03 00 00 00 00 00 01 95 00 95 10 00 01 B7 80 00
000+00:18:21.507 N 1: [emsesp] Unknown(0x08) -> All(0x00), ?(0xE4), data: 01 B1 80 00 7F FF 80 00 (offset 27)
000+00:18:21.695 N 2: [emsesp] Unknown(0x08) -> All(0x00), ?(0xE3), data: 01 00 01 00 00 00 00 00 00 00 00 01 B7 25 64 50 00 00 00 00
000+00:18:21.878 N 3: [emsesp] Unknown(0x08) -> All(0x00), ?(0xE9), data: 37 02 47 02 47 00 00 00 00 46 3C 00 00 01 00 89 53 00 04 60 00 00 00 37 00 37
000+00:18:22.036 N 4: [emsesp] Unknown(0x08) -> All(0x00), ?(0x8E4), data: 00 00 00 2D 48 00 00 2B 64 00
000+00:18:31.302 N 5: [emsesp] Unknown(0x08) -> All(0x00), ?(0xE4), data: 10 20 2D 48 00 C8 2B 01 B7 64 25 03 00 00 00 00 00 01 95 00 8A 10 00 01 B7 80 00
000+00:18:31.459 N 6: [emsesp] Unknown(0x08) -> All(0x00), ?(0xE4), data: 01 B1 80 00 7F FF 80 00 (offset 27)
000+00:18:31.647 N 7: [emsesp] Unknown(0x08) -> All(0x00), ?(0xE3), data: 01 00 01 00 00 00 00 00 00 00 00 01 B7 25 64 50 00 00 00 00
000+00:18:31.878 N 8: [emsesp] Unknown(0x08) -> All(0x00), ?(0xE9), data: 37 02 47 02 47 00 00 00 00 46 3C 00 00 01 00 89 53 00 04 60 00 00 00 37 00 37
000+00:18:32.037 N 9: [emsesp] Unknown(0x08) -> All(0x00), ?(0x8E4), data: 00 00 00 2D 48 00 00 2B 64 00`

**Comment by proddy** [comment]
thanks for sharing. I'll add it the latest build and see where that takes us...

**Comment by proddy** [comment]
if you DM on Discord I'll send over a new firmware to try out

**Comment by wt19** [comment]
Today I have received the first alpha version 3.4.0a3 which is supporting my junkers/bosch boiler GC7000F.
I did some testing and so far it looks very promising. I will come back to this issue tomorrow and update the status if I couldn't find any problem.

Thanks to @proddy for that outstanding support and development. Enjoy the next coffees ;-)

**Comment by wt19** [comment]
As I found no issues with the integration I will close this Issue.
