### ISSUE TITLE
Buderus RC25 - "hc1 mode type" incorrect value

### ISSUE THREAD

**Issue by emcekk** [emsesp/EMS-ESP32#273]
**Bug description**
First of all, I don't think that's really important, but maybe can be addressed when fixing other issues

When the RC25 is in Auto mode a "hc1 mode type" parameter appears, but it's value is always set to "day", regardless of the current state. See pictures attached below.

**Steps to reproduce**
*Steps to reproduce the behavior.*

**Expected behavior**
When in auto+day mode a value 'day' should be set to "hc1 mode type"

When in auto+night mode, a value 'night' should be set to "hc1 mode type"

**Screenshots**
![Screenshot_20211229_004826_com.android.chrome_edit_185650429532087.jpg](https://user-images.githubusercontent.com/93294817/147616463-90e04998-51a4-4245-8320-97d7dbf24dd4.jpg)

![IMG_20211229_010727.jpg](https://user-images.githubusercontent.com/93294817/147616467-fdb41e97-a2a7-4c9a-b94f-7e73dbb51afc.jpg)

**Device information**
![Screenshot_20211229_005724_com.android.chrome.jpg](https://user-images.githubusercontent.com/93294817/147616487-f738a533-f09e-47b0-b0a1-321e805cb00e.jpg)

**Additional context**
*Add any other context about the problem here.*

**Comment by MichaelDvP** [comment]
Please check the in terminal the telegram 0xAE in these modes. (`read 17 AE`)
It was a long discussion about the[ RC20/RC25 settings here](https://github.com/emsesp/EMS-ESP/issues/361#issuecomment-609473501).

**Comment by proddy** [comment]
@emcekk can you look into this so we know whether to fix in the upcoming version

**Comment by emcekk** [comment]
Sure, will give it a deeper look in the evening. I'm currently using 3.4a9 and this field is just blank ![Screenshot_20220108_113641_com.android.chrome.jpg](https://user-images.githubusercontent.com/93294817/148641078-5b3309b3-f259-44ce-8c88-d8323781fa7a.jpg)

**Comment by proddy** [comment]
ok, we need to see the data from those telegrams when in night and day so we can figure out how to translate it. or you send me over an RC25 ;)

**Comment by MichaelDvP** [comment]
The empty field is due to a wrong modytype reference [here](https://github.com/emsesp/EMS-ESP32/blob/a59a7fe44f2d2a4ccf90bbb4f0fe9cc7068c0fcd/src/devices/thermostat.cpp#L3243) and [here](https://github.com/emsesp/EMS-ESP32/blob/a59a7fe44f2d2a4ccf90bbb4f0fe9cc7068c0fcd/src/devices/thermostat.cpp#L3257), it should be `enum_modetype3`.

**Comment by proddy** [comment]
thanks Michael. I've added it to 3.4a11

**Comment by emcekk** [comment]
After flashing 3.4a11 it seems that the mode is recognized correctly

![Screenshot_20220109_233611_com.android.chrome.jpg](https://user-images.githubusercontent.com/93294817/148703962-6d98e122-cf2c-4177-9d5a-fcbd696f4b31.jpg)

![Screenshot_20220109_233657_com.android.chrome.jpg](https://user-images.githubusercontent.com/93294817/148703965-81cd895d-59cd-4211-afe4-c807b69c651d.jpg)


And for auto mode: 
![Screenshot_20220109_233710_com.android.chrome.jpg](https://user-images.githubusercontent.com/93294817/148703971-416dd631-28cd-49c4-a579-6e0579b7d1e6.jpg)

"night" is correct at the moment the screenshot was taken

Sorry for not providing those telegrams, looks like the newborn is eating up most of my time.

Should I still sniff them for you?

**Comment by proddy** [comment]
if all works as expected no need to grab those telegrams. You can just close this issue.
