### ISSUE TITLE
WebUI dashboard on mobile devices looks ugly

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#277]
On smartphones the new Dashboard table doesn't render nicely when in portrait mode. Either introduce a scroll bar or hide columns as we did in earlier versions.

<img src="https://user-images.githubusercontent.com/1230712/147876226-6600fb70-aa5b-406a-b897-ef8f302d97be.jpg" width="450">

**Comment by MichaelDvP** [comment]
If you allow line breaks in the description it looks better: `GBx72, Trendline, Cerapur, Greenstar Si/27i` instead of `GBx72/Trendline/Cerapur/Greenstar Si/27i`

**Comment by proddy** [comment]
I had a test where it would limit the string to 10 chars and postfix with ellipsis (...) but it still didn't fit. There are just too many columns?

**Comment by bbqkees** [comment]
My CSS is quite rusty but you can use CSS media queries to hide columns responsively if the page width gets too low, like on mobile in portrait mode.
That way you can hide the description column on mobile so the rest of the table will still fit.

**Comment by proddy** [comment]
fixed in a13
