### ISSUE TITLE
Make prefix for MQTT Discovery configurable in v3.4

### ISSUE THREAD

**Issue by bbqkees** [emsesp/EMS-ESP32#290]
HA's MQTT Discovery is quickly becoming the defacto standard for MQTT integrations.
This means other home automation systems like Domoticz are starting to implement it now.

Currently the discovery topic prefix is fixed to 'homeassistant', however someone with Domoticz or f.i. IOBroker does not run HA.
Therefore it would be nice if the prefix can be configured from within the settings.

Also the tickbox 'Enable Home Assistant integration' should be renamed (back) to 'Enable MQTT Discovery', as it is not only HA who uses the Discovery protocol.
![image](https://user-images.githubusercontent.com/10775682/149175890-098de66d-54e5-4034-8112-df5ea31db199.png)

**Comment by proddy** [comment]
ok

**Comment by proddy** [comment]
I'll default the 'discovery' topic prefix to `homeassistant` for backwards compatibility. Can domoticz live with the template conditionally code for the thermostat modes or should also be an option in the front-end?

**Comment by proddy** [comment]
added this like:

![image](https://user-images.githubusercontent.com/1230712/149676099-f03faa56-ec13-4eeb-9549-00bf44bd3ffd.png)

**Comment by bbqkees** [comment]
Yes that is fine.
Thanks.
