### ISSUE TITLE
No pre-build binaries for ESP32 and when compiling from source dev version is  v3.0.0b1

### ISSUE THREAD

**Issue by tp1de** [emsesp/EMS-ESP32#3]
I am a bit confused. Since I want to rewrite my node-red flows reading mqtt-messages I was looking for the actual dev version.
I could not find a pre-build binary for the esp32 like before. Any reason for this?

Therefore I dowloaded the respective source and compiled by myself.
I ended with version v3.0.0b1. Is this ok?

This binary seems to work -  I just lost my WLAN-connection. WLAN has to be setup new. All other settings where kept.
Just the mqtt messages changed in structure and data-field names. This is not very convienient. (e.g. mixer valveStatus into status).

**Comment by proddy** [comment]
fixed with move to the github org and new build & release actions
