### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by Gert05** [emsesp/EMS-ESP32#331]
**Bug description**
Something's not right in 3.4.0.b1: I'm getting "Problem fetching: unexpected token < in JSON at position 0" when clicking Dashboard or Settings in the main menu.

**Steps to reproduce**
Install 3.4.0.b1; click on Dashboard

**Screenshots**
![image](https://user-images.githubusercontent.com/12745187/151239665-7aaa9daf-ad05-4a56-93d8-b4337fa16eca.png)

**Device information**

**Additional context**

**Comment by MichaelDvP** [comment]
Try reload page, or shutdown browser and restart..

**Comment by proddy** [comment]
indeed
