### ISSUE TITLE
Refresh dashboard values without reloading the page itself.

### ISSUE THREAD

**Issue by mvjt** [emsesp/EMS-ESP32#340]
**Is your feature request related to a problem? Please describe.**
When I'm analyzing all the values available at the dashboard, after some time, page refreshes and puts me at the top of the page again. This is slightly annoying as I have to scroll down trying to find where I was. Definately low prio but still annoying :-)

**Describe the solution you'd like**
Refresh values in the background.

**Comment by MichaelDvP** [comment]
The devices list and entities are coupled to page load, but these are changing only in the first 2 minutes while scanning the bus. 
This approach is:
- if no device opened: refresh page
- if device/sensor is opend: refresh only this device
- refesh all on toggle
- refresh all on device change
- refresh all on refresh button

Please check: [EMS-ESP-3_4_0b2-ESP32.zip](https://github.com/emsesp/EMS-ESP32/files/7969683/EMS-ESP-3_4_0b2-ESP32.zip)

**Comment by mvjt** [comment]
Sounds good thank you

**Comment by proddy** [comment]
thanks michael
