### ISSUE TITLE
re previous bug

### ISSUE THREAD

**Issue by florin-laurentiu** [emsesp/EMS-ESP32#350]
hello,
just install last developing firmware; remain all problems, except that HC 1 thermostat can be controlled by HA.
please, see attachements:
![FIRMWARE report](https://user-images.githubusercontent.com/41485254/152643217-0b3a2b7a-cc45-42ca-a5f5-41bccaf6ca2d.jpg)
![unknown device](https://user-images.githubusercontent.com/41485254/152643228-dceadc61-7633-41d9-9273-6abbc97ee0fb.jpg)
![Dallas sensors on HA](https://user-images.githubusercontent.com/41485254/152643233-47c88afa-62ae-4265-bdf3-7508de832f6e.jpg)
![Dallas sensors on EMS ESP](https://user-images.githubusercontent.com/41485254/152643234-5871a29d-2377-49ed-aeac-98b6f0983509.jpg)

**Comment by proddy** [comment]
what is the bug exactly?

**Comment by florin-laurentiu** [comment]
see in attached pictures:
1.- some "unknown datafield" that appear 4 times in SOLAR in EMS as also on
HA.
2.- after new firmware , even i redefine DALLAS sensors - put again names -
, they appears in HA but no indication/values; all times VALUES for them is
ZERO.

**Comment by proddy** [comment]
1 - is by design. if you don't like it open a new enhancement request and Michael will remove it
2 - create a new GH issue and describe step by step how to reproduce this, because it works for everyone else
