### ISSUE TITLE
dhw charge duration not in device list

### ISSUE THREAD

**Issue by Ivannefit** [emsesp/EMS-ESP32#351]
In de webinterface i have the option to change "dhw charge duration" under device thermostat.

The device "dhw charge duration"is not in the device list in domoticz
 I'm using domoticz 2022.1

[emsesp_info.txt](https://github.com/emsesp/EMS-ESP32/files/8008553/emsesp_info.txt)

**Comment by proddy** [comment]
This project has nothing to do with domoticz. I'm surprised people still use that software. Talk the creators of the plugin.
