### ISSUE TITLE
can't upgrade to b4/b5 version

### ISSUE THREAD

**Issue by rickroetenberg** [emsesp/EMS-ESP32#358]
can't update to b4/b5 version, after reboot back to b2 version.

{
  "System": {
    "version": "3.4.0b2",
    "uptime": "000+00:02:47.024",
    "uptime (seconds)": 167,
    "freemem": 155,
    "reset reason": "Software reset CPU / Software reset CPU",
    "temperature sensors": 6
  },
  "Network": {
    "connection": "WiFi",
    "hostname": "ems-esp",
    "SSID": "",
    "BSSID": "",
    "RSSI": -51,
    "MAC": "",
    "IPv4 address": "",
    "IPv4 gateway": "",
    "IPv4 nameserver": ""
  },
  "Status": {
    "bus status": "connected",
    "bus protocol": "Buderus",
    "bus telegrams received (rx)": 643,
    "bus reads (tx)": 106,
    "bus writes (tx)": 0,
    "bus incomplete telegrams": 0,
    "bus reads failed": 0,
    "bus writes failed": 0,
    "bus rx line quality": 100,
    "bus tx line quality": 100,
    "MQTT status": "connected",
    "MQTT publishes": 425,
    "MQTT publish fails": 0,
    "temperature sensors": 6,
    "temperature sensor reads": 198,
    "temperature sensor fails": 0,
    "analog sensors": 0,
    "API calls": 1,
    "API fails": 1
  },
  "Devices": [
    {
      "type": "Boiler",
      "name": "Enviline/Compress 6000AW/Hybrid 7000iAW/SupraEco/Geo 5xx (DeviceID:0x08, ProductID:172, Version:01.16)",
      "entities": 101,
      "handlers received": "0xC2 0xD1 0xE3 0xE4 0xE5 0xE9 0x0494 0x0495 0x048F",
      "handlers fetched": "0x14 0xE6 0xEA 0x048D 0x048A",
      "handlers pending": "0x10 0x11 0x15 0x1C 0x18 0x19 0x1A 0x35 0x16 0x33 0x34 0x26 0x2A"
    },
    {
      "type": "Thermostat",
      "name": "RC300/RC310/Moduline 3000/1010H/CW400/Sense II (DeviceID:0x10, ProductID:158, Version:13.07)",
      "entities": 36,
      "handlers received": "0x06 0x02A5 0x02BA 0x02BB 0x02BC 0x02BD 0x02BE 0x02BF 0x02C0 0x031D 0x0267",
      "handlers fetched": "0x02B9 0x02AF 0x029B 0x0471 0x0472 0x0473 0x0474 0x0475 0x0476 0x0477 0x0478 0x02F5 0x023A 0x0240",
      "handlers pending": "0xA3 0xA2 0x12 0x02A6 0x02B0 0x029C 0x02A7 0x02B1 0x029D 0x02A8 0x02B2 0x029E 0x02A9 0x02B3 0x029F 0x02AA 0x02B4 0x02A0 0x02AB 0x02B5 0x02A1 0x02AC 0x02B6 0x02A2 0x031B 0x031E"
    },
    {
      "type": "Heatpump",
      "name": "HP Module (DeviceID:0x38, ProductID:200, Version:40.04)",
      "entities": 2,
      "handlers fetched": "0x042B 0x047B"
    },
    {
      "type": "Gateway",
      "name": "KM200/MB LAN 2 (DeviceID:0x48, ProductID:189, Version:04.08)",
      "entities": 0
    }
  ]
}

**Comment by proddy** [comment]
You on OSX? If so fixed in b4 and use a different browser or windows/Linux
