### ISSUE TITLE
Excluding thermostat entities should also remove the climate discovery topic

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#368]
As reported by eltoro on Discord, the MQTT Discovery climate component needs the selected temperature, room temperature and mode to render correctly. If any of these entities are disabled/excluded in EMS-ESP via the WebUI customization page, HA will report warnings constantly.

to reproduce: use the Web Customization and exclude `hc1/seltemp` or `hc1/currtemp` and you'll see warnings in HA like
```
Logger: homeassistant.components.mqtt.climate
Source: components/mqtt/climate.py:470
Integration: MQTT ([documentation](https://www.home-assistant.io/integrations/mqtt), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+mqtt%22))
First occurred: 15:26:36 (12 occurrences)
Last logged: 15:28:26

Could not parse temperature from
```

The fix is to remove the MQTT /climate/config topic for a heating circuit if the required entities are not active (i.e have no value) or marked as excluded.

**Comment by MichaelDvP** [comment]
I'm testing to move the HA climate from thermostat to mqtt. Depending on roomTemp active the climate is created with or without currtemp and disable roomtemp in customizations also disables climate. 
It's a suggestion,i'll make a PR, check first if you find it usefull.

**Comment by proddy** [comment]
thanks, it would be easier when moving to the mqtt class as it exposes the DeviceValue class (dv) and you can check the flags like ACTIVE and VISIBLE. I'm thinking of extending the flags to support that other enhancement so you can choose per device entitity whether to exclude it from API, MQTT & Web/Console

**Comment by proddy** [comment]
@MichaelDvP implemented this, I've tested and it works flawlessly., Nice work Michael! I think we can close this, bump to the version to b8
