### ISSUE TITLE
v3.0.1b6 -wlan not working stable

### ISSUE THREAD

**Issue by tp1de** [emsesp/EMS-ESP32#39]
I justed tested v3.0.1b6 but wlan is not connecting stable. 
ESP32 is connecting for a couple of seconds to router/accesspoint then loosing connection and so on.
I loaded new fw by webui and then tested to flash new by usb. Same result.

I went back to v3.0.1b5 which works stable.

**Comment by proddy** [comment]
ok thanks for reporting. I'll look into it

**Comment by MichaelDvP** [comment]
@proddy seems to be the linkup() in mqttsettingsservice. (like in syslog, but no bootloop, only reconnect).

**Comment by proddy** [comment]
Ah. So maybe start mqtt after network.

**Comment by proddy** [comment]
I've reproduced it - working on a fix

**Comment by proddy** [comment]
think its fixed now.

**Comment by tp1de** [comment]
@proddy Yes I can confirm it's working again.
