### ISSUE TITLE
Unknown boiler and thermostat ID

### ISSUE THREAD

**Issue by bbqkees** [emsesp/EMS-ESP32#393]
I have a customer with the following boiler and thermostat that is not yet recognized:

Worcester Logamax Plus GB122 (Product advertised in manual as  Greenstar 2000 GW2300iW C),
the Thermostat is Worcester Comfort+ 2 RF

Device-Id 0x18 Product id 246 version: 12.04
Device-id 0x50 Product id 238 version 10.05
[log(1).txt](https://github.com/emsesp/EMS-ESP32/files/8231345/log.1.txt)

**Comment by MichaelDvP** [comment]
The log says the boiler is recognized, The thermostat looks like nearly the same as in #138, also a RF-device with a RF-Base at Device-Id 0x50 (But devcie-ids 216/236) . This is not writable over the bus, sorry. (see #138)
I'll add it as compatible (read-only) to the database.

**Comment by bbqkees** [comment]
Ah yes I think I misunderstood the customer. The boiler was detected, but it did not get the name that was expected.
