### ISSUE TITLE
run web interface standalone with a mock API server

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#41]
When developing and testing the web interface, it's handy not to bother with reflashing an ESP32 each time. The idea is to mimic the ESP using a mock/stub server that responds to HTTP POST and GET requests. 

Currently a first draft at this is in the `ft_mockapi` branch. To run it do
```sh
% cd interface
% npm run dev
```

The hardcoded data is limited at the moment and can be easily extended by changing the file `/mock-api/server.js`

**Comment by bbqkees** [comment]
I tried it and it looks great.

One thing: I got an error during the build; had to install the express module, and then it worked fine.

To install Express:
`npm install express`

**Comment by proddy** [comment]
fixed that and updated the doc. https://github.com/emsesp/EMS-ESP32/blob/ft_mockapi/mock-api/README.md

**Comment by proddy** [comment]
merged into dev
