### ISSUE TITLE
3.4b11 problems

### ISSUE THREAD

**Issue by harvey637** [emsesp/EMS-ESP32#444]
Hi,
me again :-)

working parts look nice, e.g. the marking of "no api" in the dashboard enties, saving customisation of thermostat

NOT WORKING:
saving ANY customisation for "boiler" gives error 413.
saving in "thermostat" and "heatpump" give no error and work. even saving NOTHING changed in "boiler" returns 413. 

infos: not using MQTT, old customisation from 3.4b10 (some later prerelease) not recognised

this is the boiler:
```
 "Devices": [
    {
      "type": "Boiler",
      "name": "Enviline/Compress 6000AW/Hybrid 7000iAW/SupraEco/Geo 5xx",
      "device id": "0x08",
      "product id": 172,
      "version": "01.16",
      "entities": 100,
      "handlers received": "0xBF 0xC2 0xD1 0xE3 0xE4 0xE5 0xE9 0x0494 0x0495 0x048F",
      "handlers fetched": "0x14 0xE6 0xEA 0x048D 0x048A",
      "handlers pending": "0x10 0x11 0x15 0x1C 0x18 0x19 0x1A 0x35 0x16 0x33 0x34 0x26 0x2A"
    },

```

cu
Harvey

**Comment by proddy** [comment]
ok, its probably due to a recent change I made where I send all the entities back to the server, and you have 100 of them. I'll need to redesign a few things

**Comment by harvey637** [comment]
Hi,
thank you for looking into this!

You are right, I have 100 entites only for boiler (around 60 of them are for warmwater, which I dont use and want to hide).
cu
Harvey

**Comment by MichaelDvP** [comment]
This is again a to small buffer. But proddys last change was only to send always all entities, before it has worked with a few exclusions, but will give the same error if you exclude all. Proddy metioned that he plans to pack the buffer, which is some work to do. As an intermediate solution you can check with a larger buffer. I've made [a test](https://github.com/MichaelDvP/EMS-ESP32/releases) with extra debug message to check. If you use this and set a log-debug before sending the exclusions you will see a message like `[emsesp] Masked entities json size: 1307`. (This size is for my boiler with 67 entities). Yours will be more than 2048, the old limit for http:413.

**Comment by harvey637** [comment]
Hi Michael,
tested your special version - WORKING!

This is the log entry: ` [emsesp] Masked entities json size: 2153`

In the first run I removed (hided from api and dashboard)  around 57 entities, making life for iobroker/ems-esp easier,

cu
Harvey

Hope this helps.

**Comment by MichaelDvP** [comment]
@proddy: I've counted the worst case possible entities, to calculated buffer/packed size:
Heatpump: 152
RC35 with 4 hc: 173
RC300 with 4 hc: 119 (i've expected more)
Solar 72 with ww

**Comment by proddy** [comment]
@MichaelDvP that's good to know. I'll make a change to the customization screen so only the changed entities are sent back instead of the complete list. If we hit a memory limit we can always add a warning and tell users to save in batches

**Comment by proddy** [comment]
fixed in b11
