### ISSUE TITLE
Sync time with Moduline 400?

### ISSUE THREAD

**Issue by Gert05** [emsesp/EMS-ESP32#451]
Is it possible to sync/push the EMS-ESP system time (NTP) to a Moduline 400 thermostat?
Currently on latest beta (3.4.0b11). Thermostat DevID=0x10, ProdID=78, V=02.20.

**Comment by MichaelDvP** [comment]
No, sorry, there were some test with a compatible RC30 a time ago, no luck writing to the thermostat clock.
You can try using the send command:
`call system send "0b 10 06 00 <date/time>"`
with datetime hex: year-month-hour-day-min-sec-dow-dst,  DayofWeek is 0-6, starting mo, dst 2(winter) or 3(summer)
you can also try without dst, or set dst 0/1
actual date 05.04.2022 16:20:00 is than: `call system send "0b 10 06 00 16 04 10 05 14 01 03"`
