### ISSUE TITLE
how to fetch only value of entity from api, not detailed info?

### ISSUE THREAD

**Issue by harvey637** [emsesp/EMS-ESP32#462]
Hi, how do I get only the value of an entity via api?

the documented simple fetch does result in detailed info about entity, not only value ;.(

```
/usr/bin/wget --no-check-certificate -q http://ems-esp/api/thermostat/hc1/seltemp -O -
{
  "name": "seltemp",
  "fullname": "hc1 selected room temperature",
  "circuit": "hc1",
  "value": 20,
  "type": "number",
  "min": 5,
  "max": 29,
  "uom": "°C",
  "readable": true,
  "writeable": true,
  "visible": true
}
```

I hope to get only "20" 

cu
Harvey

**Comment by proddy** [comment]
you can't, but we can consider adding a "/value" after the entity to bring only the value back.

**Comment by harvey637** [comment]
Hi Proddy,
excellent idea, thank you
looking forward to test :-)
cu
Harvey
