### ISSUE TITLE
Add support for : No telegram type handler found for ID 0xF7 (src 0x10)

### ISSUE THREAD

**Issue by nhmariend** [emsesp/EMS-ESP32#463]
From debug i got this:
I Think I should get info about Brine in and Brine out.
Maybe status for extra electrial heating stage 1,2,and 3 also
Solution to get log without error and values in the device/sensor that are on my Bosch Compress 6000AW

Im use the last version: 3.4.0b11
added files of debug log and info files

**Comment by MichaelDvP** [comment]
see #150

**Comment by nhmariend** [comment]
Something failed the first time, can you look at the debug file now?
No solar in use here. 
[emsesp_settings (1).txt](https://github.com/emsesp/EMS-ESP32/files/8455401/emsesp_settings.1.txt)
[emsesp_info (2).txt](https://github.com/emsesp/EMS-ESP32/files/8455406/emsesp_info.2.txt)
[debug.txt](https://github.com/emsesp/EMS-ESP32/files/8455409/debug.txt)

I think I should get some value here, its just 0 all the time
![image](https://user-images.githubusercontent.com/64189587/162534536-a49bc2b2-32f9-4b74-90cf-d285e0271c93.png)
Picture from ems-esp Dashboard:
![image](https://user-images.githubusercontent.com/64189587/162535315-16a70ded-c5a7-430b-bc33-5ad6d79f9a76.png)

**Comment by MichaelDvP** [comment]
The temperatures coming all from the same telgeram 0x48F, the values are ok, so this is sent from your pump.
