### ISSUE TITLE
add "ignored handlers" to system info

### ISSUE THREAD

**Issue by MichaelDvP** [emsesp/EMS-ESP32#464]
@proddy When searching for settings it's always a lot of logging and searching for the changed telegram. What d you think about storing telegram-ids which are send from src but not handled yet and show in system info. 
```
   {
      "type": "Thermostat",
      "name": "RC35",
      "device id": "0x10",
      "product id": 86,
      "version": "01.18",
      "entities": 56,
      "handlers received": "0xA3 0x06 0xA2 0x12 0x3E 0x3D 0x4C 0x52 0x51 0x5C 0x5B 0x38 0x39",
      "handlers fetched": "0x48 0x47 0x49 0xA5 0x37",
      "handlers pending": "0x3F 0x42 0x53 0x56 0x5D 0x60",
      "handlers ignored": "0xAC 0x01"
    },
```
Then we know the thermostat has send out 0xAC (the mixer command) and 0x01 (i've done `read 10 01` to get a nonempty telegram).

**Comment by proddy** [comment]
a great addition!

**Comment by harvey637** [comment]
Hi,
more enhancment would be the number of "hidden" entities like

`"entities: 85 (plus 43 hidden)"`

just to inform that some entities are not shown in the dashboard.

cu
Harvey
