### ISSUE TITLE
Config conflict: wwdisinfect

### ISSUE THREAD

**Issue by sciurius** [emsesp/EMS-ESP32#465]
**Bug description**

EMS-ESP version 3.4.1b11

`homeassistant/binary_sensor/ems-esp/boiler_wwdisinfect/config` specifies `"val_tpl": "{{value_json.wwdisinfect}}"` but the actual JSON data seems to be `wwdisinfecting`. As a result, `HomeAssisant` complains:

    'dict object' has no attribute 'wwdisinfect' when rendering '{{value_json.wwdisinfect}}'

`homeassistant/binary_sensor/ems-esp/boiler_wwheat/config` specfies `"val_tpl": "{{value_json.wwheat}}"` but the actual JSON data doesn't have a `wwheat` attribute. HomeAssistant complains:

    'dict object' has no attribute 'wwheat' when rendering '{{value_json.wwheat}}'

**Comment by MichaelDvP** [comment]
Go to "MQTT Settings" and disable "MQTT Discovery" setting (do NOT disable mqtt), click "Save", wait 5 minutes, reenable "MQTT Discovery"and click "Save".

**Comment by sciurius** [comment]
IOW, these are leftovers from the previous version and retained by the MQTT broker?

**Comment by proddy** [comment]
yes. The changes we made back in Dec 2021 (https://github.com/emsesp/EMS-ESP32/issues/211) and also mentioned in the Changelog. And there is also a knowledge article on the wiki on [this](https://emsesp.github.io/docs/#/Troubleshooting?id=ha-is-showing-errors-like-quotreceived-message-on-illegal-discovery-topicquot-or-quottemplate-variable-warning-39dict-object39-has-no-attributequot).

**Comment by sciurius** [comment]
Then I gently apologise for not having taken the appropriate action at the time I read the release notes.
Thanks for the good work!
