### ISSUE TITLE
Invalid value for number.thermostat_hc1_selected_room_temperature: 0 (range 5.0 - 29.0)

### ISSUE THREAD

**Issue by bavo** [emsesp/EMS-ESP32#469]
**Bug description**
Home assistant spams the following message on every thermostat mqtt message when my selected_room_temperature is 0:

`[homeassistant.components.mqtt.number] Invalid value for number.thermostat_hc1_selected_room_temperature: 0 (range 5.0 - 29.0)`

My thermostat sets the selected room temperature to 0 when it is not heating. 

ems-esp32: v3.4.0b11
home assistant: 2022.3.7

**Comment by proddy** [comment]
The range is hardcoded in https://github.com/emsesp/EMS-ESP32/blob/fdefd028124f203484704684ee58fff8cfa1fcda/src/devices/thermostat.cpp#L3639 

we can change it.
