### ISSUE TITLE
3.4 b18 - syslog not working anymore 

### ISSUE THREAD

**Issue by tp1de** [emsesp/EMS-ESP32#505]
I installed b18 and recognized that syslog does not work anymore. Restoring b17 everything works as expected.

**Comment by MichaelDvP** [comment]
Syslog working for me as before and i can't find any code change that could effect syslog.

**Comment by tp1de** [comment]
OK, then I will test again.

**Comment by tp1de** [comment]
By new install of b18 syslog is working again. So I will close this issue.
