### ISSUE TITLE
Controller data is showing up in WebUI customization

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#522]
@MichaelDvP 

with the addition of 0x06/RCTime being added to the Controller device object everyone will now see this pop up in the Customization page like:

![image](https://user-images.githubusercontent.com/1230712/170439480-617835da-ca7a-4f25-b073-47a6f470b959.png)

although it will never show in up the Web Dashboard, MQTT/API or Console.

Any ideas on how to prevent it showing? e.g. just ignore the Controller type in the Customization or only add this device entity if the boiler type is IVT ?

**Comment by MichaelDvP** [comment]
It is shown in dashoard for IVT, if it have a value [https://github.com/emsesp/EMS-ESP32/blob/60714b0b0b2cfa913064cb5346847a956f0b6ad4/src/web/WebDataService.cpp#L81](https://github.com/emsesp/EMS-ESP32/blob/60714b0b0b2cfa913064cb5346847a956f0b6ad4/src/web/WebDataService.cpp#L81)

If you don't like it in customizations, maybe dont show devices with no active entities. But the customization shows all registered values, it's consequent to show the controller value too.

**Comment by proddy** [comment]
There is logic in boiler and thermostat to only register the entities that are supported on that particular hardware. This is what the device flags are used for. I think we should do the same for the Controller.

**Comment by MichaelDvP** [comment]
Yes, it's only the IVT controller, i'll add a model-flag.

**Comment by proddy** [comment]
fixed in 3.4.1
