### ISSUE TITLE
hidden entity hc->climate showing up in WebUI customization

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#523]
@MichaelDvP 

The hc->climate which I think is used to automatically fall back to the Thermostats roomTemp if there is no selTemp is appearing in the WebUI customization page.

![image](https://user-images.githubusercontent.com/1230712/170441689-62ebc1c9-edf4-4f39-9b8b-6de5e311811a.png)

It's an internal entity and never show in the console/mqtt/api/dashboard etc...

Question: how best to exclude it from the list?

**Comment by MichaelDvP** [comment]
It's used to generate the HA climate config, not shown in dashboard, but exclude from mqtt is used to disable the climate config.

**Comment by proddy** [comment]
yes, but how to exclude it from showing up in the Customization list?

**Comment by MichaelDvP** [comment]
If you exclude it from list, you have no way to disable it.

**Comment by proddy** [comment]
ok, I looked at the code and understand now. It's not a real EMS device entity but a derived one and used to determine if the HA's climate component should be created. It's never shown in the API/MQTT/Console/Web output as it's a internal hidden value. If you disable it from Customizations it will prevent the HA climate discovery topic from being created.

It may confuse people (like me!) so best to rename to ha_climate and give it a full-name

**Comment by MichaelDvP** [comment]
Yes, it's a bit confusing, but it's hard to create or not create the right climate config, it takes a lot of tries to find this. If you add a full-name it will show up on dashboard and mqtt, maybe use a "short-name" like `ha_climate_config_creation`, since it it not shown in mqtt, the name will not blow up the mqtt.

**Comment by SpaceTeddy** [comment]
for me the same. customization menu shows items, which i can not see in the device overview.
i.E.

<img width="919" alt="image" src="https://user-images.githubusercontent.com/9148964/170672941-a0c00edf-bc0b-4619-83f3-28a848686e0a.png">

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/9148964/170673236-871162ce-c982-453a-865e-0c23f17da39c.png">
