### ISSUE TITLE
FR100 - thermostat time correction from ntp

### ISSUE THREAD

**Issue by odelcourt** [emsesp/EMS-ESP32#536]
Since update to v3.4.1 (coming from 3.3.1), every second I have this message in console:
     000+00:54:48.710 I 2158: [thermostat] thermostat time correction from ntp

![screenshot1](https://user-images.githubusercontent.com/6671085/171617326-5d259cb8-ea9c-44f0-914e-bc348897d8fe.jpg)

it seems to "overwhelm" the thermostat because it respond much slower to command from MQTT (changing mode, tuning one wwonetime,...). I have deactivated the NTP sync on the EMS and I have no more the message in the console and the thermostat react to command "as usual" (fast). It seems that the "thermostat time correction from ntp" occupies the EMS bus.

My Thermostat is a BOSCH/JUNKERS FR100 . Do you need other information(s) ? Can I actually do something else than deactivate the NTP sync ?

![screenshot2](https://user-images.githubusercontent.com/6671085/171617320-2c8604ef-743c-4b50-8f0b-aa6b3705f146.jpg)

**Comment by odelcourt** [comment]
> That's one option, second is to set the clock correctly, than it needs no correction.

I have checked / tried that with no success :-(
I had not that problem before, is it something that has been changed with the version 3.4.x ?

**Comment by MichaelDvP** [comment]
v3.4 checks the clock and if thermostat clock differs much from NTP it writes the corrected time to the clock, see #386. But for some thermostats the clock is not writeable via ems-bus. Sad that this was not detected in beta tests.

**Comment by odelcourt** [comment]
> v3.4 checks the clock and if thermostat clock differs much from NTP it writes the corrected time to the clock, see #386. 

OK, this explains this.

>But for some thermostats the clock is not writeable via ems-bus. Sad that this was not detected in beta tests.

Bah. You can't test all with all hardware.... and the workaround was easy. Thank you for the follow of the tickets.

**Comment by odelcourt** [comment]
> Can we close this?

How can I test this  ? I guess I have to install a dev version? But mine EMS-ESP32 is used in "production", thus have you a dev build "safe" ? Otherwise, yes you can close this but I will only be able to test it with the next official release. Many thanks for your support and development.

**Comment by MichaelDvP** [comment]
I've made a test branch based on main build and only add this patch. You can [check here](https://github.com/MichaelDvP/EMS-ESP32/releases/tag/latest), [source here](https://github.com/MichaelDvP/EMS-ESP32/tree/main_patched), and after test you can also go back to previous builds.

**Comment by odelcourt** [comment]
> I've made a test branch based on main build and only add this patch. You can [check here](https://github.com/MichaelDvP/EMS-ESP32/releases/tag/latest), [source here](https://github.com/MichaelDvP/EMS-ESP32/tree/main_patched), and after test you can also go back to previous builds.

Tested successfully. I'll keep that version running for now. Many thanks !

**Comment by odelcourt** [comment]
> I've made a test branch based on main build and only add this patch. You can [check here](https://github.com/MichaelDvP/EMS-ESP32/releases/tag/latest), [source here](https://github.com/MichaelDvP/EMS-ESP32/tree/main_patched), and after test you can also go back to previous builds.

Tested successfully. I'll keep that version running for now. Many thanks !
