### ISSUE TITLE
Webinterface wrong aligned Tables 

### ISSUE THREAD

**Issue by mbenkler** [emsesp/EMS-ESP32#54]
I just installed the ne release 3.1.0 and the tables in the Dashboard seem to be wrong aligned ?!

![devices view ems-esp32](https://user-images.githubusercontent.com/51227626/116993542-ea131f80-acd7-11eb-9025-3c0b10f14fbe.png)

**Comment by proddy** [comment]
your quick! try refreshing your browser first. It may be cached

**Comment by mbenkler** [comment]
never mind, it was just cached. 
I should have thought of that
👍
