### ISSUE TITLE
Make Change Value dialog box left aligned for long text

### ISSUE THREAD

**Issue by tp1de** [emsesp/EMS-ESP32#547]
Dialog box opens right aligned (end of text) for strings longer then dialog box. 
Left aligned (start of text) would be better.

**Comment by tp1de** [comment]
Even better would be a multi line input within dialog box. 
(accepting "\n" line feeds within string or any other LF character.

**Comment by proddy** [comment]
can you provide a screenshot and an example, so I can add test data

**Comment by tp1de** [comment]
see #275 last entry.

I would like to use for hm1-hm5 e.g. 01.01.2023-01.02.2023  : {3,,2,[hc1,hc2,dhw1]}
and make a second line where the ":"  is ...

**Comment by MichaelDvP** [comment]
The input line **is** left aligned, but it's an input and with focus on it, it shows the cursor position. If the focus changesto another element, it's left aligned again.
You can insert a line `multiline` [here after this line 538](https://github.com/emsesp/EMS-ESP32/blob/a02d4ab25983da88dbdb0000ed25f509351ceb60/interface/src/project/DashboardData.tsx#L538), than the input expands for long texts like this:

![grafik](https://user-images.githubusercontent.com/59284019/173333174-aaafc1ed-3dce-4396-b5c5-6a7adb3c1cf6.png)     ![grafik](https://user-images.githubusercontent.com/59284019/173333063-a620d10e-65ea-4e56-b2c0-c3ad2ee7d537.png)

**Comment by proddy** [comment]
I was buy re-doing the tables so added this multline, it'll be in the 3.4.2b3 which I'll push soon to dev

**Comment by MichaelDvP** [comment]
Please use `multiline={deviceValue.u ? false : true}` to keep the step-up/down-arrows for number fields.

**Comment by tp1de** [comment]
> Please use `multiline={deviceValue.u ? false : true}` to keep the step-up/down-arrows for number fields.

@MichaelDvP what does this mean for formatting the lines?

**Comment by proddy** [comment]
it means you press enter and it'll accept multiline strings. You can test it using the online demo https://ems-esp.derbyshire.nl/ems-esp/dashboard/data by selecting the Boiler and clicking on 'next maintenance date'

**Comment by tp1de** [comment]
Ok understood. I am just testing multiline and I ask myself if I can use "\n" linefeed to build a second line or if I had to fill each line with " " .

**Comment by tp1de** [comment]
Filling with blanks in multiline works so far:

![image](https://user-images.githubusercontent.com/36480251/175824605-0ff14523-dd47-42d0-8e40-47cf7953e20e.png)

**Comment by tp1de** [comment]
Multiline is fine for me  ... thanks for adjusting
