### ISSUE TITLE
boiler burner selected max power range incorrect

### ISSUE THREAD

**Issue by bluediamond1984** [emsesp/EMS-ESP32#553]
I've updated firmware to the latest stable 3.4.1. And I like the new added features.
However in home assistant log I noticed errors while using the hot water.

ERROR (MainThread) [homeassistant.components.mqtt.number] Invalid value for number.boiler_burner_selected_max_power: 143 (range 0.0 - 130.0)

It seems that the upper limit is to low for my Nefit Topline/GB162.

**Comment by proddy** [comment]
@MichaelDvP make it 150?

**Comment by MichaelDvP** [comment]
Set it to 254 % for selBurnPow_, burnMaxPower_, and wwMaxPower_. For UINT this will always fit.
I'm not sure if the Bosch percentage should be renamed to `"max power (P.M.P.O)" ` or if this a simple trick to use the same burner for different power classes: 100kW boiler is 0-100%, 80kW boiler is 0-125% and 50kW is 0-200% power modulated with same burner.
