### ISSUE TITLE
Heatpump: HP Module - relative air humidity is half the value it should be

### ISSUE THREAD

**Issue by beSt0815** [emsesp/EMS-ESP32#598]
Hi,
the EMS shows the relative humidity of my CR 10H Thermostat.
Unfortunately it shows exactly half the value it should be.
The HPC400 shows the correct value.
<img width="284" alt="1" src="https://user-images.githubusercontent.com/89731552/183393333-5baac4fc-6aba-479f-a022-33506f44ced2.png">
![2](https://user-images.githubusercontent.com/89731552/183393378-c070766f-d0ee-4f4e-baa8-3dc98f6b33a1.jpg)
Thank you.

**Comment by MichaelDvP** [comment]
So this is also a thermostat (RC10H) and not a hp-module, please attach the debug info from help page of ems-esp. Then i can see the telegram-ids, product id and device id to map the values right.

**Comment by beSt0815** [comment]
Device Details

    Type:    Heatpump
    Name:    HP Module
    Brand
    Device ID:    0x38
    Product ID:    200
    Version:    40.07

**Comment by MichScha** [comment]
@MichaelDvP maybe same calculation like for rc100h #590 
I have appended a few minutes ago new debug values.

**Comment by MichaelDvP** [comment]
Yes, it's the same product_id and same device_id working as remote thermostat and should work in my [dev-branch](https://github.com/MichaelDvP/EMS-ESP32/releases) as thermostat, i've already made a PR.

**Comment by proddy** [comment]
@beSt0815 did Michael's firmware work?

**Comment by beSt0815** [comment]
Yes, the humidity is correct now.

**Comment by proddy** [comment]
Great. Can you close this issue?
