### ISSUE TITLE
Trendline outdoor temperature sensor

### ISSUE THREAD

**Issue by sweetpants** [emsesp/EMS-ESP32#604]
Does anybody know if the 'outdoor temperature' sensor of the Trendline boiler is exposed on the EMS/MQTT bus?

regards, Harry

**Comment by sweetpants** [comment]
Hmmm, searching a little further it seems a function of the Thermostat? Mine is a Moduline Easy, sw version 2.22.0 hw version 3, Boiler Trendline HRC30/CW5. Can someone confirm?
Regards, Harry

**Comment by proddy** [comment]
do you see the outdoor temp anywhere, like on the Easy thermostat or in the boiler's panel? If it's there, we should be able to grab it

**Comment by sweetpants** [comment]
Here you go, screenshot on easy app on Android
![Screenshot_20220824-150301_Nefit Easy](https://user-images.githubusercontent.com/23421160/186425725-30328f99-f8c1-428e-8f25-a02324ed0d4d.jpg)

**Comment by proddy** [comment]
ok, EMS-ESP does read the outdoor temp from the boiler, from telegram 0x19. Are you not seeing this?

**Comment by bbqkees** [comment]
Do you really have an outdoor temperature sensor connected to the boiler or is the app getting it from elsewhere?

**Comment by sweetpants** [comment]
@bbqkees , i think you are right. I have opened the ceiling and could not find an external temperature sensor wires so the app is getting it from somewhere else. Because I want to be independent of external (internet) sensors i'm going to add a separate dallas sensor to the EMS gateway. Case closed

**Comment by sweetpants** [comment]
@bbqkees , i think you are right. I have opened the ceiling and could not find an external temperature sensor wires so the app is getting it from somewhere else. Because I want to be independent of external (internet) sensors i'm going to add a separate dallas sensor to the EMS gateway. Case closed
