### ISSUE TITLE
Bosch rf room temperature sensor not identified

### ISSUE THREAD

**Issue by tfriberg** [emsesp/EMS-ESP32#624]
**Is your feature request related to a problem? Please describe.**
rf room temperature sensor not identified as sensor

**Describe the solution you'd like**
Identify rf room temperature sensor as a Sensor

**Describe alternatives you've considered**
Checking to see if I can do it myself somewhere in the EMS_ESP UI/dashboard

**Additional context**
```
Type
Unknown

Name
rf room temperature sensor

Brand
Device ID
0x40

Product ID
0

Version
00.00
```
<img width="706" alt="image" src="https://user-images.githubusercontent.com/867763/190916097-54cb2be9-6824-4d69-960a-c0960974a844.png">

Label on room sensor reads (sensor module):
Bosch
TR2 RF 8737709446
SW-Ver 2.4.004
TRX2-TIF

**Comment by MichaelDvP** [comment]
Seems like the same sensor as in #103.
It only sends the remote temperature in telegram 0x435. This temperature is shown in master thermostat as roomtemperature, there is no real need to read thisextra from sensor. But since we have now support for multiple thermostats we can register it as thermostat (like the RF100H) and show the value.

**Comment by tfriberg** [comment]
Will check. Thanks.

**Comment by tfriberg** [comment]
@MichaelDvP 
Trying to upload 3.5.0b2 and, updating from 3.4.2. No joy!

<img width="339" alt="image" src="https://user-images.githubusercontent.com/867763/191336944-9a360832-c2ea-4cdc-93ba-f399df466e87.png">


<img width="529" alt="image" src="https://user-images.githubusercontent.com/867763/191337185-90aeac12-8f34-435a-8dbd-c187d3668626.png">

**Comment by MichaelDvP** [comment]
Seems to be a common issue, see #629.
