### ISSUE TITLE
does Factory Reset from the webUI work?

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#628]
There was a note on Discord about the System->Factory Reset button not working. It does not remove the config files from the filesystem. Worth checking...

**Comment by MichaelDvP** [comment]
Checked and it does not work. [This](https://github.com/emsesp/EMS-ESP32/blob/fc057d18c99e9ded6fe34f0bd3aa46480d9d0879/lib/framework/FactoryResetService.cpp#L28) should be the `file.path()` and a strdup should be freed after use (no permanent leak because of reset in this case).

**Comment by MichaelDvP** [comment]
Tested, works.
