### ISSUE TITLE
Add aux heater limits

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#645]
### Discussed in https://github.com/emsesp/EMS-ESP32/discussions/644

<div type='discussions-op-text'>

<sup>Originally posted by **Cali1205** September 25, 2022</sup>
While working on optimizing the power consuption of my heat pump together with my PV system I thought it is a good idea to be able to control the power to the aux heater.
My idea is to use the limit setting of the aux heater.
![PXL_20220918_155339209 - Kopie](https://user-images.githubusercontent.com/11048533/192136723-bf52429c-ec92-40fa-a50b-b5d42036fbcf.jpg)

I think it would be very helpful to have these setting available.

The register seems to be 0x492.
Description | Offset
-- | --
aux heater limit with compressor active | 2
aux heater limit heating | 3
aux heater limit hot water | 4

And the values are:
Reg Value | Value
-- | --
0 | 0kW
1 | 2kW
2 | 3kW
3 | 4kW
4 | 6kW
5 | 9kW

</div>

**Comment by MichaelDvP** [comment]
I've added this to PR #650, needs to be checked by a user with this heatpump.

**Comment by proddy** [comment]
thanks. closing for now.
