### ISSUE TITLE
Optimize flash with ESP32

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#646]
This is another thing that's been on my mind for a while. A lot of the code was written based on the ESP8266 and ported over to the ESP32, including how we place and extract data from the precious flash memory. On the ESP32 any `const char` is automatically placed in PROGMEM so we can optimize in a few ways
- remove the redundant F()
- remove the redundant PROGMEM and uint32 alignment
- don't use  `__FlashStringHelper`. This is just an empty dummy class to differentiate between SRAM and Flash. Replace with const char *'s

For starters, I changed `device_library.h` which saves a 1kb of flash. I'll use the branch https://github.com/emsesp/EMS-ESP32/tree/flash_optimization for testing

**Comment by proddy** [comment]
removed flash. It makes the code cleaner and easier to read too, also I expect some performance gains. The nice thing is that it's saved almost 8KB in Flash. Now I need to test it!

**Comment by proddy** [comment]
in my tests performance is good, heap is the same and the application sized is smaller. so this is looking good...

**Comment by MichaelDvP** [comment]
I've tried your latest commit and get crashes exactly after one minute. Disabled different services and it seems to be in fetch of ems values (ems disconneced->no crash). If you can not reproduce, i have to search in RC35, MM10 and SM10 fetching.

**Comment by proddy** [comment]
yes, known issue. it's in the MQTT code and I know which line to fix. Haven't been home for a while but will resume this weekend.

**Comment by MichaelDvP** [comment]
It was the empty fullname for climate entity, that has to be added: [This line](https://github.com/emsesp/EMS-ESP32/blob/90d21445884f1c8c576deb6dcaa70f5a0f898dde/src/locale_common.h#L267) to:
`MAKE_PSTR_LIST(climate, "HA climate config creation", "")`

**Comment by proddy** [comment]
yes, i checked the fix in yesterday

**Comment by proddy** [comment]
i swapped out std::string to const char * in ha_publish and saved another 760b in flash

**Comment by proddy** [comment]
the flash_optimization is up to date with the latest 'dev'. It'll keep it running for a few days and if its stable will merge back into dev.

**Comment by proddy** [comment]
will merge into dev
