### ISSUE TITLE
Unknown: unknown (DeviceID:0x16, ProductID:220, Version:01.02) on Buderus GBH192iT-25

### ISSUE THREAD

**Issue by Wuehli** [emsesp/EMS-ESP32#663]
**Is your feature request related to a problem? Please describe.**
I just connected my Buderus GBH192iT from 2017 (basically this is the supported GB192 but with an additional buffer tank). 
EMS found one unknown device (Type: Unknown; Name: unknown; Brand: ; Device ID: 0x16; Product ID: 220; Version: 01.02).
Also i currently miss one sensor value, it's the temperature from the additional buffer tank.

**Describe the solution you'd like**
I'd love to see the missing value and get rid of an unknown device

**Describe alternatives you've considered**
?

**Additional context**
EMS-ESP Version

v3.4.2
Device (Platform / SDK)

ESP32 / v4.4.1-472-gc9140caf8c
System Uptime

000+04:09:51.200
CPU Frequency

240 MHz
Heap (Free / Max Alloc)

136.464 / 83.956 bytes
Flash Chip (Size / Speed)

4.194.304 bytes / 40 MHz
File System (Used / Total)

8.192 / 65.536 bytes (57.344 bytes free)

These EMS devices are currently active:

Boiler: Buderus Logamax Plus/GB192/Condens GC9000 (DeviceID:0x08, ProductID:208, Version:01.04)
 Received telegram type IDs: 0x10 0x15 0x1C 0x18 0x19 0x34 0x2A
 Fetched telegram type IDs: 0x14 0x16 0x33 0x26
 Pending telegram type IDs: 0xBF 0x11 0xC2 0x1A 0x35 0xD1 0xE3 0xE4 0xE5 0xE6 0xE9 0xEA
 Ignored telegram type IDs: 0x17 0x2E 0x04 0x25 0x27 0x05 0xEF

Thermostat: RC300/RC310/Moduline 3000/1010H/CW400/Sense II (DeviceID:0x10, ProductID:158, Version:18.02)
 Received telegram type IDs: 0x06 0xA2 0x2BB 0x2BC 0x2BD 0x2BE 0x2BF 0x2C0 0x31D 0x267
 Fetched telegram type IDs: 0x2A5 0x2B9 0x2AF 0x29B 0x2A6 0x2BA 0x2B0 0x29C 0x2CE 0x2F5 0x31B 0x23A 0x240
 Pending telegram type IDs: 0xA3 0x12 0x471 0x472 0x2A7 0x2B1 0x29D 0x473 0x2A8 0x2B2 0x29E 0x474 0x2A9 0x2B3 0x29F 0x475 0x2AA 0x2B4 0x2A0 0x476 0x2AB 0x2B5 0x2A1 0x477 0x2AC 0x2B6 0x2A2 0x478 0x2CC 0x2D0 0x2D2 0x31E
 Ignored telegram type IDs: 0x292 0x2E1 0x2E2 0x2EB 0x2EC 0x35 0x291 0xBF

Mixer: MM100 (DeviceID:0x20, ProductID:160, Version:24.03)
 Received telegram type IDs: 0x2D7
 Fetched telegram type IDs:
 Pending telegram type IDs:
 Ignored telegram type IDs: 0xEF 0xF6 0x2CD 0x1A 0x255 0x3BD 0xF7 0xBF

Mixer: MM100 (DeviceID:0x21, ProductID:160, Version:24.03)
 Received telegram type IDs: 0x2D8
 Fetched telegram type IDs:
 Pending telegram type IDs:
 Ignored telegram type IDs: 0xEF 0x2CE 0xF7 0xF6 0x3BE 0x1A 0x255 0xBF

Controller: 9000i (DeviceID:0x09, ProductID:224, Version:35.03)

Unknown: unknown (DeviceID:0x16, ProductID:220, Version:01.02)

**Comment by MichaelDvP** [comment]
Device-Id 0x16 is really unknown, i've never seen it before. Please check on the RC300. There should be a system information wth connected devices, what is listed there. In ems-esp set the loglevel to `All` and wait more than a minute, then click download and attach the log here. Maybe this module has to do with the missing value, please note and tell us what was this temperature reading while logging.

**Comment by Wuehli** [comment]
Hi,

i've checked my RC310 for devices:

Wärmeerzeuger:
Typ Steuereinheit: CU50
SW-Vers. Steuereinheit: 01.04
HCM/BCI-Nummer: 1526
Version: 4

Typ HMI: BC30
SW-Vers. HMI: 35.03
Typ Service HMI: HMI XS
SW-Vers. Service HMI: 01.02

Bedieneinheit:
Typ: RC310
SW-Version: NF18.02

Module:
Typ Module HK 1: MM100
SW-Vers. Modul HK1: NF24.03
Typ Module HK 2: MM100
SW-Vers. Modul HK2: NF24.03

**Comment by MichaelDvP** [comment]
I think the temperature is `wwcylmiddletemp` from telegram 0x2A.
The missing device is the control-panel of the boiler (BC30), it has no values and sends nothing on the bus in this log. I'll add it as controller. If you change a value on the panel you will see a command from device 0x16 to the boiler, butt all settings are stored in the boiler.

**Comment by proddy** [comment]
It's merged into the latest dev

**Comment by Wuehli** [comment]
Great! Thanks!

> I think the temperature is `wwcylmiddletemp` from telegram 0x2A.

After checking the description in the dashboard (dhw cylinder middle temperature (TS3) ) and the Buderus installation manual, I would fully agree. What confuses me is that in my software (IP-Symcon) I only see the value 20 as an integer, but in EMS-ESP it is correctly displayed as 20.0. i checked the log but did not find the value. Is this value only shown in the mqtt LOG if it has changed?

**Comment by MichaelDvP** [comment]
>  i checked the log but did not find the value. Is this value only shown in the mqtt LOG if it has changed?

It's in this telegram in offset 18, value `00 C8` e.g. 200  => 20.0°C, it was the only 20.0°C i've found.
2022-10-05 17:45:15.483 TRACE 15787: [emsesp] Boiler(0x08) -> All(0x00), MC110Status(0x2A), data: 00 00 00 00 00 00 00 00 9C 00 00 80 00 00 01 85 80 00 00 C8 00
The mqtt messages in log are cut, to long for logging, but in mqtt broker payload it should show.

**Comment by Wuehli** [comment]
Sorry, I have expressed myself in a misleading way.
In the EMS I found the value with decimal place. But via MQTT it arrives in the IP-Symcon as integer, so I wanted to look in the LOG whether it is transmitted with or without decimal place. It looks like only 20 instead of 20.0 is transmitted via MQTT from EMS to Symcon.

**Comment by proddy** [comment]
what's the difference between 20 and 20.0 and why would IP-Symcon care?

**Comment by Wuehli** [comment]
The problem (as far as I understand it) is that if the value is 20 when first received, Symcon creates a variable of type integer. This either causes the variable to be recreated when the value later comes in as a floating point number (resulting in lost links in automations/scripts, orphaned archive values, etc.), or it ignores the decimal places. 
Both is problematic from my point of view but I don't know enough to say what would be the right thing to do here.

**Comment by MichaelDvP** [comment]
Mqtt output is a serialized json and the temperature is number, not a string. I think there is no way to format that number.  
You can try to enable the single value on change option, the mqtt publish is a string that is always rendered with decimals for values with high resoluton.

**Comment by MichaelDvP** [comment]
Set [here](https://github.com/emsesp/EMS-ESP32/blob/4489e7149cfe34b3703f9c5040be18a8d361a189/lib/ArduinoJson/src/ArduinoJson/Numbers/FloatParts.hpp#L51) `decimalplaces > 1` and floats will show .0:
```
thermostat_data:
{
  "lastcode": "22(816) 25.07.2022 17:54 (1 min)",
  "datetime": "06.10.2022 10:27",
  "intoffset": -1.0,
  "minexttemp": -11.0,
  "damping": 1,
  "dampedoutdoortemp": 14.0,
  "building": 0,
  "wwmode": 2,
  "wwcircmode": 0,
  "wwprogmode": 0,
  "wwcircprog": 0,
  "wwdisinfecting": 0,
  "wwdisinfectday": 1,
  "wwdisinfecthour": 1.0,
  "wwmaxtemp": 60.0,
```

**Comment by MichaelDvP** [comment]
> I tried https://arduinojson.org/v6/how-to/configure-the-serialization-of-floats/#how-to-add-trailing-zeros and it didn't work for me

Tried it too, crashes if used with `serialized(String(transformNumFloat(),1))`,  but if i use `serialized(Helpers::render_value());` it works. 
In this case [this](https://github.com/emsesp/EMS-ESP32/blob/4489e7149cfe34b3703f9c5040be18a8d361a189/src/emsdevice.cpp#L1392-L1421) does not need the make_float and reduces to
```
                char val[10];
                if (dv.type == DeviceValueType::INT) {
                    json[name] = serialized(Helpers::render_value(val, *(int8_t *)(dv.value_p), dv.numeric_operator, fahrenheit));
                } else if (dv.type == DeviceValueType::UINT) {
                    json[name] = serialized(Helpers::render_value(val, *(uint8_t *)(dv.value_p), dv.numeric_operator, fahrenheit));
                } else if (dv.type == DeviceValueType::SHORT) {
                    json[name] = serialized(Helpers::render_value(val, *(int16_t *)(dv.value_p), dv.numeric_operator, fahrenheit));
                } else if (dv.type == DeviceValueType::USHORT) {
                    json[name] = serialized(Helpers::render_value(val, *(uint16_t *)(dv.value_p), dv.numeric_operator, fahrenheit));
                } else if (dv.type == DeviceValueType::ULONG) {
                    json[name] = serialized(Helpers::render_value(val, *(uint32_t *)(dv.value_p), dv.numeric_operator));
```

**Comment by proddy** [comment]
wow that's much cleaner. and we don't need make_float anymore? nice work!

**Comment by MichaelDvP** [comment]
Also it sets the decimals only to scaled values. e.g.: designtemp, targetflowtemp, summertemp are int with 1 degree scaling.
```
    "daytemp": 21.0,
    "nighttemp": 17.0,
    "designtemp": 65,
    "offsettemp": 0.0,
    "holidaytemp": 15.0,
    "targetflowtemp": 43,
    "summertemp": 16,
```

**Comment by proddy** [comment]
> Also it sets the decimals only to scaled values. e.g.: designtemp, targetflowtemp, summertemp are int with 1 degree scaling.

That's good and bad. Later if we want all temps as floats, even those with 1 degree scaling I guess we can force it. I was a little concerned about the additional computational overhead of using arduinoJSON's `serialed()` but after looking at the template it's actually quite clever and lightweight.

Do you want to do a PR for this?

**Comment by MichaelDvP** [comment]
Ok, i'll make a pr with commits for this an the Junkers thermostat.

I like it to see some temperatures without decimal and know that it can only set in full degrees. But i think it's a little change to show al temperatures with decimal.

**Comment by Wuehli** [comment]
Will this be included in a compiled beta?

**Comment by proddy** [comment]
https://github.com/emsesp/EMS-ESP32/releases/tag/latest
