### ISSUE TITLE
Summer mode setting from web always changes HC1

### ISSUE THREAD

**Issue by ecs-ghost** [emsesp/EMS-ESP32#68]
When changing summer mode option in the web dashboard for hc2... it changes always for hc1 and never for hc2

**Comment by MichaelDvP** [comment]
Yes, web commands affects ony the default (first) heatingcircuit, i've added a hc  prefix to the web commands in the dev. 
I have only one hc and can only check that it does not break anything, but can't test with a second hc. 
@ecs-ghost please check.

**Comment by ecs-ghost** [comment]
great work now it works as suspected

000+00:01:25.680 I 1: [thermostat] Setting summer mode to auto for heating circuit 2
