### ISSUE TITLE
Buderus GB135 wrong identified / 2 stage burner modulation and hysteresis missing

### ISSUE THREAD

**Issue by pudermueller** [emsesp/EMS-ESP32#716]
Dear team,

thanks for doing  this great job. I just purchased a E32 Gateway and try to replace my EMS gateway https://emswiki.thefischer.net/doku.php?id=wiki:ems:net_io which i used for years. 

I have to issues:
1. My boiler is identified as GB125 - but it is an GB135 with a 2 stage burner
2. The running time of the 2 stages of the burner are shown, but in the settings the hysteresis of the 2nd stage is missing (defaults to "Ausschalt-Hysterese 1 Stufe = 6°C" and "Einschalt-Hysterese 1 Stufe = -6°C". In the extended settings there is also Hysterese 2 ON/OFF with 8°C/-8°C show. 

My system consists of the Boiler GB135 (with 2 stage burner), a mixing module MM10 and a room controller RC35. 

In System Log "DEBUG" i found these entries:
2022-11-01 17:04:37.690   DEBUG 4322:   [emsesp]     No telegram type handler found for ID 0xAC (src 0x10)
2022-11-01 17:04:38.815   DEBUG 4323:   [telegram]   [DEBUG] New Rx telegram, message length 4
2022-11-01 17:04:38.815   DEBUG 4324:   [emsesp]     No telegram type handler found for ID 0x1A (src 0x10)

Update: i found some more missing handlers:
[emsesp]     No telegram type handler found for ID 0x35 (src 0x10)
[emsesp]     No telegram type handler found for ID 0xAC (src 0x10)
[emsesp]     No telegram type handler found for ID 0x1A (src 0x10)
[emsesp]     No telegram type handler found for ID 0x29 (src 0x09)
[emsesp]     No telegram type handler found for ID 0x35 (src 0x10)

[emsesp_info.txt](https://github.com/emsesp/EMS-ESP32/files/9911976/emsesp_info.txt)

Thanks for your support and best regards
Pudermueller

**Comment by MichaelDvP** [comment]
> My boiler is identified as GB125 - but it is an GB135 with a 2 stage burner

They share the same product-id, we can rename it to "GB125/GB135/MC10)"
> In the extended settings there is also Hysterese 2 ON/OFF with 8°C/-8°C show.

Please set to log all and change the values to 7/-7 and back to 8/-8. Send the log. Then we can identify the telegram/offset of these values.
>  No telegram type handler found

These are command telegrams send from thermostat to mixer (0xAC) and boiler (0x35, 0cx1A), The values are also broadcasted by mixer(0xAB) and boiler(0x18), so there is no need to read them. @proddy Maybe we should only mention broadcasted telegrams as "No handler". (emsesp.cpp line 850: `if (!found && telegram->dest == 0)`). 

telegram 0x29 is a single value read every 10 minutes
``` 
2022-11-01 18:53:12.172 N 21: [emsesp] Thermostat(0x10) -R-> Controller(0x09), ?(0x29), length: 0x01
2022-11-01 18:53:12.191 N 22: [emsesp] Controller(0x09) -W-> Thermostat(0x10), ?(0x29), data: 6B
```
Don't know what it is, maybe button states on MC10?

**Comment by proddy** [comment]
> @proddy Maybe we should only mention broadcasted telegrams as "No handler". (emsesp.cpp line 850: if (!found && telegram->dest == 0)).

this is now in b9, thanks Michael.

**Comment by pudermueller** [comment]
Dear all, enclosed the LOG with changes of hysteresis2 from +8 ->+7 / -8 -> -7 and back. offset seems to be 12 and 13
[log(4).txt](https://github.com/emsesp/EMS-ESP32/files/9954585/log.4.txt)
Best regards pudermueller

**Comment by MichaelDvP** [comment]
Ok, it's in the latest dev. 
For 2.stage modulation: Is there really a value for that? I expect that it's only burngas2 on and a difference in currburnpower.
In the known monitor telegrams there is no other field for this.

**Comment by pudermueller** [comment]
Thx. Works fine now. I also identified the 2 stage modulation i was looking for. It is already in and just named "burner current power ", but is at the end of the day the info i need.

**Comment by pudermueller** [comment]
Thx. Works fine now. I also identified the 2 stage modulation i was looking for. It is already in and just named "burner current power ", but is at the end of the day the info i need.

**Comment by proddy** [comment]
can we close this @pudermueller  ?

**Comment by pudermueller** [comment]
Yes thx
