### ISSUE TITLE
Values on new releases show wrong values / fluctuations

### ISSUE THREAD

**Issue by tp1de** [emsesp/EMS-ESP32#717]
Within new releases the temperature values are fluctuating:

![image](https://user-images.githubusercontent.com/36480251/199279396-1e0f8567-da5c-4f21-8042-dcee4ab66af0.png)

**Comment by tp1de** [comment]
I am not 100% sure but I think it comes with Development Build v3.5.0b7

**Comment by MichaelDvP** [comment]
Ups, wrong bracket in the #704 fix

**Comment by proddy** [comment]
This was also reported on GitHub

**Comment by tp1de** [comment]
working again
