### ISSUE TITLE
dhw circulation pump mode (setting "off" or "continuous" always result in "1x3min")

### ISSUE THREAD

**Issue by W0w3** [emsesp/EMS-ESP32#727]
EMS-ESP Version: v3.5.0b9
Interface: BBQKees Gateway S32
Boiler: Buderus Logamax plus GB152T

I have the issue that the setting for the warm water circulation pump is not possible to be set to "continuous" or "off". 
Both settings always result in "1x3min".

The issue persists both in the release version 3.4 as well as in the latest beta.

**Comment by proddy** [comment]
Can you get us some more information like the debug trace log when you set the value

https://emsesp.github.io/docs/#/Troubleshooting?id=changing-a-value-on-an-ems-device-doesn39t-work

**Comment by W0w3** [comment]
Hi proddy,
thank you for your help! :)

Here is the log:
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/40882059/200171025-4a1b45d5-61f1-463e-90c9-e2c6d0e39cb4.png">

**Comment by MichaelDvP** [comment]
Indeed, there is an issue, the command only checks for numbers 0-7, not for texts, `call boiler wwcircmode 7` set to continuous. Option 0-off does not work, valid values are only 1-7. 
I'll change the option to enum type to accept text options (enum starts always at 0, so it is 0- 1x3min, 6 - continuous then).

**Comment by W0w3** [comment]
I installed the latest beta and can confirm the issue is solved as described by fixing continuous setting and removing the off setting. 
Thank you 👍

**Comment by matzelkoenig** [comment]
EMS-ESP Version: v3.7.1
Interface: BBQKees Gateway S32
Device: Bosch XCU_THH/CS*800i, Logatherm WLW* (Boiler/HP)

For my Bosch Compress CS6800iAW 12 MB it is also not working to switch it totaly "off". It always results in "1x3min". The mode "continues" does work and also the other "x3min" modes.

**Comment by proddy** [comment]
> EMS-ESP Version: v3.7.1 Interface: BBQKees Gateway S32 Device: Bosch XCU_THH/CS_800i, Logatherm WLW_ (Boiler/HP)
> 
> For my Bosch Compress CS6800iAW 12 MB it is also not working to switch it totaly "off". It always results in "1x3min". The mode "continues" does work and also the other "x3min" modes. The Software menu of my device only offers the values 1-6 and continues. So I assume "off" is generally not possible but EMS-ESP is still showing it in my version v3.7.1

I would upgrade to the latest dev release (3.7.3) and try again. It may be resolved, otherwise we'll need to investigate further. Version 3.7.1 is a year old.

**Comment by matzelkoenig** [comment]
Thank's for your hint! I am a little bit cautious about updates. The last time my BBQKees crashed and I had to reinstall via cable. I will give it a try again 😉
