### ISSUE TITLE
summermode info on API V3 is wrong

### ISSUE THREAD

**Issue by tp1de** [emsesp/EMS-ESP32#73]
I can confirm that by using API V3 (v3.1.1b6) the field:
http://ems-esp/api/thermostat/hc1/summermode **is not identical** with km200 field heatingCircuits.hc1.suWiSwitchMode. 

In webui dashboard there are 2 identical fields summermode. 
![grafik](https://user-images.githubusercontent.com/36480251/121899312-94915000-cd24-11eb-902f-792ff0e19290.png)

This info is correct but does not correspond to V3 API info on thermostat.

I had a look and was astonished to find out that values on summermode differs:
http://ems-esp/api/thermostat/hc1 returns value 1 for summermode (wrong)
http://ems-esp/api/thermostat/hc1/summermode returns value 0 (right)

Should there be a field summersetmode ?? (ON/OFF)  - 2nd field summermode on dashboard. 
It is missing in the API. Could it be that this field overwrites the summermode?

**Comment by proddy** [comment]
This is problem reported by tobias in https://discord.com/channels/816637840644505620/816652040305901628/853583078144606208

I suspect its a type since both summermode and setsummermode use the same name, and only one is writeable. I don't have an RC3xx so can't check. @MichaelDvP could you?

**Comment by MichaelDvP** [comment]
Yes, it was naming, 'summermode' is the state on/off set by thermostat, 'summersetmode' is the setting winter/summer/auto.

**Comment by tp1de** [comment]
Yes it's working now 👍
