### ISSUE TITLE
Rounding Error MQTT

### ISSUE THREAD

**Issue by ajvdw** [emsesp/EMS-ESP32#736]
Similar to rounding problem in #704, the rounding problem has moved to the magic number x.95 it is rounded to  x.1 ....

![Schermafbeelding 2022-11-09 om 07 53 34](https://user-images.githubusercontent.com/19387825/200761134-ee482fb5-e461-4852-9578-d2df506d8d69.png)

Maybe the rounding of mqtt values should be done by the receiving party.

**Comment by MichaelDvP** [comment]
Are you sure that this is mqtt only and a rounding error? I can not imaging a mathematical function to round from 19.95 to 19.1.

**Comment by ajvdw** [comment]
19.95 -> 19.095 -> 19.1 ?
