### ISSUE TITLE
Compressor Activity is empty during defrost run

### ISSUE THREAD

**Issue by HansRemmerswaal** [emsesp/EMS-ESP32#748]
The compressor activity normally has the values none, heating, hot water, (and I guess cooling).
But I start to see examples where the compressor activity is empty. When I check it looks like it's always at the same time that there is a defrost run. For 2 min my circulation pump speed is becoming 100% and I see the temperature dropping.

Is this value retrieved from the EMS bus, so a software issue in the firmware of my Nefit heat pump? Or is this a values determined in the EMS-ESP32 and needs to be reported as an issue?

![image](https://user-images.githubusercontent.com/116959990/201850901-173d4d91-3bee-4627-9a3d-2f52a3a606f5.png)

![Capture](https://user-images.githubusercontent.com/116959990/201850240-c82dc87a-f404-465a-a59b-7732f8931c64.JPG)

Devices I use:
BBQKees Gateway E32 with firmware 3.5
Nefit Eviline A/W Split 7.0 E-S

**Comment by MichaelDvP** [comment]
I think this is a 6th option in hpactivity. If it happens again try in terminal `read 8 48D` or set in web system/log to all, wait until message 48D is received, save the log, post it here.
You can also test https://github.com/MichaelDvP/EMS-ESP32/releases/tag/latest, there i have added a option to hpactivity (5=noforst), but if the value goes to 6, 7, .. you still get empty text.

**Comment by HansRemmerswaal** [comment]
I have set in web system/log to all. Will post the log as soon as I see the issue again.

**Comment by HansRemmerswaal** [comment]
That system log is not very big, only +/- 200 lines. So I need to react within minutes when it happens...? I put the buffer size to max.

**Comment by MichaelDvP** [comment]
As long as you leave the log page open the log is only limited by the memory the browser can allocate. Buffer is emsesp internal and only used if you switch to a different emsesp-page, this is limited to max. 100 lines.
But it's easier to use syslog or telnet with logging to file (like putty) and in telnet commands `set timeout 0` and `watch 8 48d`
And/or check with my lates commit metioned above if your compressor activity log shows empty or "defrost".

**Comment by HansRemmerswaal** [comment]
Yesterday I have installed v3.5.0b9, today I had the issue again. See screenshots. So the latest development version didn't solve the problem.

Since I installed the v3.5.0b9 my initial language is each time PL, but ok that is easy to change to EN each time. An anyhow I'm using Home Assistent at the end to read all the data. More problematic is that when I click on the system log button that my screen becomes completely empty. That was not the case before. I tried with Chrome and Edge and both show the same. 

So I was not able to capture the log file.

I'm now installing Putty and will try your alternative log solution.

The issue with viewing the log file using EMS-ESP, any idea what that can be? My previous installed version was 3.50.b7 (last screenshot).

![image](https://user-images.githubusercontent.com/116959990/202093960-cd0aee14-e45d-4b93-9340-3d1b25182f1d.png)

![image](https://user-images.githubusercontent.com/116959990/202094044-bef8dfef-e947-4538-9a04-4c2d0362fb4c.png)

![image](https://user-images.githubusercontent.com/116959990/202094654-bf9b9215-90f7-4fad-85b1-2e722f887d22.png)

![image](https://user-images.githubusercontent.com/116959990/202094786-ebe9ff50-670f-4ccc-982c-0aaf76aa2a87.png)

![image](https://user-images.githubusercontent.com/116959990/202095120-11bbe3c0-643b-4dc0-9b92-37370f9c2232.png)

![image](https://user-images.githubusercontent.com/116959990/202096619-0efc7e72-0d7d-4d0b-aefd-fbb31b8d5d9f.png)

**Comment by MichaelDvP** [comment]
> Yesterday I have installed v3.5.0b9, today I had the issue again

From my link or from here?
> Since I installed the v3.5.0b9 my initial language is each time PL, but ok that is easy to change to EN each time. 

Yes, there were some discussions about that. Setting the base to PL saves a bit memory.
> More problematic is that when I click on the system log button that my screen becomes completely empty

That's strange, could you please go to help page, download the support info and attach it here.

**Comment by HansRemmerswaal** [comment]
Not sure if the support info is useful... it's empty.

Let me download v3.5.0b9 again via your link and install. 
https://github.com/MichaelDvP/EMS-ESP32/releases/tag/latest

[emsesp_info.txt](https://github.com/emsesp/EMS-ESP32/files/10019015/emsesp_info.txt)

**Comment by HansRemmerswaal** [comment]
after installing the latest v3.5.0b9 I was able to get a more meaningfull support file
[emsesp_info (2).txt](https://github.com/emsesp/EMS-ESP32/files/10019088/emsesp_info.2.txt)

**Comment by MichaelDvP** [comment]
Thanks. 
The free heap is a bit low, this could make some problems, like the empty info.
Please set system log buffer to lowest setting (25) and disable OTA, this saves some ram.
(if log-page does not load, restart em-esp and access it before buffer is filled. Also after reducing buffer a restart help to free the memory)
The E32 need some ram for the interface, with wifi enabled it is a bit more.

**Comment by HansRemmerswaal** [comment]
I read you message to late and did already a factory reset. So I took the long way but at the end the result is the same, buffer is reduced and data is displayed again. Maybe an idea to limited the size of the log file in case there is not enough memory anymore for the basic functions.

Your latest build is installed, putty is running with telnet commands set timeout 0 and watch 8 48d.
So waiting now till it happens again, typically in the morning when it's cold.
I keep you updated.

**Comment by HansRemmerswaal** [comment]
It happend again, it looks like a defrost to me. I hope you can find the reason the the log.

[putty3.txt](https://github.com/emsesp/EMS-ESP32/files/10028590/putty3.txt)

![Schermafbeelding 2022-11-17 072735](https://user-images.githubusercontent.com/116959990/202372691-3a386275-6bf0-4c89-b363-9175db20c728.jpg)

![Schermafbeelding 2022-11-17 073129](https://user-images.githubusercontent.com/116959990/202373266-1b8a32ca-8fa5-4277-a0a4-559c4237cc1f.jpg)

**Comment by MichaelDvP** [comment]
Thanks, yes the activity state goes to 6, i'll name state 5 to `unknown`. Can you check your hp-manual if there is another state? Maybe disinfecting? I'll update my github.

**Comment by HansRemmerswaal** [comment]
> Can you check your hp-manual if there is another state? Maybe disinfecting?

Sorry, what do you mean? Where do I need to check?
Disinfecting is Saturday at 12:00. Currently that is shown as "hot water"

**Comment by HansRemmerswaal** [comment]
There is a "pool" option. The heatpump can be used to heat a swimming pool. Maybe that is 5?

**Comment by HansRemmerswaal** [comment]
I do not have a pool, but maybe this is related to that compressor status 5.

![Capture](https://user-images.githubusercontent.com/116959990/202398807-108c64b9-4da7-449b-a3c5-00bdec0d57fb.JPG)

**Comment by MichaelDvP** [comment]
Pool is already in as option 4 We have now as actions:
0: none, 1:heating, 2:cooling, 3:hot_water, 4:pool, 5:unknown, 6:defrost

**Comment by HansRemmerswaal** [comment]
It's working 👍 
Thanks for making the software everyday a bit better!

![Annotation 2022-11-18 070304](https://user-images.githubusercontent.com/116959990/202632198-e8301cfe-5a98-41e0-93f3-70cf0513bb47.png)
