### ISSUE TITLE
SO Bus for IN-Z61

### ISSUE THREAD

**Issue by stmb-100** [emsesp/EMS-ESP32#75]
Could it be possible to implement an "S0 bus" on 1 or 2 free pins, e.g. for the gas meter pulse pick-up IN-Z61. It could be implemented in a similar way to ArduCounter.

![IN-Z61-1](https://user-images.githubusercontent.com/54959405/122000167-b0413880-cdae-11eb-961c-07a757308829.JPG)

**Comment by bbqkees** [comment]
I think it's easier to just add a second ESP board near the meter with Tasmota, ESPEasy etc.
In most houses the gas boiler is far away from the actual meter so I don't think a lot of people can use it this way.

**Comment by SpaceTeddy** [comment]
I use a Tasmota device to get the gas meter counter. works great.

**Comment by proddy** [comment]
I think an external method would be the easiest
