### ISSUE TITLE
Add units of measurement to translations

### ISSUE THREAD

**Issue by tp1de** [emsesp/EMS-ESP32#752]
UOM's for times are not translated:  minutes, hours and days.
I think it makes sence to add them as well to translations.

**Comment by MichaelDvP** [comment]
According to this comment:
https://github.com/emsesp/EMS-ESP32/blob/c76b4b9ede8ba28a84a55177c390b767ca393619/src/locale_common.h#L197-L198
translation is not compatible with HA.
