### ISSUE TITLE
Please add heat pump device Buderus WLW196i

### ISSUE THREAD

**Issue by jarekb76** [emsesp/EMS-ESP32#767]
Hello,
I've got heat pump as in topic but in dashboard is not listed. Currently is as boiler "Enviline/Compress 6000AW/Hybrid 7000iAW/SupraEco/Geo 5xx"

[emsesp_info.txt](https://github.com/emsesp/EMS-ESP32/files/10085437/emsesp_info.txt)

**Comment by MichaelDvP** [comment]
I can add it, but it's simply the name displayed for product-id 172.
There will be no other functions.
