### ISSUE TITLE
BBQKees Gateway E32 Restarting unregularly and resetting configuration

### ISSUE THREAD

**Issue by Poni01** [emsesp/EMS-ESP32#771]
my BBQKees Gateway E32 restarting after a view Days without any reason. Then my personal Boolean Format are gone and the "preset" formats "On/Off" are there for "Dashboard" and "API".
Happend this morning and 5 Days ago.
I only recognize it when, i didnt see any values in my Loxone. Because i set the Boolean Value in the privat Settings in the ESP Menu to 1/0 in Both the Dashboard and API Field so that i can easy reat it in Loxone.

I downloaded the system Details:
[emsesp_info.txt](https://github.com/emsesp/EMS-ESP32/files/10098192/emsesp_info.txt)

And the "api/System" info:

{

  "System Status": {

    "version": "3.4.2",

    "uptime": "000+08:14:33.436",

    "freemem": 109,

    "reset reason": "Software reset CPU / Software reset CPU"

  },

  "Network Status": {

    "connection": "Ethernet",

    "hostname": "ems-esp",

    "MAC": "0C:DC:7E:5D:89:23",

    "IPv4 address": "192.168.2.210/255.255.255.0",

    "IPv4 gateway": "192.168.2.1",

    "IPv4 nameserver": "192.168.2.1",

    "phy type": 1,

    "eth power": 16,

    "eth phy addr": 1,

    "eth clock mode": 0,

    "static ip config": false,

    "enable IPv6": false,

    "low bandwidth": false,

    "disable sleep": false,

    "AP provision mode": "disconnected",

    "AP security": "wpa2",

    "AP ssid": "ems-esp"

  },

  "NTP Status": {

    "network time": "disconnected",

    "enabled": false,

    "server": "time.google.com",

    "tz label": "Europe/Amsterdam"

  },

  "OTA Status": {

    "enabled": true,

    "port": 8266

  },

  "MQTT Status": {

    "MQTT status": "disconnected",

    "enabled": false,

    "client_id": "ems-esp",

    "keep alive": 60,

    "clean session": false,

    "base": "ems-esp",

    "discovery prefix": "homeassistant",

    "nested format": 1,

    "ha enabled": false,

    "mqtt qos": 0,

    "mqtt retain": false,

    "publish time boiler": 10,

    "publish time thermostat": 10,

    "publish time solar": 10,

    "publish time mixer": 10,

    "publish time other": 10,

    "publish time sensor": 10,

    "publish single": false,

    "publish2command": false,

    "send response": false

  },

  "Syslog Status": {

    "enabled": false

  },

  "Sensor Status": {

    "temperature sensors": 0,

    "temperature sensor reads": 0,

    "temperature sensor fails": 0,

    "analog sensors": 0,

    "analog sensor reads": 0,

    "analog sensor fails": 0

  },

  "API Status": {

    "API calls": 2481,

    "API fails": 3

  },

  "Bus Status": {

    "bus status": "connected",

    "bus protocol": "HT3",

    "bus telegrams received (rx)": 44946,

    "bus reads (tx)": 2755,

    "bus writes (tx)": 0,

    "bus incomplete telegrams": 0,

    "bus reads failed": 0,

    "bus writes failed": 0,

    "bus rx line quality": 100,

    "bus tx line quality": 100

  },

  "Settings": {

    "board profile": "E32",

    "tx mode": 2,

    "ems bus id": 11,

    "shower timer": false,

    "shower alert": false,

    "rx gpio": 5,

    "tx gpio": 17,

    "dallas gpio": 4,

    "pbutton gpio": 33,

    "led gpio": 2,

    "hide led": false,

    "notoken api": false,

    "readonly mode": false,

    "fahrenheit": false,

    "dallas parasite": false,

    "bool format": 6,

    "bool dashboard": 5,

    "enum format": 1,

    "analog enabled": true,

    "telnet enabled": true

  },

  "Devices": [

    {

      "type": "Boiler",

      "name": "Condens 2500/Logamax/Logomatic/Cerapur Top/Greenstar/Generic HT3",

      "device id": "0x08",

      "product id": 95,

      "version": "20.03",

      "entities": 61,

      "handlers received": "0x10 0x11 0x15 0x1C 0x18 0x19 0x34",

      "handlers fetched": "0x14 0x16 0x33",

      "handlers pending": "0xBF 0xC2 0x1A 0x35 0x26 0x2A",

      "handlers ignored": "0x05"

    },

    {

      "type": "Thermostat",

      "name": "RC300/RC310/Moduline 3000/1010H/CW400/Sense II",

      "device id": "0x10",

      "product id": 158,

      "version": "18.06",

      "entities": 76,

      "handlers received": "0x06 0xA2 0x02BB 0x02BC 0x02BD 0x02BE 0x02BF 0x02C0 0x031D 0x0267",

      "handlers fetched": "0x02A5 0x02B9 0x02AF 0x029B 0x02A6 0x02BA 0x02B0 0x029C 0x02CE 0x02F5 0x031B 0x023A 0x0240",

      "handlers pending": "0xA3 0x12 0x0471 0x0472 0x02A7 0x02B1 0x029D 0x0473 0x02A8 0x02B2 0x029E 0x0474 0x02A9 0x02B3 0x029F 0x0475 0x02AA 0x02B4 0x02A0 0x0476 0x02AB 0x02B5 0x02A1 0x0477 0x02AC 0x02B6 0x02A2 0x0478 0x02CC 0x02D0 0x02D2 0x031E",

      "handlers ignored": "0x02E1 0x02E2 0x02EB 0x02EC 0x35 0xBF"

    },

    {

      "type": "Mixer",

      "name": "MM200",

      "device id": "0x20",

      "product id": 161,

      "version": "29.05",

      "entities": 3,

      "handlers received": "0x02D7",

      "handlers ignored": "0x1E 0x1A 0x0255 0xBF"

    },

    {

      "type": "Mixer",

      "name": "MM200",

      "device id": "0x21",

      "product id": 161,

      "version": "29.05",

      "entities": 4,

      "handlers received": "0x02D8",

      "handlers ignored": "0x1A 0x0255 0xBF"

    },

    {

      "type": "Controller",

      "name": "HT3",

      "device id": "0x09",

      "product id": 95,

      "version": "20.03",

      "entities": 0

    }

  ]

}

**Comment by proddy** [comment]
I see this is an older version of the firmware. Please upgrade to the latest 3.4.4 (https://github.com/emsesp/EMS-ESP32/releases/tag/v3.4.4) which has the fix for the configuration.

But better still, since you've lost all the config, is to go straight to v3.5. Use the new EMS-ESP flasher from https://github.com/emsesp/EMS-ESP-Flasher and get the firmware from https://github.com/emsesp/EMS-ESP32/releases/tag/latest
