### ISSUE TITLE
minor UI bugs with decimal values (adding / editing analog sensor dialog)

### ISSUE THREAD

**Issue by lmbd** [emsesp/EMS-ESP32#774]
**Bug description**
While playing around with the analog sensor dialog I've identified 2 minor UI bugs
1. hint texts for start value and factor are misleading as they're stating that only integers are valid (which is not true)
2. it's not possible to enter decimal values with an leading 0 after decimal point (only possible with a workaround - see recording)

**Screenshots**

https://user-images.githubusercontent.com/3472161/204154951-e346bc48-c187-4b6a-be0b-72b21b4aa99e.mov

<img width="634" alt="Screenshot 2022-11-27 at 20 01 27" src="https://user-images.githubusercontent.com/3472161/204154954-921bf4e1-c87f-408e-8ab5-fd902a154218.png">

**Device information**
[emsesp_settings (1).txt](https://github.com/emsesp/EMS-ESP32/files/10099004/emsesp_settings.1.txt)

**Comment by proddy** [comment]
very cool the video! As they say,  a picture is a thousand words. We can update the hint text. The leading zero we need to fix. Both @MichaelDvP and myself have tried different techniques but it remains challenging.

**Comment by MichaelDvP** [comment]
We had this issue in: https://github.com/emsesp/EMS-ESP32/pull/755#issuecomment-1320900326
It depends on browser and the "step" setting of input field.

**Comment by lmbd** [comment]
I would suggest to support decimals as there are gasmeters which are sending an impulse for each 0,01 m^3
<img width="1487" alt="Screenshot 2022-11-27 at 21 11 21" src="https://user-images.githubusercontent.com/3472161/204157820-208fbb31-5775-49b2-94e6-b88f96ff352e.png">

<img width="1586" alt="Screenshot 2022-11-27 at 21 17 23" src="https://user-images.githubusercontent.com/3472161/204157823-23a77c2a-b358-45cc-bea3-718a2bd7bfa2.png">

**Comment by MichaelDvP** [comment]
Decimals are supported, value is float, only the browsers handles the input different and give warning if input does not match the step setting. We can remove the up/down arrows and step setting to solve this.

**Comment by MichaelDvP** [comment]
Ok, removing input props seems to work, please try https://github.com/MichaelDvP/EMS-ESP32/releases
