### ISSUE TITLE
Dutch translation error: minuuten instead of minuten

### ISSUE THREAD

**Issue by joostvdl** [emsesp/EMS-ESP32#787]
**Bug description**
In the GUI the term _Minutes_ is translated in _Minuuten_. This should be _Minuten_

**Steps to reproduce**
Just open the GUI in the dutch language

**Expected behavior**
Repair translation

**Screenshots**
n/a

**Device information**
{
  "System Info": {
    "version": "3.5.0b10",
    "platform": "ESP32",
    "uptime": "000+00:09:12.891",
    "freemem": 112,
    "maxalloc": 61,
    "free_app": 73,
    "reset reason": "Software reset CPU / Software reset CPU"
  },

**Additional context**
n/a

**Comment by proddy** [comment]
thanks! Will be fixed in the next PR

**Comment by joostvdl** [comment]
Addition: Same goes for _uuren_ instead of _uren_

**Comment by proddy** [comment]
fixed in b11
