### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by thegitarist** [emsesp/EMS-ESP32#795]
Hello,

I would like to add control buttons to my grafana dashboard, that triggers actions via open api access. Currently this fails due to CORS limitations.

Would be great having this feature.

THNX & BR

**Comment by MichaelDvP** [comment]
esp8266 have a [compile-option](https://github.com/rjwats/esp8266-react/blob/b9b9c1b2149b3d4472125c5684045f434df66d42/platformio.ini#L16-L17) to enable CORS. I've tried to use the same scheme, but add as a network setting. Please check if this works for you:
https://github.com/MichaelDvP/EMS-ESP32/releases/tag/latest
