### ISSUE TITLE
v3.5.0b11:  board profile jumps back to default

### ISSUE THREAD

**Issue by g6094199** [emsesp/EMS-ESP32#806]
running a fresh installed v3.5.0b11 on a esp32-wrooom powered board. 
when i try to set the "board profile" to custon and hit save, the "board profile" jumps back to the default (BBQ Kees gateway....)

**Comment by MichaelDvP** [comment]
@proddy : i've fixed direct to dev branch, it's only a single line deleted.

**Comment by proddy** [comment]
try b12
