### ISSUE TITLE
Webinterface shows wrong values

### ISSUE THREAD

**Issue by MaartenRs** [emsesp/EMS-ESP32#820]
Webinterdace shows values of 21.474.836 kWh, while Home Assistent shows -1.

EMS-ESP Version
v3.5.0b12

Apparaat (Platform / SDK)
ESP32 / v4.4.2

<html>
<body>

TYPE | DESCRIPTION | ENTITIES |  
-- | -- | -- | --
  | Boiler | Enviline/Compress 6000AW/Hybrid 3000-7000iAW/SupraEco/Geo 5xx/WLW196i | 122 |  
  | Thermostat | RC300/RC310/Moduline 3000/1010H/CW400/Sense II/HPC410 | 48 |  
  | Thermostat | RC100H | 4 |  
  | Sensors | Attached EMS-ESP Sensors | 0

</body>
</html>

<html>
<body>

cooling control starts | 29 |  
-- | -- | --
dhw control starts2 | 21.474.836 |  
pool control starts | 21.474.836 |  
total energy consumption | 1.946 kWh |  
total energy consumption compressor | 1.947 kWh |  
energy consumption compressor heating | 1.898 kWh |  
energy consumption compressor dhw | 21.474.836 kWh |  
energy consumption compressor cooling | 22 kWh |  
energy consumption compressor pool | 21.474.836 kWh |  
total auxiliary electrical heater energy consumption | 21.474.836 kWh |  
auxiliary electrical heater energy consumption heating | 21.474.836 kWh |  
auxiliary electrical heater energy consumption dhw | 21.474.836 kWh |  
auxiliary electrical heater energy consumption pool | 21.474.836 kWh |  
total energy supplied | 7.394 kWh |  
total energy supplied heating | 7.357 kWh |  
total energy warm supplied dhw | 21.474.836 kWh |  
total energy supplied cooling | 36 kWh |  
total energy supplied pool | 21.474.836 kWh |  
compressor power output | 3,5 kW |  
 

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by MichaelDvP** [comment]
Confusion in browser cache? Shut down and restart browser and (to be sure) also ems-esp.

**Comment by MaartenRs** [comment]
Restart PC, empty browser cache and restart ems-esp.
Error is still there. If I connect with another browser (Firefox), the result is the same.

**Comment by heennkkee** [comment]
Do you expect these values to be read? I have similar values being sent out, like for instance 

total energy supplied pool: 21.474.836 kWh

and the exported value is -1 (it was  21.474.836 when running 3.5.0b4).

I assume this is some type of default value for when a device "could have" this value (so the EMS-ESP32 detects the value) but the value has never been set in the device. I for instance do not have any pool that my heater supplies heat to, hence that value is "empty" (or defaulted to 21.474.836). I have similar for cooling, solar systems and some more.

**Comment by MichaelDvP** [comment]
Please test https://github.com/MichaelDvP/EMS-ESP32/releases and give feedback if it is fixed or not.

**Comment by pswid** [comment]
I'm experiencing similar(?) issue. In my case `uptimecontrol` and `uptimecompheating` are not displayed at all:

<img width="484" alt="image" src="https://user-images.githubusercontent.com/78219494/208979063-6b3e07b4-4e6e-42c4-a823-336cd7ca57ca.png">

v3.5.0b11 was OK:
<img width="431" alt="image" src="https://user-images.githubusercontent.com/78219494/208979254-9b2c2654-43d8-485e-a8a8-34f00e32165f.png">

Your b12 compilation doesn't solve the problem.

**Comment by MichaelDvP** [comment]
> Your b12 compilation doesn't solve the problem.

Thanks, now i understand this strange value, it's an artifact from float conversion.
I'll update my testbuild. Please check.

**Comment by MaartenRs** [comment]
Hi Michael,

 

This version solved the problem.

However, if I double click “boiler” it shows the four entities of the Thermostat RC100H. Double clicking Thermostat RC300.. shows the 116 entities if the Boiler and double clicking Thermostat RC100H shows the 48 entities of Thermostat RC300..



 

Furthermore the interface with Home Assistant is not working correctly anymore. Enitites are not found or not avaialbel.



 

Best regards,

 

Maarten Reintjes

 

Van: MichaelDvP ***@***.***> 
Verzonden: donderdag 22 december 2022 09:00
Aan: emsesp/EMS-ESP32 ***@***.***>
CC: MaartenRs ***@***.***>; Author ***@***.***>
Onderwerp: Re: [emsesp/EMS-ESP32] Webinterface shows wrong values (Issue #820)

 

Your b12 compilation doesn't solve the problem.

Thanks, now i understand this strange value, it's an artifact from float conversion.
I'll update my testbuild. Please check.

**Comment by MichaelDvP** [comment]
Nice finding, @proddy we have a large memory leak when doubleclick on a dashboard line. 

@MaartenRs reboot emsesp and only use single click and wait for data. 
The Homeassistant entities has to be configured in mqtt, use the v3.4.4 option to keep compatible to old version.

**Comment by MaartenRs** [comment]
I solved the error "Problem loading" by power off the gateway restart didn't solve the issue.

Single click works fine.

My version of MQTT is: 
Mosquitto broker
Current version: 6.1.3

I have restarted HA, but still Enitites are not found or not available.
![image](https://user-images.githubusercontent.com/121044285/209151600-7e7b4cb4-6768-4caf-a135-18f527cf8af0.png)

**Comment by MichaelDvP** [comment]
![grafik](https://user-images.githubusercontent.com/59284019/209152901-6f28bd4b-c17a-49e2-811a-73dae242fab3.png)

**Comment by pswid** [comment]
Small update. I'm already using "long name (v.3.4)" option. Regarding number of entities. I counted them and value over 100 is correct in B12/B13 (for my system). So indeed more than 20 new entities was added since B11. Nice!

**Comment by MichaelDvP** [comment]
The bad side of more entities is ram and the 507 on dashboard/customization, see #823

**Comment by MaartenRs** [comment]
Unfortenatly I don't see (anymore) MQTT at the left of my screen.
If I go to settings, I can't find this option.
![image](https://user-images.githubusercontent.com/121044285/209167294-10deb296-2aeb-42b4-9972-35ff40cc658b.png)

**Comment by MichaelDvP** [comment]
@MaartenRs : You are searching in Homeassistant., this is EMS-ESP. Open EMS-ESP webpage and set the options.

**Comment by MaartenRs** [comment]
Stupid me 😡
After having set this 
![image](https://user-images.githubusercontent.com/121044285/209177160-e68ef3f8-11ff-4587-b8dc-f513354f26f6.png)

I get this error message, even after re-booting the gatway (power off).
![image](https://user-images.githubusercontent.com/121044285/209177037-4c1c68db-69a3-4b49-950b-9767df2883a4.png)

**Comment by MichaelDvP** [comment]
see #823

**Comment by MichaelDvP** [comment]
@pswid Could you please test with https://github.com/MichaelDvP/EMS-ESP32/releases
set a log to debug and navigate to dashboard boiler and Settings/Customization Boiler
The log (please attach) should show the buffer used for the display. I've reduced the buffer to 16k to avoid 507, if it is to small a few entities at the end will be skipped.

**Comment by pswid** [comment]
Indeed the buffer is too small and the customization page is truncated (~50 entities from 104 total is missing!). Furthermore if I try to expand Boiler at dashboard only empty/white page is displayed. Log attached. It says `Customization buffer used: 7639`

![image](https://user-images.githubusercontent.com/78219494/209345502-91935a76-77f8-4788-b060-88beb7751a21.png)
![image](https://user-images.githubusercontent.com/78219494/209347291-a82a4115-607b-4d0d-ba7d-f8801334b1f5.png)

[log.txt](https://github.com/emsesp/EMS-ESP32/files/10295384/log.txt)

**Comment by MichaelDvP** [comment]
Sad, so the size measurement is packed json, but the buffer have to hold unpacked json. I'll set back to 20k.

**Comment by MichaelDvP** [comment]
Back to OP: 
@MaartenRs Is the wrong value 21.474.836 solved in latest builds?
Can this be closed or i something to do?

**Comment by MaartenRs** [comment]
Yes, you can close this.

Thanks for your help.

 

Van: MichaelDvP ***@***.***> 
Verzonden: dinsdag 27 december 2022 18:36
Aan: emsesp/EMS-ESP32 ***@***.***>
CC: MaartenRs ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [emsesp/EMS-ESP32] Webinterface shows wrong values (Issue #820)

 

Back to OP:
@MaartenRs <https://github.com/MaartenRs>  Is the wrong value 21.474.836 solved in latest builds?
Can this be closed or i something to do?
