### ISSUE TITLE
Create table of all EMS-ESP entities, by device, shortname/fullname and characteristics

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#828]
> Thanks, but how can i find the mapping for the version EMS-ESP-3_5_0b10-ESP32 ?

What do you need exactly? The mapping of the old names to the new names?

I'll create a new GH issue to maintain a table of the shortname, fullname etc. We've done a few passes at this but its not consistent

_Originally posted by @proddy in https://github.com/emsesp/EMS-ESP32/issues/804#issuecomment-1363723789_

**Comment by proddy** [comment]
My first idea for this is to do it in the code (test.cpp) which will simulate adding all devices and then printing out their details (similar to the API call for each entity).

**Comment by sciurius** [comment]
I have the entities for my boiler+thermostat in an md file that I can easily transform into any form you like.

**Comment by zibous** [comment]
I have the problem that I have to adjust my automation, scripts and graphics when I use the new version b12. So I'm looking for the mappings so I know which names to change.

|Device            |EMS-ESP-3_5_0b10-ESP32                                     |single instance b12                       |single instance  v3.4|Multi instance b12|FIELD6|FIELD7|
|------------------|-----------------------------------------------------------|------------------------------------------|---------------------|------------------|------|------|
|EMS-ESP           |sensor.system_ems_bus                                      |sensor.system_bus_status                  |                     |                  |      |      |
|                  |sensor.system_free_memory                                  |sensor.system_freemem                     |                     |                  |      |      |
|                  |sensor.system_mqtt_fails                                   |sensor.system_mqttfails                   |                     |                  |      |      |
|                  |binary_sensor.system_ntp_status                            |binary_sensor.system_ntp_status           |                     |                  |      |      |
|                  |sensor.system_rx_fails                                     |sensor.system_rxfails                     |                     |                  |      |      |
|                  |sensor.system_rx_received                                  |sensor.system_rxreceived                  |                     |                  |      |      |
|                  |entity: binary_sensor.ems_esp_status                       |entity: binary_sensor.system_status       |                     |                  |      |      |
|                  |sensor.system_tx_fails                                     |sensor.system_txfails                     |                     |                  |      |      |
|                  |sensor.system_tx_reads                                     |sensor.system_txreads                     |                     |                  |      |      |
|                  |sensor.system_tx_writes                                    |sensor.system_txwrites                    |                     |                  |      |      |
|                  |sensor.system_uptime                                       |sensor.system_uptime                      |                     |                  |      |      |
|                  |sensor.system_uptime_sec                                   |sensor.system_uptime_sec                  |                     |                  |      |      |
|                  |sensor.system_wifi_rssi                                    |sensor.system_rssi                        |                     |                  |      |      |
|                  |sensor.system_wifi_strength                                |sensor.system_wifistrength                |                     |                  |      |      |
|                  |                                                           |                                          |                     |                  |      |      |
|                  |                                                           |                                          |                     |                  |      |      |
|EMS-ESP Boiler    |sensor.boiler_current_flow_temperature                     |sensor.boiler_curflowtemp                 |                     |                  |      |      |
|                  |sensor.boiler_total_uba_operating_time                     |sensor.boiler_ubauptime                   |                     |                  |      |      |
|                  |sensor.boiler_outside_temperature                          |sensor.boiler_outdoortemp                 |                     |                  |      |      |
|                  |sensor.boiler_total_burner_operating_time                  |sensor.boiler_burnworkmin                 |                     |                  |      |      |
|                  |sensor.boiler_burner_starts                                |sensor.boiler_burnstarts                  |                     |                  |      |      |
|                  |sensor.boiler_burner_starts_heating                        |sensor.boiler_heatstarts                  |                     |                  |      |      |
|                  |sensor.boiler_burner_stage_2_operating_time                |sensor.boiler_burn2workmin                |                     |                  |      |      |
|                  |sensor.boiler_burner_current_power                         |sensor.boiler_curburnpow                  |                     |                  |      |      |
|                  |sensor.boiler_flame_current                                |sensor.boiler_flamecurr                   |                     |                  |      |      |
|                  |binary_sensor.boiler_gas                                   |binary_sensor.boiler_burngas              |                     |                  |      |      |
|                  |binary_sensor.boiler_gas_stage_2                           |binary_sensor.boiler_burngas2             |                     |                  |      |      |
|                  |binary_sensor.boiler_fan                                   |binary_sensor.boiler_fanwork              |                     |                  |      |      |
|                  |binary_sensor.boiler_heating_active                        |binary_sensor.boiler_heatingactive        |                     |                  |      |      |
|                  |sensor.boiler_total_heat_operating_time                    |sensor.boiler_heatworkmin                 |                     |                  |      |      |
|                  |binary_sensor.boiler_heating_pump                          |binary_sensor.boiler_heatingpump          |                     |                  |      |      |
|                  |sensor.boiler_heating_pump_modulation                      |sensor.boiler_heatingpumpmod              |                     |                  |      |      |
|                  |sensor.boiler_last_error_code                              |sensor.boiler_lastcode                    |                     |                  |      |      |
|                  |sensor.boiler_service_code                                 |sensor.boiler_servicecode                 |                     |                  |      |      |
|                  |sensor.boiler_service_code_number                          |sensor.boiler_servicecodenumber           |                     |                  |      |      |
|                  |binary_sensor.boiler_dhw_3_way_valve_active                |binary_sensor.boiler_ww3wayvalve          |                     |                  |      |      |
|                  |binary_sensor.boiler_dhw_active                            |binary_sensor.boiler_wwactive             |                     |                  |      |      |
|                  |sensor.boiler_dhw_active_time                              |sensor.boiler_wwworkm                     |                     |                  |      |      |
|                  |sensor.boiler_dhw_current_extern_temperature               |sensor.boiler_wwcurtemp2                  |                     |                  |      |      |
|                  |sensor.boiler_dhw_current_intern_temperature               |sensor.boiler_wwcurtemp                   |                     |                  |      |      |
|                  |sensor.boiler_dhw_current_tap_water_flow                   |sensor.boiler_wwcurflow                   |                     |                  |      |      |
|                  |sensor.boiler_dhw_starts                                   |sensor.boiler_wwstarts                    |                     |                  |      |      |
|                  |sensor.boiler_dhw_storage_extern_temperature               |sensor.boiler_wwstoragetemp2              |                     |                  |      |      |
|                  |binary_sensor.boiler_dhw_charging                          |binary_sensor.boiler_wwcharging           |                     |                  |      |      |
|                  |binary_sensor.boiler_dhw_recharging                        |binary_sensor.boiler_wwrecharging         |                     |                  |      |      |
|                  |sensor.boiler_dhw_set_temperature                          |sensor.boiler_wwsettemp                   |                     |                  |      |      |
|                  |sensor.boiler_dhw_charging_type                            |sensor.boiler_wwchargetype                |                     |                  |      |      |
|                  |binary_sensor.boiler_dhw_temperature_ok                    |binary_sensor.boiler_wwtempok             |                     |                  |      |      |
|                  |sensor.boiler_dhw_type                                     |sensor.boiler_wwtype                      |                     |                  |      |      |
|                  |binary_sensor.boiler_tapwater_active                       |binary_sensor.boiler_tapwateractive       |                     |                  |      |      |
|                  |sensor.boiler_next_maintenance_date                        |sensor.boiler_maintenancedate             |                     |                  |      |      |
|                  |sensor.boiler_maintenance_message                          |sensor.boiler_maintenancemessage          |                     |                  |      |      |
|                  |binary_sensor.boiler_ignition                              |binary_sensor.boiler_ignwork              |                     |                  |      |      |
|                  |binary_sensor.boiler_oil_preheating                        |binary_sensor.boiler_oilpreheat           |                     |                  |      |      |
|                  |number.boiler_burner_min_period                            |number.boiler_burnminperiod               |                     |                  |      |      |
|                  |number.boiler_hysteresis_off_temperature                   |number.boiler_boilhystoff                 |                     |                  |      |      |
|                  |number.boiler_hysteresis_stage_2_off_temperature           |number.boiler_boil2hystoff                |                     |                  |      |      |
|                  |number.boiler_hysteresis_on_temperature                    |number.boiler_boilhyston                  |                     |                  |      |      |
|                  |number.boiler_hysteresis_stage_2_on_temperature            |number.boiler_boil2hyston                 |                     |                  |      |      |
|                  |switch.boiler_heating_activated                            |switch.boiler_heatingactivated            |                     |                  |      |      |
|                  |number.boiler_heating_temperature                          |number.boiler_heatingtemp                 |                     |                  |      |      |
|                  |number.boiler_boiler_pump_max_power                        |number.boiler_pumpmodmax                  |                     |                  |      |      |
|                  |number.boiler_boiler_pump_min_power                        |number.boiler_pumpmodmin                  |                     |                  |      |      |
|                  |number.boiler_burner_max_power                             |number.boiler_burnmaxpower                |                     |                  |      |      |
|                  |number.boiler_burner_min_power                             |number.boiler_burnminpower                |                     |                  |      |      |
|                  |number.boiler_pump_delay                                   |number.boiler_pumpdelay                   |                     |                  |      |      |
|                  |number.boiler_burner_selected_max_power                    |number.boiler_selburnpow                  |                     |                  |      |      |
|                  |number.boiler_selected_flow_temperature                    |number.boiler_selflowtemp                 |                     |                  |      |      |
|                  |switch.boiler_dhw_activated                                |switch.boiler_wwactivated                 |                     |                  |      |      |
|                  |number.boiler_dhw_hysteresis_off_temperature               |number.boiler_wwhystoff                   |                     |                  |      |      |
|                  |number.boiler_dhw_disinfection_temperature                 |number.boiler_wwdisinfectiontemp          |                     |                  |      |      |
|                  |switch.boiler_dhw_disinfecting                             |switch.boiler_wwdisinfecting              |                     |                  |      |      |
|                  |switch.boiler_dhw_one_time_charging                        |switch.boiler_wwonetime                   |                     |                  |      |      |
|                  |number.boiler_dhw_hysteresis_on_temperature                |number.boiler_wwhyston                    |                     |                  |      |      |
|                  |number.boiler_dhw_selected_temperature                     |number.boiler_wwseltemp                   |                     |                  |      |      |
|                  |select.boiler_dhw_comfort                                  |select.boiler_wwcomfort                   |                     |                  |      |      |
|                  |number.boiler_dhw_max_power                                |number.boiler_wwmaxpower                  |                     |                  |      |      |
|                  |number.boiler_dhw_flow_temperature_offset                  |number.boiler_wwflowtempoffset            |                     |                  |      |      |
|                  |switch.boiler_dhw_circulation_active                       |switch.boiler_wwcirc                      |                     |                  |      |      |
|                  |switch.boiler_dhw_circulation_pump_available               |switch.boiler_wwcircpump                  |                     |                  |      |      |
|                  |select.boiler_dhw_circulation_pump_mode                    |select.boiler_wwcircmode                  |                     |                  |      |      |
|                  |number.boiler_time_to_next_maintenance                     |number.boiler_maintenancetime             |                     |                  |      |      |
|                  |select.boiler_maintenance_scheduled                        |select.boiler_maintenance                 |                     |                  |      |      |
|                  |                                                           |                                          |                     |                  |      |      |
|EMS-ESP Thermostat|switch.thermostat_damping_outdoor_temperature              |switch.thermostat_damping                 |                     |                  |      |      |
|                  |select.thermostat_building_type                            |select.thermostat_building                |                     |                  |      |      |
|                  |select.thermostat_hc1_reduce_mode                          |select.thermostat_hc1_reducemode          |                     |                  |      |      |
|                  |number.thermostat_hc1_off_reduce_switch_temperature        |number.thermostat_hc1_reducetemp          |                     |                  |      |      |
|                  |number.thermostat_hc1_design_temperature                   |number.thermostat_hc1_designtemp          |                     |                  |      |      |
|                  |number.thermostat_hc1_no_reduce_below_temperature          |number.thermostat_hc1_noreducetemp        |                     |                  |      |      |
|                  |number.thermostat_hc1_eco_temperature                      |number.thermostat_hc1_ecotemp             |                     |                  |      |      |
|                  |switch.thermostat_hc1_switch_on_optimization               |switch.thermostat_hc1_switchonoptimization|                     |                  |      |      |
|                  |select.thermostat_hc1_set_summer_mode                      |select.thermostat_hc1_summersetmode       |                     |                  |      |      |
|                  |select.thermostat_hc1_nofrost_mode                         |select.thermostat_hc1_nofrostmode         |                     |                  |      |      |
|                  |number.thermostat_hc1_nofrost_temperature                  |number.thermostat_hc1_nofrosttemp         |                     |                  |      |      |
|                  |select.thermostat_hc1_heating_type                         |select.thermostat_hc1_heatingtype         |                     |                  |      |      |
|                  |number.thermostat_hc1_comfort_temperature                  |number.thermostat_hc1_comforttemp         |                     |                  |      |      |
|                  |select.thermostat_hc1_control_mode                         |select.thermostat_hc1_controlmode         |                     |                  |      |      |
|                  |number.thermostat_hc1_manual_temperature                   |number.thermostat_hc1_manualtemp          |                     |                  |      |      |
|                  |number.thermostat_hc1_max_flow_temperature                 |number.thermostat_hc1_maxflowtemp         |                     |                  |      |      |
|                  |number.thermostat_hc1_min_flow_temperature                 |number.thermostat_hc1_minflowtemp         |                     |                  |      |      |
|                  |select.thermostat_hc1_mode                                 |select.thermostat_hc1_mode                |                     |                  |      |      |
|                  |select.thermostat_hc1_program                              |select.thermostat_hc1_program             |                     |                  |      |      |
|                  |number.thermostat_hc1_room_influence                       |number.thermostat_hc1_roominfluence       |                     |                  |      |      |
|                  |number.thermostat_hc1_room_influence_factor                |number.thermostat_hc1_roominflfactor      |                     |                  |      |      |
|                  |number.thermostat_hc1_fast_heatup                          |number.thermostat_hc1_fastheatup          |                     |                  |      |      |
|                  |number.thermostat_hc1_selected_room_temperature            |number.thermostat_hc1_seltemp             |                     |                  |      |      |
|                  |number.thermostat_hc1_summer_temperature                   |number.thermostat_hc1_summertemp          |                     |                  |      |      |
|                  |number.thermostat_hc1_offset_temperature                   |number.thermostat_hc1_offsettemp          |                     |                  |      |      |
|                  |number.thermostat_hc1_temporary_set_temperature_automode   |number.thermostat_hc1_tempautotemp        |                     |                  |      |      |
|                  |number.thermostat_hc1_temporary_set_temperature_from_remote|number.thermostat_hc1_remoteseltemp       |                     |                  |      |      |
|                  |number.thermostat_internal_temperature_offset              |number.thermostat_intoffset               |                     |                  |      |      |
|                  |number.thermostat_minimal_external_temperature             |number.thermostat_minexttemp              |                     |                  |      |      |
|                  |number.thermostat_dhw_disinfection_time                    |number.thermostat_wwdisinfecttime         |                     |                  |      |      |
|                  |select.thermostat_dhw_disinfection_day                     |select.thermostat_wwdisinfectday          |                     |                  |      |      |
|                  |switch.thermostat_dhw_disinfecting                         |switch.thermostat_wwdisinfecting          |                     |                  |      |      |
|                  |number.thermostat_dhw_charge_duration                      |number.thermostat_wwchargeduration        |                     |                  |      |      |
|                  |switch.thermostat_dhw_charge                               |switch.thermostat_wwcharge                |                     |                  |      |      |
|                  |select.thermostat_dhw_mode                                 |select.thermostat_wwmode                  |                     |                  |      |      |
|                  |number.thermostat_dhw_set_temperature                      |number.thermostat_wwsettemp               |                     |                  |      |      |
|                  |number.thermostat_dhw_set_low_temperature                  |number.thermostat_wwsettemplow            |                     |                  |      |      |
|                  |select.thermostat_dhw_circulation_pump_mode                |select.thermostat_wwcircmode              |                     |                  |      |      |
|                  |climate.thermostat_hc1                                     |climate.thermostat_hc1                    |                     |                  |      |      |
|                  |??                                                         |sensor.thermostat_datetime                |                     |                  |      |      |
|                  |??                                                         |sensor.thermostat_floordry                |                     |                  |      |      |
|                  |??                                                         |sensor.thermostat_floordrytemp            |                     |                  |      |      |
|                  |??                                                         |sensor.thermostat_dampedoutdoortemp       |                     |                  |      |      |
|                  |??                                                         |sensor.thermostat_hc1_curroominfl         |                     |                  |      |      |
|                  |??                                                         |sensor.thermostat_hc1_targetflowtemp      |                     |                  |      |      |
|                  |??                                                         |sensor.thermostat_hc1_modetype            |                     |                  |      |      |
|                  |??                                                         |sensor.thermostat_hc1_summermode          |                     |                  |      |      |
|                  |??                                                         |sensor.thermostat_wwextra1                |                     |                  |      |      |

**Comment by zibous** [comment]
@sciurius 
> I have the entities for my boiler+thermostat in an md file that I can easily transform into any form you like.
Where can if ind the md file ?

**Comment by MichaelDvP** [comment]
The customization page shows all registered short and fullnames, For what an extra list?
Or is this issue only HA related? But also HA discovery uses the names that are listed in customization.

**Comment by zibous** [comment]
> The customization page shows all registered short and fullnames, For what an extra list?
> Or is this issue only HA related? But also HA discovery uses the names that are listed in customization.

Because changing names will destroy all the statics data in Homeassistant, Automations base on the name do not work...

![Bildschirmfoto 2022-12-23 um 10 20 38](https://user-images.githubusercontent.com/30198737/209309191-d3059e20-3e31-45fd-a5bf-e01cec066b4d.png)

So i need the new names to fix this.

**Comment by sciurius** [comment]
@zibous 
[rename.zip](https://github.com/emsesp/EMS-ESP32/files/10293997/rename.zip)

**Comment by proddy** [comment]
> The customization page shows all registered short and fullnames, For what an extra list? Or is this issue only HA related? But also HA discovery uses the names that are listed in customization.

just to maintain a library of all entities for all devices and their details which we can add to the wiki. People ask what you can read and write and what all the entities mean.

**Comment by proddy** [comment]
> Because changing names will destroy all the statics data in Homeassistant, Automations base on the name do not work...
> 
> So i need the new names to fix this.

@zibous if you want to retain your history without using the DB script, just set the Entity ID Format back to the old v3.4 style in the MQTT settings

**Comment by proddy** [comment]
I did a rough implementation of this. How it works:

In the code, if compiled with the flag -DEMSESP_STANDALONE_DUMP it will automatically add a default value to an entity. Then a test script goes through all the known devices, adds them and dumps out the information to the Serial port. It's intended to be used once in standalone mode (i.e running on Linux) to create a file. A script basically calls it using shell command like `make clean; make ARGS=-DEMSESP_STANDALONE_DUMP; echo "test dump" | ./emsesp | python3 ./scripts/dump_entities.py > dump_entities.csv`

What is output is the device name, device type, shortname, fullname, type [(enum values) | (min/max)], uom, and the readable, writeable, visible flags. I could later if needed add the Home Assistant entity name. See the example attachments. The CSV file contains (at the time of build) around 3100 rows and can easily be sorted or filtered using Excel/Numbers etc.

I could add a GH action later for this so we always have the latest information on build.

[dump_entities.xlsx](https://github.com/emsesp/EMS-ESP32/files/10309352/dump_entities.xlsx)

[dump_entities.csv](https://github.com/emsesp/EMS-ESP32/files/10309351/dump_entities.csv)

**Comment by proddy** [comment]
I added the product_ID and HA entity ID for completeness

**Comment by MichaelDvP** [comment]
The thermostat hc specific entities are missing. Mixer shows hc entities but not wwc.

**Comment by proddy** [comment]
Oops, missed that. I'll add that.

I'm also looking at ways to show the CSV (or markdown) in a table in the Wiki so people can just look up the data

**Comment by proddy** [comment]
think I fixed it now.

[dump_entities.csv](https://github.com/emsesp/EMS-ESP32/files/10316520/dump_entities.csv)

**Comment by HansRemmerswaal** [comment]
If you have a spare moment.
You have added the HA entity ID (3.5 version), could you also add the HA entity ID (3.4 version)? That way it's easy to do a mass update in the HA database if someone wants to migrate from 3.4 to 3.5

**Comment by proddy** [comment]
> If you have a spare moment. You have added the HA entity ID (3.5 version), could you also add the HA entity ID (3.4 version)? That way it's easy to do a mass update in the HA database if someone wants to migrate from 3.4 to 3.5

sure.

**Comment by MichaelDvP** [comment]
> think I fixed it now.

Not complete, the common values are there, but the model specific are missing. It should be `HeatingCircuit(1,model);`

**Comment by proddy** [comment]
I've made the changes and added to https://emsesp.github.io/docs/All-Devices/ 

Although the table is sortable and searchable, I haven't found a JS plugin to filter yet.

Closing this and will re-open if changes are needed.
