### ISSUE TITLE
Remove the test.mosquitto.org URL in the MQTT settings

### ISSUE THREAD

**Issue by bbqkees** [emsesp/EMS-ESP32#829]
In the MQTT settings, by default the host address is test.mosquitto.org.

I often get emails from customers who have issues with MQTT and then the result after some questions about their configuration is that they are actually using test.mosquitto.org as the MQTT broker.

If we remove the default URL here then they are forced to think one step further and fill out the IP of their actual local broker.

**Comment by proddy** [comment]
ok, need to see how to do this as the value can't be blank.

**Comment by bbqkees** [comment]
I think there are lots of users who are actually using the test server, not just those who send an email with an issue.
So we need to protect them from this insecure solution.

Maybe just use 0.0.0.0?
Or when they tick the 'Enable MQTT' tickbox make the host box empty?

**Comment by proddy** [comment]
I have a solution now.

**Comment by bbqkees** [comment]
Ok thanks.
