### ISSUE TITLE
sensor.boiler_auxiliary_electrical_heater_energy_cons (umption_heating) since upgrade to 3.5.0b12

### ISSUE THREAD

**Issue by HansRemmerswaal** [emsesp/EMS-ESP32#833]
**Bug description**
On Dec 19th I upgrade to 3.5.0b12 and have put the Entity ID format to "Single instance, long name (v3.4).
Since then I noticed in Home Assistant that I'm getting the value "sensor.boiler_auxiliary_electrical_heater_energy_cons" instead of "sensor.boiler_auxiliary_electrical_heater_energy_consumption_heating".  Looks like the variable is not big enough?

SELECT *
FROM "states"
where entity_id in ('sensor.boiler_auxiliary_electrical_heater_energy_cons','sensor.boiler_auxiliary_electrical_heater_energy_consumption_heating','sensor.boiler_auxelecheatnrgconsheating')
order by last_updated 

(see screenshots)

**Expected behavior**
Get in Home Assistant
sensor.boiler_auxiliary_electrical_heater_energy_consumption_heating
instead of
sensor.boiler_auxiliary_electrical_heater_energy_cons

**Screenshots**
![image](https://user-images.githubusercontent.com/116959990/209432382-e1240fd7-a14d-42a0-b931-8ba9d294e3b5.png)
![image](https://user-images.githubusercontent.com/116959990/209432394-a05872d4-ab9a-422e-a41e-0433c602238e.png)

**Device information**
[emsesp_info (1).txt](https://github.com/emsesp/EMS-ESP32/files/10298384/emsesp_info.1.txt)

**Comment by MichaelDvP** [comment]
Check MQTT -> Settings -> Entitiy ID Format

**Comment by HansRemmerswaal** [comment]
![image](https://user-images.githubusercontent.com/116959990/209448951-2decdbe6-43ee-4508-818e-a013833b059b.png)

**Comment by proddy** [comment]
yes this is a bug, I need to make the string buffer larger for HA

**Comment by proddy** [comment]
I made a PR, being reviewed

**Comment by HansRemmerswaal** [comment]
After I installed EMS-ESP-3_5_0-dev_14-ESP32.bin the problem was resolved.

![image](https://user-images.githubusercontent.com/116959990/209630053-0ff2bd12-5bdb-4139-b836-333e48366b66.png)
