### ISSUE TITLE
Feature Request: Description for Dallas sensors

### ISSUE THREAD

**Issue by alexandergeiler** [emsesp/EMS-ESP32#84]
I have 9 Dallas sensors connected to my EMS-ESP.
It is hard to distinguish them because you only see the ID and it is hard to remember IDs.

I would like to have a description field for each sensor (see screenshot)
![Description](https://user-images.githubusercontent.com/4689177/125411399-2b9e0600-e3be-11eb-892c-4aecb67bbe31.png)
This will make it much easier to identify which sensor is taking which readings

I would be great to have the description also available at MQTT (see screenshot)
![mqtt](https://user-images.githubusercontent.com/4689177/125411764-10ddd840-5378-4bfa-b201-da836c42d1fe.png)

**Comment by MichaelDvP** [comment]
I've tested a bit, a suggestion for setting the names from the web is this:
![sensorname1](https://user-images.githubusercontent.com/59284019/126063285-92b97321-220b-415d-b77e-fc56dee2e0a2.png)
![sensorname2](https://user-images.githubusercontent.com/59284019/126063290-bd95f119-66c2-4652-9102-d45f427eb2c6.png)

**Comment by proddy** [comment]
I was thinking about this during my holiday.  Instead of showing the Sensor #, ID and Temperature like we have now with : 

![Screenshot 2021-07-18 141343](https://user-images.githubusercontent.com/1230712/126066566-06ac8d57-922c-4f91-8e24-ae1840b106e4.png)

We rename "ID" to "Name". Then on the left side of the row add the pencil icon which allows you to rename the "Name". The name is defaulted to that long ID.

**Comment by MichaelDvP** [comment]
Ok, i've used a button around the number, but pencil is better to remove for non-admin. 
As you see i also added the analog (if activated).
I can push, or push a feature-build after testing the last changes.

**Comment by MichaelDvP** [comment]
![Screenshot 2021-07-18 at 15-14-25 EMS-ESP](https://user-images.githubusercontent.com/59284019/126068443-3f68ea5f-db56-43ae-b373-536baa312fbe.png)

**Comment by MichaelDvP** [comment]
I've only done some short tests, all seems to work. I've pushed to dev, some more testers with many dallas are welcome.
Web forces to names, the setting ìd/no/name` is for api/mqtt only. Mqtt does not like spaces in names, i use the space to seperate name and offset. Console command `sensorname` can  be called with id (any) or sensornumber (sensor has to be connected). 

I like to automatic reload values after setting a value or name, but did not get managed it for now.

**Comment by proddy** [comment]
really excellent work, love it. We could enhance the dialog box to not allow spaces in the names, and have the offset as a separate field. If you want any help with coding let me know. I'm self-isolating for the next 7 days so may have odd bits of spare time

**Comment by proddy** [comment]
> @MichaelDvP really excellent work, love it. We could enhance the dialog box to not allow spaces in the names, and have the offset as a separate field. If you want any help with coding let me know. I'm self-isolating for the next 7 days so may have odd bits of spare time

I'm making these changes and doing a bit of refactoring along the way

**Comment by proddy** [comment]
> > @MichaelDvP really excellent work, love it. We could enhance the dialog box to not allow spaces in the names, and have the offset as a separate field. If you want any help with coding let me know. I'm self-isolating for the next 7 days so may have odd bits of spare time
> 
> I'm making these changes and doing a bit of refactoring along the way

finished with the changes. The edit screen has a small update. most of the changes were internal

**Comment by MichaelDvP** [comment]
> finished with the changes.

Can you manage it to reload the values after setting.  We see the snackbar saying that the name is changed, but need to hit reload to see the new name in the list, that's annoying (same for the device-values.).

**Comment by MichaelDvP** [comment]
BTW: We can change the `<OutlinedInput` to 
```
            <TextValidator
              validators={['matchRegexp:^([a-zA-Z0-9_.-]{0,19})$']}
              errorMessages={['Not a valid sensorname']}
```
to make sure that there are not spaces and the name is not to long.

**Comment by proddy** [comment]
ok adding it now

**Comment by MichaelDvP** [comment]
I think it's now fully working. @alexandergeiler please check if you have any suggestions for improvment. 
If not we can close this issue.

**Comment by alexandergeiler** [comment]
@MichaelDvP , looks great.
I would have added an alias instead of storing that in the ID field.
But I am fine with that too.
Thank´s a lot!

Regards,
Alexander
