### ISSUE TITLE
NTP status "inactive"

### ISSUE THREAD

**Issue by HansRemmerswaal** [emsesp/EMS-ESP32#843]
**Question**
On the EMS-ESP I always see the "NTP Status" as "Inactive" and the local time is incorrect. So I then use the "SET TIME" option to correct the time. How can I make the NTP Status working?

**Screenshots**
1) Shortly after reboot
![image](https://user-images.githubusercontent.com/116959990/209634027-c751482b-80f2-4fbd-946e-7f7eb39f8df9.png)

2) Few minutes later after refresh
![image](https://user-images.githubusercontent.com/116959990/209634367-174874b0-49fe-40b1-9cd9-731d38fad128.png)

3) NTP settings
![image](https://user-images.githubusercontent.com/116959990/209634070-6e03b6e0-2dce-4297-9fbf-68201ec369c8.png)

**Device information**

**Comment by HansRemmerswaal** [comment]
After using the "SET TIME" option after the reboot the date / time stays correct. But with the next reboot the time is wrong again.

**Comment by proddy** [comment]
I'm not sure why it would say Inactive. Did it work before on previous versions? Is your network blocking this perhaps? 

I tried the SET TIME, rebooted 3 times and it keeps the settings, so can't reproduce that one. Maybe Michael has an idea

**Comment by MichaelDvP** [comment]
The esp32 rtc does not have a buffer-battery, after powercut the time is reset. 
I've tried different servers (time.google.com, europe.pool.ntp.org, de.pool.ntp.org, all working. But not working if i block ems-esp from internet access in the router. I have not tested, but i think it also does not work in guest network (only web/mail allowed).

My router (fritzbox) is capable to act as timeserver, I always use this for all internal devices, makes sure that all have identical time with low latency.

**Comment by HansRemmerswaal** [comment]
Since I got my module from BBQKees, with 3.5 installed, I have this issue. 
From Windows I can do a ping to time.google.com.

![image](https://user-images.githubusercontent.com/116959990/209647024-af669f04-6fed-4287-96ce-cfb55926d3bb.png)

**Comment by MichaelDvP** [comment]
What do you want to compare? ICMP is not NTP, Your windows PC is maybe handled different by your firewall.
Your emsesp can not connect to time.google.com with NTP protocol on UDP, port 123. Make sure that this connection is allowed.

**Comment by proddy** [comment]
I would also recommend to use the NTP server that comes with your router/modem (unifi, fritzbox etc)

**Comment by HansRemmerswaal** [comment]
Interesting, I can connect to the EMS-ESP module (192.168.0.239) but the module is not visible in my router (DECO M5) in the list of connected devices.

**Comment by HansRemmerswaal** [comment]
Connected the EMS-ESP module via a network cable, still not visible in DECO M5, but now the NAT status is active. So somehow related to connected via WIFI.

**Comment by HansRemmerswaal** [comment]
Resolved... 

In the network settings I have defined a fixed IP address and defined the DNS 8.8.8.8 and 8.8.4.4.
Since then the NTP status is active.
