### ISSUE TITLE
EMS-ESP-3_5_0-dev_14-ESP32 - Problem loading (507) during export "support info"

### ISSUE THREAD

**Issue by HansRemmerswaal** [emsesp/EMS-ESP32#844]
**Bug description**
I have installed EMS-ESP-3_5_0-dev_14-ESP32. 
When I'm using the Help -> Support info I'm getting the "Problem loading (507) error and nothing is exported.

**Steps to reproduce**
Install EMS-ESP-3_5_0-dev_14-ESP32 and use the option Help -> Support info

**Expected behavior**
Export file

**Screenshots**
![image](https://user-images.githubusercontent.com/116959990/209634670-71f7ee02-a6ed-4ac5-9fad-5257b33f300f.png)

![image](https://user-images.githubusercontent.com/116959990/209635439-6d7217a1-89ac-433c-b714-c9ad34c31d5e.png)

**Device information**
And older one...
[Uploading emsesp_info (1).txt…]()

**Additional context**
N/A

**Comment by MichaelDvP** [comment]
@proddy 
I'll add a commit to the actual PR to avoid the 507 by reducing the buffer stepwise until it fits in memory. A few less users will complain that dashboard/customization or system-info will cut the last values. But that's a nice variety to all the 507 complains.

**Comment by MichaelDvP** [comment]
Sorry, first commit has a copy/past error, dahboard and customization throw errors. Fixed in a second PR.

**Comment by HansRemmerswaal** [comment]
Issue has been resolved for me with the latest build of EMS-ESP-3_5_0-dev_14-ESP32

![image](https://user-images.githubusercontent.com/116959990/209667345-43b56b1f-a258-4011-9aee-f325745e07de.png)
