### ISSUE TITLE
Compress 7000AW missing sensors 

### ISSUE THREAD

**Issue by sfbia2m** [emsesp/EMS-ESP32#846]
Hi, 
I have been using your interface for some time now, but in one of the updates after Sep 13 2021. I lost two temperature sensores TR5 and TR6, is it possible to bring that to live again?
Also my homeassistant logs has a lot of warnings like this "Template variable warning: 'dict object' has no attribute 'id' when rendering '{{value_json.hc2.id}}'" this is also an isue witch started after Sep13 2021

I know the date because at that time you got the sommer mode to work for me :-)

I have installed the current firmware v3.5.0-dev.14 

![image](https://user-images.githubusercontent.com/63424515/209650576-cc2c0c78-e1da-4e20-adc6-66d7fa718535.png)

**Comment by MichaelDvP** [comment]
Please check in terminal `read 8 48F` and write down the actual values or TR5 and TR6.
The sensors were read from TR5: offset 20, TR6: offset 0, but there was a complain that the values are wrong. So we do not know where to read the values. If you could help to identify the tight offsets, i'll add them back.
> 'dict object' has no attribute 'id' when rendering '{{value_json.hc2.id}}'" this is also an isue witch started after Sep13 2021

https://emsesp.github.io/docs/#/Troubleshooting?id=home-assistant

**Comment by sfbia2m** [comment]
Hi Michael,

Here is the result from mine. TR5 shows 1.2 and TR6 show 62.4. The values keeps changing at the moment so I home you can see them in the telegram

ems-esp:$ read 8 48f
000+08:36:05.906 I 2: [emsesp] Boiler(0x08) -W-> Me(0x0B), HpTemperatures(0x048F), data: 02 73 01 5E 01 61 01 19 00 00 00 00 00 08 02 33 01 45 00 00 00 0A 00 80
000+08:36:06.549 I 3: [emsesp] Boiler(0x08) -W-> Me(0x0B), HpTemperatures(0x048F), data: 02 6D FF D8 01 58 (offset 24)

**Comment by sfbia2m** [comment]
Thanks it works now :-)

**Comment by proddy** [comment]
in dev-16
