### ISSUE TITLE
Problem Loading (Extra x of y bytes(s) found at buffer[1]) 

### ISSUE THREAD

**Issue by akanto** [emsesp/EMS-ESP32#847]
**Bug description**
When I click on the thermostat or boiler entries I get the "extra ... of ... bytes(s) found at buffer[1]" error message. I am using the latest 3.5 b14 version of the firmware.

**Steps to reproduce**
I have opened the network tab in chrome, and as you can see on the screenshot, the data is correctly returned from the backend and it seems that it is a frontend/javascript issue.

It is reproducible from Chrome and Safari as well.

I have seen a couple of "Problem Loading" github issues, but none of them are describing this exact error.

![Screenshot 2022-12-27 at 13 28 03](https://user-images.githubusercontent.com/2838000/209667250-79877d92-3c84-4af8-ab83-836799d32ea3.png)

**Comment by MichaelDvP** [comment]
You have catched a buggy, intermediate version, update again.

**Comment by akanto** [comment]
Thanks, it looks good now.

**Comment by MichaelDvP** [comment]
So close this?

**Comment by akanto** [comment]
Yes, please. We can close this.

Thanks for the help.
