### ISSUE TITLE
Sensor TR5 and TR6 have wrong mapping?

### ISSUE THREAD

**Issue by HansRemmerswaal** [emsesp/EMS-ESP32#848]
**Question**
In the WebUI we have the TR5 and TR6 but for me no value is being shown.

![image](https://user-images.githubusercontent.com/116959990/209680795-6c2143a4-b422-4f2e-a5b9-cd940d2a8ca8.png)

But when I check on the display on my heatpump I do see values for these (pictures are available if needed).

![image](https://user-images.githubusercontent.com/116959990/209683897-1431029d-9553-42fc-a0dc-91df08efc9df.png)
The following log captures the period 15:40 - 15:48
[log (4).txt](https://github.com/emsesp/EMS-ESP32/files/10308829/log.4.txt)

Checking the WebUI I'm getting the impression that **suction gas** and **hot gas/compressed** are actually containing the TR5 and TR6 values.
![image](https://user-images.githubusercontent.com/116959990/209685029-d330acd7-bc6a-431c-a386-09c38b7cb057.png)

It looks like that 
**compressor inlet temperature (TR5)** should contain the value from **Suction gas**
**compressor outlet temperature (TR6)** should contain the value from **Hot gas/compressed**

**Screenshots**
![image](https://user-images.githubusercontent.com/116959990/209684524-e17c920f-ed7e-4045-95d0-3225bdf08832.png)

**Device information**
[emsesp_info (3).txt](https://github.com/emsesp/EMS-ESP32/files/10308833/emsesp_info.3.txt)

**Additional context**
Using EMS-ESP-3_5_0-dev_14-ESP32.bin

Nefit Eviline A/W Split 7.0 E-S
Nefit HR 300 liter boiler
Nefit Moduline 1010H

**Comment by MichaelDvP** [comment]
Same is already in #846. 
The values were double. I think we stick to Tr5/Tr6 and delete the hpSuctionGas/HotGas, as hybrid Heatpumps also use the Tr5/Tr6 naming. Memory is low having2 entities and names for the same value is really not usefull.

**Comment by sfbia2m** [comment]
Hi Michael,

Here is the result from mine. TR5 shows 1.2 and TR6 show 62.4. The values keeps changing at the moment so I home you can see them in the telegram

ems-esp:$ read 8 48f
000+08:36:05.906 I 2: [emsesp] Boiler(0x08) -W-> Me(0x0B), HpTemperatures(0x048F), data: 02 73 01 5E 01 61 01 19 00 00 00 00 00 08 02 33 01 45 00 00 00 0A 00 80
000+08:36:06.549 I 3: [emsesp] Boiler(0x08) -W-> Me(0x0B), HpTemperatures(0x048F), data: 02 6D FF D8 01 58 (offset 24)

**Comment by HansRemmerswaal** [comment]
Great!

![image](https://user-images.githubusercontent.com/116959990/209774647-9a6d4a19-d687-4286-ab65-aa202776cfd7.png)
