### ISSUE TITLE
Bus-ID in Devicelist Table

### ISSUE THREAD

**Issue by stmb-100** [emsesp/EMS-ESP32#863]
Is it possible to display the bus ID (0x..) in the device list table?

**Comment by proddy** [comment]
no, unfortunately, because the device IDs come from the bus itself and can change. See https://github.com/emsesp/EMS-ESP32/blob/dev/src/device_library.h#L81

**Comment by proddy** [comment]
oh, sorry, think I may have misunderstood you. If you're referring to the WebUI Dashboard the DeviceID is shown when you click on the little 'i' to the right of the table. Does this work?

**Comment by stmb-100** [comment]
Hi yes the klick on smal i works
