### ISSUE TITLE
Translate Device Name

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#872]
Request from Discord to translate the device names (boiler, thermostat etc)

![image](https://user-images.githubusercontent.com/1230712/210166802-027ddd43-0a82-4850-bd10-68066fd1a14f.png)

It's a change in EMSdevice::device_type_name()

**Comment by MichaelDvP** [comment]
Think about the lot of usages: mqtt topic, system-info, api device, command device and which should be translated without braking to much. Dashboard/Customizaton and HA friendly name are safe, i think.

**Comment by proddy** [comment]
yes, good point. I did check for all those cases

**Comment by proddy** [comment]
I think I'll only make this change in the WebUI and leave the rest (console, mqtt, API as it is)

**Comment by proddy** [comment]
merged into dev
