### ISSUE TITLE
Plural of "days" under EMS Status not working for Swedish

### ISSUE THREAD

**Issue by mvjt** [emsesp/EMS-ESP32#874]
**Bug description**
It seems plural for "days" for EMS Status is not working for Swedish but works for other languages. 
Day Singular = Dag
Day Plural = Dagar

In index.ts
NUM_DAYS: '{num} dag{{ar}}',

Screenshot where it should say "dagar" and not "dag"
<img width="449" alt="image" src="https://user-images.githubusercontent.com/34924009/210168820-6c14d0c7-3d4e-4171-8e58-8b883eca2bf4.png">

Version: v3.5.0-dev.14

**Comment by MichaelDvP** [comment]
I think this is because the pl base have no fixed part: `NUM_DAYS: '{num} {{dni|dzień|dni|dni|dni}}',`
Changing the pl to: `NUM_DAYS: '{num} d{{ni|zień|ni|ni|ni}}',` should work,
 or set all other languages to `NUM_DAYS: '{num} {{dag|dagar}}',`

**Comment by mvjt** [comment]
> I think this is because the pl base have no fixed part: `NUM_DAYS: '{num} {{dni|dzień|dni|dni|dni}}',`
> Changing the pl to: `NUM_DAYS: '{num} d{{ni|zień|ni|ni|ni}}',` should work,
> or set all other languages to `NUM_DAYS: '{num} {{dag|dagar}}',`

Thanks Michael, I'm not sure I understand the syntax but I used the EN one as reference...

**Comment by proddy** [comment]
I think it's something else that is causing this. And it only happens in the Bus Status and only for SE. It renders correctly in the Dashboard for the "* burner operating time".

**Comment by MichaelDvP** [comment]
For many days like in "burner operating time" the SE also renders correctly. And for minutes, hours also all languages work and PL defines cases for 1, 2, few, many, other languages only single/many. The only difference i see is that days are not defined as fixedpart/suffix, but use cases for each plural. My emsesp rarly reaches 2 days uptime without updating. Difficult to check.

**Comment by proddy** [comment]
yeah, this is a weird one and related to how the page is rendered are the variables loaded. I have a workaround which I'll push shortly.

**Comment by proddy** [comment]
I found the problem after tracing it down to internal JS library `Intl.PluralRules`. Turns out we're using the wrong locale for Swedish. It's SV and not SE (ISO 639). doh! Will do a PR...

**Comment by mvjt** [comment]
Nice work. Translations finally look really good too. The only missing piece is #872.
