### ISSUE TITLE
Small typo i18n/de & missing link in docs

### ISSUE THREAD

**Issue by MichScha** [emsesp/EMS-ESP32#875]
**Bug description**

### Typo in DE translation

https://github.com/emsesp/EMS-ESP32/blob/dev/interface/src/i18n/de/index.ts
Current
-   ENABLE_ANALOG: 'Aktiviere Analogsensorsen',

Corrected
-   ENABLE_ANALOG: 'Aktiviere **_Analogsensoren_**',

Current
-   MQTT_NEST_1: 'Als Nester in in einem Gesamttopic',

Corrected
-   MQTT_NEST_1: 'Eingebettet in einem Gesamttopic',

### Missing anchor in docs for "see the table below"

- https://emsesp.github.io/docs/Commands/
_an EMS device entity also referred to as an <entity>. See the [table below](https://emsesp.github.io/docs/Commands/Command?id=ems-device-entity-names.md) for the complete list_

**Comment by proddy** [comment]
thanks, fixed in the next PR
