### ISSUE TITLE
Manual defrosting Setting

### ISSUE THREAD

**Issue by MichScha** [emsesp/EMS-ESP32#880]
RC300 / WLW196i

It is possible to set the manual defrosting mode to ON/OFF. In my system as it is completely in house it is not relevant and cannot be changed but the telegrams are still send out. Maybe this is interesting for someone - if not just close and ignore.
```
ON
000+00:37:45.502 N 3179: [emsesp] Thermostat(0x10) -W-> Boiler(0x08), ?(0x0291), data: 01
OFF
000+00:37:45.502 N 3179: [emsesp] Thermostat(0x10) -W-> Boiler(0x08), ?(0x0291), data: 00
```

**Comment by proddy** [comment]
We could add this is a new thermostat command

**Comment by MichScha** [comment]
Can be closed when PR is been merged - works!
