### ISSUE TITLE
Boiler occasionally does not start after power cycle

### ISSUE THREAD

**Issue by zarebski-m** [emsesp/EMS-ESP32#889]
**Question**
I have a Junkers Cerapur Compact boiler connected to ESP32 with EMS-ESP32 installed and connected via BBQKees board.

There is an issue when a power cycle occurs (e.g. electricity goes down for whatever reason). After a power cycle, sometimes the boiler is unresponsive. It powers on, but does nothing at all. On the other hand, EMS-ESP32 reports that the bus is disconnected. It stays in this state until I power cycle the boiler (_not_ ESP32).

I assume the reason is that after a “global” power cycle, ESP32 takes a longer time to power up and is not ready when the boiler is turning on. Possibly there is some communication from the boiler and it waits for a response or something similar. Or maybe the board has some floating/undefined voltage level on TX pin until it's fully powered up and that sometimes trigger the boiler in this limbo state.

I've tried to reproduce the problem but it is quite hard as the nature of the problem is very non-deterministic. But I _did_ reproduce it at least once.

There are several ways to fix this issue but I'm not totally satisfied with any of them:

1. Add UPS for the boiler and ESP32. That should mostly prevent power cycles.
2. Add some battery backup to ESP32 alone – cheaper version of the UPS approach.
3. Add Home Assistant automation to power cycle the boiler when ESP32 reports EMS bus problem.

Is there any other way to make it work? I'm leaning towards option 3 as it wouldn't cost me anything (boiler is already powered via Zigbee switch). But I'm not happy with adding more components (Home Assistant, MQTT) to such essential infrastructure. Is there maybe a way to configure one of ESP32 pins as a power cycle output? Then I could simply add a relay to boiler mains power and have this workaround “localized” to a single place.

And more general question: is it actually a bug that should be addressed, either in EMS-ESP32 or in the interface board from BBQees?

---

…and while writing this question, I have checked ESP32 pinout. As it turns out, GPIO5 (used for TX) outputs PWM at boot. Maybe that's what confusing the boiler? I will try to change TX pin to e.g. GPIO4. I have used the defaults mentioned in the documentation: https://emsesp.github.io/docs/Configuring/#board-profile

**Device information**
```json
{
  "System Status": {
    "version": "3.4.4",
    "uptime": "000+06:31:18.596",
    "freemem": 134,
    "reset reason": "Power on reset / APP CPU reset by PRO CPU"
  },
  "Network Status": {
    "connection": "WiFi",
    "hostname": "ems-boiler",
    "RSSI": -56,
    "IPv4 address": "192.168.88.30/255.255.255.0",
    "IPv4 gateway": "192.168.88.1",
    "IPv4 nameserver": "192.168.88.10",
    "static ip config": true,
    "enable IPv6": false,
    "low bandwidth": false,
    "disable sleep": false,
    "AP provision mode": "disconnected",
    "AP security": "wpa2",
    "AP ssid": "ems-esp"
  },
  "NTP Status": {
    "network time": "connected",
    "enabled": true,
    "server": "time.google.com",
    "tz label": "Europe/Warsaw"
  },
  "OTA Status": {
    "enabled": true,
    "port": 8266
  },
  "MQTT Status": {
    "MQTT status": "connected",
    "MQTT publishes": 2504,
    "MQTT publish fails": 0,
    "enabled": true,
    "client_id": "ems-boiler",
    "keep alive": 60,
    "clean session": false,
    "base": "ems-boiler",
    "discovery prefix": "homeassistant",
    "nested format": 1,
    "ha enabled": true,
    "mqtt qos": 0,
    "mqtt retain": false,
    "publish time boiler": 10,
    "publish time thermostat": 10,
    "publish time solar": 10,
    "publish time mixer": 10,
    "publish time other": 10,
    "publish time sensor": 10,
    "publish single": false,
    "publish2command": false,
    "send response": false
  },
  "Syslog Status": {
    "enabled": false
  },
  "Sensor Status": {
    "analog sensors": 0,
    "analog sensor reads": 0,
    "analog sensor fails": 0
  },
  "API Status": {
    "API calls": 0,
    "API fails": 0
  },
  "Bus Status": {
    "bus status": "connected",
    "bus protocol": "HT3",
    "bus telegrams received (rx)": 4916,
    "bus reads (tx)": 495,
    "bus writes (tx)": 6,
    "bus incomplete telegrams": 6,
    "bus reads failed": 0,
    "bus writes failed": 0,
    "bus rx line quality": 100,
    "bus tx line quality": 100
  },
  "Settings": {
    "board profile": "CUSTOM",
    "tx mode": 3,
    "ems bus id": 11,
    "shower timer": false,
    "shower alert": false,
    "rx gpio": 23,
    "tx gpio": 5,
    "dallas gpio": 0,
    "pbutton gpio": 0,
    "led gpio": 2,
    "hide led": false,
    "notoken api": false,
    "readonly mode": false,
    "fahrenheit": false,
    "dallas parasite": false,
    "bool format": 1,
    "bool dashboard": 1,
    "enum format": 1,
    "analog enabled": true,
    "telnet enabled": true
  },
  "Devices": [
    {
      "type": "Boiler",
      "name": "Condens 2500/Logamax/Logomatic/Cerapur Top/Greenstar/Generic HT3",
      "device id": "0x08",
      "product id": 95,
      "version": "43.10",
      "entities": 57,
      "handlers received": "0x10 0x11 0x15 0x1C 0x18 0x19 0x34 0x2A",
      "handlers fetched": "0x14 0x16 0x33",
      "handlers pending": "0xBF 0xC2 0x1A 0x35 0x26",
      "handlers ignored": "0x03 0x04"
    },
    {
      "type": "Controller",
      "name": "HT3",
      "device id": "0x09",
      "product id": 95,
      "version": "43.10",
      "entities": 0
    }
  ]
}
```

**Comment by proddy** [comment]
We would really need to try and reproduce this and see if it's Rx or Tx that is not working. When EMS-ESP starts it opens up the serial UART and just listens to data streaming in. It will try and reconnect every 10 seconds. I don't recall building in a timeout (but will check) so in theory, EMS-ESP should eventually continue communicating the boiler. Since it's the master device you can't really test this hypothesis with a thermostat, which is a pity.

@bbqkees any ideas?
