### ISSUE TITLE
Bosh Heating System 8000iF, CW400: Supported by EMS-ESP32 ? 

### ISSUE THREAD

**Issue by ced2git** [emsesp/EMS-ESP32#916]
Hello, 

I'm about the change my existing heating system with a BOSH 8000iF and a controller CW400. 

I'm interested to export from the heating system when it starts and stop burning oil in order to follow my consumption. My intention is to retrieve this information trough MQTT then send it to an influxdb. 

THere are a lot of examples with boiler and thermostat but it's not clear for heating system Bosch 8000iF, It's a new system.  

Thanks

**Comment by bbqkees** [comment]
Yes it will work.
perhaps we need to add the ID of the boiler to the database.

This boiler has a service connector on the front, below the CW400.
This is where you can plug in a Gateway or interface board with the EMS service cable.
![image](https://user-images.githubusercontent.com/10775682/213005424-6536162a-50c7-408b-ae53-f3f23013886f.png)
