### ISSUE TITLE
Support for IVT GEO608C

### ISSUE THREAD

**Issue by dominikstupka** [emsesp/EMS-ESP32#917]
Hi, i have heat pump IVT GEO 608C. EMS ESP board can communicate with heat pump i can see some values, temperatures, power etc. but i think that information coming from pump isnt complete. I can't control and also see set heating temperature, device mode like vacation/normal. Biggest issue is that i can't control device. If i change some value like dhw comfort mode nothing happens. EMS Write is ok without failure but mode doesn't change.

My machine consist this modules:

**Main board**
![Main board](https://user-images.githubusercontent.com/10763450/213011355-cafbf01b-aac2-46f6-9e77-c164f298878a.png)
**WiFi module K30RF**
![WiFi Modul](https://user-images.githubusercontent.com/10763450/213011365-21744087-2362-4f0c-b318-c5a41642f9a5.png)
**Control panel UI800**
![TouchScreen](https://user-images.githubusercontent.com/10763450/213011358-30fc21df-6ec8-47be-98c8-a86186715d8d.png)
![ControlPanel](https://user-images.githubusercontent.com/10763450/213011346-baa42e1f-02c6-4c1f-b552-3be77d35a237.png)
**Wireless thermostat TR120RF**
![Thermostat](https://user-images.githubusercontent.com/10763450/213011356-a212db6f-6c3d-4960-87fb-7fdf6c7668b6.png)

**Exported files from EMS-ESP DashBoard**
[device_entities (1).csv](https://github.com/emsesp/EMS-ESP32/files/10439404/device_entities.1.csv)
[log.txt](https://github.com/emsesp/EMS-ESP32/files/10439283/log.txt)
[emsesp_info.txt](https://github.com/emsesp/EMS-ESP32/files/10439282/emsesp_info.txt)

Thanks for Help!

**Comment by MichaelDvP** [comment]
Please try this build: https://github.com/MichaelDvP/EMS-ESP32/releases/tag/latest
and post another info.txt and log.

BTW: You have shower timer activated, this works only on flow type dhw-systems, but i think heatpumps always have a  dhw-buffer.

**Comment by dominikstupka** [comment]
Now it seems perfect. I can control the thermostat remotely.

[emsesp_info.txt](https://github.com/emsesp/EMS-ESP32/files/10449137/emsesp_info.txt)
[log.txt](https://github.com/emsesp/EMS-ESP32/files/10449138/log.txt)

**Comment by MichaelDvP** [comment]
The mapping of integrated devices (0x48, 0x50) needs a fix, but both have no entities, so it's a cosmetic fix. I'll update my build.

Funny, once again bosch do not know what bosch do, the thermostat floods the bus with version requests on wifi-module, but can not map the answer.

**Comment by proddy** [comment]
in dev-16
