### ISSUE TITLE
malformatted dashboard

### ISSUE THREAD

**Issue by wrohdewald** [emsesp/EMS-ESP32#93]
see attachment. On Debian 11.09 with Chromium 90.0.4430.212 and Firefox 78.12.0esr

{
  "System": {
    "version": "3.0.3b2",
    "uptime": "000+00:07:45.363"
  },
  "Status": {
    "bus": "connected",
    "bus protocol": "HT3",
    "#telegrams received": 618,
    "#read requests sent": 201,
    "#write requests sent": 0,
    "#incomplete telegrams": 0,
    "#tx fails": 0,
    "rx line quality": 100,
    "tx line quality": 100,
    "#MQTT publish fails": 0,
    "#dallas sensors": 0,
    "#dallas fails": 0
  },
  "Devices": [
    {
      "type": "Boiler",
      "name": "GBx72/Trendline/Cerapur/Greenstar Si/27i (DeviceID:0x08, ProductID:123, Version:06.03)",
      "handlers": "0x10 0x11 0x14 0x15 0x1C 0x18 0x19 0x35 0x16 0x33 0x34 0x1A 0x26 0x2A 0xD1 0xE3 0xE4 0xE5 0xE6 0xE9 0xEA 0x494 0x495"
    },
    {
      "type": "Thermostat",
      "name": "RC300/RC310/Moduline 3000/1010H/CW400/Sense II (DeviceID:0x10, ProductID:158, Version:18.06)",
      "handlers": "0xA3 0x06 0xA2 0x12 0x2A5 0x2B9 0x2AF 0x29B 0x2A6 0x2BA 0x2B0 0x29C 0x2A7 0x2BB 0x2B1 0x29D 0x2A8 0x2BC 0x2B2 0x29E 0x2F5 0x31B 0x31D 0x31E 0x23A 0x267 0x240"
    },
    {
      "type": "Mixer",
      "name": "MM200 (DeviceID:0x20, ProductID:161, Version:29.04)",
      "handlers": "0x2D7"
    },
    {
      "type": "Mixer",
      "name": "MM200 (DeviceID:0x21, ProductID:161, Version:29.04)",
      "handlers": "0x2D8"
    },
    {
      "type": "Controller",
      "name": "Controller (DeviceID:0x09, ProductID:152, Version:03.01)",
      "handlers": ""
    }
  ]
}

![Bildschirmfoto vom 2021-07-31 13-41-19](https://user-images.githubusercontent.com/2433071/127738878-c8e24b73-2f78-4c27-a8cb-20dd896a8ab2.png)

**Comment by proddy** [comment]
upgrade to the latest dev branch and refresh your browser cache.
