### ISSUE TITLE
Junkers  boilers don't set any command 

### ISSUE THREAD

**Issue by matteopedani** [emsesp/EMS-ESP32#934]
I have a junkers boiler but I can't send any command, but I can read all state of boilers. The boiler stay always ON. And there is no way to switch off. (I'm using Home Assistant integration) 

Can you give me the right command to switch off

**Comment by matteopedani** [comment]
I have a junkers boiler but I can't send any command, but I can read all state of boilers. The boiler stay always ON. And there is no way to switch off. (I'm using Home Assistant integration) 

Can you give me the right command to switch off

**Comment by bbqkees** [comment]
See also:  #951
